"""Lesson-specific explanatory plates for every unillustrated computing lesson."""

from __future__ import annotations

from .core import spec


def S(node_id, title, stage, slug, alt, caption, kind, **payload):
    payload["kind"] = kind
    return spec(node_id, title, stage, slug + "-plate", alt, caption, payload)


SPECS = {
    item["id"]: item
    for item in (
        S(
            "cs.0.instructions", "Step by Step", 0, "ordered-path",
            "Four numbered cards put tooth-brushing commands in dependency order: get the brush, add paste, brush, then rinse.",
            "Each step creates the condition needed by the next; reversing dependent steps can change or prevent the result.",
            "flow", steps=(("1  GET BRUSH", "empty hand -> brush in hand"), ("2  ADD PASTE", "needs the brush first"), ("3  BRUSH", "needs brush + paste"), ("4  RINSE", "after brushing; task complete")),
            footer="order encodes dependencies: rinsing first cannot clean the teeth",
        ),
        S(
            "cs.0.sorting", "Sorting and Ordering", 0, "choose-a-sort-key",
            "Four mixed blocks become ordered from shortest to tallest after the rule sort by height is chosen, while a color grouping is shown as a different valid rule.",
            "A sort needs an explicit key. Height creates an ordered sequence; color creates groups. The same objects can therefore have different correct arrangements for different purposes.",
            "compare", columns=(("MIXED", ("red short | blue tall", "red medium | blue tiny")), ("BY HEIGHT", ("tiny < short < medium < tall", "one ordered line")), ("BY COLOR", ("RED: short, medium", "BLUE: tiny, tall"))),
            footer="the rule determines which arrangement counts as sorted",
        ),
        S(
            "cs.0.patterns", "Patterns and Rules", 0, "find-repeat-unit",
            "A written circle-square sequence is split into repeated AB units; the isolated unit predicts that a square must follow the final circle.",
            "A repeating pattern is generated by a unit and a rule, not by visual guesswork alone. Once AB is identified, the next position after A must be B.",
            "flow", steps=(("OBSERVE", "circle square | circle square | circle ?"), ("FIND UNIT", "A B"), ("APPLY RULE", "after A comes B"), ("PREDICT", "square")),
            footer="AB repeated three times fixes the missing item",
        ),
        S(
            "cs.1.binary", "Ones and Zeros", 1, "binary-place-values",
            "Three binary place-value panels labelled 4, 2 and 1 show ON, OFF and ON; the active values 4 and 1 are added to decode binary 101 as decimal 5.",
            "Binary place values are powers of two. In 101 base two, a 1 includes its place value and a 0 excludes it, so four plus zero plus one equals five.",
            "compare", columns=(("4s PLACE", ("1 = ON", "include 4")), ("2s PLACE", ("0 = OFF", "include 0")), ("1s PLACE", ("1 = ON", "include 1"))),
            footer="101 (base 2) = 1x4 + 0x2 + 1x1 = 5",
        ),
        S(
            "cs.1.blocks", "Block Coding", 1, "blocks-control-flow",
            "A block trace starts at position zero, loops two one-step moves to a star at position two, then takes the true branch and jumps to position four.",
            "Blocks express control flow. A sequence fixes order, a loop repeats enclosed steps, and an if statement runs its branch only when its condition is true.",
            "flow", steps=(("START", "position 0; face right"), ("LOOP x2", "move 1 -> pos 1; move 2 -> pos 2"), ("IF at star on pos 2", "true -> jump 2; false -> continue"), ("RESULT", "true branch lands on position 4")),
            footer="a branch chooses; a loop repeats; sequence orders them",
        ),
        S(
            "cs.1.parts", "Parts of a Computer", 1, "computer-data-path",
            "A keyboard sends input to a processor, the processor reads and writes memory, and a processed result travels to the screen as output.",
            "Input and output are data paths, not places where all computation happens. The processor executes instructions while memory holds instructions and data needed now or later.",
            "flow", steps=(("INPUT", "keyboard encodes key A"), ("PROCESS", "CPU executes a display instruction"), ("CPU <-> MEMORY", "RAM supplies instructions and stores program state"), ("OUTPUT", "screen draws A")),
            footer="data moves; the CPU transforms it using stored instructions",
        ),
        S(
            "cs.2.programming", "Programming Basics", 2, "program-state-trace",
            "A short program loops over 2, 5 and 8, adds only values greater than 4, and traces total from zero to five to thirteen.",
            "Variables name changing state, loops repeat a block, and conditionals decide whether that block runs. Tracing each iteration explains why the final total is thirteen.",
            "trace", code=("total = 0", "for n in [2, 5, 8]:", "    if n > 4:", "        total = total + n"), states=("start: total = 0", "n = 2; condition false; total = 0", "n = 5; condition true; total = 5", "n = 8; condition true; total = 13"),
            code_heading="PROGRAM", state_heading="STATE AFTER EACH ITERATION", footer="the trace makes every state change inspectable",
        ),
        S(
            "cs.2.data-types", "Data and Types", 2, "type-operations",
            "Four panels apply type-specific operations: integer 7 plus 2 becomes 9, string 7 joined with 2 becomes 72, a Boolean conjunction is false, and a list appends an item.",
            "A type constrains representation and valid operations. The same plus-like notation can mean arithmetic for numbers and concatenation for strings, so values must not be interpreted by appearance alone.",
            "compare", columns=(("NUMBER", ("7 + 2", "= 9")), ("STRING", ('"7" + "2"', '= "72"')), ("BOOLEAN", ("true AND false", "= false")), ("LIST", ("[7, 2] append 5", "= [7, 2, 5]"))),
            footer="type determines which operations and results are meaningful",
            footer_size=25,
        ),
        S(
            "cs.2.functions", "Functions", 2, "function-reuse",
            "The function double returns x times 2 and is called twice; the trace substitutes 3 to produce 6 and 5 to produce 10 without duplicating the function body.",
            "A function packages a parameterized computation. Each call binds a fresh argument to x, evaluates the same body, and returns a result to the caller.",
            "trace", code=("def double(x):", "    return x * 2", "a = double(3)", "b = double(5)"), states=("call 1: x = 3", "return 3 x 2 = 6; a = 6", "call 2: x = 5", "return 5 x 2 = 10; b = 10"),
            code_heading="ONE DEFINITION", state_heading="TWO CALLS", footer="reuse the rule; change only the argument",
        ),
        S(
            "cs.2.debugging", "Finding Bugs", 2, "off-by-one-debugging",
            "A failing test for the three-item list A B C traces indexes zero through three, exposes index three as out of range, and fixes a loop bound from less-than-or-equal to strictly less-than length.",
            "Debugging links a reproducible failure to the smallest causal state. A length-three list has valid indexes zero, one and two; stopping before length removes the off-by-one access.",
            "trace", code=("items = ['A','B','C']", "i = 0", "while i <= len(items):", "    print(items[i]); i += 1"), states=("i = 0 -> A", "i = 1 -> B", "i = 2 -> C", "i = 3 -> IndexError", "fix: while i < len(items)"),
            code_heading="FAILING PROGRAM", state_heading="REPRODUCE -> LOCATE -> FIX", footer="the failing state reveals an off-by-one loop bound",
        ),
        S(
            "cs.2.internet", "How the Internet Works", 2, "web-request-path",
            "A browser asks DNS for example.org's address, opens an encrypted HTTPS connection to that server, sends a request, and receives the page response.",
            "The web runs over networks: DNS maps a name to an address, routing carries packets, and HTTPS authenticates the site and encrypts data in transit. Encryption does not make every site trustworthy.",
            "flow", steps=(("NAME", "browser asks for example.org"), ("DNS", "returns the server's IP address"), ("HTTPS", "authenticate; establish encrypted channel"), ("REQUEST / RESPONSE", "GET / -> HTML arrives")),
            footer="a name lookup locates the server; HTTPS protects the connection",
            footer_size=24,
        ),
        S(
            "cs.2.bigo-intro", "Fast and Slow Programs", 2, "search-comparisons",
            "For sixteen sorted cards, linear search checks up to sixteen cards one by one, while binary search halves the remaining interval and needs at most five checks.",
            "Algorithm speed depends on how work grows with input size. Linear search can inspect every item; binary search uses sorted order to discard half the candidates after each comparison.",
            "compare", columns=(("LINEAR SEARCH", ("16 candidates", "check 1, 2, 3, ...", "worst case: 16 checks")), ("BINARY SEARCH", ("16 -> 8 -> 4 -> 2 -> 1", "discard half each check", "worst case: 5 checks"))),
            footer="structure in the data enables less work",
        ),
        S(
            "cs.3.algorithms", "Algorithms", 3, "merge-sort-trace",
            "Merge sort transforms 7 2 5 1 by recursively splitting it into two pairs, ordering each pair, and merging 2 7 with 1 5 to produce 1 2 5 7.",
            "Merge sort uses divide, recurse, and combine. Each merge is linear in the items merged; across logarithmically many split levels, total time grows on the order of n log n.",
            "flow", steps=(("INPUT", "[7, 2, 5, 1]"), ("SPLIT", "[7, 2] | [5, 1]"), ("SORT SUBPROBLEMS", "[2, 7] | [1, 5]"), ("MERGE", "[1, 2, 5, 7]")),
            footer="divide recursively, then merge in order: O(n log n)",
        ),
        S(
            "cs.3.oop", "Object-Oriented Programming", 3, "class-object-structure",
            "A Vehicle class containing speed and move branches to Bike and Car subclasses; two bike objects then hold different speed values despite sharing behavior.",
            "A class defines fields and behavior, while each object has its own state. Inheritance can share an interface or implementation, but composition is often preferable when the relation is not truly is-a.",
            "network", columns=(("CLASS", (("vehicle", "Vehicle\nfield: speed\nmethod: move()"),)), ("SUBCLASSES", (("bike", "Bike\ninherits move(); adds ringBell()"), ("car", "Car\ninherits move(); adds refuel()"))), ("BIKE OBJECTS", (("b1", "Bike b1\nspeed = 12"), ("b2", "Bike b2\nspeed = 20")))), edges=(("vehicle", "bike", "subclass"), ("vehicle", "car", "subclass"), ("bike", "b1", "instance"), ("bike", "b2", "instance")),
            footer="shared class behavior does not merge each object's state",
        ),
        S(
            "cs.3.web", "Building for the Web", 3, "web-three-layers",
            "A web button is built in layers: HTML supplies the button element, CSS sets its visible style, JavaScript handles a click, and the browser combines them into interactive output.",
            "HTML describes document structure, CSS applies presentation, and JavaScript can update state and behavior. The browser parses and combines these resources into an accessible interface.",
            "layers", layers=(("HTML", '<button id="save">Save</button>'), ("CSS", "button { color: white; background: teal; }"), ("JAVASCRIPT", "on click -> status.textContent = 'Saved'"), ("BROWSER", "visible Save button; click announces Saved")),
            footer="structure + presentation + behavior become one interface",
        ),
        S(
            "cs.3.databases", "Databases", 3, "sql-filter",
            "A four-row books table is filtered by the SQL condition year at least 2020 and rating above 4, producing only the two rows that satisfy both predicates.",
            "A relational query transforms a table into a result relation. WHERE keeps rows for which the complete Boolean condition is true; it does not modify the stored table.",
            "trace", code=("SELECT title, year", "FROM books", "WHERE year >= 2020", "  AND rating > 4.0;"), states=("Atlas | 2018 | 4.7 -> reject year", "Moss | 2021 | 4.3 -> keep", "Cloud | 2022 | 3.9 -> reject rating", "Tide | 2024 | 4.8 -> keep", "RESULT: Moss 2021; Tide 2024"),
            code_heading="QUERY", state_heading="PREDICATE ON EACH ROW", footer="both WHERE conditions must be true for a row to appear",
            footer_size=24,
        ),
        S(
            "cs.3.hardware", "How Computers Work", 3, "one-bit-adder",
            "Two logic panels derive a one-bit half adder: XOR produces the sum bit and AND produces the carry bit, with input 1 and 1 yielding sum 0 and carry 1.",
            "Logic gates implement Boolean functions in hardware. For two one-bit inputs, XOR records whether exactly one input is one, while AND records the carry when both are one.",
            "compare", columns=(("SUM = A XOR B", ("00 -> 0", "01 -> 1", "10 -> 1", "11 -> 0")), ("CARRY = A AND B", ("00 -> 0", "01 -> 0", "10 -> 0", "11 -> 1"))),
            footer="A=1, B=1 represents binary 10: carry 1, sum 0",
        ),
        S(
            "cs.3.versioncontrol", "Tools of the Trade", 3, "branch-test-merge",
            "A main commit splits into feature and bug-fix branches, each passes tests, and both changes join through reviewed merge commits while preserving history.",
            "Version control records a graph of changes rather than one mutable file. Branches isolate work; automated tests and review provide evidence before integration, though they cannot prove absence of every bug.",
            "network", columns=(("BASE", (("a", "main: commit A"),)), ("BRANCHES", (("b", "feature: commit B"), ("c", "fix: commit C"))), ("GATES", (("tb", "tests + review B"), ("tc", "tests + review C"))), ("MAIN", (("m", "integrated history"),))), edges=(("a", "b", "branch"), ("a", "c", "branch"), ("b", "tb", "check"), ("c", "tc", "check"), ("tb", "m", "merge"), ("tc", "m", "merge")),
            footer="branches separate work; evidence gates integration",
        ),
        S(
            "cs.4.algorithms-adv", "Advanced Algorithms", 4, "shortest-path-relaxation",
            "A weighted graph sends paths from S through A or B to T; edge weights show S-A-T costs 7, S-B-T costs 6, and relaxation selects the lower distance six.",
            "Shortest-path algorithms maintain tentative distances and relax an edge when it gives a cheaper route. With nonnegative weights, Dijkstra's greedy finalization is correct under its stated invariant.",
            "network", columns=(("START", (("s", "S: distance 0"),)), ("FRONTIER", (("a", "A: 3"), ("b", "B: 5"))), ("TARGET", (("t", "T: min(3+4, 5+1) = 6"),))), edges=(("s", "a", "weight 3"), ("s", "b", "weight 5"), ("a", "t", "weight 4"), ("b", "t", "weight 1")),
            footer="relaxing B -> T improves the best known cost from 7 to 6",
            footer_size=24,
        ),
        S(
            "cs.4.theory", "Theory of Computation", 4, "dfa-ending-zero-one",
            "A three-state deterministic finite automaton tracks whether a binary string currently ends in 01; the accepting double-circle state is reached by input 1101.",
            "A finite automaton remembers only its current state. This DFA recognizes exactly the binary strings ending in 01; other computational models have different power, and some problems are undecidable by any algorithm.",
            "state", states=(("q0", "start / other", False), ("q1", "last symbol 0", False), ("q2", "ends in 01", True)), transitions=(("q0", "q0", "1"), ("q0", "q1", "0"), ("q1", "q1", "0"), ("q1", "q2", "1"), ("q2", "q1", "0"), ("q2", "q0", "1")),
            footer="trace 1,1,0,1: q0 -> q0 -> q0 -> q1 -> q2 (accept)",
            footer_size=24,
        ),
        S(
            "cs.4.os", "Operating Systems", 4, "operating-system-mediation",
            "Two application processes submit work to an operating-system scheduler, which time-slices one CPU, maps each virtual address space to physical memory, and mediates file and device access.",
            "An operating system multiplexes and protects resources. Processes see virtual abstractions; the kernel schedules CPU time, maps memory, and checks requests before drivers access hardware.",
            "layers", layers=(("PROCESSES", "P1 and P2 each see private virtual addresses"), ("KERNEL", "scheduler: P1 5 ms -> P2 5 ms; system-call boundary"), ("MEMORY", "page tables map virtual pages to protected physical frames"), ("FILES + DEVICES", "filesystem and drivers serialize checked I/O")),
            footer="virtual resources are mapped onto finite shared hardware",
        ),
        S(
            "cs.4.databases-adv", "Database Systems", 4, "database-guarantees",
            "Three panels connect a balanced index path to fewer page reads, a debit-credit transaction to atomic commit, and replicated log positions to a stated consistency rule.",
            "Database mechanisms solve different problems: indexes accelerate access, transactions preserve declared invariants, and replication improves availability or scale under an explicit consistency protocol.",
            "compare", columns=(("B-TREE INDEX", ("root -> branch -> matching leaf", "logarithmic page path")), ("TRANSACTION", ("BEGIN; debit 10; credit 10", "COMMIT both or ABORT both")), ("REPLICATION", ("ordered log positions", "acknowledgement rule defines visibility"))),
            footer="performance, atomicity, and consistency require different mechanisms",
            footer_size=23,
        ),
        S(
            "cs.4.ml", "Machine Learning", 4, "learning-evaluation-loop",
            "A supervised-learning pipeline separates labelled examples into training and held-out sets, adjusts parameters to reduce training loss, then measures unseen prediction errors without training on them.",
            "Machine learning estimates a rule from data rather than receiving every case explicitly. Held-out evaluation tests generalization; leakage or a shifted population can make a high score misleading.",
            "flow", steps=(("LABELLED DATA", "features x + target y"), ("SPLIT", "training set | untouched test set"), ("FIT", "update parameters to reduce training loss"), ("EVALUATE", "predict held-out y; inspect errors and groups")),
            footer="never use the held-out answers to tune the model being tested",
            footer_size=24,
        ),
        S(
            "cs.4.security", "Security & Cryptography", 4, "crypto-properties",
            "Encryption maps plaintext and a secret key plus nonce to ciphertext that the key can reverse, while hashing maps a message to a fixed digest and a threat model states the attacker capabilities.",
            "Encryption provides confidentiality only under assumptions about keys, nonces, algorithms, and attackers. Cryptographic hashes are designed for one-way integrity uses, not reversible secrecy.",
            "compare", columns=(("ENCRYPTION", ("Enc(key, nonce, plaintext)", "-> ciphertext", "Dec with key -> plaintext")), ("HASHING", ("Hash(message) -> digest", "same input, same digest", "not an encryption method")), ("THREAT MODEL", ("attacker reads network", "cannot obtain secret key", "nonce must not be reused when prohibited"))),
            footer="name the property and attacker before choosing a primitive",
        ),
        S(
            "cs.4.systems", "Systems Programming", 4, "pointer-state",
            "A C-like trace stores integer x at address 0x1000, points p at that address, writes 43 through p, and shows x changing from 42 to 43 in the same memory cell.",
            "A pointer value is an address interpreted with a type. Dereferencing accesses the pointed-to object only while its lifetime and bounds are valid; an invalid address causes undefined behavior in C.",
            "trace", code=("int x = 42;", "int *p = &x;", "*p = 43;", "printf(\"%d\", x);"), states=("0x1000: x stores 42", "p stores 0x1000", "*p selects cell 0x1000", "cell changes to 43; output is 43"),
            code_heading="C-LIKE CODE", state_heading="MEMORY STATE", footer="p and &x identify one live cell; *p reads or writes it",
            footer_size=24,
        ),
        S(
            "cs.5.deep-learning", "Deep Learning & AI", 5, "transformer-training",
            "A transformer pipeline turns tokens into vectors, uses attention to mix context-dependent information, predicts next-token probabilities, computes loss against a target and propagates gradients to update parameters.",
            "Transformers learn parameters by optimizing prediction loss over examples. Attention forms weighted combinations of representations; a fluent output is still a probabilistic model result, not a guarantee of truth.",
            "cycle", steps=(("TOKENS", "river | bank | was"), ("ATTENTION", "context weights disambiguate bank"), ("PREDICT", "next-token probability distribution"), ("LOSS + UPDATE", "compare target; backpropagate gradients")),
            footer="training changes parameters; inference uses the learned parameters",
            footer_size=24,
        ),
        S(
            "cs.5.distributed", "Distributed Systems", 5, "majority-commit",
            "A three-node replicated log accepts command x equals 7 at the leader, receives one follower acknowledgement while another follower is offline, reaches a two-of-three majority and then commits entry 42.",
            "In a majority-based consensus protocol, replication to a quorum can allow progress despite one unavailable node. Exact safety also depends on term, log-matching, and leader-election rules not compressed into this trace.",
            "flow", steps=(("PROPOSE", "client sends x = 7"), ("APPEND", "leader writes log entry 42"), ("REPLICATE", "follower 1 acks; follower 2 offline"), ("COMMIT", "2 of 3 store entry -> apply x = 7")),
            footer="a majority intersects every later majority, preserving evidence of commit",
            footer_size=23,
        ),
        S(
            "cs.5.pl-theory", "Programming Language Theory", 5, "typed-reduction",
            "The typed lambda term lambda x of integer type, x plus 1, applied to 4 is type-checked, substitutes 4 for x, and reduces in one arithmetic step to integer 5.",
            "A type judgment predicts which terms may be evaluated, while operational semantics defines each reduction step. For this term, substitution preserves the integer type and evaluation produces five.",
            "layers", layers=(("TERM", "(lambda x:Int. x + 1) 4"), ("TYPE", "x:Int entails x+1:Int; argument 4:Int; whole term:Int"), ("BETA REDUCE", "substitute 4 for free occurrences of x -> 4 + 1"), ("EVALUATE", "4 + 1 -> 5 : Int")),
            footer="typing classifies the term; semantics explains how it runs",
        ),
        S(
            "cs.5.quantum", "Quantum Computing", 5, "hadamard-interference",
            "An ideal qubit starts in state zero, one Hadamard gate creates equal positive zero and one amplitudes, and a second Hadamard makes the one-path amplitudes cancel so measurement returns zero.",
            "Quantum gates transform amplitudes, including their signs or phases. Applying H twice is the identity: constructive interference restores the amplitude of state zero and destructive interference cancels state one.",
            "flow", steps=(("PREPARE", "|0> amplitudes: (1, 0)"), ("FIRST H", "(|0> + |1>) / sqrt(2)"), ("SECOND H", "|0> paths add; |1> paths cancel"), ("MEASURE", "ideal result: 0 with probability 1")),
            footer="H x H = I: interference depends on amplitudes, not hidden coin flips",
            footer_size=23,
        ),
        S(
            "cs.5.frontier", "Research Frontiers", 5, "spec-counterexample-loop",
            "A research loop translates a safety claim into a formal specification, verifies a bounded model, tests the running system adversarially, and feeds any counterexample back into the claim and design.",
            "Verification can prove a specified property of a model under explicit assumptions; testing samples behavior of an implementation. Neither alone settles alignment, specification quality, or behavior outside the model.",
            "cycle", steps=(("CLAIM", "state the intended safety property"), ("FORMALIZE", "model, assumptions, invariant"), ("CHECK", "proof/model checker + adversarial tests"), ("COUNTEREXAMPLE", "refine specification, model, or system")),
            footer="a proof is only as relevant as its property, model, and assumptions",
            footer_size=23,
        ),
    )
}
