"""Lesson-specific explanatory plates for every unillustrated language lesson."""

from __future__ import annotations

from .core import spec


def S(node_id, title, stage, slug, alt, caption, kind, **payload):
    payload["kind"] = kind
    return spec(node_id, title, stage, slug + "-plate", alt, caption, payload)


SPECS = {
    item["id"]: item
    for item in (
        S(
            "lang.0.phonics", "Letter Sounds", 0, "sound-blending",
            "The written word cat is separated into C, A and T, matched to three speech sounds, then blended back into the spoken word cat.",
            "Phonics links graphemes with phonemes and blends the phonemes in sequence. English mappings are useful but not perfectly one-to-one: the same letter can represent different sounds.",
            "flow", steps=(("SEE", "C  A  T"), ("SAY", "k sound | short-a sound | t sound"), ("BLEND", "k-a-t"), ("WORD", "cat")),
            footer="letters -> sounds -> a spoken word",
        ),
        S(
            "lang.0.rhymes", "Rhymes and Songs", 0, "rhyme-rhythm",
            "Cat, hat and sun are split into beginning and ending sound groups; cat and hat share the ending at while four beat marks show a steady pulse.",
            "A rhyme repeats a final stressed vowel and following sounds, as cat and hat do. Rhythm is a separate pattern of beats, so a poem can have rhythm without every line rhyming.",
            "compare", columns=(("CAT", ("c + AT", "shared ending")), ("HAT", ("h + AT", "shared ending")), ("SUN", ("s + UN", "different ending")), ("BEAT", ("1 | 2 | 3 | 4", "steady pulse"))),
            footer="cat and hat rhyme; the beat can continue underneath",
            footer_size=25,
        ),
        S(
            "lang.0.stories", "Story Time", 0, "story-clues",
            "A story map follows Mina in a garden from a missing key through searching under leaves to finding the key, with who and where identified first.",
            "Listeners can reconstruct a story by tracking its character and setting, then arranging events causally: Mina loses a key, searches, and finds it under the leaves.",
            "flow", steps=(("WHO + WHERE", "Mina in the garden"), ("PROBLEM", "the key is missing"), ("ACTION", "she searches under leaves"), ("OUTCOME", "the key is found")),
            footer="who + where anchor what happened",
        ),
        S(
            "lang.0.speaking", "Talking and Listening", 0, "conversation-turns",
            "Four linked stages form a conversation loop: one person asks, the other listens, answers the question, and checks whether the message was understood.",
            "Conversation is coordinated turn-taking. A relevant response depends on listening to the previous turn, and a check or follow-up question repairs misunderstandings.",
            "cycle", steps=(("ASK", "What did you build?"), ("LISTEN", "hold the question in mind"), ("ANSWER", "I built a tall bridge"), ("CHECK", "Do you mean this one?")),
            footer="each new turn responds to the turn before it",
        ),
        S(
            "lang.1.spelling", "Spelling", 1, "sound-to-spelling",
            "The spoken word ship is segmented into three ordered phonemes, mapped to the graphemes SH, I and P, then checked against the complete written word.",
            "Segmenting speech helps select graphemes in order. Ship has three phonemes but four letters because the digraph SH represents one phoneme; English spellings still need visual or dictionary checks.",
            "flow", steps=(("SAY", "ship"), ("SEGMENT", "sh sound | short-i sound | p sound"), ("MAP", "SH | I | P"), ("CHECK", "ship: 3 sounds, 4 letters")),
            footer="keep every sound in order, then verify the spelling",
        ),
        S(
            "lang.1.vocabulary", "Word Collecting", 1, "precise-word-scale",
            "Three word choices climb an intensity scale from big through huge to enormous, then the strongest word is used in the sentence An enormous wave crossed the wall.",
            "Vocabulary adds distinctions, not just substitutes. Choosing enormous rather than big encodes greater scale, while context determines whether that stronger word is accurate.",
            "layers", layers=(("GENERAL", "big"), ("STRONGER", "huge"), ("MOST INTENSE", "enormous"), ("IN CONTEXT", "An enormous wave crossed the wall.")),
            footer="a precise word carries the exact degree you mean",
        ),
        S(
            "lang.1.sentences", "Sentences", 1, "complete-sentence",
            "The sentence The dog ran fast is assembled from a capitalized subject, a predicate that completes the thought, and a full stop at the end.",
            "A written English sentence expresses a complete clause and marks its boundary. Here The dog is the subject, ran fast is the predicate, and capitalization plus punctuation show the limits.",
            "flow", steps=(("START", "capital T"), ("SUBJECT", "The dog"), ("PREDICATE", "ran fast"), ("END", "full stop .")),
            footer="The dog + ran fast + . = one complete sentence",
        ),
        S(
            "lang.1.handwriting", "Handwriting", 1, "legible-letter-process",
            "A handwriting sequence shows a relaxed grip, baseline and midline guides, the ordered strokes for a lowercase a, and a final check for size and spacing.",
            "Legibility comes from repeatable letter formation, alignment, spacing, and a comfortable grip. Checking the result matters more than writing quickly.",
            "flow", steps=(("SET UP", "gentle grip; paper steady"), ("USE GUIDES", "midline ----- baseline"), ("FORM a", "round stroke, then downstroke"), ("CHECK", "even size and a clear gap")),
            footer="consistent strokes + alignment + spacing make writing readable",
            footer_size=25,
        ),
        S(
            "lang.1.childrens-lit", "Great Children's Books", 1, "reading-response",
            "A passage detail about a character returning a lost purse branches into an inference about honesty, a question about motive, and a personal response supported by the detail.",
            "Talking about literature becomes stronger when a response points back to the text. One detail can support an inference, invite a question, and lead readers to compare interpretations.",
            "tree", root=("TEXTUAL DETAIL", "She returned the lost purse unopened."), leaves=(("INFER", "the action suggests honesty"), ("ASK", "why was the choice difficult?"), ("RESPOND", "I admired the choice because...")),
            footer="a thoughtful response returns to evidence in the story",
        ),
        S(
            "lang.1.writing-stories", "Writing Your Own Stories", 1, "story-arc",
            "A three-part story arc introduces Leo and a kite, creates the problem of the kite catching in a tree, and resolves it when a neighbor brings a ladder.",
            "A beginning establishes the character and situation, a middle changes that situation with a problem, and an ending shows the consequence or resolution.",
            "flow", steps=(("BEGINNING", "Leo launches a red kite"), ("MIDDLE", "the kite catches in a tree"), ("ENDING", "a neighbor's ladder frees it")),
            footer="each part changes what can happen next",
        ),
        S(
            "lang.1.dictionary", "Using a Dictionary", 1, "dictionary-search",
            "A lookup for cater narrows alphabetically from the C section to CA, then CAT, and finally compares cat, catch, cater and cattle in order.",
            "Dictionary guide words support repeated alphabetical decisions. When first letters match, compare the second, third, and later letters until the target position is determined.",
            "flow", steps=(("FIRST", "C section"), ("SECOND", "CA pages"), ("THIRD", "CAT group"), ("ORDER", "cat < catch < cater < cattle")),
            footer="compare the next letter whenever earlier letters tie",
        ),
        S(
            "lang.2.grammar", "Grammar", 2, "clause-structure",
            "A clause diagram places The fox jumps over logs at the root, then separates the noun phrase The fox from the verb phrase jumps over logs and labels their roles.",
            "Grammar describes relationships inside a sentence. This clause divides into a noun phrase functioning as subject and a verb phrase functioning as predicate; words form nested constituents.",
            "tree", root=("CLAUSE", "The fox jumps over logs."), leaves=(("NOUN PHRASE", "The + fox\nsubject"), ("VERB PHRASE", "jumps + over logs\npredicate")),
            footer="words combine into phrases; phrases combine into a clause",
        ),
        S(
            "lang.2.paragraphs", "Paragraphs and Essays", 2, "paragraph-logic",
            "A paragraph plan connects a topic sentence about street trees to temperature evidence, explains the shade mechanism, and links the result back to the claim.",
            "A coherent paragraph does more than list facts: its evidence must support the topic sentence, and its explanation must make that relevance explicit.",
            "flow", steps=(("CLAIM", "Street trees cool a block"), ("EVIDENCE", "shaded pavement measured cooler"), ("EXPLAIN", "leaves block radiation and release water"), ("LINK", "so planting changes local heat")),
            footer="claim -> evidence -> explanation -> warranted link",
        ),
        S(
            "lang.2.poetry", "Poetry", 2, "poetic-patterns",
            "Three aligned panels distinguish two repeated metrical feet, a shared final sound, and the image a silver path across the sea, then connect them to an effect.",
            "Meter organizes stressed and unstressed syllables, sound patterning links words acoustically, and imagery evokes sensory experience. These devices can reinforce one another without being identical.",
            "compare", columns=(("RHYTHM", ("da-DUM | da-DUM", "two repeated feet")), ("SOUND", ("light / night", "shared final sound")), ("IMAGE", ("a silver path across the sea", "visual detail"))),
            footer="form shapes how an image is heard and remembered",
        ),
        S(
            "lang.2.mythology", "Myths and Legends", 2, "myth-comparison",
            "Three traditions are compared without merging them: Gilgamesh confronts mortality, the Odyssey centers homecoming, and Sundiata connects a founder to communal history.",
            "Comparative reading can trace recurring questions while preserving cultural differences. These works arise from distinct languages, genres, performance histories, and communities.",
            "compare", columns=(("GILGAMESH", ("Mesopotamian epic", "mortality and kingship")), ("ODYSSEY", ("ancient Greek epic", "homecoming and identity")), ("SUNDIATA", ("Mande epic tradition", "founding and communal memory"))),
            footer="compare a question; do not erase each tradition's context",
            footer_size=25,
        ),
        S(
            "lang.2.novels", "Reading Novels", 2, "novel-tracking",
            "A novel tracker links a character's changing goal, three causally connected plot events, and a setting shift from village to city across chapters.",
            "Long-form reading becomes manageable when character, plot, and setting are tracked together. An event matters because it changes a goal, relationship, or later possibility.",
            "layers", layers=(("CHARACTER", "Asha wants independence -> learns to accept help"), ("PLOT", "letter arrives -> journey begins -> choice is tested"), ("SETTING", "village, then city: new constraints and opportunities"), ("SYNTHESIS", "the new setting pressures the character's goal")),
            footer="track change across chapters, not isolated events",
        ),
        S(
            "lang.2.research", "Finding Things Out", 2, "source-corroboration",
            "A bridge-date question compares an archive plan, a newspaper report, and a dated museum photograph before separating construction from opening dates.",
            "Reliable research compares relevant, traceable sources and checks whether they are independent. Agreement is stronger when sources do not merely copy one another.",
            "network", columns=(("QUESTION", (("q", "When was the bridge built?"),)), ("SOURCES", (("a", "archive plan: 1928"), ("b", "newspaper: opened 1930"), ("c", "museum photo: 1929 works"))), ("ANSWER", (("z", "built 1928-29; opened 1930"),))), edges=(("q", "a", "search"), ("q", "b", "search"), ("q", "c", "search"), ("a", "z", "combine"), ("b", "z", "combine"), ("c", "z", "combine")),
            footer="separate construction evidence from the opening date",
        ),
        S(
            "lang.2.etymology", "Where Words Come From", 2, "word-family-history",
            "The Latin verb portare, meaning to carry, branches through historical borrowing and word formation into portable, import and export, with prefixes changing direction.",
            "Etymology traces attested forms and pathways, not just visual resemblance. The English family around port reflects a borrowed Latin root, while im- and ex- contribute inward and outward senses.",
            "tree", root=("LATIN ROOT", "portare = to carry"), leaves=(("PORTABLE", "able to be carried"), ("IMPORT", "carry in"), ("EXPORT", "carry out")),
            footer="a shared root explains meaning only when history supports it",
        ),
        S(
            "lang.2.speaking", "Public Speaking", 2, "speech-argument",
            "A short talk moves from a clear claim through one concrete example and an explanation to a concise takeaway directed to the audience.",
            "A listener can follow a talk when its signposts expose the reasoning. Evidence becomes persuasive only after the speaker explains how it supports the claim.",
            "flow", steps=(("CLAIM", "Our pond needs shade"), ("EXAMPLE", "summer water reached 30 C"), ("REASON", "shade reduces solar heating"), ("TAKEAWAY", "plant suitable bank trees")),
            footer="tell listeners where the argument is going",
        ),
        S(
            "lang.3.literature", "Literature", 3, "close-reading",
            "A repeated locked-door image connects two quoted details to a pattern of exclusion and then to a qualified thematic interpretation about belonging.",
            "Close reading moves from observable language to pattern and interpretation. A theme is an argued meaning supported by multiple details, not a hidden label attached to one symbol.",
            "flow", steps=(("DETAIL 1", "the door stayed locked"), ("DETAIL 2", "again, the key turns away"), ("PATTERN", "repeated barriers exclude the speaker"), ("INTERPRET", "belonging is made conditional")),
            footer="interpretation is strongest when the textual chain stays visible",
            footer_size=25,
        ),
        S(
            "lang.3.shakespeare", "Shakespeare", 3, "comic-tragic-shapes",
            "Two dramatic structures are contrasted: a comedy moves from blocked relationships through recognition to social reunion, while a tragedy moves from choice through reversal to irreversible loss.",
            "Shakespearean comedies and tragedies vary, but genre expectations shape audience inference. Comic recognition often enables renewed social order; tragic action makes loss difficult or impossible to undo.",
            "compare", columns=(("COMEDY", ("desire is blocked", "confusion compounds", "recognition", "reunion or marriage")), ("TRAGEDY", ("high-stakes choice", "reversal", "recognition too late", "irreversible loss"))),
            footer="genre changes what an ending can resolve",
        ),
        S(
            "lang.3.world-lit", "World Literature", 3, "world-text-context",
            "An epic comparison aligns the Epic of Gilgamesh, Mahabharata and Sundiata by transmission form, central question and cultural setting rather than treating them as interchangeable.",
            "World literature requires both comparison and context. Translation and circulation make texts travel, but form, performance, and historical setting continue to shape what each work means.",
            "compare", columns=(("GILGAMESH", ("clay-tablet witnesses", "kingship and mortality")), ("MAHABHARATA", ("Sanskrit epic tradition", "duty amid kinship conflict")), ("SUNDIATA", ("Mande oral performance", "founding and memory"))),
            footer="read across borders while keeping historical differences in view",
            footer_size=24,
        ),
        S(
            "lang.3.rhetoric", "Rhetoric", 3, "rhetorical-appeals",
            "One proposal to add a crossing is supported three ways: ethos cites an engineer, pathos evokes a child's risky walk, and logos compares traffic counts and stopping distance.",
            "Ethos concerns credibility, pathos addresses emotion, and logos develops reasoning. They can work together, but none excuses false evidence or an invalid inference.",
            "tree", root=("PROPOSAL", "Add a marked pedestrian crossing."), leaves=(("ETHOS", "transport engineer reviews the site"), ("PATHOS", "children currently cross fast traffic"), ("LOGOS", "counts + stopping distance support placement")),
            footer="persuasion is ethical only when its evidence remains honest",
        ),
        S(
            "lang.3.essays", "The Essay", 3, "argument-structure",
            "A five-step essay map links a qualified thesis to source evidence, an explicit warrant, a cost counterargument, and a bounded pilot-study conclusion.",
            "An argument earns its conclusion by making warrants visible and confronting relevant objections. Qualification is a strength when the evidence supports a limited claim.",
            "flow", steps=(("THESIS", "Later buses may improve attendance"), ("EVIDENCE", "attendance falls after missed transfers"), ("WARRANT", "missed transfers explain some absences"), ("COUNTER", "a later route costs more"), ("JUDGMENT", "pilot one route; measure both effects")),
            footer="a good conclusion is no broader than its evidence",
        ),
        S(
            "lang.3.linguistics-intro", "How Language Works", 3, "language-levels",
            "The utterance Cats sleep is analyzed from contrasting speech sounds to the plural morpheme cat plus s, then the noun phrase and verb phrase, and finally its compositional meaning.",
            "Language is organized at interacting levels. Phonemes distinguish forms, morphemes contribute meaning or grammar, syntax combines constituents, and semantics interprets the result.",
            "layers", layers=(("PHONEMES", "contrastive speech sounds distinguish word forms"), ("MORPHEMES", "cat + -s = plural noun"), ("SYNTAX", "[NP Cats] [VP sleep]"), ("SEMANTICS", "more than one cat is sleeping")),
            footer="small contrasts combine into structured meaning",
        ),
        S(
            "lang.3.media", "Media Literacy", 3, "framing-same-data",
            "The same outcome of 90 successes among 100 trials is framed as a 90 percent success headline and a 10 percent failure headline, both pointing back to one data table.",
            "Framing changes emphasis without necessarily changing the underlying numbers. A critical reader returns to the denominator, method, source, and omitted comparison before judging either headline.",
            "tree", root=("SOURCE DATA", "90 succeeded; 10 did not; n = 100"), leaves=(("FRAME A", "Nine in ten succeed"), ("FRAME B", "One in ten does not succeed"), ("CHECK", "Who was counted? Compared with what?")),
            footer="trace every headline back to the same underlying evidence",
        ),
        S(
            "lang.3.second-language", "A Second Language", 3, "language-practice-loop",
            "A daily learning loop connects comprehensible input, noticing a useful phrase, retrieving it from memory, using it in conversation and receiving corrective feedback.",
            "Frequent retrieval and meaningful use strengthen access to a second language. Feedback updates a learner's hypothesis, while spaced return is more useful than one long exposure.",
            "cycle", steps=(("INPUT", "hear a phrase in context"), ("NOTICE", "connect form and meaning"), ("RETRIEVE", "recall without copying"), ("USE + FEEDBACK", "speak, adjust, return later")),
            footer="short, spaced cycles turn recognition into usable language",
        ),
        S(
            "lang.4.linguistics", "Linguistics", 4, "formal-linguistic-analysis",
            "Four branches analyze Those dogs bark as a sound phrase, plural-agreement morphology, the syntax noun phrase plus verb phrase, and a compositional proposition.",
            "Formal analysis separates but connects phonological form, morphosyntactic features, constituent structure, and semantic composition. Evidence determines which representation is appropriate.",
            "tree", root=("CLAUSE", "Those dogs bark."), leaves=(("PHONOLOGY", "prosodic phrase and sound contrasts"), ("MORPHOSYNTAX", "dog + PL; demonstrative agrees"), ("SYNTAX", "[NP those dogs] [VP bark]"), ("SEMANTICS", "bark'(the contextually identified dogs)")),
            footer="each level models a different, testable regularity",
        ),
        S(
            "lang.4.lit-theory", "Literary Theory", 4, "reading-lenses",
            "Four critical approaches ask different questions of the same unnamed text: formal pattern, historical conditions, reader response and instability in its oppositions.",
            "A critical lens foregrounds particular evidence and questions; it is not a machine that guarantees one answer. Interpretations remain accountable to the text and their stated assumptions.",
            "compare", columns=(("FORMAL", ("pattern, voice, structure", "How do parts interact?")), ("HISTORICAL", ("institutions and archive", "What conditions shaped it?")), ("READER", ("situated response", "How is meaning activated?")), ("POST-STRUCTURAL", ("tensions in oppositions", "Where does language unsettle itself?"))),
            footer="different questions disclose different relations in the same text",
            footer_size=23,
        ),
        S(
            "lang.4.creative", "Creative Writing", 4, "revision-cycle",
            "A revision cycle turns The storm was bad into Rain hammered the tin roof by identifying vague language, selecting sensory evidence and checking whether the new verb fits the scene.",
            "Revision is a sequence of decisions, not mere polishing. A writer diagnoses what the draft fails to convey, changes specific language, then rereads for accuracy, rhythm, and consequence.",
            "cycle", steps=(("DRAFT", "The storm was bad."), ("DIAGNOSE", "bad is vague; no sensory detail"), ("REVISE", "Rain hammered the tin roof."), ("REREAD", "Does hammered fit the scene and voice?")),
            footer="revision changes the reader's experience, not just the surface",
        ),
        S(
            "lang.4.history-english", "History of English", 4, "knight-word-history",
            "A timeline follows Old English cniht with pronounced initial consonants through Middle English knyght to present-day knight, where the k and gh are no longer pronounced.",
            "English changes in sound, spelling, meaning, and grammar at different rates. Knight preserves letters associated with earlier pronunciations; spelling is historical evidence, not a phonetic transcript.",
            "timeline", events=(("OLD ENGLISH", "cniht: initial k and fricative pronounced"), ("MIDDLE ENGLISH", "knyght: spelling and sound keep changing"), ("EARLY MODERN", "major sound changes; print favors stable spellings"), ("PRESENT", "knight sounds like 'nite'; older letters remain")),
            footer="pronunciation changed faster than the conventional spelling",
        ),
        S(
            "lang.4.classics", "The Ancient Canon", 4, "epic-reception",
            "A chain links Homeric epic conventions to Virgil's selective Roman adaptation and then to later readers who translate, imitate, contest and reinterpret both traditions.",
            "Classical reception is active transformation. The Aeneid draws on Homeric forms while redirecting them toward Roman history; later works inherit choices, not an unchanged universal template.",
            "flow", steps=(("HOMERIC EPIC", "invocation, journey, battle, simile"), ("VIRGIL", "reworks inherited forms for Roman questions"), ("TRANSMISSION", "manuscripts, teaching, translation"), ("RECEPTION", "later writers imitate, revise, resist")),
            footer="influence is a traceable relation of reuse and change",
        ),
        S(
            "lang.4.comp-lit", "Comparative Literature", 4, "comparative-method",
            "Three columns compare Text A's form and setting, two translation priorities, and Text B's different tradition and stakes before limiting the comparison.",
            "Comparative literature distinguishes textual evidence, translation decisions, and context. A productive comparison names a shared problem while showing how each work handles it differently.",
            "compare", columns=(("TEXT A", ("wording and form", "language + historical setting")), ("TRANSLATION", ("choice A: preserve rhythm", "choice B: preserve idiom")), ("TEXT B", ("different tradition", "similar question, different stakes"))),
            footer="compare relations, not decontextualized plot summaries",
        ),
        S(
            "lang.5.philology", "Philology and Textual Criticism", 5, "manuscript-stemma",
            "A manuscript stemma connects a lost archetype to two intermediate copies and three surviving witnesses; B and C share one copied error while D preserves another reading.",
            "Textual critics compare variants and shared errors to infer relationships among witnesses. A stemma is a revisable historical hypothesis, and the oldest surviving manuscript is not automatically best.",
            "network", columns=(("INFERRED", (("a", "*A: lost archetype"),)), ("COPIES", (("x", "*x: introduces shared error"), ("y", "*y: different branch"))), ("WITNESSES", (("b", "B: ...sea..."), ("c", "C: ...sea..."), ("d", "D: ...see...")))), edges=(("a", "x", "copy"), ("a", "y", "copy"), ("x", "b", "copy"), ("x", "c", "copy"), ("y", "d", "copy")),
            footer="shared innovations reveal descent; readings still need evaluation",
            footer_size=24,
        ),
        S(
            "lang.5.socioling", "Sociolinguistics", 5, "register-variation",
            "One speaker expresses the same request differently to a close friend, in a seminar and in a formal application, while audience, purpose and identity shift together.",
            "Register varies with situation, relationship, medium, and purpose. Variation is systematic social meaning, not evidence that one community's everyday variety lacks grammar.",
            "compare", columns=(("FRIEND", ("Can you send it?", "shared context; informal")), ("SEMINAR", ("Could you share the source?", "disciplinary audience")), ("APPLICATION", ("Please provide the cited record.", "formal written request"))),
            footer="speakers style-shift; every dialect has structured patterns",
        ),
        S(
            "lang.5.psycholing", "Psycholinguistics", 5, "incremental-reanalysis",
            "An incremental parser first treats the baby as the object in While Anna dressed the baby, then reaches played, detects a conflict and revises to two clauses.",
            "Comprehension is incremental and prediction can produce a garden path. In While Anna dressed the baby played, played forces reanalysis: Anna dressed herself, and the baby played.",
            "flow", steps=(("INPUT", "While Anna dressed ..."), ("PREDICT", "expect a possible object"), ("GARDEN PATH", "... the baby ... initially attached as object"), ("REANALYZE", "played -> [Anna dressed] [the baby played]")),
            footer="later evidence can force the parser to revise an earlier structure",
            footer_size=24,
        ),
        S(
            "lang.5.comp-ling", "Computational Linguistics", 5, "corpus-to-analysis",
            "A computational pipeline moves from a documented corpus through tokenization and representation to a dependency parser or next-token model, then evaluates held-out predictions and errors.",
            "Computational linguistics turns linguistic hypotheses into representations and measurable tasks. Performance on held-out data is evidence about a model under that dataset, not proof of human-like understanding.",
            "layers", layers=(("CORPUS", "sampled texts + metadata + usage rights"), ("REPRESENT", "tokens, features, embeddings, or linguistic annotations"), ("MODEL", "estimate a parse or probability of the next token"), ("EVALUATE", "held-out accuracy, calibration, subgroup errors")),
            footer="a model claim is bounded by its task, data, and evaluation",
        ),
        S(
            "lang.5.narratology", "Narratology and Critical Theory", 5, "story-discourse",
            "Three panels distinguish chronological story events A then B then C, narrated discourse ordered C then A then B, and focalization that limits which character's knowledge reaches the reader.",
            "Narratology separates what happens from how it is presented. Reordering, duration, narration, and focalization guide inference without altering the underlying event chronology.",
            "compare", columns=(("STORY", ("A departure", "B discovery", "C return", "chronological events")), ("DISCOURSE", ("C return", "A departure", "B discovery", "narrated order")), ("FOCALIZATION", ("reader knows what one observer perceives", "other knowledge is withheld"))),
            footer="the same events produce different effects through presentation",
        ),
    )
}
