"""Authored reasoning relationships for every new radiology plate.

Each record supplies the smallest clinically useful chain the plate should make
visible.  The curriculum remains the source of full teaching detail; these
records deliberately avoid simulating scans or adding unsupported precision.
"""

from __future__ import annotations

from typing import Dict, List, Tuple


def I(label: str, detail: str, mark: str = "") -> Dict[str, str]:
    return {"label": label, "detail": detail, "mark": mark}


def R(node_id: str, mode: str, motif: str, takeaway: str,
      first: Dict[str, str], second: Dict[str, str], third: Dict[str, str],
      *, headings: Tuple[str, str, str] = ()) -> Dict[str, object]:
    record: Dict[str, object] = {
        "id": node_id,
        "mode": mode,
        "motif": motif,
        "takeaway": takeaway,
        "items": [first, second, third],
    }
    if headings:
        record["headings"] = headings
    return record


_RECORDS: List[Dict[str, object]] = [
    # Foundations, acquisition, reporting, intervention
    R("rad.3.contrast", "physics", "scanner",
      "Contrast earns its risk only when enhancement changes the clinical answer.",
      I("Question", "Start with the tissue and phase the diagnosis requires.", "contrast"),
      I("Enhancement", "Agent timing turns vascularity and perfusion into visible evidence.", "contrast"),
      I("Safety", "Screen the patient; prepare for reaction and kidney risk.", "contrast")),
    R("rad.2.radiation-safety", "flow", "scanner",
      "Justify first, then use the lowest exposure that still answers the question.",
      I("Justify the examination", "Proceed only when imaging can answer a clinical question and change care.", "question"),
      I("Choose and optimise", "Use ultrasound or MRI when suitable; otherwise match dose and scanned range to the task.", "as low as useful"),
      I("Verify and review", "Check the delivered exposure and give children and repeated examinations extra scrutiny.", "review"),
      headings=("JUSTIFY FIRST", "CHOOSE & OPTIMISE", "VERIFY & REVIEW")),
    R("rad.3.mri-sequences", "compare", "scanner",
      "Fluid, fat, diffusion and enhancement identify the sequence before interpretation begins.",
      I("T1 pattern", "Fat is usually bright; fluid is usually dark.", "mri"),
      I("T2 / fluid", "Water-rich tissue becomes conspicuous on fluid-sensitive imaging.", "sequence"),
      I("DWI / ADC", "Restricted diffusion needs high DWI and low ADC together.", "signal")),
    R("rad.2.modalities", "compare", "scanner",
      "Choose the modality by the physical property that can answer the question.",
      I("Radiograph / CT", "Both use X-ray attenuation: projection radiography excels at gas and bone, while CT localises attenuation and is sensitive to acute blood.", "xray-ct"),
      I("Ultrasound / MRI", "Echoes show interfaces and motion; magnetic signal distinguishes soft tissues without ionising radiation.", "ultrasound-mri"),
      I("Nuclear medicine", "A radiotracer's distribution reports physiology rather than anatomy alone.", "nuclear-tracer")),
    R("rad.5.ultrasound-physics", "physics", "scanner",
      "Every ultrasound setting trades one kind of information for another.",
      I("Transmit", "Higher frequency improves detail but penetrates less deeply.", "signal"),
      I("Echo / Doppler", "Angle, velocity scale and tissue boundaries shape the signal.", "signal"),
      I("Interpret", "Artefacts can disclose interfaces, flow and hidden material.", "signal")),
    R("rad.5.biopsy-safety", "flow", "vessel",
      "A diagnostic target is useful only when the route and rescue plan are safe.",
      I("Plan tract and haemostasis", "Choose a route that avoids vulnerable structures and future surgical planes; assess and correct coagulopathy first.", "biopsy-plan"),
      I("Guide tip and path", "Use real-time or intermittent image guidance to confirm the needle tip and entire safe path while sampling or draining.", "biopsy-guidance"),
      I("Monitor and rescue", "Observe for bleeding or organ injury, and have a defined plan to treat and escalate complications.", "biopsy-rescue"),
      headings=("ASSESS & PLAN", "IMAGE-GUIDED CONTROL", "MONITOR & RESCUE")),
    R("rad.4.oncology-response", "scale", "scanner",
      "Comparable targets and comparable technique make interval change interpretable.",
      I("Select targets", "Choose measurable lesions and record a reproducible baseline.", "baseline"),
      I("Sum diameters", "Repeat the same measurements and assign the response category.", "interval"),
      I("Confirm exceptions", "Apparent immune-related growth may require confirmation.", "confirm")),
    R("rad.4.structured-reporting", "flow", "scanner",
      "A report is complete when the finding reaches a named action and owner.",
      I("Describe", "Use a fixed template so decisive negatives are not omitted.", "image"),
      I("Categorise when valid", "Use a validated RADS system only for the population, indication and technique it was designed to cover.", "category"),
      I("Close the loop", "Urgent or unexpected findings need acknowledged communication to a named owner.", "action"),
      headings=("EVIDENCE", "VALIDATED SYSTEM", "COMMUNICATE")),
    R("rad.5.ir-basics", "flow", "vessel",
      "Intervention joins image guidance to a planned endpoint and complication response.",
      I("Access", "Choose the vessel or cavity and a route that can be closed.", "flow"),
      I("Treat", "Match embolic or catheter behaviour to the intended level.", "occlusion"),
      I("Check", "Confirm the endpoint and look immediately for complications.", "flow"),
      headings=("PLAN ACCESS", "DELIVER TREATMENT", "CONFIRM ENDPOINT")),

    # Thorax
    R("rad.5.airways", "compare", "lungs",
      "Airway calibre, distribution and expiratory change separate airway disorders.",
      I("Bronchiectasis", "Airway exceeds its artery and fails to taper.", "mass"),
      I("Small airways", "Tree-in-bud or expiratory air trapping reveals obstruction.", "air"),
      I("Large airway", "Fixed narrowing differs from dynamic expiratory collapse.", "narrowing")),
    R("rad.4.hrct", "compare", "lungs",
      "Pattern, distribution and discordant features together determine the UIP-pattern category.",
      I("Elementary sign", "Name reticulation, ground glass, nodule or consolidation first.", "reticulation"),
      I("Distribution", "Central, peripheral, upper or lower location changes the differential.", "nodule"),
      I("Fibrotic category", "Honeycombing supports UIP; traction bronchiectasis or bronchiolectasis can support probable UIP, while discordant features suggest an alternative diagnosis.", "fibrosis")),
    R("rad.5.mediastinum", "map", "lungs",
      "Compartment localisation turns a long mass list into a short one.",
      I("Prevascular", "Use thymic, germ-cell, thyroid and lymphoid clues.", "mass"),
      I("Visceral", "Relate the mass to trachea, oesophagus and nodes.", "mass"),
      I("Paravertebral", "Neural and vertebral origin become more likely posteriorly.", "mass")),
    R("rad.5.pleura", "compare", "lungs",
      "Pleural shape and content distinguish air, simple fluid and infected or malignant disease.",
      I("Air", "A pleural line with absent peripheral lung markings shows pneumothorax.", "pneumothorax"),
      I("Fluid", "Dependent fluid layers unless loculation fixes its shape.", "effusion"),
      I("Complex pleura", "Enhancing thick pleura or nodularity changes management.", "mass")),
    R("rad.5.chest-infection", "compare", "lungs",
      "Host, distribution and time course keep infection patterns from becoming diagnoses alone.",
      I("Air-space", "Lobar or multifocal opacity may reflect bacterial pneumonia.", "mass"),
      I("Airway / nodules", "Tree-in-bud and cavities direct attention to spread and host.", "nodule"),
      I("Immune setting", "Opportunistic patterns must be read with immune status.", "reticulation")),
    R("rad.5.pe-pulm-htn", "flow", "lungs",
      "A filling defect matters only after acquisition quality and pretest probability are checked.",
      I("Acquire CTPA", "Time dense pulmonary arterial contrast and control motion.", "embolus"),
      I("Prove embolus", "Trace a true intraluminal defect across planes and branches.", "clot"),
      I("Assess strain", "Right-heart enlargement and reflux change risk assessment.", "embolus"),
      headings=("ACQUISITION QUALITY", "VESSEL SIGN", "RISK FEATURES")),
    R("rad.4.lung-cancer", "map", "lungs",
      "Tumour extent, nodal station and distant spread each alter lung-cancer treatment.",
      I("T: primary", "Measure invasion and relation to pleura, airway and vessels.", "mass"),
      I("N: nodes", "Name the nodal station, not merely the mediastinum.", "nodule"),
      I("M: spread", "Search the opposite lung, pleura and distant organs.", "nodule")),
    R("rad.3.chest-xray", "flow", "lungs",
      "Technique is checked before the search pattern, localisation and conclusion.",
      I("Check quality", "Projection, rotation, inspiration and exposure can mimic disease.", "air"),
      I("Search in order", "Airway, lungs, pleura, heart, hila and bones each get a pass.", "mass"),
      I("Localise", "A lost border identifies which lobe touches that structure.", "mass"),
      headings=("TECHNIQUE", "SYSTEMATIC SEARCH", "LOCALISATION")),
    R("rad.4.pulmonary-nodule", "scale", "lungs",
      "Nodule size, attenuation and patient context determine whether follow-up helps.",
      I("Measure", "Use the recommended plane and a reproducible average diameter.", "small"),
      I("Classify", "Solid, part-solid and ground-glass nodules behave differently.", "subsolid"),
      I("Apply context", "Risk, age and exclusions determine the follow-up pathway.", "follow-up")),

    # Cardiovascular
    R("rad.5.aorta", "compare", "vessel",
      "The intima, wall and lumen separate dissection, intramural haematoma and ulcer.",
      I("Dissection", "An intimal flap separates contrast-filled true and false lumina.", "aortic-dissection-flap"),
      I("Intramural haematoma", "Crescentic blood lies in the wall without a visible flap or flowing false lumen.", "aortic-intramural-haematoma"),
      I("Penetrating ulcer", "A focal contrast outpouching extends through atherosclerotic intima into the wall.", "aortic-penetrating-ulcer")),
    R("rad.5.cardiac-mri", "compare", "heart",
      "Sequence and enhancement distribution connect tissue state to mechanism.",
      I("Function", "Cine imaging measures chamber motion and ventricular volumes.", "dilation"),
      I("Oedema", "Fluid-sensitive signal supports acute myocardial injury.", "oedema"),
      I("Late enhancement", "Coronary-territory scar differs from non-ischaemic patterns.", "enhancement")),
    R("rad.5.cardiac-masses-devices", "compare", "heart",
      "Location, perfusion and enhancement separate thrombus, tumour and device complication.",
      I("Thrombus", "Most thrombus is non-perfused, but organised thrombus may show peripheral or heterogeneous late enhancement; location and stasis remain essential clues.", "thrombus"),
      I("Tumour", "Attachment, tissue signal and perfusion narrow the diagnosis.", "mass"),
      I("Device", "Lead position and surrounding anatomy disclose complications.", "device")),
    R("rad.5.congenital-ct", "flow", "heart",
      "Segmental analysis prevents a familiar-looking heart from hiding an abnormal connection.",
      I("Situs", "Name atrial arrangement and the position of thoracoabdominal organs.", "dilation"),
      I("Connections", "Trace atrioventricular and ventriculoarterial continuity.", "flow"),
      I("Great vessels", "Map arches, pulmonary arteries, veins and collaterals.", "flow"),
      headings=("ORIENTATION", "CONNECTIONS", "VESSEL MAP")),
    R("rad.5.coronary-ct", "flow", "vessel",
      "Image quality, stenosis and plaque burden together drive a CAD-RADS action.",
      I("Acquire", "Control motion and time contrast to the coronary lumen.", "flow"),
      I("Grade", "Trace each segment and quantify its worst interpretable narrowing.", "stenosis"),
      I("Report action", "Category, plaque and modifiers communicate the next step.", "flow"),
      headings=("IMAGE QUALITY", "STENOSIS", "REPORT & ACTION")),
    R("rad.5.peripheral-vascular", "flow", "vessel",
      "A vascular roadmap must show inflow, lesion, runoff and a usable measurement.",
      I("Time the bolus", "Match acquisition to the arterial or venous question.", "flow"),
      I("Measure correctly", "Use the true lumen and a plane normal to the vessel.", "stenosis"),
      I("Map consequences", "Describe inflow, runoff, collaterals and threatened bowel or limb.", "occlusion"),
      headings=("ACQUISITION", "MEASUREMENT", "ROADMAP")),
    R("rad.5.tavi-ct", "map", "heart",
      "Annulus, coronary height and access vessels are one connected procedural plan.",
      I("Size annulus", "Measure a systolic annular plane for valve selection.", "dilation"),
      I("Protect coronaries", "Relate coronary height and sinus dimensions to obstruction risk.", "mass"),
      I("Choose access", "Minimal vessel calibre, plaque and tortuosity determine the route.", "device")),

    # Brain and head/neck
    R("rad.4.stroke", "flow", "brain",
      "Haemorrhage, vessel occlusion and salvageable tissue answer different stroke questions.",
      I("Noncontrast CT", "Exclude haemorrhage and score early ischaemic change.", "haemorrhage"),
      I("CTA", "Locate the occluded artery and assess collateral routes.", "infarct"),
      I("Select treatment", "Core, penumbra, time and clinical status guide thrombectomy.", "territory"),
      headings=("EXCLUDE BLEED", "LOCATE VESSEL", "SELECT TREATMENT")),
    R("rad.5.brain-tumour", "flow", "brain",
      "Compartment comes before enhancement, diffusion and perfusion in mass diagnosis.",
      I("Localise", "Separate intra-axial from extra-axial origin before naming lesions.", "extra-axial"),
      I("Characterise", "Use signal, enhancement, diffusion and susceptibility together.", "mass"),
      I("Map effect", "Report oedema, herniation, vessels and surgical relationships.", "mass"),
      headings=("LOCALISE", "CHARACTERISE", "MAP EFFECT")),
    R("rad.5.brain-anatomy", "map", "brain",
      "A lesion's vascular territory links its location to vessel, deficit and mechanism.",
      I("Arterial map", "Cortical and deep territories point to the supplying artery.", "territory"),
      I("Venous map", "Atypical oedema or haemorrhage may cross arterial boundaries.", "venous"),
      I("Clinical map", "Anatomic function predicts the deficit that should be sought.", "infarct")),
    R("rad.5.cns-infection", "compare", "brain",
      "Compartment, enhancement pattern and diffusion distinguish infection from its mimics.",
      I("Abscess", "A capsule surrounds material with central restricted diffusion.", "infection"),
      I("Encephalitis", "Parenchymal distribution can suggest a neurotropic process but is not organism-specific by itself.", "territory"),
      I("Host-specific masses", "Immune state changes both organisms and mimics.", "mass")),
    R("rad.5.venous-csf", "compare", "brain",
      "Venous injury and CSF-pressure disorders ignore ordinary arterial boundaries.",
      I("Venous thrombosis", "Prove absent or filled sinus flow while excluding variants.", "venous"),
      I("Raised pressure", "Look for secondary signs and a safe venous explanation.", "csf"),
      I("Low pressure", "Brain sag and diffuse dural enhancement suggest CSF loss.", "extra-axial")),
    R("rad.5.dementia", "compare", "brain",
      "Age-adjusted regional atrophy patterns are evidence, not diagnoses by themselves.",
      I("Medial temporal", "Disproportionate hippocampal loss may support an amnestic phenotype when the clinical pattern fits.", "atrophy"),
      I("Frontal / posterior", "Regional predominance may support, but does not by itself establish, a neurodegenerative phenotype.", "territory"),
      I("Treatable mimic", "Ventricular pattern and clinical fit keep hydrocephalus in view.", "csf")),
    R("rad.5.epilepsy-mri", "flow", "brain",
      "A dedicated protocol makes subtle epileptogenic structure visible and localisable.",
      I("Acquire core HARNESS", "Acquire millimetric isotropic 3D T1, millimetric isotropic 3D FLAIR, and high-in-plane-resolution coronal T2 perpendicular to the hippocampal long axes.", "epilepsy-protocol"),
      I("Search concordantly", "Review cortex, hippocampi, scars and vascular lesions.", "mass"),
      I("Escalate if negative", "Re-review with electroclinical localisation and advanced methods.", "territory"),
      headings=("CORE HARNESS", "CONCORDANT SEARCH", "IF NEGATIVE")),
    R("rad.4.head-trauma", "flow", "brain",
      "Trauma CT answers immediate threats first, then mechanism and hidden vascular injury.",
      I("Select and time", "Clinical risk determines immediate and repeat imaging.", "trauma"),
      I("Find mass effect", "Blood, swelling and herniation demand urgent recognition.", "haemorrhage"),
      I("Extend the search", "Fracture pattern may require angiography or MRI for axons.", "territory"),
      headings=("TRIAGE", "IMMEDIATE THREAT", "EXTEND IF INDICATED")),
    R("rad.5.intracranial-haemorrhage", "compare", "brain",
      "Blood shape and compartment point back to vessel, mechanism and next test.",
      I("Extra-axial", "Biconvex epidural and crescentic subdural blood follow different meningeal spaces.", "ich-extra-axial-shapes"),
      I("Intraparenchymal", "A focus within brain parenchyma is interpreted by location and ventricular extension.", "ich-intraparenchymal"),
      I("Subarachnoid", "Blood in basal cisterns and cortical sulci raises the urgency of aneurysm imaging.", "ich-subarachnoid-cisterns-sulci")),
    R("rad.5.ms-white-matter", "compare", "brain",
      "Distribution and lesion-specific signs matter more than counting white-matter spots.",
      I("Brain locations", "Periventricular, cortical or juxtacortical, and infratentorial lesions are separate characteristic regions.", "ms-brain-locations"),
      I("Cord and optic nerve", "Short-segment cord lesions and typical optic-nerve involvement add dissemination in space.", "ms-cord-optic-nerve"),
      I("Lesion-specific signs", "A central-vein sign supports perivenular origin; enhancement and a paramagnetic rim answer different activity and chronicity questions.", "ms-central-vein-sign")),
    R("rad.4.spine-imaging", "compare", "bone",
      "Spine imaging separates common degeneration from compression that cannot wait.",
      I("Describe disc", "Name level, direction and relation to the nerve root.", "spine-disc"),
      I("Find compression", "Cord, cauda equina or epidural disease changes urgency.", "spine-compression"),
      I("Add trauma clues", "Alignment, ligament and marrow findings reveal instability.", "spine-trauma")),
    R("rad.5.neck-nodes", "map", "head-neck",
      "Node level, morphology and drainage territory connect staging to the primary search.",
      I("Assign level", "Use vessels, muscles and hyoid landmarks consistently.", "node"),
      I("Judge morphology", "Necrosis, round shape and extranodal spread raise concern.", "node"),
      I("Change the plan", "Side and level guide stage, operation and occult-primary search.", "node")),
    R("rad.5.deep-neck-spaces", "map", "head-neck",
      "Displaced parapharyngeal fat reveals the space where a neck process began.",
      I("Localise space", "Fascial boundaries organise both masses and infection.", "space"),
      I("Read displacement", "Direction of fat and vessel displacement indicates origin.", "space"),
      I("Map spread", "Airway, mediastinum and perineural routes determine urgency.", "airway")),
    R("rad.5.orbit", "compare", "head-neck",
      "Orbital compartment and tempo narrow trauma, infection, inflammation and tumour.",
      I("Trauma", "Wall, globe, muscle and optic nerve each need inspection.", "orbit"),
      I("Inflammation", "Fat, muscle and sinus pattern distinguish inflammatory spread.", "orbit"),
      I("Mass", "Compartment, bone and enhancement direct diagnosis and urgency.", "orbit")),
    R("rad.5.sinuses", "map", "head-neck",
      "Drainage pathways and risk variants turn a sinus CT into a surgical map.",
      I("Trace drainage", "Name the obstructed ostium and the sinus it serves.", "sinus"),
      I("Flag hazards", "Map skull base, orbit, optic nerve and carotid variants.", "orbit"),
      I("Question tumour", "Bone destruction and unilateral mass-like disease need escalation.", "mass")),
    R("rad.5.temporal-bone", "map", "head-neck",
      "Tiny temporal-bone structures are read by the function and operation they support.",
      I("Middle ear", "Ossicles, scutum and diffusion help identify cholesteatoma.", "temporal"),
      I("Otic capsule", "Fracture, otosclerosis and labyrinth anatomy predict hearing effects.", "temporal"),
      I("Implant route", "Cochlea, nerve and surgical access determine candidacy.", "temporal")),
    R("rad.5.thyroid-tirads", "scale", "head-neck",
      "Feature points and size together determine whether a thyroid nodule is sampled.",
      I("Score features", "Composition, echogenicity, shape, margin and foci add points.", "low"),
      I("Assign category", "The total expresses imaging suspicion, not certainty.", "TR category"),
      I("Use size", "Category-specific thresholds separate aspiration from surveillance.", "FNA / follow-up")),

    # Abdomen and pelvis
    R("rad.5.pancreas-acute", "compare", "abdomen",
      "Time and collection contents determine the correct acute-pancreatitis name and action.",
      I("Classify severity", "Clinical course and organ failure frame what imaging must answer.", "pancreas-severity"),
      I("Name by time", "Early fluid or necrosis evolves into walled collections later.", "pancreas-collection"),
      I("Find complication", "Gas, haemorrhage and vascular injury change intervention.", "pancreas-complication")),
    R("rad.5.appendicitis", "flow", "abdomen",
      "A noncompressible inflamed appendix is interpreted with secondary signs and patient context.",
      I("Choose first test", "Age, pregnancy and local expertise guide ultrasound or CT.", "appendix"),
      I("Combine signs", "Diameter alone is weaker than wall, fat and focal tenderness together.", "appendix"),
      I("Find perforation", "Collection, free gas or wall defect changes urgency.", "obstruction"),
      headings=("CHOOSE TEST", "COMBINE EVIDENCE", "COMPLICATION")),
    R("rad.5.biliary", "compare", "abdomen",
      "Level, cause and inflammatory signs turn jaundice or pain into a biliary pathway.",
      I("Start with ultrasound", "Stones, duct calibre and tenderness answer the first branch.", "biliary-stones"),
      I("Locate obstruction", "Upstream duct dilatation points to the obstructed level.", "biliary-obstruction"),
      I("Separate inflammation", "Wall thickening needs distension, stones and surrounding signs.", "biliary-inflammation")),
    R("rad.5.bowel-ischaemia", "compare", "abdomen",
      "Mechanism and contrast phase explain why ischaemic bowel can enhance differently.",
      I("Arterial", "Occlusion and poor enhancement support reduced inflow.", "ischaemia"),
      I("Venous", "Congestion, oedema and venous clot reflect blocked outflow.", "bowel"),
      I("Strangulation", "Closed-loop geometry plus threatened wall demands urgent action.", "obstruction")),
    R("rad.5.bowel-obstruction", "flow", "abdomen",
      "The transition point explains both the obstruction and the threat to bowel viability.",
      I("Prove mechanical", "Dilated upstream bowel collapses beyond a transition point.", "obstruction"),
      I("Find the cause", "Adhesion, hernia, mass or twist shapes the operation.", "bowel"),
      I("Find strangulation", "Closed loop, oedema and reduced enhancement increase urgency.", "ischaemia"),
      headings=("TRANSITION POINT", "CAUSE", "VIABILITY")),
    R("rad.5.abdominal-trauma", "flow", "abdomen",
      "Contrast phase separates contained organ injury from active bleeding that needs control.",
      I("Acquire phases", "Arterial and portal information answer different bleeding questions.", "phase"),
      I("Grade organ", "Depth and vascular involvement communicate injury severity.", "lesion"),
      I("Route treatment", "Extravasation, instability and hollow-viscus signs direct intervention.", "phase"),
      headings=("CONTRAST PHASES", "INJURY GRADE", "ROUTE CARE")),
    R("rad.5.ibd", "compare", "abdomen",
      "Inflammatory and fibrotic components commonly coexist in the same Crohn stricture.",
      I("Active inflammation", "Hyperenhancement, oedema and comb-like vessels support activity.", "ibd"),
      I("Fibrotic component", "Fixed narrowing may suggest fibrosis, but cross-sectional imaging cannot accurately quantify the fibrotic component.", "obstruction"),
      I("Complication", "Fistula, abscess and upstream dilatation alter management.", "bowel")),
    R("rad.5.pancreas-tumour", "compare", "abdomen",
      "Pancreatic lesion type and vessel contact determine resectability and sampling.",
      I("Acquire protocol", "Timed phases show a hypovascular tumour and arterial anatomy.", "pancreas-protocol"),
      I("Map contact", "Degree and contour of vessel involvement guide resectability.", "pancreas-vessel-contact"),
      I("Triage lesion", "Cystic and hypervascular lesions follow different pathways.", "pancreas-lesion-types")),
    R("rad.5.peritoneum", "map", "abdomen",
      "Peritoneal recesses explain where fluid, tumour and infection travel.",
      I("Follow spaces", "Gravity and mesenteric attachments channel disease spread.", "bowel"),
      I("Read surfaces", "Nodules, cake-like omentum and ascites suggest carcinomatosis.", "lesion"),
      I("Check wall", "Hernia contents and threatened bowel determine urgency.", "obstruction")),
    R("rad.5.rectal-mr", "map", "abdomen",
      "MRI maps the tumour or fistula against the planes the surgeon must preserve.",
      I("Tumour depth", "Extramural spread and nodes establish local stage.", "rectum"),
      I("Surgical margin", "Distance to mesorectal fascia predicts threatened resection margin.", "pelvis"),
      I("Fistula map", "Internal opening, sphincter relation and abscess guide surgery.", "bowel")),
    R("rad.3.acute-abdomen", "compare", "abdomen",
      "Free gas, a transition point and inflammatory epicentre organise the acute CT search.",
      I("Perforation", "Extraluminal gas and the nearest diseased viscus suggest the source.", "phase"),
      I("Obstruction", "A calibre change separates mechanical blockage from diffuse ileus.", "obstruction"),
      I("Inflammation", "Centre the process on the organ with the strongest local signs.", "lesion")),
    R("rad.4.liver", "flow", "abdomen",
      "A liver lesion is characterised by how it changes across contrast phases.",
      I("Unenhanced", "Fat, blood, calcium and baseline density prevent false enhancement.", "liver"),
      I("Dynamic phases", "Arterial uptake and later washout describe lesion vascularity.", "phase"),
      I("Apply context", "Risk population and ancillary features determine the LI-RADS path.", "lesion"),
      headings=("BASELINE", "DYNAMIC CHANGE", "CLINICAL CONTEXT")),
    R("rad.4.kidney", "flow", "abdomen",
      "Enhancement separates a simple cyst pathway from a solid renal mass pathway; category informs rather than dictates care.",
      I("Establish baseline", "Unenhanced attenuation prevents pseudo-enhancement errors.", "renal-baseline"),
      I("Find enhancement", "Compare matched regions across correctly timed phases.", "renal-enhancement"),
      I("Classify", "Cyst wall, septa and nodules determine a Bosniak category that informs management with clinical context.", "renal-cystic-mass"),
      headings=("BASELINE", "TRUE ENHANCEMENT", "CATEGORY & CONTEXT")),
    R("rad.5.scrotum", "compare", "abdomen",
      "Perfusion and lesion location separate the acute surgical pathway from mass work-up.",
      I("Check flow", "Absent or reduced intratesticular perfusion supports torsion.", "testis-perfusion"),
      I("Localise mass", "Intra- and extratesticular origins carry different priors.", "testis-mass-location"),
      I("Integrate markers", "Imaging and tumour markers guide staging and surgery.", "testis-staging")),
    R("rad.5.adrenal", "compare", "abdomen",
      "Attenuation, signal loss and washout answer different adrenal lesion questions.",
      I("Unenhanced CT", "Low attenuation can establish a lipid-rich adenoma.", "adrenal-ct"),
      I("Chemical shift", "Signal loss reveals intracellular lipid.", "adrenal-chemical-shift"),
      I("Washout / limits", "Kinetics help selected lesions but cannot settle every diagnosis.", "adrenal-washout")),
    R("rad.5.bladder-virads", "flow", "abdomen",
      "The muscular layer is the boundary that turns bladder MRI into local stage.",
      I("T2 anatomy", "Show tumour, wall and muscular continuity in the correct plane.", "bladder-t2"),
      I("DWI and enhancement", "Concordant interruption raises suspicion of muscle invasion.", "bladder-dwi-enhancement"),
      I("Assign VI-RADS", "Combine sequences and report extension beyond the bladder.", "bladder-virads"),
      headings=("ANATOMIC LAYER", "SEQUENCE CONCORDANCE", "LOCAL STAGE")),
    R("rad.5.ovarian-orads", "flow", "abdomen",
      "Morphology and vascular solid tissue determine an adnexal lesion's risk pathway.",
      I("Describe morphology", "Simple fluid, septa and solid parts establish the branch.", "ovary-morphology"),
      I("Assess tissue", "Flow and MRI enhancement refine risk when ultrasound is indeterminate.", "ovary-solid-tissue"),
      I("Assign action", "Category and clinical setting guide follow-up or referral.", "ovary-action"),
      headings=("MORPHOLOGY", "SOLID TISSUE", "CATEGORY & ACTION")),
    R("rad.5.prostate-mri", "compare", "abdomen",
      "Zone determines which sequence dominates PI-RADS assessment and which mimics matter.",
      I("Peripheral zone", "Diffusion abnormality carries the greatest weight.", "prostate-peripheral"),
      I("Transition zone", "T2 architecture separates organised nodules from suspicious tissue.", "prostate-transition"),
      I("Stage and target", "Capsule, seminal vesicles and lesion map guide biopsy and care.", "prostate-stage-target")),
    R("rad.5.uterine-mr", "map", "abdomen",
      "Zonal anatomy links tumour, endometriosis and congenital form to the operation.",
      I("Cancer planes", "Stroma, myometrium and parametria define local extension.", "uterus"),
      I("Surgical disease map", "Fibroids and deep endometriosis are mapped by compartment.", "pelvis"),
      I("Congenital form", "Fundal contour and cavity relationship distinguish anomalies.", "uterus")),

    # Breast
    R("rad.5.breast-calcifications", "compare", "breast",
      "Calcification morphology and distribution together determine whether sampling is needed.",
      I("Morphology", "Fine linear or fine pleomorphic particles carry more concern than coarse benign forms.", "calcification-morphologies"),
      I("Distribution", "Grouped, linear and segmental arrangements imply different ductal extents.", "calcification-distributions"),
      I("If sampled", "Specimen imaging confirms target retrieval; pathology must explain that same imaging target.", "calcification-sampling-target")),
    R("rad.5.breast-mri", "flow", "breast",
      "Breast MRI is most useful when enhancement changes staging or management.",
      I("Choose indication", "Use MRI for questions where added sensitivity changes care.", "mass"),
      I("Read enhancement", "Morphology, distribution and kinetics are interpreted together.", "mass"),
      I("Map extent", "Nodes, implants and treatment change complete the surgical map.", "mass"),
      headings=("INDICATION", "CHARACTERISE", "MAP EXTENT")),
    R("rad.4.breast", "flow", "breast",
      "A mammographic finding becomes a BI-RADS action through complete diagnostic work-up.",
      I("Detect", "Mass, distortion, asymmetry and calcification start different analyses.", "mass"),
      I("Characterise", "Views and ultrasound decide whether the sign persists and what it is.", "calcification"),
      I("Assign action", "BI-RADS names surveillance, biopsy or routine screening.", "mass"),
      headings=("DETECTION", "DIAGNOSTIC WORK-UP", "CATEGORY & ACTION")),

    # Musculoskeletal
    R("rad.5.ankle-foot", "flow", "bone",
      "Clinical rules select radiographs; alignment and fracture pattern determine stability.",
      I("Select imaging", "Tenderness and weight-bearing ability guide the first radiograph.", "ankle-rules"),
      I("Judge stability", "Malleoli, mortise and syndesmosis form one injury pattern.", "ankle-stability"),
      I("Chase occult injury", "Midfoot, tendon and heel clues direct further imaging.", "midfoot-occult"),
      headings=("CLINICAL RULE", "STABILITY", "OCCULT INJURY")),
    R("rad.5.marrow-muscle", "compare", "bone",
      "Distribution and structural damage separate reactive oedema from marrow or muscle disease.",
      I("Reactive oedema", "Signal follows load or nearby inflammation without destructive replacement.", "marrow"),
      I("Stress / muscle", "Fracture line or fibre disruption helps grade injury and informs activity modification with clinical findings.", "stress"),
      I("Diabetic foot", "Track ulcer to bone while separating neuropathic joint change.", "lesion")),
    R("rad.5.bone-tumours", "flow", "bone",
      "Age, site, margin, periosteum and matrix together determine bone-lesion aggression.",
      I("Localise", "Patient age and exact position in the bone set the prior.", "lesion"),
      I("Read behaviour", "Margin and periosteal response show growth tempo.", "tumour"),
      I("Protect the pathway", "Aggressive lesions reach the sarcoma team before biopsy.", "lesion"),
      headings=("AGE & SITE", "AGGRESSIVE FEATURES", "SARCOMA PATHWAY")),
    R("rad.3.fracture-description", "compare", "bone",
      "A fracture description connects geometry, soft-tissue risk and surgical planning.",
      I("Name geometry", "Bone, segment, line, displacement and angulation come first.", "fracture"),
      I("Name consequences", "Joint extension, open injury and neurovascular risk change urgency.", "joint"),
      I("Seek the hidden pair", "Mechanism directs additional views and adjacent-joint imaging.", "stress")),
    R("rad.5.hip", "compare", "bone",
      "Hip measurements matter only when linked to impingement, collapse or implant failure.",
      I("Shape / coverage", "Alpha and coverage measures support a mechanical conflict.", "hip-coverage"),
      I("Osteonecrosis", "Subchondral extent and collapse determine stage.", "hip-osteonecrosis"),
      I("Arthroplasty", "Position, loosening, wear and infection form the failure pattern.", "hip-arthroplasty")),
    R("rad.5.knee", "compare", "bone",
      "The tear pattern is reported through the mechanical consequence it creates.",
      I("Meniscus", "Name surface contact, orientation, displacement and root involvement.", "knee-meniscus"),
      I("Ligaments", "Direct fibre change and secondary signs establish instability.", "knee-ligament"),
      I("Cartilage", "Depth, area and subchondral response communicate severity.", "knee-cartilage")),
    R("rad.5.msk-mri", "compare", "bone",
      "Sequence selection and artefact recognition prevent normal physics becoming disease.",
      I("T1 anatomy", "Marrow fat and structural boundaries provide the baseline.", "marrow"),
      I("Fluid-sensitive", "Oedema and fluid become conspicuous when fat is suppressed.", "joint"),
      I("Artefact check", "Direction, hardware and magic-angle behaviour expose mimics.", "stress")),
    R("rad.5.shoulder", "compare", "bone",
      "Shoulder imaging turns tear morphology and bone loss into an operative plan.",
      I("Cuff", "Tendon, retraction, muscle and atrophy determine repairability.", "shoulder-cuff"),
      I("Labrum", "Separate normal variants from tears by attachment and associated signs.", "shoulder-labrum"),
      I("Instability", "Quantify glenoid and humeral bone loss before choosing treatment.", "shoulder-instability")),
    R("rad.4.arthritis", "compare", "bone",
      "Distribution, erosion, density and new bone distinguish major arthritis patterns.",
      I("Degenerative", "Nonuniform loss, osteophytes and sclerosis follow mechanical load.", "arthritis"),
      I("Inflammatory", "Uniform loss, erosions and periarticular change follow synovitis.", "joint"),
      I("Crystal / proliferative", "Characteristic sites and mineralisation redirect the diagnosis.", "lesion")),
    R("rad.5.wrist-hand", "flow", "bone",
      "Carpal arcs and angles expose instability even when no fracture is obvious.",
      I("Check alignment", "Trace arcs and measure key carpal relationships.", "wrist-carpal-arcs"),
      I("Find occult fracture", "Mechanism and focal tenderness direct repeat or cross-sectional imaging.", "wrist-occult-fracture"),
      I("Report decision", "Displacement, instability and vascular risk inform urgency and operative discussion alongside examination and patient factors.", "wrist-instability"),
      headings=("CARPAL ALIGNMENT", "OCCULT FRACTURE", "MANAGEMENT FEATURE")),
    R("rad.5.paeds-hip-elbow", "compare", "bone",
      "Age-appropriate landmarks turn changing paediatric anatomy into reliable alignment tests.",
      I("Infant hip", "Ultrasound tests coverage and stability before ossification dominates.", "infant-hip-ultrasound"),
      I("Older hip", "Radiographic lines and symmetry reveal displacement.", "older-hip-lines"),
      I("Child elbow", "Ossification order and alignment lines uncover subtle fracture.", "child-elbow-lines")),

    # Paediatrics and safeguarding
    R("rad.4.paediatric", "flow", "scanner",
      "The right paediatric test answers the question while limiting dose and missed safeguarding clues.",
      I("Choose by age", "Changing anatomy determines ultrasound, radiograph or cross-sectional imaging.", "signal"),
      I("Read the whole study", "Lines, lungs, bowel and bones each receive a deliberate search.", "ct"),
      I("Protect the child", "Injury pattern and history may require a safeguarding pathway.", "radiation"),
      headings=("CHOOSE TEST", "COMPLETE SEARCH", "SAFEGUARD")),
    R("rad.5.child-abuse", "flow", "bone",
      "A standardised complete survey preserves evidence and protects the child.",
      I("Acquire completely", "Required projections and identifiers make the survey auditable.", "bone"),
      I("Interpret patterns", "Specific fractures, healing stages and clinical history are integrated.", "fracture"),
      I("Document and escalate", "Clear reporting and multidisciplinary communication close the duty.", "trauma"),
      headings=("STANDARD SURVEY", "PATTERN & CONTEXT", "DOCUMENT & ESCALATE")),
    R("rad.5.paeds-masses-neuro", "compare", "scanner",
      "Age and organ of origin narrow childhood masses before signal features do.",
      I("Age prior", "Likely tumours change sharply across infancy and childhood.", "signal"),
      I("Find origin", "Displaced organs and vessels reveal where a mass began.", "ct"),
      I("Use ultrasound", "Fontanelle and posterior elements provide safe acoustic windows.", "signal")),
    R("rad.5.paeds-chest", "compare", "lungs",
      "Lines, air leaks and lung pattern are one linked neonatal chest search.",
      I("Device and tip", "Trace umbilical, endotracheal and enteric devices to the correct age-specific tip landmark; malposition can cause immediate harm.", "paeds-device-tip"),
      I("Air leak", "Pleural, mediastinal and interstitial air have different shapes.", "paeds-air-leak"),
      I("Lung pattern", "Age, lung volume and opacity distribution narrow the cause of distress.", "paeds-lung-pattern")),
    R("rad.5.paeds-abdomen", "compare", "abdomen",
      "Age and suspected mechanism determine the order of paediatric abdominal tests.",
      I("Radiograph when useful", "Serial radiographs can reveal gas pattern and dangerous free air.", "paeds-abdomen-radiograph"),
      I("Ultrasound first when apt", "Dynamic compression and perfusion answer common focal questions without radiation.", "paeds-abdomen-ultrasound"),
      I("Surgical red flags", "Suspected volvulus, perforation or ischaemia requires immediate surgical escalation while imaging is completed.", "paeds-abdomen-surgical-red-flags")),

    # Nuclear medicine
    R("rad.5.nuclear-general", "compare", "tracer",
      "Tracer choice and time pattern turn uptake into a physiological answer.",
      I("Bone / VQ", "Bone turnover and ventilation-perfusion mismatch are different tracer maps answering different questions.", "bone-vq"),
      I("Thyroid", "Uptake in the neck shows the distribution and intensity of functioning thyroid tissue.", "thyroid-neck"),
      I("Sentinel node", "Tracer travels from the injection site along lymphatic channels to the first draining nodal basin.", "sentinel-lymph-drainage")),
    R("rad.5.pet-ct", "flow", "tracer",
      "Preparation, physiology and treatment timing prevent FDG uptake from becoming a false diagnosis.",
      I("Prepare", "Glucose, uptake time and recent treatment affect biodistribution.", "pet"),
      I("Match anatomy", "Every focus is located and compared with expected physiology.", "pet"),
      I("Act proportionately", "Stage-changing disease differs from incidental uptake needing context.", "bone"),
      headings=("PREPARATION", "ANATOMIC MATCH", "PROPORTIONATE ACTION")),
    R("rad.5.theranostics", "flow", "tracer",
      "The same molecular target distribution links diagnostic imaging to treatment, but uptake alone does not establish eligibility.",
      I("Assess eligibility", "Target uptake is one criterion alongside whole-body distribution, disease status, organ function, prior therapy and treatment-specific criteria.", "theranostic-diagnostic-target"),
      I("Treat the same target", "The therapeutic ligand binds the same target distribution and carries a therapeutic radionuclide to expressing tissue.", "theranostic-therapy-same-target"),
      I("Protect and follow", "Dosimetry, blood counts, renal or salivary toxicity, response and radiation-safety advice complete the pathway.", "theranostic-followup-organs"),
      headings=("ELIGIBILITY", "SAME TARGET", "DOSIMETRY & FOLLOW-UP")),
]


SPECS: Dict[str, Dict[str, object]] = {str(item["id"]): item for item in _RECORDS}
if len(SPECS) != len(_RECORDS):
    raise ValueError("Duplicate radiology illustration specification")
for _record in _RECORDS:
    if _record["mode"] == "flow" and len(_record.get("headings", ())) != 3:
        raise ValueError("Flow plate {} needs three role-specific headings".format(_record["id"]))
