#!/usr/bin/env python3
"""Require source-resolved full CN V anatomy and keep clinical diagnosis outside contact geometry."""
import copy,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];INV='ra.mri-trigeminal';URLS=['https://radiologyassistant.nl/head-neck/trigeminus/trigeminal-neuralgia-and-neuropathy','https://pmc.ncbi.nlm.nih.gov/articles/PMC5750829/','https://pubmed.ncbi.nlm.nih.gov/20227216/']
def build():
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];guide=copy.deepcopy(ref['reporting'])
    details=['Assess actual source brainstem/root origin and obtained central pathway extent, with explicit limits on tiny nuclear or microscopic resolution.',
        'Trace every actual sensory/motor root and cisternal segment, and each acquired vascular contact with source-supported nerve morphology and uncertainty.',
        'Review the actual porus, CSF recess, nerve/ganglion and dural interfaces; interpret enhancement only with appropriate source sequence and comparison.',
        'Trace actual V1/V2/V3 and motor-root routes, skull-base passages and adjacent cavernous/petrous/orbital interfaces within acquired coverage.',
        'Trace each actual covered peripheral division/branch and primary-site/tissue relation; distinguish acquired muscle abnormalities from clinical denervation or histological perineural invasion.']
    looks=['Use the actual acquired midbrain/pons/medulla/upper-cord extent, T2/FLAIR, paired DWI/ADC and pre/postcontrast sequences as available. A nucleus name or a schematic dot is not independent resolution of every nuclear boundary.',
        'Inspect full obtained sensory and motor-root courses, root-entry/central-peripheral transition region, surrounding CSF and every arterial/venous contact. State source side, segment, image/plane, contact versus deformation/atrophy and vascular identification limits.',
        'Inspect actual porus trigeminus, Meckel cave walls/CSF, ganglion and motor-root bypass. Record source-resolved size/signal/CSF replacement and enhancement against precontrast/fat-suppressed images if acquired; unresolved structures remain unassessed.',
        'Trace V1/V2 in the cavernous lateral wall and V3/motor root through foramen ovale; inspect source superior orbital fissure/rotundum/ovale and covered orbital/pterygopalatine/masticator interfaces. MRI and bone CT roles remain distinct.',
        'Review obtained face/orbit/sinonasal/dental/skin/salivary/masticator extent and every actually identified peripheral branch or connection. Map source lesion extent, foraminal/fat-space findings, muscle signal/volume and actual comparison; distal unacquired pathways cannot be declared normal.']
    tips=['Tiny nuclei, fascicles, transition-zone histology and all central tracts are not resolved merely because brainstem MRI is available.',
        'Simple vascular contact is not the clinical diagnosis of neuralgia or proof of symptomatic compression, vessel flow or surgical benefit. TOF or a flow void alone does not establish every arterial/venous identity.',
        'A ganglion/root schematic or enhancement pattern does not establish tumour histology or independently identify all dural/CSF boundaries.',
        'The motor root bypasses the sensory ganglion; V3 does not follow the V1/V2 cavernous route. Source anatomy and variants must be traced rather than copied from a generic nerve diagram.',
        'Muscle edema/atrophy has a differential. Clinical motor dysfunction and microscopic perineural invasion require actual corresponding evidence; limited proximal MRI does not exclude distal disease.']
    guide.update(reviewed_at='2026-10-07',protocol=['Record actual MRI coverage, isotropic sampling, motion/artifacts, heavily T2, vascular correlation, DWI/ADC and pre/postcontrast fat-suppressed sources if acquired. Symptomatic division and malignancy history determine needed peripheral coverage; missing sources remain explicit.',
        'Keep supplied clinical neuralgia/neuropathy, symptom side/distribution, biopsy, treatment and prior examinations separate from source morphology. Native photography or a source model is not a matched patient MRI or functional measurement.'],checklist=[{'label':label,'detail':text} for label,text in zip(['Central origin','Cisternal roots and contacts','Meckel cave and ganglion','Divisions and skull base','Peripheral course and muscle findings'],details)],pitfalls=tips,sources=[{'title':title,'url':url} for title,url in zip(['RA trigeminal reporting reference','Source segmental imaging review (graphics not reused)','Full-course trigeminal imaging review'],URLS)])
    bodies=['Actual side and acquired brainstem/upper-cord extent [ ]; source-resolved nuclei/root-origin/pathway findings [ ]; paired DWI/ADC/T2/FLAIR or enhancement if obtained [ ]; unresolved tiny or microscopic boundaries [ ].',
        'Each actual sensory/motor root and obtained cisternal extent [ ]; every source vessel/contact/side/segment [ ]; nerve displacement/indentation/atrophy and source confidence [ ]; vascular identity/sequence/comparison [ ]; clinical correlation and unassessed function [ ].',
        'Actual porus/CSF recess/nerve/ganglion/dural interfaces [ ]; source size/signal/enhancement or tissue replacement [ ]; motor-root bypass if resolved [ ]; actual acquisition/comparison and unresolved extent [ ].',
        'Each obtained V1/V2/V3/motor route [ ]; actual cavernous/petrous/orbital and foraminal interfaces [ ]; source MRI or bone CT findings and limits [ ]; every variant/lesion/repair connection and unacquired extent [ ].',
        'Every obtained peripheral branch/primary-site/tissue connection [ ]; source muscle signal/volume and comparison [ ]; suspected perineural or other disease and differential [ ]; supplied histology/clinical motor or sensory context [ ]; distal unassessed anatomy [ ].']
    for section,body in zip(guide['template_sections'],bodies):section['body']=body
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data.setdefault(INV,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/head-neck.json';text=path.read_text();start=text.index('{',text.index('"'+INV+'"'));node,end=json.JSONDecoder().raw_decode(text,start)
    node['model']={'family':'trigeminal','reporting_aim':'Partial pathway orientation only. This schematic does not supply every actual nuclear/fascicular boundary, sensory/motor root, ganglion/CSF/dural interface, small vessel contact, peripheral branch or patient lesion. Source-resolved anatomy, missing coverage and clinical/histological function remain separate.'}
    for i,step in enumerate(node['steps']):step.update(normal={},detail=details[i],look=looks[i],tip=tips[i],findings=['Actual acquired '+step['label'].lower()+' findings [ ]; source/side/segment/extent [ ]; uncertainty and unassessed anatomy [ ].'])
    path.write_text(text[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+text[end:])
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];structures=[]
    def add(key,parts,steps,side='not_applicable',pathology=False):
        ident='trigeminal.'+side+'_'+key;structures.append({'id':ident,'name':side.replace('_',' ').capitalize()+' '+key.replace('_',' '),'tissue_class':'trigeminal_neural_compartment_component_or_adjacent_interface','required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['MRI'],'condition':'Independently instantiate every actual obtained root, division, branch, variant, compartment boundary, adjacent structure and lesion/repair connection. A named region or schematic is not each native tiny nerve/fascicle/vessel interface; unacquired or unresolved distal, microscopic and central extent remains missing.','requirement_basis':'effective_full_course_trigeminal_MRI_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'}})
    neural='actual_origin_and_full_obtained_course each_resolved_component_and_boundary every_actual_branch_or_communicating_connection adjacent_CSF_dura_vessel_or_target_tissue_interface each_source_resolved_lesion_variant_or_repair source_unresolved_fascicular_microscopic_or_uncovered_extent'
    adjacent='every_actual_obtained_component_and_extent each_resolved_tissue_or_space_boundary neural_contact_displacement_or_extension_interface every_encountered_variant_lesion_or_repair each_actual_connection_and_acquisition_limits unresolved_microscopic_or_uncovered_extent'
    for side in ['left','right']:
        for key in ['mesencephalic_nucleus_and_tract','principal_sensory_nucleus','motor_nucleus_and_fascicles','spinal_trigeminal_nucleus_and_tract','pontine_intrinsic_sensory_fascicles','root_entry_and_transition_region']:add(key,neural,[0,1],side)
        for key in ['cisternal_sensory_root_and_rootlets','cisternal_motor_root_and_rootlets','porus_trigeminus','Meckel_cave_CSF_and_dural_recess','trigeminal_ganglion','motor_root_ganglion_bypass']:add(key,neural,[1,2],side)
        for key in ['superior_cerebellar_artery_contacts','anterior_inferior_cerebellar_artery_contacts','basilar_vertebral_or_other_arterial_contacts','petrosal_and_other_venous_contacts','actual_nerve_to_vessel_interface']:add(key,adjacent,[1],side)
        for key in ['V1_cavernous_and_orbital_course','V2_cavernous_and_pterygopalatine_course','V3_and_motor_foramen_ovale_course','superior_orbital_fissure','foramen_rotundum','foramen_ovale','cavernous_sinus_walls_and_ICA','covered_adjacent_III_IV_VI_or_optic_interfaces','petrous_apex_and_dural_interfaces']:add(key,adjacent,[2,3],side)
        branches=['frontal_supraorbital_and_supratrochlear','lacrimal_and_communicating_branches','nasociliary_ciliary_ethmoidal_and_infratrochlear','zygomatic_and_communicating_branches','infraorbital_and_canal','superior_alveolar_and_dental_branches','pterygopalatine_and_palatal_nasal_connections','auriculotemporal','buccal','lingual_and_encountered_connections','inferior_alveolar_and_mandibular_canal','mental_and_incisive','mylohyoid_and_anterior_digastric_motor','masseteric_deep_temporal_and_pterygoid_motor','tensor_veli_palatini_and_tensor_tympani_motor','other_actual_variant_or_unassigned_branches']
        for key in branches:add(key,neural,[3,4],side)
        for key in ['pterygopalatine_fossa_and_vidian_connections','infratemporal_and_masticator_spaces','orbital_apex_and_fat_spaces','masseter','temporalis','medial_pterygoid','lateral_pterygoid','mylohyoid_and_anterior_digastric','covered_tensor_veli_palatini','covered_tensor_tympani','encountered_skin_mucosal_sinonasal_dental_or_salivary_primary','each_actual_perineural_or_other_lesion_interface']:add(key,adjacent,[3,4],side,pathology='lesion' in key or 'primary' in key)
    for key in ['obtained_brainstem_and_upper_cervical_extent','prepontine_and_cerebellopontine_CSF_spaces','covered_posterior_fossa_skull_base_and_orbital_extent','actual_midline_or_crossing_lesion_extent']:add(key,adjacent,[0,1,2,3,4])
    item={'investigation_id':INV,'module_id':ref['investigation']['module_id'],'title':'Every source-resolved central cisternal skull-base and peripheral trigeminal component','scope_status':'expanded_draft_requires_independent_trigeminal_anatomical_review','modality_scope':['MRI'],'sources':[{'title':s['title'],'url':s['url'],'reviewed_at':'2026-10-07','review_status':'source_scope_reviewed_no_restricted_graphics_reused'} for s in guide['sources']],'source_contract_sha256':digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Every actual branch/root/contact/interface is independently instantiated; listed groups are a known floor, not every native patient variant or lesion.','No ganglion traversal is invented for the motor root, no V1/V2 cavernous route is copied onto V3, and no unacquired peripheral region is called normal.','MRI signal, diffusion, enhancement and vascular correlation require actual corresponding acquisitions; a permitted modality or static photograph does not supply every microscopic nucleus/fascicle or functional observation.'],
        'source_scope_issues':['Existing pathway model and selected still references do not establish actual tiny nerve/vessel/dural/CSF interfaces or full extracranial extent.','Noncommercial/no-derivatives source graphics remain held; no source image or model is anatomically approved by this scope expansion.'],
        'functional_evidence_requirements':['Clinical neuralgia, sensory loss, motor dysfunction and treatment effect are supplied clinical evidence; contact geometry alone is not symptomatic disease or surgical benefit.','Muscle edema/atrophy has a differential; functional denervation, tumour histology and microscopic perineural invasion are not fabricated 3D structures.','Flow, arterial/venous identity, diffusion restriction and enhancement require actual acquisition and technical context, not shared generic source labels.'], 'clinical_validation_status':'draft_requires_neuroradiologist_and_relevant_cranial_nerve_review'}
    path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=INV]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');n=len(requirements_for(item));print(len(structures),'groups;',n,'parts;',n*3,'representation obligations')
if __name__=='__main__':build()
