#!/usr/bin/env python3
"""Require actual device components, routes, tissue interfaces and functional-source limits."""
import json
from pathlib import Path
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.cardiovascular-devices'
URLS=['https://radiologyassistant.nl/cardiovascular/devices/cardiovascular-devices','https://pmc.ncbi.nlm.nih.gov/articles/PMC6837806/','https://pmc.ncbi.nlm.nih.gov/articles/PMC4286824/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11211236/','https://pmc.ncbi.nlm.nih.gov/articles/PMC10350447/','https://www.livanova.com/cannulae/en-us/specialty-cannulae']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];guide=ref['reporting'];structures=[]
    def add(key,name,children,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'cardiovascular_device.'+key,'name':name,'tissue_class':'cardiovascular_device_component_interface_or_control',
            'required_parts':[{'id':'cardiovascular_device.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in children.split()],
            'laterality':side,'modality_scope':['Radiography','CT','Ultrasound','MRI'],
            'condition':'Instantiate every actual device, lead/channel, manufacturer/model/version, intended site, patient variant, insertion/revision and relevant complication. Preserve native source identity, modality, projection/phase, physical calibration, covered extent and uncertainty. Modality capabilities and any MRI assessment are conditional on actual system/protocol evidence; an unvisualised interface is not normal.',
            'requirement_basis':'effective_cardiovascular_device_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],
            'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    device='actual_type_model_and_version every_actual_component actual_connection_configuration full_visible_geometry source_resolved_radiopaque_vs_radiolucent_parts intended_site_and_procedure_source actual_patient_interface relative_position_and_axis source_coverage_and_artefact unresolved_identity_or_boundary'
    for key,name in [('pacemaker_generator','Each pacemaker generator'),('icd_generator','Each ICD generator'),('crt_generator','Each CRT-P/CRT-D generator'),('temporary_generator','Each temporary generator'),('loop_recorder','Each implanted loop recorder'),('leadless_body','Each leadless pacing body'),('subcutaneous_icd_generator','Each subcutaneous ICD generator'),('other_generator_mimic','Each noncardiac stimulator/generator mimic if relevant')]:add(key,name,device,[0,1,2,4])
    add('generator_header','Each actual generator header/connector assembly','every_actual_port terminal_pin_insertion_and_connection source_resolved_connector_geometry manufacturer_marker_if_visible connected_vs_unconnected_component connector_artefact_or_separation actual_full_system_identification unresolved_nonradiopaque_components',[0,1,4])
    add('pocket','Each actual device pocket','side_and_anatomical_site generator_axis_and_orientation pocket_boundary_if_resolved muscle_fascial_relation skin_interface source_resolved_collection_or_air relation_to_each_lead_and_connection local_artefact_and_unresolved_extent',[0,1,3,4])
    lead='generator_or_external_connection venous_arterial_epicardial_or_other_entry complete_visible_course slack_and_bend_geometry every_electrode_or_coil source_resolved_conductor_and_insulation fixation_or_anchor_if_resolved actual_tip_and_target_interface source_resolved_separation_or_externalisation comparison_and_uncovered_extent'
    for key,name in [('atrial_lead','Each atrial pacing/sensing lead'),('ventricular_lead','Each ventricular pacing/sensing lead'),('coronary_sinus_lead','Each coronary-sinus/cardiac-vein lead'),('conduction_system_lead','Each intended His/left-bundle/septal lead'),('epicardial_lead','Each epicardial lead/wire'),('temporary_transvenous_lead','Each temporary transvenous lead'),('subcutaneous_electrode','Each subcutaneous ICD electrode'),('other_shock_array','Each other actual shock array'),('abandoned_lead','Each abandoned/retained lead'),('lead_fragment','Each retained/broken lead fragment')]:add(key,name,lead,[0,1,2,3,4])
    add('leadless_anchors','Each actual leadless anchor/fixation interface','actual_device_body orientation_and_septal_wall_relation every_source_resolved_anchor electrode_tissue_interface expected_device_specific_design unresolved_radiolucent_or_thin_parts projection_and_coverage_limits',[0,2,3])
    for site in ['aortic','mitral','tricuspid','pulmonary']:
        for kind in ['mechanical','bioprosthetic','annuloplasty']:
            add(site+'_'+kind,'Each actual '+site+' '+kind+' prosthesis/repair','actual_model_type_and_implant_history source_resolved_ring_frame_or_repair every_actual_leaflet_disc_or_occluder_if_resolved strut_or_support_geometry sewing_or_landing_interface native_annular_and_chamber_relation orientation_and_axis actual_prosthetic_or_paravalvular_boundary motion_source_and_limits artefact_and_uncovered_extent',[0,2,3,4])
    for key,name in [('transcatheter_aortic_valve','Each transcatheter aortic prosthesis'),('transcatheter_pulmonary_valve','Each transcatheter pulmonary prosthesis'),('other_transcatheter_valve','Each other actual transcatheter valve'),('mitral_edge_repair','Each actual mitral edge-to-edge repair implant'),('other_edge_repair','Each other actual edge-to-edge repair implant')]:add(key,name,device+' actual_leaflet_or_device_attachment adjacent_outflow_and_branch_relation',[0,2,3,4])
    for key,name in [('atrial_septal_occluder','Each actual ASD/PFO closure implant'),('appendage_occluder','Each left-atrial-appendage closure implant'),('ductal_occluder','Each actual ductal closure implant'),('venous_plug','Each actual scimitar/other venous plug'),('other_occluder','Each other actual vascular/septal occluder')]:add(key,name,'actual_model_type_and_history every_actual_disc_waist_plug_or_anchor intended_defect_or_channel each_native_landing_surface adjacent_valve_vessel_and_chamber_relation residual_channel_if_resolved orientation_and_migration_relation source_resolved_thrombus_or_obstruction actual_flow_or_residual_shunt_source uncovered_or_unresolved_interface',[0,2,3,4])
    for key,name in [('coronary_stent','Each coronary stent'),('aortic_coarctation_stent','Each coarctation/aortic stent'),('thoracic_stent_graft','Each thoracic aortic stent-graft'),('other_vascular_stent','Each other actual vascular stent/graft')]:add(key,name,'actual_device_type_and_version each_actual_segment_and_overlap proximal_distal_landings source_resolved_frame_and_cover native_lumen_wall_interface every_covered_or_nearby_branch integrity_migration_or_kink actual_patency_leak_or_obstruction_source source_plane_and_calibration uncovered_or_unresolved_extent',[0,1,2,3,4])
    for key,name in [('lvad_inflow','Each actual LVAD inflow cannula'),('lvad_pump','Each actual LVAD pump body'),('lvad_outflow','Each actual LVAD outflow graft'),('lvad_driveline','Each actual LVAD driveline'),('left_temporary_pump','Each actual left-sided temporary pump/catheter'),('right_temporary_pump','Each actual right-sided temporary pump/catheter'),('balloon_pump','Each actual balloon pump'),('pa_catheter','Each actual pulmonary-artery catheter'),('other_monitoring_catheter','Each other actual cardiovascular catheter'),('support_cannula','Each actual support/ECMO cannula or conduit if present')]:add(key,name,device+' every_inlet_outlet_or_sidehole proximal_distal_marker_and_extent each_native_entry_landing_and_branch_interface actual_flow_or_pressure_source',[0,1,2,3,4])
    add('dual_lumen_ra_pa_cannula','Each actual dual-lumen RA-PA support cannula','outer_drainage_lumen inner_return_lumen each_drainage_sidehole each_return_fenestration jugular_entry_and_sheath covered_caval_atrial_course valve_and_rv_traversal actual_distal_pa_endpoint branch_and_wall_relation actual_model_version_ifu source_geometry_and_unresolved_extent actual_flow_source',[0,1,2,3,4])
    add('surgical_material','Each actual CABG/maze/other surgical material','actual_procedure_and_date each_source_resolved_clip_wire_or_connector intended_graft_or_ablation_route each_anastomosis_if_resolved native_coronary_atrial_or_vessel_relation expected_material_vs_retained_foreign_body source_coverage_and_uncertainty',[0,1,2,3,4])
    route='actual_entry_or_origin full_covered_course device_to_lumen_or_wall_relation each_branch_or_junction actual_tip_or_landing_relation local_axis_if_measured patency_or_obstruction_source uncovered_or_unresolved_extent'
    for side in ['right','left']:
        for key,name in [('internal_jugular','Internal jugular access'),('subclavian','Subclavian/axillary access'),('brachiocephalic','Brachiocephalic route'),('svc','Actual SVC route'),('femoral_access','Femoral access if covered')]:add(side+'_'+key,side.capitalize()+' '+name,route,[1,2,3],side)
    for key,name in [('ivc','Covered IVC route'),('coronary_sinus','Coronary sinus and each target cardiac vein'),('pulmonary_arteries','Actual PA trunk/branches traversed or landed'),('aortic_access','Actual aortic/access path'),('arch_branches','Each arch branch near balloon/stent/device'),('visceral_branches','Each visceral/renal branch near balloon/device if covered'),('postoperative_routes','Every actual congenital/postoperative device route')]:add(key,name,route,[1,2,3])
    for key,name in [('right_atrium','Covered RA/appendage and device interfaces'),('left_atrium','Covered LA/appendage and device interfaces'),('right_ventricle','Covered RV/septum/outflow and device interfaces'),('left_ventricle','Covered LV/septum/outflow and device interfaces')]:add(key,name,'source_resolved_wall_and_blood_pool actual_chamber_or_appendage_morphology each_actual_device_interface nearby_valve_or_outflow_relation every_crossed_septal_or_other_connection source_plane_phase_and_artefact each_unresolved_or_uncovered_boundary',[1,2,3])
    for valve in ['aortic','mitral','tricuspid','pulmonary']:add(valve+'_annulus_interface',valve.capitalize()+' actual valve/annular interface','actual_annular_plane source_resolved_leaflet_or_disc source_native_prosthetic_relation each_device_crossing_or_attachment inflow_outflow_relation neighbouring_wall_or_branch motion_or_functional_source unresolved_thin_interface',[1,2,3])
    for key,name in [('pericardium','Pericardial compartment'),('pleura','Each relevant pleural compartment'),('access_soft_tissues','Each access/pocket soft-tissue compartment'),('mediastinal_tissues','Each affected mediastinal compartment'),('adjacent_organs','Every affected adjacent lung/organ region')]:add(key,name,'actual_compartment_and_boundaries device_relation source_resolved_fluid_air_or_haemorrhage each_collection_extent_and_dimensions_if_measured active_leak_or_perforation_source infection_or_obstruction_evidence modality_and_coverage_limits unavailable_functional_or_clinical_context',[3])
    add('complications','Every actual displacement/integrity/penetration/obstruction complication','exact_affected_component actual_site_and_extent source_resolved_geometry fracture_vs_projection_or_tie_down_mimic malposition_vs_intended_variant perforation_and_adjacent_compartment_evidence thrombus_obstruction_or_leak_evidence every_affected_structure comparison_and_uncertainty urgent_communication_and_confirmatory_source',[1,2,3,4],purpose='pathology_example')
    add('comparison','Every actual prior device/timepoint','patient_and_examination_identity dates_and_procedure_or_revision actual_component_correspondence projection_and_patient_position respiratory_cardiac_phase calibration_and_reference_landmarks measured_position_or_geometry_change uncertainty_of_migration_vs_projection uncovered_or_unavailable_prior_extent',[4])
    add('function_and_system','Actual device function/system-condition evidence','complete_manufacturer_model_and_component_identification current_device_specific_instructions_and_version electrical_interrogation_if_available valve_motion_or_regurgitation_source_if_available pump_flow_or_pressure_source_if_available residual_shunt_or_branch_perfusion_source clinical_tamponade_or_infection_evidence complete_system_mri_condition_and_specialist_protocol_if_relevant uncertainty_and_unavailable_function',[0,2,3,4])
    add('acquisition','Actual imaging and measurement controls','actual_modality_and_safety_context source_patient_series_and_date complete_available_coverage projection_and_position cardiac_respiratory_phase contrast_or_sequence_if_relevant original_voxel_or_projection_calibration source_reformatted_planes metal_motion_or_overlap_artefacts every_unresolved_device_or_tissue_boundary',[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':'rad.5.cardiac-masses-devices','title':'Cardiovascular device imaging',
        'scope_status':'expanded_draft_requires_independent_device_anatomical_and_clinical_review','modality_scope':['Radiography','CT','Ultrasound','MRI'],
        'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':s} for t,u,s in zip(['Radiology Assistant devices','Chest cardiac devices pictorial review','Conduction device radiography review','SCMR CIED/MRI consensus','Mechanical support imaging review','ProtekDuo manufacturer product context'],URLS,['effective_scope_and_relevant_device_sections_reviewed','original_XML_body_tables_and_selected_captions_reviewed','original_XML_lead_course_complication_extracts_reviewed','original_XML_relevant_complete_system_and_abandoned_lead_extracts_reviewed','original_XML_main_figures_body_and_complete_JPEGs_reviewed','current_product_description_of_RA_drainage_MPA_return_only_not_full_IFU'])],
        'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),
        'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Instantiate each actual device/model/component/route, intended anatomy, patient variant and complication; this is a known floor, not a complete device catalogue.',
            'Each leaf requires independently reviewed image/schematic/model evidence for actual state, modality, laterality and device identity; a generic heart or manufacturer silhouette cannot grant coverage.',
            'Radiolucent/thin structures, functional measurements and MRI conditions need their actual source; no modality is assumed to resolve every leaf.'],
        'source_scope_issues':['Generator marker/appearance alone does not establish complete-system MRI conditions; older blanket contraindication or reassurance is not current universal guidance.',
            'Primary RA LVAD text mislabels the apical cannula as outflow; inflow/outflow are separately required and actual device/procedure source must govern.',
            'No generic arch-distance, ideal tip, manufacturer brand or source-case threshold is adopted as universal safe device position.',
            'PMC4286824 licence URL is CC BY-NC-SA 3.0 despite broad attribution wording; its images are not commercially cleared/reused.',
            'PMC6837806 is CC BY 4.0; 20 complete original radiographs are reviewed/preserved, but in-pixel permission-only Figures 13/21 are excluded. The erratum changes article classification only; complete anatomy/current-device-system validation remains pending.',
            'PMC7758755 snapshot was unavailable (404/500); no uninspected contents or rights are borrowed.',
            'PMC10350447 Figure 12 port wording conflicts with its body/table and current ProtekDuo manufacturer RA drainage/MPA return; no RV-outlet normal target is adopted. Creator CLAHE is not raw unprocessed acquisition.',
            'No complete current manufacturer IFU catalogue, clinical certification or independent device/tissue-boundary review is claimed.'],
        'functional_evidence_requirements':['Imaging appearance/position does not prove capture, sensing, shock effectiveness, valve/pump performance, shunt or clinical complications.',
            'Use actual model/system and applicable specialist protocols; static 3D geometry is not device interrogation or MRI clearance.',
            'Device-specific anatomical acceptance and complications require appropriate source acquisitions and clinical context, not normal preset text.'],
        'clinical_validation_status':'draft_requires_cardiovascular_radiologist_device_specialist_and_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=IDENT]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n')
    print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
