#!/usr/bin/env python3
"""Enumerate actual radiographic interfaces, hidden regions and every covered bone/device route."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_chest_radiograph_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.chest-radiography'
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];items=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        items.append({'id':'cxr.'+key,'name':name,'tissue_class':'chest_radiographic_structure_interface_or_source_control','required_parts':[{'id':'cxr.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['Radiography'],'condition':'Instantiate every actual covered side, regional interface, variant, lesion, bone and device route with its acquired projection/position and evaluability. Standard labels are a known floor, not a fixed patient anatomy or proof of every visible interface. Unresolved/overlapped or uncovered structures remain missing; CT/echo/physiology are separate sources.','requirement_basis':'effective_full_chest_radiograph_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    add('trachea_carina','Covered trachea/carinal region','actual_obtained_airway_course lumen_column_and_projected_wall_if_resolved carinal_bifurcation_and_main_bronchial_relationship source_deviation_narrowing_or_overlapping_mimic actual_view_rotation_and_quality unresolved_or_uncovered_extent',[0,1,4])
    for key,name in [('cardiac_silhouette','Cardiac silhouette and actual chamber-related contours'),('aortic_contours','Covered aortic knob/ascending/descending projected contours'),('pulmonary_trunk','Pulmonary trunk and relevant projected arterial contours'),('caval_azygos','Covered caval/azygos projected interfaces'),('paratracheal','Actual right/left paratracheal interfaces'),('azygos_oesophageal','Azygo-oesophageal recess/interface'),('aortopulmonary_window','Aortopulmonary window/interface'),('anterior_posterior_junctions','Actual anterior/posterior junction lines'),('retrosternal','Retrosternal clear-space interfaces'),('retrocardiac','Retrocardiac/posterior cardiac interfaces'),('posterior_mediastinum','Covered posterior mediastinal/paraspinal interfaces')]:add(key,name,'actual_source_visible_boundary_and_extent each_actual_contour_or_silhouette_component adjacent_lung_airway_vessel_or_soft_tissue_relationship source_size_or_position_method_if_appropriate projection_magnification_rotation_and_overlap_limit actual_corresponding_view_or_prior_if_obtained unresolved_native_wall_or_uncovered_extent',[0,1,2,4])
    for side,lobes in [('right',['upper','middle','lower']),('left',['upper_with_lingula','lower'])]:
        add(side+'_main_bronchus',side.capitalize()+' main/covered central bronchial region','actual_obtained_course_and_branch_relation projected_airway_boundary_if_resolved source_narrowing_displacement_or_mimic adjacent_hilar_lung_and_device_relation source_view_quality_and_overlap unresolved_or_uncovered_extent',[0,1,2,4],side)
        add(side+'_hilum',side.capitalize()+' hilar region and relevant vascular/nodal overlap','full_source_hilar_region_and_projected_edges arterial_venous_bronchial_or_nodal_relation_if_resolved actual_size_position_density_and_component each_relevant_lung_mediastinal_interface actual_view_and_comparison_support native_unresolved_or_overlapped_tissue',[0,1,2],side)
        for lobe in lobes:add(side+'_'+lobe+'_territory',side.capitalize()+' source-supported '+lobe.replace('_',' ')+' territory','actual_obtained_region_and_supported_localisation each_opacity_lucency_nodule_mass_or_other_component source_air_bronchogram_or_vascular_pattern volume_and_hilar_fissural_diaphragmatic_relationship silhouette_or_other_obtained_view_support actual_quality_and_comparison_limits unresolved_or_uncovered_extent',[0,1,2,3],side)
        for zone in ['apical','upper','middle','lower','perihilar','retrocardiac','subdiaphragmatic']:
            add(side+'_'+zone+'_zone',side.capitalize()+' '+zone+' projected review zone','each_actual_covered_region source_lung_or_overlapping_tissue_interface every_source_resolved_lesion_or_pattern adjacent_pleural_diaphragmatic_hilar_or_mediastinal_relation actual_view_and_sampling_quality comparison_and_unassessed_extent',[0,1,2,3,4],side)
        add(side+'_additional_region',side.capitalize()+' every actual accessory/variant/unassigned region','actual_source_anatomical_variant_and_site complete_obtained_regional_extent every_lesion_and_tissue_interface supported_vs_unresolved_projected_assignment actual_acquired_view_and_quality any_additional_actual_region_not_standard_labels',[0,1,2,3,4],side)
        for key,name in [('pleural_apex','apical pleural region'),('costophrenic','lateral/posterior costophrenic recesses'),('fissures','visible major_minor_accessory_fissures'),('subpulmonic','subpulmonic pleural region'),('diaphragm','hemidiaphragmatic contour')]:add(side+'_'+key,side.capitalize()+' '+name.replace('_',' '),'each_actual_source_visible_boundary every_air_fluid_thickening_mass_or_other_component source_lung_chest_wall_or_abdominal_interface projected_extent_and_position_dependent_visibility actual_corresponding_views_if_obtained mimics_and_unresolved_or_uncovered_extent',[0,2,3,4],side)
        for key,name in [('opacity','each pulmonary opacity/interstitial component'),('lucency','each pulmonary lucency or cystic component'),('nodular_mass','every nodule/mass or projected mimic'),('volume_loss','each volume-loss/distortion component'),('pneumothorax','every suspected pleural-air region'),('effusion','every suspected pleural-fluid region')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_named_region_and_obtained_extent every_source_visible_border_or_component source_lung_vessel_airway_or_pleural_relationship local_projection_quality_and_superimposition supported_differential_and_confidence actual_prior_source_if_available unassessed_extent_and_unavailable_clinical_confirmation',[0,1,2,3,4],side,'pathology_example')
        for n in range(1,13):add(side+'_rib'+str(n),side.capitalize()+' actual rib '+str(n)+' and adjacent interfaces','actual_source_number_or_variant_assignment complete_obtained_posterior_lateral_anterior_course each_resolved_cortical_or_medullary_interface visible_articulation_and_costal_cartilage_relationship every_source_fracture_lesion_or_overlapping_mimic projection_quality_and_uncovered_extent',[0,4],side)
        for key,name in [('clavicle','clavicle'),('scapula','scapula and covered shoulder'),('chest_wall','chest-wall/breast/axillary soft tissue')]:add(side+'_'+key,side.capitalize()+' '+name,'complete_obtained_extent every_relevant_source_tissue_or_bone_interface joint_air_soft_tissue_mass_or_other_component_if_resolved actual_projection_and_overlap_limit comparison_and_uncovered_extent',[0,4],side)
    for level in ['C7']+['T'+str(n) for n in range(1,13)]:add('vertebra_'+level,'Actual covered '+level+' vertebral region','source_supported_level_and_variant_assignment obtained_body_posterior_element_and_joint_boundaries_if_resolved projected_alignment_or_lesion_component adjacent_paraspinal_lung_and_rib_relation view_quality_and_unresolved_or_uncovered_extent',[0,4])
    for key,name in [('additional_bone','Every actual additional/variant covered bone or joint'),('sternum','Covered manubrium/sternal body/xiphoid and joint interfaces'),('neck_soft_tissue','Covered lower-neck/chest-wall soft tissue'),('upper_abdomen','Every covered relevant upper abdominal organ/gas interface')]:add(key,name,'actual_named_site_and_obtained_extent every_source_visible_tissue_or_joint_boundary actual_lesion_air_fluid_calcification_or_other_component adjacent_thoracic_or_abdominal_relation actual_projection_and_quality unassessed_or_uncovered_extent',[0,3,4])
    for key,name in [('airway_device','Every actual airway device'),('enteric_device','Every actual enteric device'),('vascular_device','Every actual vascular catheter/lead/vascular support device'),('pleural_device','Every actual pleural/drain device'),('other_device','Every actual other support/implant/foreign body')]:add(key,name,'source_device_identity_type_and_time full_obtained_route_and_every_component_or_port projected_tip_and_named_landmark_relation each_source_resolved_tissue_entry_crossing_or_endpoint actual_view_position_and_calibrated_distance_if_available observed_complication_or_mimic_and_confidence unresolved_3D_wall_lumen_route_or_uncovered_extent',[0,1,3,4])
    for key,name in [('acquisition','Actual radiograph acquisition/processing sources'),('comparison','Every actual matching prior/view comparison'),('clinical_source','Actual relevant clinical/physiological confirmation')]:add(key,name,'source_identity_date_and_available_scope actual_projection_position_and_coverage_or_clinical_method source_calibration_measurement_and_uncertainty actual_source_quality_processing_or_timing_limit current_source_not_teaching_case_inference unavailable_or_unassessed_evidence',[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':ref['investigation']['module_id'],'title':'Chest radiography','scope_status':'expanded_draft_requires_independent_chest_radiograph_clinical_review','modality_scope':['Radiography'],'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-07','review_status':'relevant_primary_systematic_projection_and_source_limit_scope_reviewed'} for t,u in zip(['RA systematic chest anatomy','RA position-dependent heart failure','RA pulmonary patterns/localisation','Original quality-control workflow and processing limits'],URLS)],'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':items,'expansion_rules':['Every actual covered rib/bone/region/device and source-visible interface must be instantiated; standard numbers/regions are not fixed patient counts.','Projected silhouettes do not approve native chamber/wall/lumen/branch anatomy or full3D device course.','Unavailable views and clinical function/pressure/fluid chemistry remain missing; parent thorax models cannot supply them.'],'source_scope_issues':['Actual projection/position/inspiration and processing are required; PA/erect/adequate quality cannot be presumed.','AP/supine magnification and low inspiration do not supply a comparable standardPA cardiothoracic ratio or measured function.','Supine fluid/air distributions and overlying skinfolds/other mimics require explicit confidence; absent visible signs on a limited image do not exclude pathology.','Consolidation, collapse, oedema, infection, haemorrhage and neoplasia overlap; radiographic signs do not alone prove cause.','AutoQC publication illustrates annotation removal and rotation correction; processed workflow screenshots are not unchanged native anatomical radiograph evidence.','All native region/tissue/device3D models and independent clinical/anatomical/source-media review remain required.'],'functional_evidence_requirements':['Clinical urgency, pressure/EF/shunt, tension physiology and fluid chemistry require actual clinical/other corresponding sources.','Device course/function and serial change require actual acquired views/time/position/calibration; no invisible lumen or expected device position is filled automatically.'],'clinical_validation_status':'draft_requires_chest_radiologist_and_relevant_clinical_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=IDENT]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n');n=len(requirements_for(item));print(len(item['structures']),'groups;',n,'leaves;',n*3,'representation obligations')
