#!/usr/bin/env python3
"""Enumerate actual HRCT patterns and lobular anatomy, regional tissue interfaces and diagnostic source limits."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_hrct_fibrosis_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.hrct-lung'
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'hrct_lung.'+key,'name':name,'tissue_class':'HRCT_lobular_tissue_interface_or_source_control','required_parts':[{'id':'hrct_lung.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['CT'],'condition':'Instantiate every actual covered side/lobe/segment, variant, pattern or lesion, associated component and tissue interface with actual source plane/reconstruction and evaluability. Standard labels are a known floor, not a fixed actual variant or complete patient count. Microscopic, unacquired or unresolved anatomy remains missing. Clinical/genetic/tissue sources are separate from CT.','requirement_basis':'effective_full_HRCT_and_fibrotic_lung_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    regional='actual_covered_extent_and_boundaries each_actual_pattern_or_lesion_site source_airway_vessel_pleural_or_septal_interfaces regional_pattern_and_justified_disease_extent source_opacity_nodule_fibrosis_or_other_component each_resolved_or_unresolved_boundary actual_reconstruction_phase_window_and_evaluability uncovered_or_unassessed_extent'
    segs={'right':['upper_apical','upper_posterior','upper_anterior','middle_lateral','middle_medial','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal'],'left':['upper_apical','upper_posterior','upper_anterior','lingular_superior','lingular_inferior','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal']}
    for side,lobes in [('right',['upper','middle','lower']),('left',['upper_with_lingula','lower'])]:
        for lobe in lobes:add(side+'_'+lobe+'_lobe',side.capitalize()+' '+lobe.replace('_',' ')+' lobe/territory',regional,[0,1,2,3],side)
        for segment in segs[side]:add(side+'_'+segment+'_region',side.capitalize()+' actual '+segment.replace('_',' ')+' segmental region',regional+' actual_combined_accessory_or_variant_assignment',[0,1,2,3],side)
        add(side+'_additional_region',side.capitalize()+' every actual combined/accessory/unassigned regional variant',regional+' each_additional_source_defined_region_not_standard_label',[0,1,2,3],side)
        for key,name in [('pleura_recesses','pleura and costophrenic/other recesses'),('fissures','actual major_minor_accessory_fissures'),('peribronchovascular','peribronchovascular compartment'),('subpleural','subpleural peripheral compartment'),('paramediastinal','paramediastinal compartment')]:add(side+'_'+key,side.capitalize()+' '+name.replace('_',' '),'full_actual_covered_boundary each_cyst_lesion_or_mimic_relation local_wall_airway_vessel_or_septal_interface source_extent_distribution_and_quality each_actual_opacity_or_solid_component comparison_and_unresolved_or_uncovered_extent',[0,1,2,3,4],side)
        for key,name in [('ground_glass','every ground_glass region'),('consolidation','every consolidative_or_airspace region'),('reticulation','every reticular_or_septal region'),('honeycomb','each honeycomb_or_mimic region'),('traction_airway','each traction_bronchial_bronchiolar region'),('cyst_emphysema','each cystic_or_emphysematous region'),('solid_mass','every source solid_mass_or_nodular component')]:add(side+'_'+key,side.capitalize()+' '+name,'each_actual_site_and_obtained_extent source_parenchymal_airspace_or_wall_boundary_if_relevant actual_attenuation_texture_and_border_with_source_limits each_relevant_reticular_airspace_solid_or_cystic_component each_airway_vessel_and_adjacent_parenchymal_relation local_axis_measurement_window_and_calibration actual_same_site_comparison_and_chronology mimics_and_unresolved_microscopic_components',[0,1,2,3],side,purpose='pathology_example')
        for key,name in [('nodular_pattern','every centrilobular_perilymphatic_random_nodular region'),('mosaic','every mosaic_or_three_density region'),('distortion','every distortion_or_volume_loss region'),('perilobular_organising','every perilobular_or_organising_opacity region')]:add(side+'_'+key,side.capitalize()+' '+name.replace('_',' '),'each_actual_site_and_extent lesion_vs_intervening_parenchymal_boundary local_airway_vessel_septal_or_pleural_relation actual_distribution_and_source_sampling source_measurement_or_comparison_if_available technical_limits_and_differential unresolved_or_uncovered_components',[0,1,2,3],side,purpose='pathology_example')
        for key,name in [('pneumothorax','actual pneumothorax'),('pleural_fluid','each pleural fluid or other lesion')]:add(side+'_'+key,side.capitalize()+' '+name,'source_pleural_compartment_and_obtained_extent adjacent_cyst_lung_and_chest_wall_relationship source_resolution_and_quality clinical_effect_or_fluid_characterisation_if_supplied chronology_and_actual_prior_source uncertainty_and_uncovered_extent',[0,4],side,purpose='pathology_example')
        add(side+'_secondary_lobule',side.capitalize()+' every source-resolved relevant secondary pulmonary lobule','actual_lobular_boundary_and_obtained_extent interlobular_septal_interfaces source_centrilobular_arterial_and_bronchiolar_core source_peripheral_venous_and_lymphatic_relationship intralobular_interstitial_and_acinar_interfaces_if_resolved lesion_nodule_opacity_and_airspace_distribution airway_vessel_septal_or_pleural_endpoint_and_continuity resolved_vs_microscopic_or_inferred_tissue source_resolution_sampling_and_uncertainty',[0,1,2,3],side)
        add(side+'_bronchiolocentric_pattern',side.capitalize()+' every actual bronchiolocentric interstitial pattern region','actual_small_airway_centric_site full_obtained_parenchymal_extent source_wall_airspace_septal_and_vessel_relationship each_associated_nodular_ground_glass_reticular_or_other_component CT_pattern_vs_supplied_histology_and_multidisciplinary_source actual_secondary_or_idiopathic_differential_and_confidence unresolved_or_uncovered_extent',[0,1,2,3,4],side)
        for key,name in [('airway','every actually covered relevant airway branch'),('artery','every source-resolved relevant pulmonary/systemic arterial branch'),('vein','every source-resolved relevant venous connection')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_origin_and_obtained_course every_relevant_branch_or_connection source_lumen_wall_or_partial_volume_limit cyst_or_mimic_interface_and_continuity actual_distal_endpoint_if_covered contrast_phase_or_noncontrast_evaluability unavailable_or_unresolved_extent',[0,1,2,3,4],side)
    for key,name,parts,steps in [('nodes','Every covered mediastinal/hilar lymph-node or mass region','each_actual_site_and_source_boundary local_size_method_and_calibration cyst_lung_airway_and_vessel_relation source_density_or_component_if_resolved comparison_and_coverage_limits',[2,4]),('renal','Every covered relevant renal/adrenal/upper-abdominal lesion','each_actual_organ_and_covered_extent lesion_or_mass_interfaces_if_present actual_acquired_phase_and_calibration source_only_morphology_and_uncertainty renal_or_genetic_diagnosis_not_from_uncovered_source',[4]),('acquisition','Actual CT acquisition and measurement sources','source_identity_date_and_clinical_question complete_obtained_coverage_and_sampling reconstruction_window_phase_and_motion local_measurement_axis_edge_convention_calibration actual_inspiration_expiration_contrast_if_obtained uncertainty_and_unperformed_tests',[0,1,2,3,4]),('comparison','Every actual comparison lesion/site','source_identity_date_and_prior_coverage actual_corresponding_site_and_component registration_or_plane_sampling_difference supported_interval_change_and_uncertainty changes_not_inferred_from_unmatched_teaching_cases',[0,1,2,3,4]),('clinical_context','Actual systemic/history/diagnostic sources','source_identity_date_and_available_scope smoking_autoimmune_infection_or_hereditary_history actual_genetic_microbiology_or_histological_evidence clinical_function_or_systemic_findings_if_supplied current_patient_not_teaching_case_source unavailable_or_uncertain_confirmation',[4]),('distribution_burden','Complete obtained regional distribution/burden source','actual_coverage_of_each_side_lobe_and_variant number_or_explicitly_qualified_burden_estimate apical_basal_axial_and_pleural_relationship every_relevant_cyst_or_associated_component age_count_heuristic_not_unique_or_exclusion_diagnosis source_quality_and_unassessed_regions',[0,1,2,3,4])]:add(key,name,parts,steps)
    add('oesophagus','Covered oesophageal and mediastinal soft-tissue relationships','actual_source_covered_course lumen_wall_and_dilation_or_other_component_if_resolved adjacent_lung_airway_vessel_or_pleural_relation source_phase_sampling_and_evaluability clinical_reflux_aspiration_or_motility_not_from_still uncovered_or_unresolved_extent',[4])
    add('cardiovascular_context','Every covered relevant cardiac/pericardial/vascular clue','actual_named_chamber_vessel_or_pericardial_site full_obtained_tissue_pool_or_channel_extent source_resolved_size_shape_calcium_or_other_component local_acquisition_axis_and_measurement_calibration actual_separate_echo_hemodynamic_or_function_source_if_supplied unresolved_or_uncovered_extent',[3,4])
    return {'investigation_id':IDENT,'module_id':'rad.4.hrct','title':'HRCT lung and pulmonary fibrosis','scope_status':'expanded_draft_requires_independent_HRCT_and_ILD_clinical_review','modality_scope':['CT'],'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':'relevant_primary_morphology_pattern_or_definition_scope_reviewed'} for t,u in zip(['RA basic morphology','RA common differential','RA fibrosis patterns','ESR/ESTI recommendations','Named2022IPF/PPF definition','2025ERS/ATS terminology'],URLS)],'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':structures,'expansion_rules':['Instantiate every actual covered lobule, tissue/airway/vessel interface, regional disease component and lesion; standard region names are not fixed complete anatomy.','Unresolved microscopic septal/acinar/vascular/lymphatic walls and unacquired respiratory phases remain missing; parent thorax models or static source cases cannot supply them.','Every supplied comparison/function/clinical result must bind its actual source and date, not a teaching case.'],'source_scope_issues':['UIP CT pattern differs from idiopathic/secondary disease or histological diagnosis; unclassifiable/mixed patterns and confidence remain valid.','No unperformed expiration/prone/contrast or unavailable perfusion/physiology can be inferred from inspiration-only stills. Mosaicism and bronchiolocentric findings have multiple causes.','2025ERS/ATS source introduces major BIP pattern and AMP terminology; CT appearance alone does not establish histological disease or idiopathic aetiology.','Named2022PPF definition requires at least2 of symptoms/radiology/physiology within1year, no alternative explanation, in fibrotic ILD other thanIPF. Source13/15month follow-up cases do not independently prove that window.','New acute ground glass may reflect exacerbation/infection/oedema/other causes; microscopic rupture and treatment indications are not derived from a still.'],'functional_evidence_requirements':['Actually acquired respiratory phases are required for reported expiration/prone behaviour.','Physiological impairment/progression requires supplied symptoms/PFT/source dates and context; CT burden alone does not measure function, pressure or treatment response.'],'clinical_validation_status':'draft_requires_thoracic_radiologist_and_multidisciplinary_ILD_review'}

if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=IDENT]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n');n=len(requirements_for(item));print(len(item['structures']),'groups;',n,'leaves;',n*3,'representation obligations')
