#!/usr/bin/env python3
"""Require source anatomy and actual temporal swallowing evidence, without preset function."""
import copy,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];INV='ra.swallowing'
SOURCES=[{'title':'RA swallowing source approach','url':'https://radiologyassistant.nl/head-neck/swallowing/swallowing-disorders-update'},{'title':'ESSD–ESGAR adult VFSS technical consensus','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC12081525/'},{'title':'ASHA VFSS practice resource','url':'https://www.asha.org/practice-portal/resources/videofluoroscopic-swallow-study/'}]
def build():
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];guide=copy.deepcopy(ref['reporting'])
    details=['Map actual source oral tissues, bolus and preparation/transport events for each recorded trial; distinguish observed movement from inferred muscle or nerve function.',
      'Trace actual palate/pharyngeal/hyoid/laryngeal relationships and bolus/residue route with recorded timing, projections and evaluability.',
      'Describe each actually recorded airway-entry event relative to the visible vocal-fold level, bolus passage and observed response; unresolved timing or boundaries remain uncertain.',
      'Map each acquired wall/lumen, pouch/web/bar, external impression or treated interface and its observed passage effect; static contour is not a unique physiological cause.',
      'Identify each tested bolus, delivery, position and manoeuvre with trial-specific observations; acquired esophageal screening, unavailable phases and clinical management remain separately documented.']
    looks=['Review the acquired lips, teeth/appliances, cheeks, tongue, oral floor and palate with source bolus containment, mastication, transfer and residue. Preserve actual trial identity and every visible component; absent coverage is unassessed.',
      'Review acquired velopharyngeal passage, tongue-base relationship, valleculae, pharyngeal walls, pyriform regions, hyoid/laryngeal movement and pharyngoesophageal passage. Use actual cine frame order and timing; identify projection overlap and unresolved wall/structure boundaries.',
      'Trace source bolus/material relative to the laryngeal vestibule, visible vocal-fold landmark, subglottis and acquired trachea before/during/after passage. Document recorded clearance/cough or absent observed response; a selected still or static model cannot exclude aspiration or establish event timing.',
      'Review source pharyngeal/cervical esophageal contour and each pouch neck, wall, retained content, web/bar, narrowing or extrinsic interface. Correlate actual opening/passage over recorded frames. Other acquired CT/MRI, endoscopy, pathology or pressure data remain explicit separate sources.',
      'Compare only actual recorded trials with their bolus type/volume/consistency, delivery, posture and tested manoeuvre. Describe source observation and limits; one successful trial does not guarantee general safety. Record obtained esophageal extent and recommend clinical interpretation through the relevant team.']
    tips=['Projection overlap or unobserved preparatory events do not establish normal oral control. Source bolus boundaries are not every tiny muscle, mucosal layer or neural branch.',
      'Asymmetry has a differential, including positioning/rotation, distension, structural change and functional impairment; it does not uniquely diagnose unilateral paresis.',
      'Document aspiration and observed response without a universal risk ranking. Absence of cough during an observed event is distinct from an unrecorded response or a unique cause of impaired airway protection.',
      'A visible bar/impression, pouch or static narrowing alone does not establish functional obstruction, sphincter pressure, neurological cause, histology or a surgical indication.',
      'A tested manoeuvre or consistency has source-specific results; future diet safety, treatment benefit and full esophageal motility are not certified by a selected still or schematic.']
    guide.update(reviewed_at='2026-10-08',protocol=['Record patient/source/trial identity, indication, supplied clinical context and populations; actual projections, posture, field coverage, fluoroscopy pulse rate, recorded frame rate, frame order/timestamps and missing/dropped frames if known.',
      'Record actual contrast type, bolus volume/consistency, delivery and instructions; tested strategies and examinations obtained, recording/storage and available dose. State temporal/spatial, calibration, projection and cooperation limits. Adult technical consensus is not an automatic pediatric protocol or acquired finding.'],checklist=[{'label':label,'detail':detail} for label,detail in zip(['Oral tissues bolus and transfer','Pharyngeal route and clearance','Airway entry and response','Structural and passage interfaces','Tested trials and source limits'],details)],pitfalls=tips,sources=SOURCES,
      impression_prompts=['Summarise actual acquired morphology and recorded trial-specific swallowing/airway events with their source confidence and limits.','Keep uncovered anatomy, clinical diagnosis, neurological mechanism and treatment decisions explicit rather than filling normal or safe findings automatically.'])
    bodies=['Every acquired oral component/bolus interface and trial [ ]; source containment, mastication/transfer and residue [ ]; observed events/frames and unresolved neural or microscopic mechanism [ ].',
      'Each acquired palate/tongue-base/pharyngeal/hyoid/laryngeal/upper-esophageal interface [ ]; bolus route/residue and source sequence timing [ ]; asymmetry, overlap and unobserved extent [ ].',
      'Each recorded trial and airway-entry event [ ]; source vocal-fold/vestibular/subglottic landmarks and evaluability [ ]; observed timing and clearance/response [ ]; unobserved response, differential and temporal limitations [ ].',
      'Every actual pouch/neck/wall/content, web/bar/narrowing or extrinsic/treated interface [ ]; obtained projections and source passage effect [ ]; separate structural/clinical/pressure/tissue evidence and uncertainty [ ].',
      'Every tested bolus/volume/consistency/delivery, posture/manoeuvre and trial-specific response [ ]; actually acquired esophageal screening/other sources [ ]; absent coverage, source limitations and relevant clinical communication [ ].']
    for section,body in zip(guide['template_sections'],bodies):section['body']=body
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data.setdefault(INV,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/head-neck.json';text=path.read_text();start=text.index('{',text.index('"'+INV+'"'));node,end=json.JSONDecoder().raw_decode(text,start);removed=sum(bool(s.get('normal')) for s in node['steps']);node['reviewed_at']='2026-10-08'
    for n,step in enumerate(node['steps']):step.update(detail=details[n],normal={},look=looks[n],tip=tips[n],findings=['Actual acquired '+step['label'].lower()+' anatomy/events [ ]; source/trial/frame/projection [ ]; confidence and unavailable evidence [ ].'])
    node['model']={'family':'swallow','reporting_aim':'Partial swallowing orientation only. This static schematic does not represent every native oral/pharyngeal/laryngeal/esophageal tissue, bolus, wall, nerve/muscle or treated interface. It supplies no timed swallowing motion, aspiration exclusion, pressure, muscle/nerve function or treatment/diet safety.'}
    path.write_text(text[:start]+json.dumps(node,indent=2).replace('\n','\n    ')+text[end:])
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];structures=[]
    def add(key,steps,side='not_applicable',event=False):
        ident='swallowing.'+side+'_'+key;parts=['every_actual_component_and_source_extent','source_resolved_wall_margin_or_tissue_boundary','each_bolus_content_or_adjacent_tissue_interface','actual_variant_lesion_or_treatment_connection','source_frame_projection_and_spatial_calibration','unresolved_microscopic_functional_or_uncovered_extent']
        if event:parts=['actual_source_trial_and_bolus_identity','every_observed_event_frame_and_temporal_boundary','each_source_bolus_tissue_lumen_or_residue_interface','source_projections_overlap_and_visible_landmarks','recorded_clearance_response_or_tested_modification','unobserved_time_coverage_or_unresolved_causal_mechanism']
        structures.append({'id':ident,'name':side.replace('_',' ').capitalize()+' '+key.replace('_',' '),'tissue_class':'source_swallowing_tissue_or_bolus_event_interface','required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts],'laterality':side,'modality_scope':['Radiography'],'condition':'Independently instantiate every acquired actual side, tissue/branch/bolus, source frame/trial, variant, lesion and treated interface. VFSS projection permission does not resolve every fine tissue or prove full 3D anatomy; CT/MRI, endoscopy, pressure and clinical sources stay separate and explicitly identified.','requirement_basis':'full_effective_swallowing_reporting_anatomy_and_actual_recorded_events','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':[s['url'] for s in SOURCES],'requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if event else 'anatomical_reference'},'requires_actual_temporal_evidence':event})
    for side in ['left','right']:
        for key in ['labial_buccal_and_gingival_tissues','dentition_alveolar_ridge_and_appliances','oral_tongue_intrinsic_and_extrinsic_components','oral_floor_and_sublingual_interfaces','palatine_and_lingual_tonsillar_regions']:add(key,[0,1,3],side)
        for key in ['pharyngeal_lateral_wall_and_constrictor_components','vallecular_space_and_tongue_base_interface','pyriform_recess_and_apical_interface','aryepiglottic_fold_and_laryngeal_inlet','arytenoid_false_fold_and_true_vocal_fold','pharyngeal_elevator_and_suprahyoid_components','infrahyoid_and_laryngeal_elevator_interfaces','hyoid_horn_and_hyolaryngeal_connections','laryngeal_cartilage_and_ligament_interfaces','parapharyngeal_prevertebral_and_other_extrinsic_interfaces']:add(key,[1,2,3],side)
        for key in ['each_actual_or_supplied_V_VII_IX_X_XII_route_and_target','each_encountered_neural_muscle_or_dental_variant','each_obtained_salivary_duct_or_gland_interface','each_acquired_pharyngeal_pouch_and_neck','each_actual_postoperative_or_reconstructed_tissue']:add(key,[0,1,2,3,4],side)
        for key in ['each_actual_lateral_bolus_route_or_residue','each_observed_asymmetry_and_recorded_projection','each_recorded_reflux_into_a_covered_pharyngeal_route']:add(key,[0,1,2,4],side,True)
    for key in ['hard_palate_and_soft_palate_velum','uvula_and_velopharyngeal_port','nasopharyngeal_wall_and_lumen','oral_posterior_tongue_and_faucial_gateway','epiglottis_petiolus_and_vallecular_septal_interfaces','posterior_pharyngeal_wall_and_constrictor_plane','hyoid_body_and_laryngeal_suspension','laryngeal_vestibule_and_vocal_fold_level','subglottic_airway_wall_and_lumen','obtained_cervical_tracheal_wall_and_lumen','postcricoid_hypopharyngeal_wall_and_lumen','pharyngoesophageal_segment_and_cricopharyngeal_interfaces','cervical_esophageal_wall_and_lumen','covered_thoracic_esophagus_and_junctional_extent','cervical_vertebral_osteophyte_and_posterior_impression','each_actual_web_ring_bar_or_intrinsic_narrowing','each_actual_pouch_wall_content_and_reentry_route','every_encountered_primary_lesion_and_mucosal_interface','each_acquired_foreign_body_or_device_interface']:add(key,[0,1,2,3,4])
    for key in ['every_actual_bolus_consistency_volume_and_delivery','each_preparatory_containment_and_mastication_event','each_source_oral_transport_and_spillage_event','each_velopharyngeal_closure_or_nasal_escape_event','each_observed_tongue_base_pharyngeal_contact','each_source_hyoid_laryngeal_and_epiglottic_event','each_observed_upper_esophageal_opening_and_passage','each_actual_laryngeal_penetration_event','each_observed_subglottic_aspiration_event','each_actual_airway_material_clearance_or_response','each_observed_cough_or_absent_recorded_response','each_actual_residue_collection_and_subsequent_route','each_repeated_swallow_and_source_trial_comparison','each_tested_posture_or_compensatory_manoeuvre','each_actual_esophageal_screening_clearance_or_reflux','each_obtained_comparison_or_treatment_response']:add(key,[0,1,2,3,4],event=True)
    item={'investigation_id':INV,'module_id':ref['investigation']['module_id'],'title':'Complete acquired swallowing anatomy and actual trial-specific temporal interfaces','scope_status':'expanded_draft_requires_independent_swallowing_anatomical_and_temporal_review','modality_scope':['Radiography'],'sources':[dict(s,reviewed_at='2026-10-08',review_status='primary_reporting_context_no_source_graphics_or_cine_reused') for s in SOURCES],'source_contract_sha256':digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
      'expansion_rules':['Every actual tissue/branch/bolus/variant/lesion and source trial/frame/interface requires separate source instantiation; listed groups are a known floor.','Fine shape and native 3D labels require independent matched-source anatomy; a projection or generic orientation model is not a complete tissue reconstruction.','Timed events require actual recorded sequences with frame/pulse rate, frame order/gaps and trial/bolus context; still images and smooth model animation do not supply those events.'],
      'source_scope_issues':['The current partial swallow orientation model and selected still references do not establish full microscopic walls, neural/muscle anatomy or every native interface.','Adult ESSD–ESGAR technical guidance is not a pediatric acquisition protocol, patient normality, current risk score or universal clinical action.'],
      'functional_evidence_requirements':['Each bolus/consistency/volume, delivery, source trial and manoeuvre must have its actual observed cine; before/during/after timing, clearance or response cannot be inferred from a still.','Pressure/manometry, muscle/nerve physiological mechanism, endoscopic/pathological identity, diet safety and treatment benefit require actual separately supplied relevant clinical evidence.','Record acquired frame and pulse rates, timestamps/frame order/gaps and temporal/spatial evaluability. Untested textures or positions, absent cough recording and incomplete esophageal coverage remain unassessed.'], 'clinical_validation_status':'draft_requires_radiologist_speech_language_swallowing_and_anatomical_review'}
    path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=INV]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');n=len(requirements_for(item));print(len(structures),'groups;',n,'parts;',n*3,'representation obligations;',removed,'unsupported normal presets removed')
if __name__=='__main__':build()
