#!/usr/bin/env python3
"""Expand actual cardiac lesion, attachment, mimic and spread anatomy with source controls."""
import json
from pathlib import Path
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.cardiac-masses'
URLS=['https://radiologyassistant.nl/cardiovascular/cardiac-masses1/cardiac-masses','https://pmc.ncbi.nlm.nih.gov/articles/PMC10818366/','https://pmc.ncbi.nlm.nih.gov/articles/PMC9558634/']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];guide=ref['reporting'];structures=[]
    def add(key,name,children,steps,purpose='anatomical_reference',side='not_applicable'):
        structures.append({'id':'cardiac_mass.'+key,'name':name,'tissue_class':'cardiac_mass_structure_interface_or_source_control',
            'required_parts':[{'id':'cardiac_mass.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in children.split()],
            'laterality':side,'modality_scope':['CT','MRI','Ultrasound','PET-CT'],
            'condition':'Instantiate every actual lesion/component, attachment, site, mimic, variant, timepoint and affected interface. Preserve patient/source identity, modality/sequence, phase, calibration, coverage and uncertainty. Conditional modality capabilities, physiological observations and diagnoses require actual source evidence; an unseen structure or missing test is not normal.',
            'requirement_basis':'effective_cardiac_mass_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],
            'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    boundary='source_resolved_endocardial_boundary myocardial_or_wall_extent adjacent_epicardial_or_pericardial_interface actual_lesion_relation each_attachment_or_invasive_interface covered_inflow_outflow_or_vessel_relation phase_and_visibility_limit uncovered_or_unresolved_extent'
    for key,name,side in [('left_atrium','Left atrium','left'),('right_atrium','Right atrium','right'),('left_ventricle','Left ventricle','left'),('right_ventricle','Right ventricle','right'),('left_appendage','Left atrial appendage','left'),('right_appendage','Right atrial appendage','right')]:add(key,name,boundary,[0,1,4],side=side)
    for key,name in [('interatrial_septum','Interatrial septum/fossa and surrounding rims'),('interventricular_septum','Interventricular septum'),('left_outflow','LV outflow tract'),('right_outflow','RV outflow tract')]:add(key,name,boundary+' actual_septal_or_outflow_subregions',[0,1,4])
    for valve in ['aortic','mitral','tricuspid','pulmonary']:
        add(valve+'_valve',valve.capitalize()+' native/prosthetic valve interface','actual_leaflet_or_disc_identity source_resolved_leaflet_surfaces free_edge_and_attachment each_actual_annular_segment commissural_or_subvalvar_relation every_lesion_or_thrombotic_attachment prosthetic_or_repair_interface_if_present inflow_outflow_relation actual_temporal_motion_source unresolved_thin_or_uncovered_boundary',[0,1,4])
    for side in ['left','right']:
        add(side+'_papillary_chordal',side.capitalize()+' actual papillary/chordal apparatus','every_actual_papillary_group source_resolved_base_body_tip each_resolved_chordal_course leaflet_attachment lesion_vs_muscle_or_chordal_mimic actual_temporal_relation unresolved_or_uncovered_thin_parts',[0,1,4],side=side)
    for key,name in [('pulmonary_veins','Every covered pulmonary vein/atrial ostium'),('svc','Covered SVC/atrial junction'),('ivc','Covered IVC/atrial junction'),('coronary_sinus','Coronary sinus/venous interfaces'),('aortic_root','Aortic root/covered aorta'),('pulmonary_arteries','Covered pulmonary trunk/branches'),('coronary_arteries','Each relevant coronary artery/ostium/graft')]:add(key,name,'actual_origin_or_ostium full_covered_course lumen_wall_and_thrombotic_interface each_branch_or_connection actual_lesion_compression_encasement_or_extension each_attachment_or_fistulous_relation source_patency_or_perfusion_evidence uncovered_or_unresolved_extent',[0,1,4])
    for key,name in [('pericardium','Actual pericardial layers/compartments'),('epicardium','Actual epicardial surface and fat'),('av_grooves','Each affected atrioventricular groove'),('mediastinal_interfaces','Each covered mediastinal/hilar interface'),('lung_pleura','Each affected lung/pleural region'),('nodes','Each covered suspicious nodal station'),('extracardiac_organs','Each covered extracardiac primary/deposit/extension')]:add(key,name,'actual_site_and_source_boundary lesion_to_normal_tissue_interface full_covered_extent source_resolved_invasion_vs_contact every_affected_vessel_airway_or_organ each_fluid_or_soft_tissue_component modality_and_functional_limits uncovered_or_unresolved_extent',[0,1,4])
    for key,name in [('coumadin_ridge','Actual left atrial/Coumadin ridge'),('crista_terminalis','Actual crista terminalis'),('taenia_sagittalis','Actual sagittal pectinate bundle'),('pectinate_trabeculae','Every relevant pectinate/trabecular structure'),('eustachian_valve','Actual Eustachian remnant'),('thebesian_valve','Actual Thebesian remnant'),('chiari_network','Actual Chiari network'),('moderator_band','Actual moderator band'),('septal_variant','Each actual atrial septal variant'),('postoperative_mimic','Each actual suture/baffle/repair mimic')]:add(key,name,'actual_origin_and_course each_source_resolved_attachment source_resolved_morphology relation_to_adjacent_wall_valve_or_vessel actual_signal_or_attenuation_comparison temporal_source_if_observed every_unresolved_or_variant_part',[0,1,2,3])
    for key,name in [('lipomatous_septum','Lipomatous septal thickening if present'),('caseous_annular_calcification','Caseous/calcified annular region if present'),('cyst','Each actual pericardial/other cyst'),('aneurysm_pseudoaneurysm','Each chamber/vessel/graft aneurysm mimic'),('extracardiac_mimic','Each actual extracardiac hernia/other mimic')]:add(key,name,'actual_site_and_all_components source_resolved_boundary each_attachment_or_connection relation_to_normal_landmark fat_fluid_calcific_or_thrombotic_component actual_enhancement_or_communication_source affected_structure_or_compartment uncovered_or_unresolved_extent',[0,1,2,3,4])
    lesion='actual_site_and_number full_source_resolved_extent every_attachment_stalk_or_base local_normal_tissue_and_invasive_interfaces each_solid_fluid_fat_blood_fibrous_or_calcific_component orthogonal_dimensions_and_source_axes surface_contour_and_margins actual_temporal_mobility_or_prolapse_source actual_perfusion_enhancement_or_uptake_source each_affected_valve_vessel_wall_or_compartment clinical_operative_or_pathology_correspondence uncertainty_and_uncovered_extent'
    for key,name in [('thrombus','Each actual thrombus component'),('vegetation','Each actual vegetation/suspected endocarditic component'),('myxoma','Each actual suspected/confirmed myxoma'),('lipoma','Each actual suspected/confirmed lipoma'),('rhabdomyoma','Each actual suspected/confirmed rhabdomyoma'),('fibroma','Each actual suspected/confirmed fibroma'),('fibroelastoma','Each actual suspected/confirmed fibroelastoma'),('sarcoma','Each actual suspected/confirmed sarcoma'),('lymphoma','Each actual suspected/confirmed lymphoma'),('metastasis','Every actual metastatic component'),('other_lesion','Every other actual histological/inflammatory/neoplastic lesion')]:add(key,name,lesion,[0,1,2,3,4],purpose='pathology_example')
    add('mixed_components','Each lesion-associated thrombus/necrosis/haemorrhage component','actual_component_identity complete_source_resolved_boundary lesion_to_component_interface site_and_extent relative_attenuation_or_signal actual_enhancement_or_nonenhancement separate_uncertainty_and_histological_source unresolved_small_or_uncovered_extent',[0,1,2,3,4],purpose='pathology_example')
    add('attachment','Each actual attachment/stalk/base footprint','source_resolved_origin every_attached_tissue_or_device footprint_surface_and_axes stalk_length_width_and_axis_if_resolved base_vs_mobile_component relation_to_normal_ridge_or_septal_landmark actual_temporal_interface source_sampling_and_unresolved_attachment',[0,1,4])
    add('measurement','Each actual lesion/component measurement','source_patient_series_and_date cardiac_phase actual_orthogonal_planes_and_axes dimensions_with_units native_calibration_or_pixel_scale attachment_vs_mobile_component contour_and_partial_volume_limit comparison_method_and_uncertainty',[1])
    add('tissue','Each actual tissue-characterisation region','source_region_and_component ct_attenuation_and_roi_or_iodine_source ct_calcification_and_acquisition mri_t1_t2_and_sequence mri_fat_suppression_or_chemical_shift blood_fluid_fibrous_components_if_resolved actual_reference_tissue field_strength_sampling_and_artefact qualitative_vs_quantitative_limits unavailable_or_conflicting_characterisation',[2])
    add('enhancement','Each actual contrast/perfusion/enhancement region','precontrast_or_baseline_source each_obtained_phase_or_sequence contrast_agent_and_timing reference_blood_pool_or_myocardium local_perfusion_early_delayed_lge_pattern actual_inversion_time_if_used image_quality_and_registration mixed_lesion_thrombus_or_necrosis organised_thrombus_enhancement_uncertainty unavailable_or_unresolved_source',[3])
    add('mixing_artefact','Every actual mixing/artefact hypothesis','actual_location_and_phase original_opacification_and_acquisition quality_motion_and_partial_volume actual_later_source_if_obtained resolution_persistence_or_uncertainty registered_component_correspondence thrombus_or_other_lesion_alternatives missing_or_uncovered_followup',[0,2,3])
    add('effects','Every actual obstruction/valve/vascular effect','actual_affected_site source_resolved_narrowing_or_contact extent_and_mobility_if_observed inflow_outflow_or_regurgitation_source actual_coronary_venous_or_branch_perfusion_source ventricular_function_source embolic_complication_source clinical_pressure_or_tamponade_evidence imaging_vs_functional_uncertainty',[4])
    add('spread','Each actual invasion/extension/staging site','actual_wall_or_compartment source_resolved_border_vs_contact longitudinal_and_transverse_extent each_direct_vascular_or_lymphatic_route relevant_extracardiac_primary_or_deposit complete_obtained_coverage clinical_pathology_or_staging_source unresolved_or_unexamined_sites',[4])
    add('comparison','Each actual serial/treatment comparison','patient_and_lesion_identity dates_and_interval source_modality_sequence_and_phase identical_landmark_or_plane source_dimensions_and_calibration each_changed_component_or_attachment treatment_or_procedure_context if_available_pathology_source uncertainty_and_unavailable_prior_extent',[0,1,2,3,4])
    add('functional_source','Actual clinical/temporal/diagnostic context','clinical_history_and_prior_diagnosis operative_or_pathology_evidence actual_temporal_cine_echo_source actual_flow_pressure_or_valve_measurement actual_perfusion_or_metabolic_source_if_obtained symptoms_and_urgent_complication_context differential_confidence_vs_histological_claim modality_specific_sampling_and_unavailable_tests',[0,1,2,3,4])
    add('acquisition','Actual imaging/geometry controls','patient_series_and_modality field_strength_or_projection_if_relevant full_coverage_and_uncovered_regions actual_cardio_respiratory_phase temporal_and_spatial_sampling native_voxel_units_and_calibration contrast_timing_and_sequence original_reformatted_planes artefact_and_unresolved_boundary source_patient_case_correspondence',[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':'rad.5.cardiac-masses-devices','title':'CT and MRI cardiac masses',
        'scope_status':'expanded_draft_requires_independent_cardiac_anatomical_and_clinical_review','modality_scope':['CT','MRI','Ultrasound','PET-CT'],
        'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':s} for t,u,s in zip(['Radiology Assistant cardiac masses','Masses/pseudomasses overview','Updated cardiac mass imaging overview'],URLS,['effective_reporting_scope_reviewed','original_XML_relevant_anatomical_mimic_thrombus_and_tumour_passages_reviewed','original_XML_relevant_variant_and_organised_thrombus_extracts_reviewed'])],
        'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Instantiate every actual lesion/site/component/attachment and adjacent structure; diagnostic categories are not substitutes for full spatial anatomy.',
            'Every leaf needs independent modality/state/site-matched image, schematic and model evidence; normal generic heart geometry cannot fill pathology or thin attachments.',
            'Known floor, not exhaustive histological catalogue or complete staging/MRI protocol. Missing tests, temporal sources or coverage remain uncertainty.'],
        'source_scope_issues':['Organised chronic thrombus may rarely enhance peripherally; no absolute nonenhancement rule or one-phase diagnosis is adopted.',
            'Imaging patterns and FDG uptake are not automatic histology/malignancy; source clinical/operative/pathology evidence matters.',
            'Normal ridges/remnants/trabeculations and actual vascular/extracardiac connections need complete tracing.',
            'PMC10818366 is CC BY 4.0 but original figure-specific credits/pixels/panel roles need review before packaging.',
            'PMC9558634 is CC BY-NC-SA 4.0; no figures are commercially reused from that grant.',
            'Generic heart model omits actual lesions/attachments/invasion. Native lesion datasets and independent complete anatomical/clinical validation remain outstanding.'],
        'functional_evidence_requirements':['Mobility, perfusion, obstruction, valve effects, flow and tamponade need actual temporal/functional/clinical sources; still images and geometry alone do not prove them.',
            'Enhancement needs actual timing/sequence quality/reference and mixed-component assessment; signal or one phase is not a universal tissue diagnosis.',
            'Report observed spread and acquisition limits separately from complete clinical staging or management.'],
        'clinical_validation_status':'draft_requires_cardiovascular_radiologist_and_cardio_oncology_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=IDENT]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
