#!/usr/bin/env python3
"""Expand full named endometriosis report anatomy; published examples do not clear thin boundaries."""
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_msk_fidelity import requirements_for
from tools.check_radiology_fidelity import digest
INV='ra.mri-endometriosis';URL='https://link.springer.com/article/10.1007/s00330-025-11611-3'
def build():
 ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];guide=copy.deepcopy(ref['reporting']);groups=[]
 def add(key,name,parts,indices,side='midline',pathology=False,condition=None):
  prefix='endometriosis.'+key
  groups.append({'id':prefix,'name':name,'laterality':side,'tissue_class':'pelvic_reproductive_urinary_bowel_peritoneal_neural_or_extra_pelvic_reporting_structure','modality_scope':['MRI'],'required_parts':[{'id':prefix+'.'+p,'name':p.replace('_',' ')} for p in parts.split()],'report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in indices],'walkthrough_step_indices':indices,'source_urls':[URL,'https://radiologyassistant.nl/abdomen/unsorted/endometriosis-mri-detection'],'requirement_basis':'effective_full_reporting_contract_and_primary_ESUR_compartment_interface_scope','requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'},'condition':condition or 'Instantiate separately for every actual covered/reported side, structure, lesion and interface. A parent organ, source diagram or published local view cannot stand for unresolved fine layers or unacquired extent.'})
 whole='actual_covered_identity_and_course source_origin_endpoints_or_boundaries adjacent_tissue_or_organ_interface source_resolution_unresolved_or_unacquired_extent'
 layer='actual_named_site_and_extent source_inner_and_outer_boundaries thickness_or_explicitly_unresolved_layer adjacent_layer_lumen_or_lesion_interface source_resolution_and_uncertainty'
 lesion='each_actual_lesion_identity_site_and_extent source_signal_or_material_observation source_outer_and_internal_boundaries adjacent_organ_layer_lumen_or_nerve_interface source_measurement_plane_scale_and_uncertainty source_unresolved_or_unacquired_extent'
 for side in ['left','right']:
  for site in ['ovary','residual_ovarian_parenchyma','ovarian_capsule_surface','ovarian_hilum_and_observed_attachment','each_observed_follicle']:
   add(side+'.adnexa.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[0,5],side)
  for site in ['uterine_tube_uterine_segment','tube_isthmus','tube_ampulla','tube_infundibulum_fimbrial_end','tube_lumen_content_and_wall','ovarian_fossa','mesosalpinx']:
   add(side+'.adnexa.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[0,5],side)
  for site in ['each_endometrioma_or_micro_endometrioma','each_tubal_content_or_distension_abnormality','each_suspected_adnexal_solid_component','each_adnexal_adhesion_or_tethering_interface']:
   add(side+'.adnexal_lesion.'+site,side.capitalize()+' '+site.replace('_',' '),lesion,[0,5],side,True)
  for site in ['round_ligament_uterine_origin_and_proximal_third','round_ligament_distal_pelvic_course','round_ligament_deep_inguinal_ring','covered_round_ligament_inguinal_course']:
   add(side+'.ligament.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[1,4,6],side)
  for site in ['proximal_uterosacral_ligament','covered_distal_uterosacral_ligament','uterosacral_torus_interface']:
   add(side+'.ligament.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[2,4],side)
  for site in ['mediolateral_parametrium','posterolateral_parametrium','parametrial_vascular_fat_interface','pararectal_space_mesorectal_fascia_interface','covered_pelvic_sidewall_interface']:
   add(side+'.lateral.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[4],side)
  for site in ['covered_proximal_ureter','pelvic_ureter','parametrial_or_broad_ligament_ureter_course','distal_ureter','ureteric_orifice','covered_renal_collecting_system']:
   add(side+'.urinary.'+site,side.capitalize()+' '+site.replace('_',' '),whole,[1,4],side)
  for site in ['ureter_lumen_wall_interface','ureter_outer_wall_periureteral_interface']:
   add(side+'.urinary_layer.'+site,side.capitalize()+' '+site.replace('_',' '),layer,[4],side)
  for site in ['each_ureteric_or_periureteric_lesion','each_renal_or_ureteric_obstruction','each_round_ligament_lesion','each_uterosacral_lesion','each_parametrial_or_neural_interface_lesion']:
   add(side+'.lesion.'+site,side.capitalize()+' '+site.replace('_',' '),lesion,[1,2,4,6],side,True)
  for site in ['obturator_nerve','covered_lumbosacral_plexus','S2_root_or_branch','S3_root_or_branch','S4_root_or_branch','covered_sciatic_nerve']:
   add(side+'.neural.'+site,side.capitalize()+' actual covered '+site.replace('_',' '),whole,[4],side,condition='Required for actually covered/reported neural sites and suspected interfaces. Preserve each real root/branch and unresolved course; conceptual lines or pelvic parent meshes are not original segmented nerves or functional evidence.')
 for site in ['bladder_anterior_two_thirds_dome','bladder_posterior_third_dome_vesicouterine_level','bladder_base_and_trigone','vesicouterine_space','uterus_covered_body_and_orientation','uterine_cavity_endometrium_interface','uterine_junctional_zone','inner_myometrium','outer_myometrium_serosal_interface','uterine_cervix','torus_uterinus','rectouterine_space_pouch_of_Douglas','pelvic_peritoneal_reflection','posterior_vaginal_wall','posterior_vaginal_fornix','rectovaginal_space','covered_parietal_peritoneum']:
  add('central.'+site,site.replace('_',' ').capitalize(),whole,[1,2,5])
 for site in ['bladder_mucosa_submucosa_interface','bladder_muscular_wall','bladder_outer_surface_adjacent_tissue_interface','vaginal_lumen_wall_interface','vaginal_outer_wall_adjacent_tissue_interface']:
  add('central_layer.'+site,site.replace('_',' ').capitalize(),layer,[1,2])
 for segment in ['low_rectum','middle_rectum','high_rectum','rectosigmoid_junction','covered_sigmoid','covered_ileocaecal_junction','covered_caecum','covered_appendix']:
  add('bowel.'+segment,segment.replace('_',' ').capitalize(),whole,[3,6])
  for tissue in ['mucosa','submucosa','muscularis_propria','serosa_or_covered_outer_surface','lumen_wall_interface']:
   add('bowel_layer.'+segment+'.'+tissue,segment.replace('_',' ')+' '+tissue.replace('_',' '),layer,[3,6])
 add('bowel.anal_verge_reference','Actual anal-verge reference for lesion distance','source_reference_identity_and_evaluability actual_inferior_lesion_margin measured_path_plane_and_scale source_field_of_view_and_uncertainty',[3])
 for site in ['each_bladder_or_vesicouterine_lesion','each_torus_or_pouch_of_Douglas_lesion','each_posterior_vaginal_or_rectovaginal_lesion','each_external_myometrial_infiltration','each_internal_adenomyosis_pattern_or_adenomyoma','each_superficial_peritoneal_focus','each_bowel_nodule','each_adhesional_or_fibrotic_interface']:
  add('central_lesion.'+site,site.replace('_',' ').capitalize(),lesion,[1,2,3,5],pathology=True)
 for site in ['covered_abdominal_wall_skin_subcutaneous_layers','covered_abdominal_wall_fascial_planes','covered_rectus_abdominis','each_actual_abdominal_wall_surgical_scar','umbilical_scar_and_interfaces','covered_inguinal_canal','covered_diaphragm_and_pleural_peritoneal_interfaces']:
  add('extra_pelvic.'+site,site.replace('_',' ').capitalize(),whole,[6])
 for site in ['each_scar_or_abdominal_wall_nodule','each_umbilical_nodule','each_inguinal_nodule','each_diaphragmatic_nodule','each_covered_extra_pelvic_bowel_nodule']:
  add('extra_pelvic_lesion.'+site,site.replace('_',' ').capitalize(),lesion,[6],pathology=True)
 for key,name,parts in [('acquisition','Actual examination and source adequacy','actual_patient_examination_identity symptoms_prior_surgery_and_comparison recorded_preparation_sequences_and_coverage actual_T1_fat_separation_T2_plane_quality acquired_or_unperformed_diffusion_and_contrast kidney_or_extra_pelvic_coverage source_resolution_scale_and_uncertainty'),('case_instantiation','Each actual variant and postoperative/adhesional interface','actual_structure_or_lesion_identity_and_count true_left_right_midline_or_variant_identity every_actual_covered_branch_or_tissue_interface original_source_extent_and_quality unacquired_unresolved_or_uncertain_boundaries'),('measurement','Each actual measurement and reference','lesion_or_structure_identity actual_source_plane_sequence_and_scale units_method_and_reference_site original_source_values_and_uncertainty no_measurement_from_uncalibrated_artwork'),('classification','Each actually adopted classification','system_name_version_and_source each_actual_required_input_or_missing_input source_supported_derivation_if_performed no_automatic_score_from_examples_or_parent_geometry'),('comparison','Each actually obtained serial comparison','examination_dates_and_matching_site comparable_source_method_and_coverage observed_interval_change treatment_or_surgery_context_if_supplied no_borrowed_publication_case_registration')]:add('assessment.'+key,name,parts,list(range(7)))
 return {'investigation_id':INV,'module_id':'rad.5.uterine-mr','title':'MRI endometriosis','scope_status':'expanded_draft_requires_independent_specialist_MRI_and_clinical_review','modality_scope':['MRI'],'sources':[{'title':'ESUR 2025 protocol/lexicon/compartment consensus','url':URL,'reviewed_at':'2026-10-10','review_status':'original_XML_PDF_protocol_table_compartment_and_case_scope_reviewed'},{'title':'Effective assigned MRI endometriosis source','url':'https://radiologyassistant.nl/abdomen/unsorted/endometriosis-mri-detection','review_status':'effective_full_existing_reading_heading_and_reporting_contract_reconciled'}],'source_contract_sha256':digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':groups,'expansion_rules':['Clinical MRI, schematic and 3D requirements remain separate for every fine structure and actual conditional site. A licensed whole figure does not grant anatomical approval.','Compartment boundaries are reporting conventions, not new biological septa. Every actual source interface and unknown extent requires review.','Preserve actual lesion/side/variant/source identity. Do not manufacture missing organs, wall layers, nerve branches, operative relationships, or normality from a parent label.'],'source_scope_issues':['Published Figure3 has an axial-panel letter conflict, and Figure5 contains a corrupted distance-caption token; neither is silently corrected or used as calibrated acquired metadata.','Original MRI cases, clinical photographs, surgical images and conceptual table drawings are distinct source evidence. Different panels/figures are not a registered complete native examination or current-patient diagnosis.','The original table extra-pelvic image cell spans multiple rows; its upper-abdominal graphic is not relabelled as an abdominal-wall scar or bowel lesion.','CVH5 full decoding remains independently unverified; West Bohemia template anatomy/physical calibration/fine layers remain unverified. No held candidate is promoted as clinically faithful 3D.','Negative MRI cannot exclude superficial disease. Missing acquired contrast, neural or diaphragmatic coverage remains explicitly unassessed rather than normal.'],'functional_evidence_requirements':['Diagnostic characterization and bowel/ureteric/neural functional consequences require corresponding actual acquisition and clinical evidence. Static shape alone does not prove function or surgical operability.','Each measurement or adopted classification must use its actual source method/reference/version and complete required inputs; no automatic score or scale is inferred from publication pixels.'],'clinical_validation_status':'draft_requires_specialist_pelvic_MRI_and_gynaecological_surgical_review'}
if __name__=='__main__':
 item=build();p=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(p.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=INV]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];p.write_text(json.dumps(d,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'fine leaves;',len(requirements_for(item))*3,'representation obligations')
