#!/usr/bin/env python3
"""Bind all named myocardial regions, source contours and actual tissue/function evidence."""
import json
from pathlib import Path
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.mri-cardiomyopathy'
URLS=['https://radiologyassistant.nl/cardiovascular/anatomy/cardiac-anatomy','https://radiologyassistant.nl/cardiovascular/cardiomyopathy/ischemic-and-non-ischemic-cardiomyopathy','https://pmc.ncbi.nlm.nih.gov/articles/PMC7066763/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11084160/']
SEGMENTS=['basal_anterior','basal_anteroseptal','basal_inferoseptal','basal_inferior','basal_inferolateral','basal_anterolateral','mid_anterior','mid_anteroseptal','mid_inferoseptal','mid_inferior','mid_inferolateral','mid_anterolateral','apical_anterior','apical_septal','apical_inferior','apical_lateral','apical_cap']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];guide=ref['reporting'];structures=[]
    def add(key,name,children,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'cardiomyopathy.'+key,'name':name,'tissue_class':'cardiomyopathy_myocardial_structure_or_source_control',
            'required_parts':[{'id':'cardiomyopathy.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in children.split()],
            'laterality':side,'modality_scope':['MRI'],
            'condition':'Instantiate every actual ventricular region, layer, phase, contour, tissue abnormality, reference/timepoint and patient variant. Preserve original series/sequence, native calibration, coverage and uncertainty. Motion/function/maps require obtained temporal/quantitative sources, not stills or a generic heart. External modalities/clinical data are separate context and do not become acquired MRI.',
            'requirement_basis':'effective_cardiomyopathy_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],
            'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    layer='actual_longitudinal_extent circumferential_landmarks source_endocardial_surface compact_myocardial_boundary source_midwall_region epicardial_surface trabecular_or_papillary_interface phase_defined_thickness actual_temporal_thickening_source each_lge_or_oedematous_region actual_mapping_roi_if_measured coronary_variant_or_noncoronary_relation unresolved_layer_or_uncovered_extent'
    for n,key in enumerate(SEGMENTS,1):add('lv_segment_'+str(n),'Actual LV segment '+str(n)+' '+key.replace('_',' '),layer,[0,1,2,3],'left')
    for side in ['left','right']:
        add(side+'_ventricular_pool',side.capitalize()+' ventricular source blood pool','complete_obtained_base_to_apex_extent each_actual_phase_endocardial_contour ed_es_selection_and_source basal_valve_plane_relation apical_boundary papillary_trabecular_inclusion_convention outflow_inclusion_and_variant each_slice_spacing_or_gap original_geometry_and_calibration uncovered_or_unresolved_extent',[0,1],side)
        add(side+'_ventricular_wall',side.capitalize()+' complete covered ventricular wall','source_endocardial_boundary compact_wall_and_midwall source_epicardial_boundary each_actual_region maximal_thickness_site_and_phase papillary_trabecular_relation actual_mass_contour_source every_disease_or_artifact_region unresolved_or_uncovered_thin_wall',[0,1,2,3],side)
        add(side+'_papillary_chordal',side.capitalize()+' actual papillary/chordal apparatus','each_actual_group origin_body_tip_source each_resolved_chordal_course leaflet_and_wall_attachment contour_inclusion_convention temporal_source_and_limits unresolved_thin_parts',[0,1,4],side)
    for key,name in [('rv_inflow','RV inflow'),('rv_body','RV body/free wall'),('rv_outflow','RV outflow'),('rv_septal_interface','RV septal/insertion interfaces')]:add(key,name,'actual_region_and_extent source_resolved_blood_pool_wall_border compact_vs_trabecular_interface endocardial_midwall_epicardial_regions actual_temporal_motion_source actual_disease_or_artifact_region source_sampling_and_phase unresolved_or_uncovered_extent',[0,1,2,3],'right')
    for key,name,side in [('left_atrium','LA','left'),('right_atrium','RA','right'),('left_appendage','LAA','left'),('right_appendage','RAA','right')]:add(key,name,'source_resolved_wall_and_pool actual_extent_and_dimensions_if_measured each_venous_valve_or_septal_interface actual_thrombus_or_other_region measurement_phase_and_convention actual_temporal_function_source uncovered_or_unresolved_extent',[1,4],side)
    for valve in ['aortic','mitral','tricuspid','pulmonary']:add(valve+'_valve',valve.capitalize()+' actual native/prosthetic valve','source_resolved_leaflet_disc_or_repair actual_annulus_plane subvalvar_and_chamber_interface actual_temporal_motion_source flow_or_regurgitation_source_if_measured obstruction_or_other_effect_source unresolved_thin_or_uncovered_extent',[0,1,4])
    for key,name in [('interatrial_septum','Interatrial septum'),('interventricular_septum','Interventricular septum'),('lv_outflow','LV outflow/aortomitral interface')]:add(key,name,'actual_extent_and_morphology source_boundaries each_adjacent_chamber_or_valve_interface tissue_or_disease_region actual_temporal_relation variant_or_repair_if_present unresolved_or_uncovered_extent',[0,1,2,3,4])
    for key,name in [('root_aorta','Covered aortic root/aorta'),('pulmonary_arteries','Covered pulmonary trunk/branches'),('pulmonary_veins','Every covered pulmonary vein/ostium'),('caval_veins','Covered caval veins/atrial junctions'),('coronaries','Each relevant coronary territory/artery/graft'),('coronary_venous','Covered coronary sinus/venous interfaces')]:add(key,name,'actual_origin_or_interface complete_covered_course native_lumen_wall_relation each_relevant_branch_or_connection myocardial_region_relation actual_flow_or_patency_source uncovered_or_unresolved_extent',[0,1,3,4])
    for key,name in [('pericardium','Actual pericardial layers/compartments'),('epicardial_fat','Covered epicardial fat'),('extracardiac','Every relevant covered extracardiac finding')]:add(key,name,'actual_site_and_boundary full_covered_extent each_abnormal_component relation_to_myocardium_vessel_or_organ actual_tissue_or_enhancement_source actual_function_or_clinical_effect_source unresolved_or_uncovered_extent',[1,2,3,4])
    disease='actual_site_and_all_components full_source_resolved_extent layer_or_regional_distribution each_native_tissue_interface actual_phase_defined_morphology actual_temporal_motion_or_function_source actual_oedema_mapping_or_lge_source mixed_or_overlapping_disease_regions clinical_histological_or_genetic_correspondence_if_available unresolved_or_uncovered_extent'
    for key,name in [('ischaemic_injury','Each actual ischaemic/infarct region'),('dilated_pattern','Actual dilated phenotype'),('hypertrophic_pattern','Actual hypertrophic phenotype'),('restrictive_infiltrative','Actual restrictive/infiltrative phenotype'),('amyloid_pattern','Actual suspected/confirmed amyloid pattern'),('arrhythmogenic_pattern','Actual suspected/confirmed arrhythmogenic phenotype'),('myocarditis_pattern','Actual suspected/confirmed inflammatory injury'),('stress_pattern','Actual stress-cardiomyopathy phenotype'),('iron_or_other_storage','Actual iron/storage/metabolic injury if assessed'),('other_disease','Every other actual myocardial/repair/disease variant'),('thrombus','Each actual suspected/confirmed thrombus'),('mvo_haemorrhage','Every actual no-reflow/haemorrhagic component')]:add(key,name,disease,[0,1,2,3,4],purpose='pathology_example')
    add('volume_function','Actual biventricular quantitative function','complete_source_cine_identity each_contour_and_phase valve_plane_and_basal_apical_convention papillary_trabecular_and_outflow_convention ed_es_sv_ef_method units_and_bsa_index_source actual_reference_population_and_method arrhythmia_or_sampling_bias interreader_or_processing_uncertainty unavailable_or_unresolved_result',[0])
    add('segment_model','Actual region/segment assignment','named_model_and_version basal_mid_apical_landmarks rv_insertion_or_other_reference_axis coronary_anatomy_variants each_lv_and_rv_region layer_boundaries source_orientation_registration_and_phase apical_cap_and_motion_assessment_limits uncovered_or_unassigned_extent',[0,1,2,3])
    add('mapping','Each actual native/postcontrast T1/T2/T2-star map/ROI','original_source_and_sequence field_strength_and_acquisition_scheme raw_source_and_map_quality roi_location_boundary_and_size motion_registration_and_partial_volume actual_values_and_units local_or_method_comparable_reference artefact_or_confounder_context uncertainty_and_unavailable_quantification',[2])
    add('ecv','Actual ECV calculation/data if acquired','named_actual_method matched_native_postcontrast_myocardial_roi matched_native_postcontrast_blood_roi contrast_agent_dose_and_timing haematocrit_source_value_and_date_if_used named_synthetic_or_other_alternative_if_used quality_and_registration reference_method_and_units unavailable_or_uncertain_inputs',[2])
    add('lge','Every actual enhancement region and measurement','source_sequence_and_timing nulling_psir_or_other_method actual_region_layer_and_extent orthogonal_or_other_source_verification reference_myocardium_and_blood_pool actual_visual_or_quantitative_method source_threshold_or_contour_if_quantified mvo_or_other_mixed_component source_artefact_and_unavailable_extent',[3])
    add('effects','Actual haemodynamic/clinical effect source','actual_ventricular_or_valve_function_source flow_pressure_or_perfusion_measurement_if_available regional_motion_or_strain_source_if_measured clinical_tamponade_or_obstruction_context tissue_pattern_vs_aetiological_claim clinical_genetic_histology_or_other_diagnostic_evidence unknown_or_unperformed_tests',[0,1,2,3,4])
    add('comparison','Each actual serial examination/reference comparison','patient_and_examination_identity dates_and_interval same_region_phase_and_sequence contour_and_processing_conventions native_calibration_and_coverage each_actual_changed_region_or_metric treatment_or_clinical_context_if_available uncertainty_and_unavailable_prior_extent',[0,1,2,3,4])
    add('acquisition','Actual acquisition and source controls','patient_series_and_modality cardiac_respiratory_phase_and_gating temporal_resolution_and_arrhythmia spatial_sampling_thickness_gap_and_coverage native_voxel_units_and_coordinates sequence_field_strength_and_processing contrast_if_used_and_timing source_reformatted_planes metal_motion_and_other_artefacts every_uncovered_or_unresolved_region',[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':'rad.5.cardiac-mri','title':'MRI cardiac cardiomyopathy','scope_status':'expanded_draft_requires_independent_cmr_anatomical_and_clinical_review','modality_scope':['MRI'],
        'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':s} for t,u,s in zip(['RA cardiac anatomy','RA cardiomyopathy','SCMR 2020 interpretation/post-processing','Mapping in cardiomyopathy review'],URLS,['effective_scope_reviewed','effective_reporting_scope_reviewed','original_XML_relevant_function_contour_LGE_mapping_ECV_passages_reviewed','original_XML_relevant_tissue_mapping_extracts_reviewed'])],
        'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Instantiate every actual region/layer/phase/contour and disease component; labels/segments are a known floor, not full source geometry.',
            'Each leaf requires independently reviewed acquired-MRI/site/state-specific image/schematic/model evidence. Generic normal heart or source blood pool cannot fill compact wall, scar, map or pathological geometry.',
            'Temporal/quantitative/source-quality evidence is required for reported function/maps; absent acquisitions or references are uncertainty.'],
        'source_scope_issues':['Coronary-type and other LGE patterns support a differential; global subendocardial/mixed patterns and absent LGE do not uniquely classify or exclude all cardiomyopathy.',
            'LV segment labels are not complete tissue boundaries or automatic RV segmentation; apical and unresolved motion assessment needs its actual source/model.',
            'Contouring, basal/apical/papillary/trabecular conventions, phase and indexing/reference populations must remain comparable.',
            'Tissue mapping and ECV need raw-source quality, actual acquisition/ROI/method-comparable reference and documented haematocrit or named alternative inputs.',
            'Both primary article grants are CC BY 4.0; thirteen complete original figures are inspected/preserved with contour, static/map/graph and caption-unit limits. SCMR adapted/modified Figures 5/10 are held pending upstream rights; complete current guidelines and independent anatomical/clinical review remain outstanding.',
            'No native myocardial cine/scar/map models or validated quantitative function are supplied by the generic heart companion.'],
        'functional_evidence_requirements':['EF/volumes/regional motion and flow require complete obtained temporal/contour sources with declared conventions, not a still/picture/model.',
            'Mapping/ECV/LGE quantification requires valid source quality, method/calibration/reference and uncertainty; no universal cutoff or colour map diagnosis.',
            'Aetiology, genetic/histological diagnosis and clinical severity require corresponding clinical source rather than exclusive pattern rules.'],
        'clinical_validation_status':'draft_requires_cardiovascular_mri_radiologist_and_cardiology_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=IDENT]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
