#!/usr/bin/env python3
"""Require full acquired primary/interface/nodal anatomy without MRI-as-histology or preset staging."""
import copy,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];INV='ra.head-neck-malignancy'
URLS=['https://radiologyassistant.nl/head-neck/neck-masses/head-neck-tumors','https://pmc.ncbi.nlm.nih.gov/articles/PMC6251248/','https://pmc.ncbi.nlm.nih.gov/articles/PMC6251244/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11719534/','https://pmc.ncbi.nlm.nih.gov/articles/PMC6420596/']
def build():
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];guide=copy.deepcopy(ref['reporting'])
    details=['Inventory every actual obtained primary/other lesion and source epicentre/subsite/component, with identity, dimensions, technique and unresolved extent.',
        'Trace each actual lesion-to-mucosa/fat/muscle/gland/bone/cartilage interface, distinguishing source suspicion from supplied tissue diagnosis or microscopic invasion.',
        'Map every source-supported neural/foraminal/skull-base connection and actual division/branch, with acquired coverage and uncertainty.',
        'Trace each actual vessel/airway/visceral contact and source morphology; vessel invasion, patency, clinical airway or swallowing function require corresponding evidence.',
        'Inventory every actual acquired node/group/component and other covered lesion; source morphology, imaging ENE and supplied pathology/assays/stage remain separate domains.']
    looks=['Review actual acquired MRI/CT coverage and every mucosal, glandular, deep-space or other lesion, including solid/fluid/necrotic-appearing/secretory components. Name the source identity/subsite, comparative planes and calibrated dimensions; unknown extent remains unassessed.',
        'Trace actual local interfaces on MRI and appropriate source bone CT if obtained. Use T1/T2, paired DWI/ADC and pre/postcontrast sources with limits. Secretions, blood, cystic or necrotic material and tumour have variable appearances; do not label each from a single signal rule.',
        'Trace every obtained cranial/peripheral nerve and actual foraminal/ganglion/CSF/dural interface relevant to the source lesion, including facial/trigeminal and other acquired routes. Record thickening/enhancement/fat-space changes and uncertainty; missing distal coverage is not absent disease.',
        'Review actual carotid/jugular/other vessel source course and each contact/encasement/deformation, with phase/calibration/flow limitations. Inspect each obtained pharyngeal/laryngeal/tracheal/esophageal interface and actual lumen/morphology; static narrowing is not a functional measurement.',
        'Review all actually acquired named nodal regions and every relevant node/component, source local axes and cortical/hilar/capsular/perinodal findings. Map every other covered site separately. Supplied clinical primary, biopsy/pathological ENE, HPV/other assays and staging applicability/version are not inferred from geometry.']
    tips=['A generic primary-site icon or selected slice does not establish every component or lesion extent. Retained secretions and tumour are not separated reliably by a universal T2/enhancement rule.',
        'Destruction can have a nonmalignant differential; remodelling is not proof of benignity. Contact or absent visible fat plane alone is not microscopic invasion or unique tissue identity.',
        'Perineural imaging suspicion is distinct from supplied microscopic invasion. Fat-space loss/enhancement has a differential, and unacquired nerve branches remain unassessed.',
        'Contact or a measured encasement arc is not a stand-alone diagnosis of vascular invasion, thrombosis, resectability or airway function.',
        'Small/cystic nodes do not exclude metastasis or establish a congenital benign cyst. Histology, assays, primary-specific stage and clinical actions require their actual applicable sources.']
    guide.update(reviewed_at='2026-10-07',protocol=['Record actual MRI/CT coverage, planes/sampling, motion/artifact, bone/soft-tissue reconstructions, paired DWI/ADC and pre/postcontrast sources if acquired. Ultrasound, PET, functional studies and pathology remain separately identified sources.',
        'Record actual symptom/site, supplied tissue/primary/assays and dates, treatment and comparison. A source suspicion framework is not a universal tumour stage or unique pathology classifier.'],checklist=[{'label':label,'detail':text} for label,text in zip(['Primary and components','Local tissue interfaces','Neural and skull-base routes','Vascular airway and visceral interfaces','Nodes and other acquired sites'],details)],pitfalls=tips,sources=[{'title':title,'url':url} for title,url in zip(['RA head/neck tumour reporting','Salivary anatomy/source review (restricted graphics)','Salivary tumour source review (restricted graphics)','Source high-field parotid MRI study','Source cranial nerve imaging overview'],URLS)])
    bodies=['Each actual lesion identity/subsite/side/epicentre and component [ ]; actual source orthogonal dimensions/planes/calibration [ ]; other obtained lesions, comparison and unresolved extent [ ].',
        'Every actual mucosal/fat/muscle/gland/bone/cartilage interface [ ]; acquired MRI or bone CT appearances and confidence [ ]; contact versus supported extension and differential [ ]; unassessed/microscopic extent and supplied tissue evidence [ ].',
        'Every actual obtained neural route/branch/foramen/ganglion/dural connection [ ]; source signal/enhancement/size/fat-space findings and uncertainty [ ]; uncovered course and supplied pathological context [ ].',
        'Each source vessel/contact/encasement/deformation and acquired sequence/phase [ ]; source airway/visceral wall/lumen interface [ ]; actual clinical/flow/swallowing evidence and uncertainty [ ]; unexamined extent [ ].',
        'Every acquired named nodal region/node/component/side/source dimensions [ ]; cortical/hilar/capsular/perinodal and imaging ENE findings [ ]; other obtained sites [ ]; supplied biopsy/pathological ENE/assay/primary-specific staging version and unresolved components [ ].']
    for section,body in zip(guide['template_sections'],bodies):section['body']=body
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data.setdefault(INV,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/head-neck.json';text=path.read_text();start=text.index('{',text.index('"'+INV+'"'));node,end=json.JSONDecoder().raw_decode(text,start);node['model']={'family':'neck','reporting_aim':'Partial head/neck orientation only. This schematic does not represent every native primary/subsite, gland/duct/internal component, nerve/vessel/wall, nodal cortex/hilum/capsule or tumour interface. Source extent, tissue/assays/staging applicability and function remain separate.'}
    for i,step in enumerate(node['steps']):step.update(normal={},detail=details[i],look=looks[i],tip=tips[i],findings=['Actual acquired '+step['label'].lower()+' findings [ ]; source/side/subsite/interface [ ]; confidence and unavailable evidence [ ].'])
    path.write_text(text[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+text[end:])
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];structures=[]
    def add(key,parts,steps,side='not_applicable',pathology=False):
        ident='head_neck_tumour.'+side+'_'+key;structures.append({'id':ident,'name':side.replace('_',' ').capitalize()+' '+key.replace('_',' '),'tissue_class':'head_neck_primary_tissue_route_or_actual_disease_interface','required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['MRI','CT'],'condition':'Independently instantiate every actual source lesion/subsite/component, gland/duct, neural/vascular route, node and adjacent interface, variant or repair. Modality permission does not supply unacquired or unresolved microscopic/tiny anatomy, and one source example is not the current patient or every reported lesion.','requirement_basis':'effective_head_neck_tumour_source_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'}})
    tissue='every_actual_component_and_obtained_extent each_source_resolved_boundary_and_internal_content mucosal_fat_gland_muscle_bone_or_cartilage_interface every_actual_variant_lesion_or_repair_connection source_acquisition_signal_phase_and_evaluability unresolved_microscopic_or_uncovered_extent'
    gland='every_actual_gland_component_and_obtained_extent each_source_resolved_internal_tissue_and_boundary each_actual_main_tributary_or_variant_duct_and_orifice every_adjacent_neural_vascular_muscle_or_space_interface every_actual_lesion_content_and_source_relation unresolved_microscopic_functional_or_uncovered_extent'
    route='actual_origin_and_full_obtained_course every_source_resolved_branch_wall_or_boundary each_actual_lesion_contact_displacement_or_extension_interface every_target_tissue_or_skull_base_connection source_acquisition_calibration_and_comparison_limits unresolved_microscopic_functional_or_uncovered_extent'
    node='every_actual_node_identity_and_obtained_extent source_resolved_cortex_hilum_margin_and_capsular_interface every_resolved_solid_fluid_necrotic_appearing_calcific_or_other_component each_perinodal_node_muscle_gland_skin_or_vessel_interface actual_named_map_source_axes_and_comparison unresolved_microscopic_or_uncovered_extent'
    for side in ['left','right']:
        for key in ['parotid_superficial_deep_accessory_gland_and_duct','submandibular_gland_deep_extension_and_duct','sublingual_gland_and_ducts','thyroid_lobe_and_encountered_ectopic_tissue','each_encountered_minor_salivary_gland_site']:add(key,gland,[0,1,2,3],side)
        for key in ['oral_tongue_and_floor_of_mouth','buccal_labial_gingival_and_retromolar_mucosa','palatine_tonsil_tongue_base_and_lateral_pharyngeal_wall','nasopharyngeal_tubal_and_retropharyngeal_interfaces','nasal_and_sinonasal_mucosal_or_bone_interfaces','hypopharyngeal_piriform_and_laryngeal_interfaces','encountered_skin_subcutaneous_and_ear_primary','masticator_and_deep_neck_space_contents','mandible_maxilla_dental_and_marrow_interfaces','skull_base_temporal_and_orbital_interfaces','strap_muscle_sternocleidomastoid_and_pterygoid_interfaces','obtained_thoracic_inlet_or_mediastinal_interfaces']:add(key,tissue,[0,1,2,3,4],side)
        for key in ['facial_nerve_intraparotid_branches_and_skull_base_route','trigeminal_V1_V2_V3_and_actual_peripheral_branches','covered_IX_X_XI_XII_sympathetic_or_other_neural_routes','each_actual_neural_ganglion_foramen_or_dural_connection','common_internal_external_carotid_and_other_arterial_routes','internal_external_jugular_and_other_venous_routes','every_actual_nerve_to_primary_or_lesion_interface','each_actual_vessel_wall_lumen_to_lesion_interface']:add(key,route,[1,2,3],side)
        for key in ['actual_Ib_nodes','actual_IIa_IIb_nodes','actual_III_nodes','actual_IV_nodes','actual_V_nodes','actual_VI_nodes','covered_VII_and_other_map_dependent_nodes','retropharyngeal_parotid_facial_and_other_unassigned_nodes']:add(key,node,[0,1,4],side)
        for key in ['each_primary_and_nonindex_lesion_component','each_actual_gland_duct_content_or_obstruction_interface','each_actual_mucosal_gland_muscle_bone_or_cartilage_extension','each_actual_perineural_vascular_or_airway_connection','each_actual_nodal_perinodal_or_other_site_lesion','each_actual_treated_or_repaired_tissue_interface']:add(key,tissue,[0,1,2,3,4],side,True)
    for key in ['hard_soft_palate_uvula_and_midline_tongue_interfaces','posterior_pharyngeal_wall_and_cervical_esophagus','laryngeal_supraglottic_glottic_subglottic_and_cartilage_components','tracheal_wall_lumen_and_source_air_interface','thyroid_isthmus_and_encountered_midline_variants','hyoid_floor_of_mouth_and_midline_neck_interfaces','midline_Ia_nodes_and_other_actual_named_groups','every_actual_midline_crossing_or_unassigned_primary','each_actual_lesion_to_fascial_or_compartment_connection','covered_vertebral_spinal_canal_or_intracranial_extension']:add(key,tissue,[0,1,2,3,4])
    item={'investigation_id':INV,'module_id':ref['investigation']['module_id'],'title':'Every acquired primary salivary mucosal neural vascular and nodal tumour interface','scope_status':'expanded_draft_requires_independent_head_neck_tumour_anatomical_review','modality_scope':['MRI','CT'],'sources':[{'title':s['title'],'url':s['url'],'reviewed_at':'2026-10-07','review_status':'source_reporting_context_no_graphics_reused'} for s in guide['sources']],'source_contract_sha256':digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Every actual primary/subsite/lesion/node/branch/interface and variant needs separate source instantiation; the listed groups are a known floor.','Major/minor glands, ducts and internal lesion contents are not fulfilled by a parent salivary outline or generic tumour model.','MRI, CT bone/calcium, ultrasound/PET, pathology/assays and functional evidence remain separate; source modality permission is not acquired anatomy or diagnostic certainty.'],
        'source_scope_issues':['Current partial neck orientation and selected figures do not establish all source microscopic wall/nerve/gland/node or invasive tissue interfaces.','Restricted salivary review graphics are not commercial evidence; paper classifiers or source outcomes are not independently validated current-patient histology.'],
        'functional_evidence_requirements':['Actual histology/cytology, pathological ENE, molecular assays, primary/treatment context and formal site-specific staging version are supplied clinical evidence, not fabricated model tissues.','Airway/swallowing/vocal or neural function, salivary secretion/duct patency, vessel flow and clinical resectability need actual appropriate acquisitions/clinical context, not a static surface.', 'Source signal, diffusion, enhancement, bone destruction/remodelling or contact patterns have a differential; no universal malignant/benign tissue rule is inferred.'], 'clinical_validation_status':'draft_requires_head_neck_radiologist_and_relevant_oncologic_anatomical_review'}
    path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=INV]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');n=len(requirements_for(item));print(len(structures),'groups;',n,'parts;',n*3,'representation obligations')
if __name__=='__main__':build()
