#!/usr/bin/env python3
"""Draft all six breast reporting inventories; never approve media or change on import."""
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
DATE='2026-10-08'
IDS=('ra.mammography','ra.ultrasound-breast','ra.mri-breast','ra.breast-cancer-staging','ra.breast-implants','ra.male-breast')
ACR='https://www.acr.org/Clinical-Resources/Publications-and-Research/ACR-Bulletin/2026/definitive-guide-to-breast-imaging'
ACR_US='https://accreditationsupport.acr.org/support/solutions/articles/11000067043-reporting-breast-ultrasound'
NCI='https://www.cancer.gov/types/breast/hp/breast-treatment-pdq'
FDA='https://www.fda.gov/medical-devices/breast-implants/questions-and-answers-about-breast-implant-associated-anaplastic-large-cell-lymphoma-bia-alcl'
FDA_SCC='https://www.fda.gov/medical-devices/safety-communications/update-reports-squamous-cell-carcinoma-scc-capsule-around-breast-implants-fda-safety-communication'
ANATOMY='https://pmc.ncbi.nlm.nih.gov/articles/PMC8998991/'
CONFIG={
 'ra.mammography':{'modalities':['Radiography'],'protocol':'Record screening/diagnostic purpose, side, actual digital mammography, tomosynthesis, synthetic or contrast-enhanced acquisitions and views. Identify compression, positioning, obtained tissue, motion and obscured extent; density and enhancement are different observations.','looks':['Map actual bilateral composition and obtained skin-to-chest-wall tissue, including nipple, retroareolar ducts and axillary tail. Preserve view and depth; a compressed projection is not native3D geometry.','Locate each actual mass and all internal, marginal and adjacent components using acquired projections or tomosynthesis; document site, dimensions and evidence for cross-view correspondence.','Trace each acquired asymmetry and distortion, its centre, radiating tissue and adjacent interfaces; compare dated studies and actual additional views without treating unacquired workup as negative.','Map every actual calcification group, individual resolved morphology/distribution, span, skin/duct/lesion relation and associated nipple, skin or node finding. A selected projection does not resolve every microscopic boundary.','Reconcile each imaging and clinical site, prior intervention and obtained other modality. Record unresolved discordance and assessment rationale under the applicable current framework; source morphology is not current histology.']},
 'ra.ultrasound-breast':{'modalities':['Ultrasound'],'protocol':'State targeted or survey scope, clinical site, side, probe and actual scan planes, settings and coverage. Identify radial/antiradial orientation, pressure, artifacts and obtained Doppler or other acquisitions; a targeted negative examination is not whole-breast clearance.','looks':['Map each actual scanned skin, fat, glandular, ductal, retroareolar and chest-wall interface, with side, clock/quadrant, depth and measured nipple distance where applicable.','Trace each mass or non-mass finding separately, including shape, orientation, every margin, duct extension and surrounding rind or tissue distortion. Preserve orthogonal planes and source measurement boundaries.','Describe actual internal solid/fluid/debris/calcific components, echo texture and posterior features with settings and artifact. An echogenic focus is not automatically confirmed calcification or tissue identity.','Review supplied vascularity, skin, duct, edema and adjacent tissue changes. Recorded Doppler depends on its settings and motion; a static colour panel is not calibrated flow or proof of absent vascularity.','Map each acquired intramammary and regional node with cortex, hilum, capsule and vessel interfaces. Correlate actual clinical/mammographic/MRI findings and sampling, keeping unscanned nodes and discordance explicit.']},
 'ra.mri-breast':{'modalities':['MRI'],'protocol':'Document indication, side, obtained breast/chest-wall/nodal coverage, coil, source spatial sampling, sequences and fat suppression. Record actual contrast dose/route, baseline and acquired postcontrast times, motion/subtraction limitations and comparison; acquisition pitch does not prove fine-tissue resolution.','looks':['Map actual fibroglandular tissue and background enhancement separately, with native source extent and sequence quality. Include skin, nipple, ductal, fat, fascial and chest-wall interfaces only to the extent acquired.','Localise each source finding in its native planes, with side, site/depth, nipple, skin and chest-wall relationships. Projection/MIP and other modalities do not establish registered3D correspondence without evidence.','Trace every actual mass and non-mass enhancing component, margin, distribution, ductal and adjacent interface; keep acquired total span distinct from separately proven invasive tumour size.','Review original T1/T2, diffusion/ADC and dynamic acquisitions where supplied. Preserve ROI, actual times, source series and subtraction/motion context; enhancement kinetics or ADC alone are not histology or universal malignancy classifiers.','Reconcile every finding, overall span, additional breast/nodal findings, actual tissue results and prior therapy. Document assessment framework/version and unresolved correlations; a negative or nonenhancing study does not prove pathological eradication.']},
 'ra.breast-cancer-staging':{'modalities':['Radiography','Ultrasound','MRI','CT','PET-CT'],'protocol':'Identify the proven index lesion, dated tissue diagnosis and actual imaging modalities/extent. State clinical versus pathological evidence, applicable staging framework/edition, pretreatment or post-treatment setting, dates and measured comparators. No local examination supplies unacquired systemic staging.','looks':['Map each index tumour component, site, margins and actual invasive-size evidence; separate imaging span from supplied biopsy/resection histology and biomarkers.','Inventory each additional ipsilateral/contralateral mass, non-mass component and calcific/ductal extension with actual intervening tissue and span. Do not equate all enhancement with invasive tumour.','Describe separately acquired nipple, skin, fascia, pectoral and deeper chest-wall interfaces. Contact, lost fat plane or isolated pectoral involvement is not alone complete evidence of chest-wall stage or invasion.','Map actual nodes by side and basin, with relation to pectoralis minor, cortex/hilum/capsule, vessels and treatment markers. Imaging suspicion and clinical, sampled, pathological or post-treatment nodal evidence remain distinct.','Record supplied clinical evidence and obtained imaging/pathology for distant disease, plus actual treatment comparisons, residual targets, clips and complications. No whole-body imaging is automatically required by this draft. Preserve clinical/pathological/post-treatment evidence and staging limits; no automatic M0, response or therapy eligibility is assigned.']},
 'ra.breast-implants':{'modalities':['Ultrasound','MRI','Radiography','CT'],'protocol':'Record side, supplied device identity, fill/shell type, surgery/reconstruction dates and actual prepectoral, retropectoral or dual-plane pocket. Distinguish integrity sequences from a contrast-enhanced breast examination and document obtained capsule, breast, chest-wall and nodal extent.','looks':['Map each actual implant/expander, fill, shell, valve/port where present, pocket and muscle/fascial relationship. Preserve reconstruction and actual device-specific source evidence.','Trace source shell, folds, contour, external fibrous capsule and their interface separately. A radial fold is not automatically shell failure; separate shell rupture from capsular or pocket findings.','Locate every observed internal line, displaced shell fragment and fill/material component in source planes and sequences. An isolated sign is not full proof of every rupture boundary or current device identity.','Map each supplied extracapsular material route, peri-implant fluid, capsular thickening/mass and surrounding interface. Delayed fluid or a capsular mass requires its actual clinical/tissue workup; rupture, BIA-ALCL and SCC are different source questions.','Review each acquired breast, chest-wall and node compartment, including material within nodes and postoperative change. Integrity imaging does not establish a complete malignancy assessment or tumour histology.']},
 'ra.male-breast':{'modalities':['Radiography','Ultrasound','MRI'],'protocol':'Record actual symptoms, side, source age/developmental and hormonal context, prior therapy/surgery and obtained modalities/extent. Assess the supplied tissue rather than imposing a female atlas, fat-only normal template or categorical exclusion of a tumour type.','looks':['Map each symptomatic source site and obtained bilateral tissues, with actual skin, nipple, retroareolar gland/fat and chest-wall relation. Clinical and imaging correspondence must be identified.','Describe source retroareolar ductal/stromal and fatty components, distribution and symmetry in the actual hormonal/treatment context; an appearance label does not provide an independent endocrine cause.','Characterise each separate focal mass/non-mass component, margin, internal tissue and adjacent route. Retain eccentric and coexisting lesions rather than absorbing every finding into a glandular pattern.','Trace source nipple, areolar/skin layers, duct orifices, actual discharge-related route and surface lesions, documenting retraction or inflammatory features without inferred histology.','Review acquired nodal basins and every clinical/imaging/sampling correlation. State the applicable assessment rationale, unresolved discordance and coverage limitations; patient sex does not itself certify benignity.']}}
COMMON=[
 'skin_epidermis','dermis_and_cutaneous_adnexal_interfaces','subcutaneous_fat_and_septa','superficial_fascia_anterior_layer','superficial_fascia_posterior_layer','Cooper_ligaments_and_actual_attachments','circummammary_and_inframammary_attachment_interfaces','fibroglandular_parenchyma_and_stroma','each_actual_terminal_duct_lobular_unit_and_acini','duct_luminal_epithelium_and_myoepithelial_interfaces_when_supplied','duct_basement_membrane_and_intralobular_stroma_when_supplied','each_actual_terminal_segmental_and_lactiferous_duct_wall_lumen','nipple_epidermis_smooth_muscle_and_actual_duct_orifices','areolar_glands_and_subareolar_interfaces','retroareolar_ductal_glandular_and_fatty_components','axillary_tail_accessory_tissue_and_each_actual_variant','retromammary_space_and_pectoral_fascia','pectoralis_major_and_actual_treated_attachments','pectoralis_minor_and_nodal_level_boundaries','serratus_anterior_and_lateral_chest_wall','covered_ribs_cartilage_intercostal_tissues_and_pleural_interfaces','each_actual_arterial_branch_wall_lumen_and_perforator','each_actual_superficial_deep_and_internal_mammary_venous_route','each_actual_cutaneous_intercostal_and_nipple_neural_route','each_actual_cutaneous_glandular_and_subareolar_lymphatic_route','axillary_level_I_nodes','axillary_level_II_nodes','axillary_level_III_nodes','interpectoral_Rotter_nodes','internal_mammary_nodes','infraclavicular_supraclavicular_nodes','intramammary_nodes','covered_axillary_neurovascular_and_fascial_interfaces','each_actual_unlisted_variant_or_reconstructed_tissue']
LESIONS=['every_actual_mass_boundary_and_internal_component','each_actual_non_mass_lesion_or_enhancement_component','each_actual_asymmetry_or_distortion_tissue_route','every_actual_calcification_group_and_resolved_component','each_actual_cyst_fluid_debris_solid_or_septal_component','each_actual_ductal_extension_and_intraductal_component','each_actual_perilesional_rind_edema_and_tissue_interface','each_actual_skin_nipple_or_chest_wall_lesion_interface','each_actual_biopsy_clip_wire_seed_and_tissue_correspondence','each_actual_postoperative_bed_scar_cavity_or_reconstruction','each_actual_residual_treated_or_recurrent_lesion','each_encountered_unlisted_lesion_or_treated_interface']
IMPLANTS=['actual_fill_material_and_internal_compartments','each_actual_shell_layer_and_shell_discontinuity','external_fibrous_capsule_and_implant_capsule_interface','each_actual_fold_or_displaced_shell_fragment','each_actual_valve_port_expander_and_connection','prepectoral_retropectoral_or_dual_plane_pocket','each_actual_extracapsular_material_and_tissue_route','each_actual_peri_implant_fluid_collection_and_capsular_mass','each_actual_material_containing_node_and_route','each_actual_contracture_infection_or_other_device_interface','each_actual_explant_residual_material_or_reconstruction']
PARTS=('entire_source_extent_and_native_geometry','every_actual_internal_component','each_boundary_and_adjacent_tissue_interface','every_actual_branch_connection_or_attachment','source_site_axes_modality_phase_and_comparison','unresolved_microscopic_or_uncovered_extent')
NODE_PARTS=('each_actual_node_and_basin_location','cortex_hilum_and_capsular_boundaries','every_actual_internal_component','each_vascular_pedicle_and_extranodal_interface','source_sampling_marker_treatment_and_comparison','unresolved_microscopic_or_uncovered_extent')
def build_draft(inv,ref,original):
    if inv not in CONFIG:raise ValueError('Unknown breast investigation')
    guide=copy.deepcopy(ref['reporting']);node=copy.deepcopy(original);config=CONFIG[inv]
    if len(node['steps'])!=5 or len(guide['checklist'])!=5 or len(guide['template_sections'])!=5:raise ValueError('Breast reader topology requires review')
    removed=sum(bool(s.get('normal')) for s in node['steps'])
    guide['reviewed_at']=DATE;guide['protocol']=[config['protocol'],'Record every relevant source population, age/development, hormonal/lactation, intervention and dated comparison context. Source views, planes and tissue confirmation are separate evidence; unrelated patients and modalities are not implicitly registered.']
    guide['sources']=[s for s in copy.deepcopy(guide.get('sources',[])) if s.get('url') not in {ACR,ACR_US,NCI,FDA,FDA_SCC,ANATOMY}]+[{'title':'ACR public BI-RADS v2025 context; full manual not retrieved','url':ACR},{'title':'Source human mammary anatomy review','url':ANATOMY}]
    if inv in ['ra.ultrasound-breast','ra.male-breast']:guide['sources'].append({'title':'ACR public breast ultrasound reporting requirements','url':ACR_US})
    if inv=='ra.breast-cancer-staging':guide['sources'].append({'title':'NCI professional breast cancer staging/treatment evidence','url':NCI})
    if inv=='ra.breast-implants':guide['sources'] += [{'title':'FDA BIA-ALCL clinical/source context','url':FDA},{'title':'FDA capsular SCC source context','url':FDA_SCC}]
    guide['pitfalls']=['Unacquired tissue is not negative. Preserve every source limitation and unresolved clinical/imaging/tissue discordance.','A whole-breast outline, single-side schematic, one published case or surface mesh does not supply all ductal, fascial, neural, vascular, nodal, microscopic, lesion or implant interfaces.','Appearance, source kinetics or device shape is not current histology, complete stage or an automatic clinical-action rule.']
    guide['measurements']=[m for m in guide.get('measurements',[]) if m.get('name')!='Source finding and every relevant interface']+[{'name':'Source finding and every relevant interface','method':'Record actual side/site, acquisition axes and calibration; measure each source-resolved component and total span where relevant, preserving supplied tissue and temporal context.','pitfall':'A displayed source shape or ROI does not prove every native boundary, histology or calibrated physiological measurement.'}]
    for index,(step,look) in enumerate(zip(node['steps'],config['looks'])):
        step['look']=look;step['detail']=look;step['tip']=guide['pitfalls'][index%len(guide['pitfalls'])];step['normal']={}
        step['measurements']=list(dict.fromkeys(step.get('measurements',[])+['Source finding and every relevant interface']))
        step['findings']=step.get('findings') or ['Actual source finding at [side/site]: [components, interfaces and measured extent]; unresolved source coverage and clinical/tissue correlation [ ].']
        guide['checklist'][index]['detail']=look
        guide['template_sections'][index]['body']=guide['template_sections'][index]['body'].split('\n\nAdditional source anatomy:')[0]+'\n\nAdditional source anatomy: Actual acquired side/site and every relevant component/interface [ ]; source extent, dimensions and dated comparison [ ]; separate clinical/tissue correlation [ ]; unresolved or uncovered anatomy [ ].'
    if any(i not in {m['name'] for m in guide['measurements']} for step in node['steps'] for i in step.get('measurements',[])):raise ValueError('Breast measurement routing requires review')
    node['model']={'family':'breast','reporting_aim':'Partial single-left-breast schematic orientation only. Bilateral native gland/duct, skin/fascia, neurovascular/lymphatic, chest-wall, nodal, lesion and implant anatomy and physiology remain unverified; no current patient registration or full reporting coverage is supplied.'}
    if inv=='ra.mri-breast':guide['classification']={'name':'Breast MRI assessment framework','version':'Record applicable current source version; public v2025 context only','applicability':'Actual contrast-enhanced or other supplied breast MRI and acquired workup scope.','summary':'Document source findings and integrated assessment rationale; this draft does not reproduce the full BI-RADS manual or assign a category from kinetics alone.'}
    structures=[];namespace=inv.removeprefix('ra.').replace('-','_')
    def add(key,side,steps,pathology=False):
        ident=namespace+'.'+side+'_'+key.lower();parts=NODE_PARTS if 'nodes' in key else PARTS
        structures.append({'id':ident,'name':side.capitalize()+' '+key.replace('_',' '),'tissue_class':'breast_source_tissue_route_node_lesion_or_device_interface','laterality':side,'modality_scope':config['modalities'],'required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ')} for p in parts],'condition':'Instantiate every actual acquired side, tissue, duct/lobular unit, branch, node, lesion, device and treated component. Microscopic or uncovered tissue remains unproven; imaging modality permission does not establish its resolution. Supplied histology, assays and physiological evidence remain identified separate sources.','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':[s['url'] for s in guide['sources']],'requirement_basis':'full_effective_breast_reporting_anatomy_and_actual_source_interfaces','requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'},'requires_independent_source_layer_review':True})
    for side in ['left','right']:
        for key in COMMON:
            if 'nodes' in key or 'nodal_level' in key:steps=[3] if inv=='ra.breast-cancer-staging' else [4]
            elif any(s in key for s in ['skin','nipple','areolar']):steps=[2] if inv=='ra.breast-cancer-staging' else [3] if inv=='ra.male-breast' else [0,1,2,3,4]
            else:steps=[0,1,2,3,4]
            add(key,side,steps)
        for key in LESIONS:add(key,side,[0,1,2,3,4],True)
        if inv=='ra.breast-implants':
            for key in IMPLANTS:add(key,side,[0,1,2,3,4],True)
    if inv=='ra.mri-breast':
        for key in ['each_actual_baseline_postcontrast_frame_and_ROI','each_actual_diffusion_b_value_ADC_and_source_region','each_actual_subtraction_motion_or_registration_interface']:add(key,'not_applicable',[0,3,4],True)
    if inv=='ra.breast-cancer-staging':
        for key in ['each_actual_obtained_distant_site_and_lesion','each_actual_pretreatment_posttreatment_target_and_comparison','each_actual_clinical_pathological_and_biomarker_evidence_interface']:add(key,'not_applicable',[0,4],True)
    item={'investigation_id':inv,'module_id':catalog.resolve(inv)['module_id'],'title':'Every actual bilateral breast tissue route node lesion and device interface','scope_status':'expanded_draft_requires_independent_breast_anatomical_and_source_review','modality_scope':config['modalities'],'sources':[{**s,'reviewed_at':DATE,'review_status':'public_primary_reporting_or_anatomical_context; no source graphics or full proprietary manual reused'} for s in guide['sources']],'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,'expansion_rules':['Each actual source side, tissue layer, duct/lobular unit, nerve/vessel/lymphatic branch, node, lesion, device and repair requires separate native geometry and interfaces. This floor is not a closed list.','Appropriate independent anatomical/microscopic sources remain necessary for fine components not resolved by the clinical study. No acquired modality implies visibility or proves every microstructure.','Preserve source patient/population, laterality, positioning/compression, source plane/sequence/phase, calibration, acquisition time and treatment context. Projection, MIP or shared module does not establish native3D registration.'],'source_scope_issues':['Current single-left-breast schematic is not bilateral native anatomy or all actual lesions/nodes/implants.','Public BI-RADS v2025 pages are not the complete proprietary manual; old MRI/staging source percentages and treatment pathways are not universal current-patient rules.','Imaging, sampling/pathology and actual physiological/temporal measurements remain distinct; source-only examples are not current diagnoses or approved reporting coverage.'],'functional_evidence_requirements':['DCE kinetics require actual baseline/frames, contrast route/dose/times, ROI and motion/subtraction context; a still or animation does not supply dynamic evidence.','Doppler, elastography and supplied diffusion/ADC require actual source acquisition/settings and calibration. A colour, stiffness or ADC label is not a unique histology/flow classifier.','Current staging, tissue identity, residual disease, biomarkers or device-associated malignancy require applicable clinical/pathological evidence and examination extent; no auto M0, pathological complete response or lymphoma diagnosis is supplied.'],'clinical_validation_status':'draft_requires_independent_breast_radiologist_anatomist_pathology_and_relevant_surgical_review'}
    return guide,node,item,removed

def build():
    path=ROOT/'data/radiology/reporting-steps/breast.json';data=json.loads(path.read_text());overpath=ROOT/'data/radiology/investigation-overrides-non-msk.json';over=json.loads(overpath.read_text());items=[]
    for inv in IDS:
        ref=catalog.detail(Curriculum(),catalog.resolve(inv))['radiology_reference'];guide,node,item,removed=build_draft(inv,ref,data['investigations'][inv]);data['investigations'][inv]=node;over.setdefault(inv,{})['reporting']=guide;items.append(item);print(inv,len(item['structures']),'groups;',len(requirements_for(item))*3,'representation obligations;',removed,'unsupported presets removed')
    path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');overpath.write_text(json.dumps(over,indent=2)+'\n')
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    for item in items:
        ref=catalog.detail(Curriculum(),catalog.resolve(item['investigation_id']))['radiology_reference'];item['source_contract_sha256']=digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']})
    path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[r for r in d['investigations'] if r['investigation_id'] not in IDS]+items;d['scope']['catalog_investigation_ids']=[r['investigation_id'] for r in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n')
if __name__=='__main__':build()
