#!/usr/bin/env python3
"""Expand every obtained arterial territory, chronic lesion, cardiac/venous/lung cause and source control."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_pulmonary_hypertension_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.pulmonary-hypertension'
RIGHT=['upper_apical','upper_posterior','upper_anterior','middle_lateral','middle_medial','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal']
LEFT=['upper_apical','upper_posterior','upper_anterior','lingular_superior','lingular_inferior','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'pulm_htn.'+key,'name':name,'tissue_class':'pulmonary_cardiovascular_structure_or_source_control','required_parts':[{'id':'pulm_htn.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],
          'laterality':side,'modality_scope':['CT'],'condition':'Instantiate every actual covered side/branch/subsegment/variant, region, lesion and repair with its actual acquired CT/phase/source calibration and evaluability. Standard segment labels are a known floor, not a fixed universal branch count or full native anatomy. Thin/microvascular or uncovered tissue remains unresolved; other modalities/hemodynamic data are separate sources and cannot become acquired CT.',
          'requirement_basis':'effective_CT_PH_and_thromboembolic_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    artery='actual_origin_and_branch_assignment full_obtained_course each_resolved_distal_subdivision lumen_wall_and_defect_interface_if_resolved source_defect_margins_and_full_covered_extent acute_chronic_mixed_or_mimic_features source_evaluability_opacification_motion_and_phase stenosis_pouch_recanalisation_or_variant_if_present local_axis_measurement_and_calibration_if_available uncovered_or_unresolved_extent'
    add('pulmonary_trunk','Pulmonary trunk and bifurcation',artery,[0,1,2,3])
    for side,segments,lobes in [('right',RIGHT,['upper','middle','lower']),('left',LEFT,['upper','lingular','lower'])]:
        add(side+'_main_PA',side.capitalize()+' main pulmonary artery',artery,[0,1,2,3],side)
        for lobe in lobes:add(side+'_'+lobe+'_lobar_PA',side.capitalize()+' '+lobe+' lobar/territory pulmonary arterial supply',artery,[0,1,2,4],side)
        for segment in segments:add(side+'_'+segment+'_segmental_PA',side.capitalize()+' actual '+segment.replace('_',' ')+' segmental supply',artery+' actual_combined_or_accessory_origin_relationship',[0,1,2,4],side)
        add(side+'_combined_accessory_PA',side.capitalize()+' every combined/accessory/unassigned arterial branch',artery+' actual_anatomical_segment_model_and_variant each_actual_additional_branch_not_in_standard_labels',[0,1,2,4],side)
        add(side+'_subsegmental_tree',side.capitalize()+' every actual acquired subsegmental/distal arterial subdivision',artery+' every_source_named_distal_endpoint each_evaluable_or_unevaluable_subsegment',[0,1,2,4],side)
        add(side+'_microvascular_region',side.capitalize()+' actual implicated small-arterial/capillary/venular region','actual_region_and_source_evidence small_arterial_capillary_or_venular_site_if_known parenchymal_vascular_or_other_interface CT_resolved_vs_microscopic_inferred_extent actual_histology_or_other_diagnostic_source_if_provided missing_microvascular_geometry_not_parent_tree source_resolution_and_uncertainty',[0,2,4],side)
        for key,name in [('acute_defect','Every suspected acute defect'),('chronic_material','Every chronic wall-adherent/laminated component'),('web_band_slit','Every actual web/band/slit'),('stenosis_ring','Each source stenotic/ring region'),('pouch_occlusion','Each pouch/tapered/amputated or other occlusion'),('recanalisation','Every actual recanalised channel'),('mixed_defect','Each actual mixed acute-on-chronic or unresolved component')]:
            add(side+'_'+key,side.capitalize()+' '+name,'actual_named_site_and_side each_source_resolved_proximal_distal_extent local_vessel_lumen_wall_relation every_component_and_branch_interface source_plane_phase_and_quality calibre_angle_or_other_morphology comparison_and_actual_chronology_if_available flow_or_other_confirmatory_source_if_obtained mimic_or_unresolved_extent',[0,1,2,4],side,purpose='pathology_example')
        add(side+'_bronchial_collaterals',side.capitalize()+' every actual bronchial collateral','actual_systemic_origin complete_covered_course each_actual_branch_and_connection pulmonary_or_other_endpoint local_calibre_and_aneurysmal_component_if_present source_anatomy_vs_flow_direction_evidence unresolved_or_uncovered_extent',[0,2,4],side)
        add(side+'_nonbronchial_collaterals',side.capitalize()+' every nonbronchial systemic collateral','each_actual_origin internal_thoracic_intercostal_or_other_route complete_source_resolved_course each_branch_anastomosis_or_endpoint local_vessel_and_tissue_relations source_phase_and_quality unavailable_function_or_uncovered_extent',[0,2,4],side)
        for vein in ['upper','lower','common_accessory_or_dual']:add(side+'_'+vein+'_pulmonary_vein',side.capitalize()+' actual '+vein.replace('_',' ')+' pulmonary venous return','actual_origin_and_tributaries full_source_resolved_course drainage_site_and_every_connection lumen_wall_and_lesion_or_variant_if_resolved adjacent_chamber_and_lung_relation contrast_phase_mixing_and_evaluability any_actual_venous_obstruction_or_mimic directly_visualised_vs_uncovered_or_inferred_extent',[0,3,4],side)
        for lobe in lobes:add(side+'_'+lobe+'_lung',side.capitalize()+' '+lobe+' covered lung region','actual_region_extent_and_segment_assignment each_parenchymal_and_vascular_interface source_opacity_mosaic_or_scar_pattern regional_vessel_calibre_source airway_interstitial_or_other_differential expiratory_or_quantitative_perfusion_source_if_obtained infarct_or_other_pathology_component actual_coverage_sampling_and_source_quality unresolved_or_uncovered_extent',[0,2,4],side)
        add(side+'_pleura',side.capitalize()+' pleura and covered compartments','source_resolved_boundaries each_actual_effusion_thickening_or_other_region extent_and_adjacent_lung_relation actual_source_phase_sampling_and_quality clinical_or_temporal_context_if_available unresolved_or_uncovered_extent',[4],side)
        add(side+'_arteriovenous_shunt',side.capitalize()+' every actual vascular/systemic-lung shunt component','actual_feeding_arterial_origin full_covered_arterial_route nidus_or_connection_if_resolved actual_draining_venous_course endpoint_and_chamber_or_organ_relation original_source_phase_and_quality actual_flow_or_shunt_measurement_if_supplied unresolved_or_uncovered_components',[0,3,4],side)
    for key,name,side in [('RA','Right atrium','right'),('RV','Right ventricle','right'),('RVOT','RV outflow tract','right'),('LA','Left atrium','left'),('LV','Left ventricle','left'),('LAA','Left atrial appendage','left')]:add(key,name,'full_covered_wall_and_pool source_phase_defined_size_shape_or_thickness actual_valve_septal_or_vessel_interface each_actual_disease_or_mimic_region defined_measurement_plane_and_calibration actual_temporal_function_source_if_supplied native_blood_pool_vs_tissue_and_opacification_limits unresolved_or_uncovered_extent',[0,3,4],side)
    for key,name in [('interventricular_septum','Interventricular septum'),('interatrial_septum','Interatrial septum'),('pericardium','Covered pericardium/compartments'),('aortic_root','Aortic root/ascending reference'),('IVC_hepatic','Covered IVC/hepatic-vein junctions'),('caval_azygos','Every covered caval/azygos variant'),('coronary_relation','Covered relevant coronary/PA relations')]:add(key,name,'complete_source_covered_extent each_native_boundary_if_resolved actual_connection_branch_or_compartment each_defect_or_other_morphological_component source_phase_motion_and_quality pressure_or_flow_source_if_supplied unassessed_or_unresolved_extent',[0,3,4])
    for valve in ['tricuspid','pulmonary','mitral','aortic']:add(valve+'_valve',valve.capitalize()+' actual native/prosthetic apparatus','source_resolved_leaflet_disc_or_repair annular_and_chamber_interface each_actual_disease_or_mimic original_phase_and_source_quality temporal_or_flow_function_if_supplied unresolved_thin_or_uncovered_extent',[3,4])
    for key,name in [('intracardiac_shunt','Each actual septal/ductal/intracardiac shunt component'),('PVOD_PCH_pattern','Each actual PVOD/PCH-suggestive region'),('arterial_sarcoma','Each actual sarcoma/other intravascular-mass differential'),('other_intravascular_mimic','Each vasculitic/congenital/in_situ/tumour or other mimic'),('lung_disease','Each actual emphysema/fibrotic/airway/inflammatory region'),('left_heart_disease','Every actual left-heart/valve/pericardial disease component'),('other_cause','Every other actual clinical/structural associated cause')]:
        add(key,name,'actual_site_and_every_component full_obtained_extent source_resolved_tissue_or_vessel_interfaces actual_branch_chamber_airway_or_other_relation source_signal_attenuation_or_morphology clinical_histological_genetic_or_other_evidence_if_supplied pattern_vs_aetiology_or_function_claim unavailable_tests_and_unresolved_extent',[0,2,3,4],purpose='pathology_example')
    for key,name,parts in [('mosaic_regions','Every actual mosaic-attenuation region','source_region_and_extent regional_vessel_calibre_and_density airway_and_interstitial_relationships actual_inspiratory_expiratory_source_if_obtained original_CT_quality_and_window actual_perfusion_or_other_function_source_if_obtained nonspecific_pattern_and_uncertainty'),('infarct_regions','Every suspected infarct/scar/other opacity','actual_site_and_extent pleural_vascular_and_airway_relationship attenuation_or_other_source_features embolic_vessel_correspondence_if_resolved clinical_and_serial_comparison other_differential_or_mimic unknown_viability_or_uncovered_extent'),('airways_interstitium_nodes','Covered airway/interstitial/septal/nodal findings','each_actual_airway_or_tissue_region ground_glass_or_other_opacity_extent septal_thickening_and_lymphatic_pattern_if_seen actual_node_site_and_morphology associated_vascular_or_cardiac_interfaces original_source_sampling_and_quality pattern_vs_cause_uncertainty')]:add(key,name,parts,[0,2,4],purpose='pathology_example')
    for key,name,parts in [('acquisition','Actual CT/CTPA acquisition','patient_exam_indication_and_dates actual_CT_contrast_phase_or_unenhanced_method per_territory_coverage_and_opacification cardiac_respiratory_motion_mixing_and_metals slice_sampling_reconstruction_axes_and_native_calibration each_unperformed_extra_phase_expiration_or_map source_artefact_and_unevaluable_regions'),('measurements','Each actual CT morphology/measurement','source_structure_site_and_side RV_LV_actual_method_planes_and_phase actual_PA_aortic_axis_edge_measurement_and_reference raw_source_units_and_calibration ratio_or_wall_measurement_uncertainty actual_prior_method_comparability missing_source_or_unresolved_boundaries'),('haemodynamics','Actual supplied pressure/resistance/classification','actual_RHC_or_other_source_and_date resting_or_exercise_context if_supplied_mPAP_PAWP_PVR_CO_values_units_method named_definition_and_reference pre_post_combined_or_other_supplied_pattern WHO_group_clinical_source_if_established no_pressure_or_disease_class_from_CT_morphology missing_or_unperformed_measurements'),('perfusion_sources','Each actually obtained perfusion/functional source','actual_deCT_iodine_subtraction_or_dynamic_CT_method_if_acquired original_map_data_quality_and_registration VQ_ventilation_and_perfusion_source_if_separately_obtained MRI_echo_or_other_function_source_if_supplied units_and_quantification_method_if_valid source_modality_not_borrowed_as_acquired_CT missing_unavailable_or_uncertain_tests'),('comparison','Each actual serial/reference comparison','patient_examination_dates_and_interval same_named_vessel_region_and_coverage comparable_method_source_phase_and_calibration each_actual_changed_region_or_component treatment_or_clinical_context_if_supplied absent_priors_or_uncertain_chronology'),('intervention_repair','Each actual covered postoperative/intervention region','source_known_procedure_or_device_identity full_covered_native_and_repair_extent anastomotic_attachment_or_other_interfaces actual_residual_recurrent_defect_or_complication original_source_and_comparison quality_and_uncovered_extent individual_operability_or_treatment_decision_not_geometry_only')]:add(key,name,parts,[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':'rad.5.pe-pulm-htn','title':'CT pulmonary hypertension and thromboembolic disease','scope_status':'expanded_draft_requires_independent_pulmonary_vascular_CT_clinical_review','modality_scope':['CT'],'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':s} for t,u,s in zip(['RA PH/thromboembolic scope','2022 ESC/ERS guideline','CTEPD current imaging review','Updated haemodynamic definitions review'],URLS,['effective_full_heading_and_relevant_morphology_scope_reviewed','primary_definition_and_CT_vs_hemodynamic_extracts_reviewed','original_XML_relevant_CTEPD_morphology_perfusionsource_and_limits_reviewed','original_XML_definition_classification_extracts_reviewed'])],
      'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':structures,'expansion_rules':['Every actual branch/subsegment, variant, lesion and adjacent regional interface requires independently reviewed CT/site/state-specific image/schematic/model evidence. Labels are not native geometry.','Unassessed microvascular/thin structure or missing acquired source remains unresolved; normal parent thorax/PA geometry cannot supply it.','Standard left/right segment names are not fixed branch counts: instantiate combined apicoposterior/anteromedial, accessory and other actual branching without inventing separate absent branches.'],
      'source_scope_issues':['RA states mPAP≥20 in one passage; the named 2022 ESC/ERS threshold is strictly>20. Actual RHC/PAWP/PVR/context/reference is required; CT does not measure pressure or classify pre/postcapillary disease.','Acute thrombus can be eccentric; location or angle alone does not uniquely date material, diagnose chronicity or exclude mixed/acute-on-chronic disease.','CTEPD can exist without PH. Negative/limited CTPA does not alone exclude distal chronic disease; source quality and complementary clinical/perfusion evidence remain separate.','Mosaic attenuation and PVOD/PCH-suggestive patterns are not unique diagnosis or measured perfusion; source expiration, iodine/VQ/MRI and clinical/histological data cannot be borrowed when unperformed.','PMC11657945 is CC BY-NC-ND4; no commercial figures derived from that grant. Other source grants/pixels and native full vascular/tissue/physiological validation remain separate pending work.'],
      'functional_evidence_requirements':['Confirm haemodynamic PH and actual clinical group with supplied measured/clinical sources, not a CT diameter/ratio or model.','Perfusion/viability, flow direction, functional severity and operability require actual corresponding evidence and clinical assessment.','Measurements require recorded planes/phase/reference/calibration and uncertainty; artifact/source nonvisualisation is not negative disease evidence.'],
      'clinical_validation_status':'draft_requires_pulmonary_vascular_radiologist_and_PH_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=IDENT]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
