#!/usr/bin/env python3
"""Expand full covered peripheral MRA vessel trees, variants, lesions, intervention and source controls."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.mra-peripheral-vessels'
URLS=['https://radiologyassistant.nl/cardiovascular/peripheral-mra/contrast-enhanced-mra-of-peripheral-vessels','https://www.jacc.org/doi/10.1016/j.jacc.2024.02.013','https://pubmed.ncbi.nlm.nih.gov/26994952/','https://pmc.ncbi.nlm.nih.gov/articles/PMC8218015/','https://pmc.ncbi.nlm.nih.gov/articles/PMC4175671/','https://pmc.ncbi.nlm.nih.gov/articles/PMC4154940/','https://pmc.ncbi.nlm.nih.gov/articles/PMC9964888/']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];guide=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'peripheral_mra.'+key,'name':name,'tissue_class':'peripheral_arterial_structure_or_source_control','required_parts':[{'id':'peripheral_mra.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],
          'laterality':side,'modality_scope':['MRI'],'condition':'Instantiate each actual covered vessel, branch, side, variant, lesion, collateral and intervention with its obtained MRI/sequence/station/phase and original calibration. Uncovered or non-diagnostic anatomy is unassessed, not normal/absent. Standard segment names are a known floor; every additional actual branch/site remains required. Extra peripheral territories require their complete named inventory and actual source evidence.',
          'requirement_basis':'effective_peripheral_MRA_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    vessel='actual_origin complete_covered_course proximal_distal_landmarks each_actual_branch_or_connection lumen_and_wall_if_source_resolved local_vessel_axis_or_centreline actual_minimum_orthogonal_lumen_reference_if_measured source_supported_patency_or_lesion actual_variant_and_adjacent_structure_relation original_station_phase_and_sampling uncovered_or_unresolved_extent'
    add('covered_aorta','Covered abdominal aortic inflow',vessel+' aortic_bifurcation terminal_aortic_inflow',[0,2,4])
    add('aortoiliac_bifurcation','Actual aortoiliac bifurcation',vessel+' right_left_branch_identity common_or_variant_origins',[0,2,4])
    arteries=[('common_iliac','Common iliac',[0]),('external_iliac','External iliac',[0]),('internal_iliac','Internal iliac',[0]),('internal_iliac_divisions','Each relevant internal iliac division/branch',[0,3]),('pelvic_collateral_branches','Each actual relevant pelvic/gluteal collateral branch',[0,3]),
      ('common_femoral','Common femoral',[1]),('femoral_bifurcation','Actual femoral bifurcation',[1]),('profunda_femoris','Profunda femoris',[1,3]),('superficial_femoral','Superficial femoral/adductor canal course',[1]),('medial_circumflex_femoral','Medial circumflex femoral if relevant/covered',[1,3]),('lateral_circumflex_femoral','Lateral circumflex femoral if relevant/covered',[1,3]),('profunda_perforators','Each relevant profunda perforating branch',[1,3]),('popliteal','Complete covered popliteal segments',[1,3]),('genicular_collaterals','Each actual genicular collateral pathway',[1,3]),
      ('anterior_tibial','Anterior tibial',[3]),('tibioperoneal_trunk','Tibioperoneal trunk if present',[3]),('posterior_tibial','Posterior tibial',[3]),('peroneal','Peroneal/fibular',[3]),('peroneal_perforating','Actual peroneal perforating branch',[3]),('peroneal_communicating','Actual peroneal communicating branches',[3]),('ankle_connections','Each covered malleolar/ankle arterial connection',[3]),
      ('dorsalis_pedis','Dorsalis pedis',[3]),('medial_plantar','Medial plantar',[3]),('lateral_plantar','Lateral plantar',[3]),('deep_plantar_connection','Actual dorsal-to-plantar perforating connection',[3]),('plantar_arch','Actual plantar arterial arch',[3]),('dorsal_connections','Actual dorsal arterial connections/arch',[3]),('metatarsal_branches','Every relevant covered dorsal/plantar metatarsal branch',[3]),('digital_branches','Every relevant covered digital branch',[3]),('calcaneal_branches','Every relevant covered calcaneal/heel branch',[3])]
    for side in ['right','left']:
        for key,name,steps in arteries:add(side+'_'+key,side.capitalize()+' '+name,vessel,sorted(set(steps+[2,4])),side)
        add(side+'_runoff_tree',side.capitalize()+' complete obtained runoff topology','each_actual_tibial_peroneal_origin trunk_or_trifurcation_if_present high_origin_or_other_branching_variant hypoplastic_absent_or_dominant_channels source_supported_vs_unresolved_identity each_distal_endpoint dorsal_and_plantar_connections incomplete_or_complete_source_resolved_arch each_actual_lesion_or_collateral wound_region_relation_if_supplied uncovered_or_unresolved_foot_extent',[1,3,4],side)
        add(side+'_collateral_routes',side.capitalize()+' each actual collateral/reconstitution route','origin_named_vessel full_obtained_route each_actual_branch_or_anastomosis reconstitution_site_and_distal_continuity calibre_if_measured flow_direction_source_if_obtained source_station_phase_and_quality uncertain_or_uncovered_extent',[0,1,3,4],side)
        add(side+'_intervention',side.capitalize()+' each actual bypass/stent/repair','device_or_conduit_identity_if_known proximal_anastomosis_or_attachment full_covered_conduit_or_stented_course distal_anastomosis_or_attachment adjacent_native_inflow_outflow each_actual_lesion_or_complication device_signal_loss_or_other_unresolved_lumen native_source_and_comparison uncertainty_and_uncovered_extent',[0,1,2,3,4],side,purpose='pathology_example')
        add(side+'_perforator_tissue_relations',side.capitalize()+' each actual reported fibular/perforator tissue relationship','parent_arterial_origin exit_point_and_level complete_source_resolved_perforator_course septocutaneous_or_musculocutaneous_route_if_resolved actual_septal_or_muscle_interface actual_fascial_or_cutaneous_endpoint fibular_or_other_named_landmark_relation source_resolution_and_registration operative_target_context_if_supplied unassessed_or_unresolved_thin_tissue_extent',[1,3,4],side)
        add(side+'_venous_overlap',side.capitalize()+' covered veins/arteriovenous overlap','each_actual_overlapping_venous_channel arterial_venous_identity_source station_and_contrast_phase contamination_extent_and_effect adjacent_arterial_segments shunt_or_early_filling_source_if_present unavailable_dynamic_or_flow_data unresolved_channels',[0,1,3,4],side)
        add(side+'_adjacent_tissues',side.capitalize()+' actual adjacent tissue/extravascular findings','each_source_covered_tissue_or_organ original_signal_or_enhancement_if_resolved actual_lesion_extent adjacent_vessel_or_intervention_relation wound_site_from_clinical_source_if_supplied dedicated_tissue_or_viability_data_if_obtained incomplete_tissue_protocol_or_uncovered_extent',[1,2,3,4],side,purpose='pathology_example')
        for key,name in [('stenosis','Each source-supported stenotic region'),('occlusion','Each source-supported occluded region'),('aneurysm','Each actual aneurysmal/pseudoaneurysmal region'),('dissection_or_thrombus','Each actual dissection/thrombus component'),('other_pathology','Every other actual arterial/repair/pathological region')]:
            add(side+'_'+key,side.capitalize()+' '+name,'named_site_and_all_components source_resolved_proximal_distal_extent actual_lumen_and_wall_boundaries orthogonal_lumen_reference_or_sac_neck_if_measured lesion_length_and_measurement_axis each_branch_or_adjacent_structure_interface collateral_and_distal_continuity actual_source_phase_and_quality flow_signal_loss_or_other_mimic source_supported_vs_inferred_or_unresolved_extent',[0,1,2,3,4],side,purpose='pathology_example')
    add('source_acquisition','Actual per-station MRI acquisition','patient_modality_and_exam_identity indication_actual_side_and_territory ce_vs_noncontrast_actual_sequence spatial_acquired_and_reconstructed_resolution temporal_sampling_and_phase bolus_or_flow_source_if_available mask_and_subtraction_sources coverage_and_station_overlap coil_motion_or_metal_context native_voxel_coordinates_and_units source_reformat_and_processing every_uncovered_or_unresolved_region',[0,1,2,3,4])
    add('signal_and_artefact','Every actual source signal/artefact region','arterial_vs_venous_identity bolus_timing_or_venous_contamination slow_in_plane_or_turbulent_flow_effect motion_subtraction_or_station_misregistration susceptibility_metal_or_other_signal_loss aliasing_partial_volume_or_other_source_effect named_affected_segments actual_confirmatory_source_if_obtained residual_diagnostic_uncertainty',[0,1,2,3,4])
    add('measurements','Each actual lumen/length/severity measurement','native_source_and_calibration named_site_and_axes minimum_orthogonal_lumen reference_site_and_convention_percent_if_used lesion_start_end_and_centreline aneurysm_neck_or_sac_if_measured partial_volume_and_source_resolution serial_method_comparability uncertainty_or_unavailable_measurement',[0,1,2,3,4])
    add('clinical_function','Actual clinical/flow/perfusion correspondence','clinical_presentation_and_source limb_threat_and_wound_site_if_supplied actual_pressure_or_velocity_test_if_obtained dynamic_flow_direction_source_if_obtained actual_perfusion_or_viability_test_if_obtained imaging_morphology_vs_clinical_significance unavailable_or_unperformed_tests urgent_communication_source_if_needed',[0,1,2,3,4])
    add('comparison','Actual prior/source comparison','patient_examination_and_dates actual_corresponding_vessels_and_sides prior_modality_sequence_and_coverage source_axis_measurement_and_reference convention_or_calibration_difference each_interval_change intervention_and_clinical_context uncertainty_and_unavailable_prior_segments',[0,1,2,3,4])
    add('additional_territories','Every actual additional peripheral territory','actual_territory_side_and_extent complete_named_origin_course_branch_inventory each_connection_and_distal_endpoint each_actual_lesion_and_intervention native_source_calibration_and_quality every_uncovered_or_unresolved_region separate_scope_expansion_required',[0,1,2,3,4])
    return {'investigation_id':IDENT,'module_id':'rad.5.peripheral-vascular','title':'MRA peripheral vessels','scope_status':'expanded_draft_requires_independent_peripheral_vascular_MRI_review','modality_scope':['MRI'],'sources':[{'title':title,'url':url,'reviewed_at':'2026-10-06','review_status':status} for title,url,status in zip(['RA peripheral CE-MRA','2024 multisociety PAD guideline','Popliteal branching meta-analysis','Pedal arterial anatomy review','Profunda/circumflex variant cadaver study','Pedal noncontrast MRA research','QISS lower-leg variants/perforator source'],URLS,['effective_reporting_and_historical_protocol_scope_reviewed','primary_society_clinical_context_and_imaging_timing_extracts_reviewed','primary_abstract_branching_extract_reviewed','primary_anatomy_and_modality_scope_extract_reviewed','primary_variant_anatomy_extract_reviewed','primary_pedal_MRA_quality_extract_reviewed','original_XML_captions_selected_figures_and_actual_MRI_annotation_roles_reviewed'])],
      'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
      'expansion_rules':['Instantiate every actual bilateral/unilateral covered tree, branch variant, lesion, collateral and intervention; standard names do not prove coverage.','Every leaf needs independently reviewed MRI/source/site/state-specific image, schematic and model evidence; parent aorta and normal trees cannot fill distal or diseased anatomy.','Other peripheral territories remain mandatory named-scope expansion, not zero requirements or automatic lower-limb equivalence.'],
      'source_scope_issues':['The original RA article includes historical scanner, injection/compression and treatment statements; these are not universal current protocol, pixel-grade guarantees or automatic intervention/amputation decisions.','Source signal loss/nonvisualisation can reflect timing, flow, metal, motion, overlap, variant/hypoplastic anatomy or uncovered tissue; it does not independently prove occlusion or absence.','Actual runoff branches, dominant supply, arch connections and wound target must be traced; three-vessel runoff cannot be presumed.','Static luminal appearance does not prove haemodynamic severity, wound perfusion, tissue viability, native device function or treatment outcome.','The current aorta companion lacks the native complete iliac-to-pedal/intervention/pathology tree. Existing image rights, original pixel/series correspondence and full anatomical/clinical review remain unverified.'],
      'functional_evidence_requirements':['Flow direction, pressure, perfusion and viability need their actual acquired/clinical sources rather than MIP brightness or tree connectivity.','Report measurement/reference/sequence/calibration and per-station uncertainty; MRI source resolution is not independent scanner calibration.','Urgent suspected acute limb ischaemia requires clinical assessment without delay for routine MRA; individual management remains with the clinical team.'],
      'clinical_validation_status':'draft_requires_peripheral_vascular_radiologist_and_vascular_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=IDENT]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
