#!/usr/bin/env python3
"""Expand rectal/fistula source anatomy and preserve baseline/restaging distinctions."""
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
IDS=['ra.mri-rectal-cancer','ra.mri-perianal-fistula'];DATE='2026-10-08'
ANATOMY='https://pmc.ncbi.nlm.nih.gov/articles/PMC9849549/'
PRIMARY='https://pmc.ncbi.nlm.nih.gov/articles/PMC13212678/'
RESTAGE='https://pmc.ncbi.nlm.nih.gov/articles/PMC13212783/'
FISTULA='https://pmc.ncbi.nlm.nih.gov/articles/PMC13512459/'
PARTS=['complete_actual_source_extent','each_internal_layer_or_component','outer_inner_and_adjacent_interfaces','proximal_distal_and_branch_course','each_resolved_boundary','unresolved_or_uncovered_extent']
COMMON=['rectal_mucosa','rectal_submucosa','inner_circular_muscularis_propria','outer_longitudinal_muscularis_propria','rectal_lumen_and_centreline','sigmoid_takeoff_and_rectosigmoid_transition','anorectal_junction','anal_verge_and_margin','dentate_line_with_separate_clinical_correlation','anal_transitional_epithelium_and_crypt_duct_interfaces','anal_longitudinal_muscle_and_intersphincteric_plane','mesorectal_fat_and_each_fascial_interface','anterior_peritoneal_reflection_and_actual_peritoneal_covering','rectoprostatic_or_rectovaginal_fascial_interface','Waldeyer_fascia_and_presacral_space','superior_rectal_artery_and_each_branch','superior_rectal_vein_and_each_branch','presacral_venous_plexus','urinary_bladder_wall_lumen_and_trigone','each_actual_separate_pelvic_bowel_loop_and_mesenteric_interface','each_actual_obtained_bone_cortex_marrow_or_finding']
BILATERAL=['internal_anal_sphincter_and_smooth_muscle_continuity','external_anal_sphincter_and_each_source_resolved_component','puborectalis_and_anorectal_sling','levator_ani_pubococcygeal_component','levator_ani_iliococcygeal_component','coccygeus_when_obtained_or_reported','ischioanal_fossa_and_fat','obturator_compartment_and_muscle','pelvic_plexus_and_each_actual_autonomic_nerve_route','sacral_or_sciatic_nerve_interface_when_reported','pudendal_nerve_artery_vein_and_each_branch','middle_rectal_artery_and_vein_branches','inferior_rectal_artery_and_vein_branches','ureter_and_urethral_interface_when_present','prostate_seminal_vesicle_or_vas_interface_when_present','vagina_cervix_uterus_or_adnexal_interface_when_present','sacral_pubic_or_hip_interface_when_obtained']
NODES=['mesorectal_and_superior_rectal_route','obturator','internal_iliac','external_iliac','common_iliac','presacral','inguinal_with_actual_tumour_dentate_context']
LOOKS={
 IDS[0]:[
 'Map every actual tumour component, lower/upper border, length, circumferential position and relation to sigmoid take-off, ARJ, verge, anal canal and peritoneal reflection. Record exact landmark and measurement convention; source height-category inequalities differ at5cm, so no automatic category is assigned.',
 'Trace source-resolved wall layers, extramural invasion and every sphincter, pelvic-floor, peritoneal, fascial, neural, vascular and adjacent-organ interface. MRI may not separate T1 fromT2. Internal sphincter/intersphincteric involvement is described separately from the rectal cT descriptor; external sphincter invasion has different staging implications.',
 'Distinguish MRF from peritoneum and the eventual surgical margin. Name the closest primary tumour, EMVI or nodule and actual morphology, with measured distance and uncertainty. A smooth node within1mm does not automatically make MRF involved; baseline and treated fibrosis require separate interpretation.',
 'Inventory each actual node/nodule by side, compartment, size, morphology, vascular relationship and confidence. Preserve regional/nonregional context, including actual anal/dentate involvement. Baseline lateral criteria and mesorectal risk assessment are not universal restaging thresholds or histological proof of deposits.',
 'Record treatment/date, complete original tumour bed and dated comparisons, fibrosis and actual matched T2/DWI/ADC findings. Reconcile supplied DRE/endoscopy and tissue information. MRI alone does not prove pathological complete response, provide all ycT detail or automatically select organ preservation; lateral nodal restaging remains uncertain.'
 ],
 IDS[1]:[
 'Locate every source-demonstrated internal opening and actual height with an explicitly stated clock-face/view convention. Distinguish ARJ, verge and inferred dentate level; a schematic or lithotomy clock convention is not verified source MRI acquisition position.',
 'Trace the complete actual primary tract wall/lumen and each sphincter/intersphincteric/ischioanal crossing in native planes. Keep source visible segments and unresolved continuation distinct; a blind sinus is not a proven complete fistula.',
 'Map each branch, horseshoe component, blind endpoint, separate tract and external opening, including bilateral and deep extensions. Original drawn yellow fills are publication annotations, not supplied native segmentation masks or verified complete lumen boundaries.',
 'Review every collection and its wall/content, three source dimensions, communicating tract and relation to puborectalis/levator and supralevator compartments. Selected views or signal alone do not independently establish organism, drainability or the complete route.',
 'Review actual sphincter defects, perineal skin/soft tissue, proctitis, prior surgery/seton and supplied inflammatory/tissue context. State source limitations and operative correlation. Parks type describes the demonstrated anatomical relation; it is not current histology, disease activity or a complete treatment plan.'
 ]}

def build_draft(inv,ref,node):
    guide=copy.deepcopy(ref['reporting']);node=copy.deepcopy(node);guide['reviewed_at']=DATE
    additions=[{'title':'Source rectal MRI anatomy and modality limits','url':ANATOMY}]
    additions+=([{'title':'ESGAR2026 PartI primary staging consensus','url':PRIMARY},{'title':'ESGAR2026 PartII restaging and response consensus','url':RESTAGE}] if inv==IDS[0] else [{'title':'Original perianal MRI/source illustration review','url':FISTULA}])
    guide['sources']=[s for s in guide['sources'] if s['url'] not in {a['url'] for a in additions}]+additions
    guide['protocol'].append('Retain actual examination purpose,source patient/position,planes,acquisition/processing,coverage,quality and temporal context. Source sampling does not establish fine anatomical resolution; unacquired structures remain unassessed.')
    guide['measurements'].append({'name':'Every source component and interface','method':'Measure each actually resolved component,tract/nodule/lesion or interface in the supplied native plane with stated calibration,landmark and source series. Preserve complete extent and all uncovered tissue.','pitfall':'A still,diagram,source measurement or whole-organ model does not supply every layer,branch,opening,clinical state or histological boundary.'})
    for i,(step,look) in enumerate(zip(node['steps'],LOOKS[inv])):
        guide['checklist'][i]['detail']=look;step['look']=look;step['detail']=look;step['normal']={};step['parts']=[]
        step['measurements']=list(dict.fromkeys(step.get('measurements',[])+['Every source component and interface']))
        guide['template_sections'][i]['body']+='\nActual source-resolved components/interfaces [ ]; exact reference,quality and uncovered extent [ ]; separate clinical/tissue/temporal correlation [ ].'
    removed=sum(bool(s['normal']) for s in ref['walkthrough']['steps'])
    node['model']={'family':'rectal','reporting_aim':'Partial schematic orientation only; complete source wall layers,fascia,peritoneum,sphincter/pelvic-floor,duct/neurovascular,nodal,tract/tumour and treated anatomy remain unverified. Selected published MRI/diagrams are separate source references,not registered whole-patient3D geometry or full reporting coverage.'}
    if inv==IDS[0]:
        guide['pitfalls'] += ['MRF invasion alone is notT4; MRF,peritoneal covering and eventual surgical CRM are distinct. A baseline smooth-margin node nearMRF is not the same as tumour,EMVI or irregular nodule involvement.','ESGAR2026 no longer recommends a baseline1–2mm threatenedMRF category. Its tumour-height boundary at5cm is inconsistent between source sections; record exact height/landmark and adopted convention.','Fibrosis or no visible restriction does not prove pathological complete response. Combine actual MRI quality and obtained clinical/endoscopic evidence; baseline nodal thresholds are not lateral restaging rules.']
        node['steps'][3]['findings'][2]='Irregular source nodule in continuity with a vein, suspicious for a deposit [ ]; nodal/deposit distinction and confidence [ ]; no histological N1c assignment from appearance alone.'
        node['steps'][4]['findings'][0]='Hypointense fibrotic tumour-bed remnant with actual diffusion findings [ ]; source quality [ ]; reconcile obtained DRE/endoscopy and response confidence [ ]. MRI alone does not establish pathological complete response.'
        node['steps'][4]['findings'][1]='Residual intermediate T2 signal and corresponding source diffusion finding [ ]; extent and quality [ ]; response class/confidence and supplied clinical/tissue correlation [ ].'
    structures=[];namespace='rectal_cancer' if inv==IDS[0] else 'perianal_fistula'
    def add(key,side,steps,pathology=False):
        ident=namespace+'.'+side+'_'+key
        structures.append({'id':ident,'name':side+' '+key.replace('_',' '),'laterality':side,'tissue_class':'actual_anorectal_tissue_route_compartment_node_or_pathological_interface','modality_scope':['MRI'],'required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ')} for p in PARTS],'condition':'Instantiate every actual reported side,tissue layer,branch,node,tract/lesion,device or treated component and its native source interfaces. Microscopic,unacquired or unresolved tissue remains unproven; modality permission does not establish visibility or histology.','requires_site_instantiation':True,'requires_independent_source_layer_review':True,'requirement_basis':'full_effective_anorectal_reporting_scope_and_actual_interfaces','walkthrough_step_indices':steps,'report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'source_urls':[s['url'] for s in guide['sources']],'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'}})
    for key in COMMON:add(key,'not_applicable',[0,1,2,3,4])
    for side in ['left','right']:
        for key in BILATERAL:add(key,side,[0,1,2,3,4])
        for key in NODES:add(key+'_each_actual_node_and_vessel_interface',side,[3] if inv==IDS[0] else [4])
    conditional=(['each_actual_primary_tumour_and_every_component','each_actual_satellite_or_separate_lesion','each_actual_extramural_venous_invasion_route','each_actual_suspicious_deposit_and_nodal_interface','each_actual_MRF_peritoneal_or_adjacent_extension','each_actual_source_baseline_treated_tumour_bed_and_fibrosis','each_actual_resection_anastomosis_flap_stoma_or_device'] if inv==IDS[0] else ['each_actual_internal_opening_and_crypt_duct_relation','each_actual_external_opening_and_skin_interface','each_actual_primary_tract_wall_lumen_and_crossing','each_actual_secondary_branch_and_blind_endpoint','each_actual_horseshoe_or_bilateral_extension','each_actual_supralevator_or_deep_compartment_extension','each_actual_collection_wall_contents_and_communication','each_actual_sinus_without_proven_complete_fistula','each_actual_seton_surgery_defect_and_treated_tract','each_actual_proctitis_skin_change_or_separate_source_finding'])
    for key in conditional:add(key,'not_applicable',[0,1,2,3,4],True)
    for key in ['each_actual_T2_diffusion_ADC_or_contrast_frame_and_ROI','each_actual_source_movement_distortion_or_uncovered_region','each_actual_supplied_clinical_endoscopic_operative_and_tissue_correspondence']:add(key,'not_applicable',[0,1,2,3,4],True)
    item={'investigation_id':inv,'module_id':catalog.resolve(inv)['module_id'],'title':'All actually reported anorectal anatomy and source interfaces','modality':'MRI','modality_scope':['MRI'],'scope_type':'native_anorectal_anatomy_with_conditional_lesion_route_nodal_and_treated_scope','scope_status':'expanded_draft_requires_independent_anorectal_source_review','clinical_validation_status':'draft_requires_anorectal_radiologist_anatomist_pathology_and_relevant_surgical_review','required_representations':['image','schematic','model'],'sources':[{**s,'reviewed_at':DATE,'review_status':'primary_reporting_or_source_anatomy_context; not a current-patient diagnostic rule'} for s in guide['sources']],'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,'expansion_rules':['Expand each actual reported source tissue,branch,opening,node,lesion,extension and repair. This is a floor,not a closed list or a requirement to invent unseen microscopy.','MRI,surgical/histological specimen,conceptual drawing and separate clinical/endoscopic/operative evidence retain their own patient,modality,position and timing context.','No original source labels,static figure or schematic automatically supplies native3D registration,complete physiology or current histology.'],'source_scope_issues':['Existing schematic is not complete native layered or pathological anatomy.','Original published selected planes/annotations do not prove every reported source boundary or a complete current examination.','Primary staging and post-treatment response criteria remain distinct; absent acquisitions or source contradictions are preserved.'],'functional_evidence_requirements':['Diffusion,contrast,tract activity and response claims require actual source sequence/processing,ROIs,calibration,timing and quality; a still or drawn fill is not physiological evidence.','Current treatment,clinical complete response,pathological complete response,organism or disease activity requires relevant actual clinical/tissue/temporal correlation.']}
    return guide,node,item,removed

def build():
    p=ROOT/'data/radiology/reporting-steps/abdomen.json';text=p.read_text();overp=ROOT/'data/radiology/investigation-overrides-non-msk.json';over=json.loads(overp.read_text());items=[]
    for inv in IDS:
        ref=catalog.detail(Curriculum(),catalog.resolve(inv))['radiology_reference'];start=text.index('{',text.index('"'+inv+'"'));node,end=json.JSONDecoder().raw_decode(text,start);guide,node,item,removed=build_draft(inv,ref,node);text=text[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+text[end:];over.setdefault(inv,{})['reporting']=guide;items.append(item);print(inv,len(item['structures']),'groups;',len(requirements_for(item))*3,'representation obligations;',removed,'unsupported presets removed')
    p.write_text(text);overp.write_text(json.dumps(over,indent=2,ensure_ascii=False)+'\n')
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    for item in items:
        ref=catalog.detail(Curriculum(),catalog.resolve(item['investigation_id']))['radiology_reference'];item['source_contract_sha256']=digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']})
    p=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(p.read_text());d['investigations']=[r for r in d['investigations'] if r['investigation_id'] not in IDS]+items;d['scope']['catalog_investigation_ids']=[r['investigation_id'] for r in d['investigations']];p.write_text(json.dumps(d,indent=2)+'\n')

if __name__=='__main__':build()
