#!/usr/bin/env python3
"""Require every acquired neck-space component/interface without inventing invisible fascia or function."""
import copy,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
ROOT=Path(__file__).resolve().parents[2];INV='ra.mri-neck-spaces'
URLS=['https://radiologyassistant.nl/head-neck/infrahyoid-neck/MR-anatomy-and-pathology','https://radiologyassistant.nl/head-neck/infrahyoid-neck','https://pmc.ncbi.nlm.nih.gov/articles/PMC3994542/','https://pmc.ncbi.nlm.nih.gov/articles/PMC6377693/','https://pmc.ncbi.nlm.nih.gov/articles/PMC7309289/']
def build():
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];guide=copy.deepcopy(ref['reporting'])
    details=['Localise each actual source epicentre and obtained supra/infrahyoid extent using named compartments, retained landmarks and explicit convention/uncertainty.',
        'Describe every actual source lesion/component and acquired tissue signal, diffusion and enhancement; maintain technical limitations and differential rather than unique tissue identity.',
        'Trace actual source displacement/contact of each fat plane, vessel, gland, muscle and neural/visceral interface; direction is evidence for localisation, not a diagnosis by itself.',
        'Map each source-supported fascial, skull-base, neural, airway, visceral and mediastinal connection; distinguish contact from supported invasion and obtained from unassessed extent.',
        'Record every acquired nodal group/node and collection/vascular/other complication with actual source confidence; infection, flow and microscopic disease require corresponding evidence.']
    looks=['Use actual axial/coronal/sagittal coverage and non-fat-suppressed T1 landmarks. Name the anatomical convention and descriptive boundaries; lost or distorted landmarks can leave the epicentre unresolved.',
        'Inspect actual T1/T2, fat-suppressed pre/postcontrast sources and paired DWI/ADC if acquired. Describe each solid/fluid/fat/blood-appearing or other component, source phase/sequence and unresolved tissue.',
        'Trace obtained parapharyngeal/other fat and actual carotid/jugular/gland/muscle/nerve routes. Record side, source planes and every contact/displacement interface; mass distortion and variants may limit localisation.',
        'Trace actual acquired skull base, pharynx/larynx/trachea, esophagus, thyroid, fascia and neural pathways to all obtained connections. Record whether each boundary is directly resolved or inferred; unacquired lower mediastinum or thin fascia is not normal.',
        'Survey only obtained named nodal regions and every relevant node component. Describe actual collection contents/boundaries/adjacent tissue and source vessel lumen/wall appearances with appropriate flow/contrast correlation if available.']
    tips=['A schematic space boundary is not an independently seen fascial layer; use the actual convention and preserve unresolved boundaries.',
        'Signal or enhancement patterns have a differential; they do not establish histology, organism, viability or a unique diagnosis.',
        'ICA/ECA bifurcation splaying can support a carotid-body-region differential but is not unique proof of paraganglioma or another tissue diagnosis.',
        'Contact, displacement or loss of fat plane alone is not proof of invasion, perineural spread or airway function; microscopy and clinical compromise remain separate evidence.',
        'Rim enhancement/restriction does not independently prove a drainable abscess or organism; a flow void or static lumen shape does not certify thrombosis, patency or function.']
    guide.update(reviewed_at='2026-10-07',protocol=['Record actual MRI source coverage from obtained skull-base/face through neck and lower extent, planes/sampling, motion/artifact, pre/postcontrast fat-suppression and paired DWI/ADC/vascular sequences if acquired. Bone CT, US and functional examinations remain separate sources.',
        'Record source symptom/site, supplied primary/tissue/microbiology, treatment and comparison. Source-resolved anatomy and uncertainty guide compartment localisation; there is no preset normality for unexamined spaces or physiology.'],checklist=[{'label':label,'detail':text} for label,text in zip(['Compartment and extent','Tissue components','Displacement and contacts','Spread and critical interfaces','Nodes and complications'],details)],pitfalls=tips,sources=[{'title':title,'url':url} for title,url in zip(['RA infrahyoid MRI reporting','RA supra/infrahyoid source index','Retropharyngeal/prevertebral imaging anatomy','Carotid space imaging','Source cervical-fascia terminology review'],URLS)])
    bodies=['Each actual epicentre/side/space and anatomical convention [ ]; obtained supra/infrahyoid/skull-base/mediastinal extent [ ]; retained landmarks, inferred boundaries and uncertainty [ ].',
        'Each actual lesion/tissue component and source extent [ ]; source T1/T2, pre/postcontrast/fat suppression and paired DWI/ADC findings if obtained [ ]; unresolved contents and differential [ ].',
        'Actual fat-plane/gland/muscle/neural and vessel contact/displacement [ ]; each source side/course/interface and source plane [ ]; variant/distortion and localisation limits [ ].',
        'Each obtained fascial/skull-base/neural/airway/esophageal/thyroid/mediastinal interface or connection [ ]; source confidence, contact versus supported extension [ ]; unexamined extent and clinical function [ ].',
        'Every actual acquired node/group/named map/side/component [ ]; source collection or vessel/other complication findings and confidence [ ]; supplied clinical/tissue/microbiology/flow evidence [ ]; unavailable or microscopic extent [ ].']
    for section,body in zip(guide['template_sections'],bodies):section['body']=body
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data.setdefault(INV,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/head-neck.json';text=path.read_text();start=text.index('{',text.index('"'+INV+'"'));node,end=json.JSONDecoder().raw_decode(text,start);node['model']={'family':'neck','reporting_aim':'Partial neck compartment orientation only. This schematic does not supply every native fascia/space boundary, gland, muscle, small vessel/nerve, node, airway wall or lesion interface. Actual MRI source extent, unresolved thin tissues and clinical function remain separate.'}
    for i,step in enumerate(node['steps']):step.update(normal={},detail=details[i],look=looks[i],tip=tips[i],findings=['Actual acquired '+step['label'].lower()+' findings [ ]; source side/extent/interface [ ]; uncertainty and unavailable evidence [ ].'])
    path.write_text(text[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+text[end:])
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];structures=[]
    def add(key,parts,steps,side='not_applicable',pathology=False):
        ident='neck_spaces.'+side+'_'+key;structures.append({'id':ident,'name':side.replace('_',' ').capitalize()+' '+key.replace('_',' '),'tissue_class':'neck_space_fascial_tissue_component_or_actual_connection','required_parts':[{'id':ident+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['MRI'],'condition':'Instantiate every actual acquired space, side, component, variant, lesion/repair and tissue/route connection using the named anatomical convention. A schematic line or a preserved parent region is not independently resolved thin fascia, every node, nerve, wall or microscopic interface. Unacquired extent remains missing.','requirement_basis':'effective_supra_infrahyoid_neck_MRI_reporting_scope','report_refs':[{'checklist_index':i,**guide['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'}})
    space='full_actual_obtained_compartment_extent each_source_resolved_or_explicitly_inferred_boundary all_actual_contents_and_tissue_interfaces superior_inferior_and_adjacent_space_connections each_actual_variant_lesion_or_repair acquired_landmarks_convention_and_unresolved_extent'
    tissue='every_actual_component_and_obtained_extent each_source_resolved_boundary_or_wall all_adjacent_neural_vascular_fascial_or_visceral_interfaces each_actual_route_branch_or_tissue_connection every_encountered_variant_lesion_or_repair unresolved_microscopic_or_uncovered_extent'
    node='every_actual_node_identity_and_obtained_extent source_resolved_cortex_hilum_margin_and_capsular_interface every_resolved_solid_fluid_necrotic_appearing_or_calcific_component each_perinodal_and_adjacent_node_tissue_relation actual_named_map_and_source_local_axes unresolved_microscopic_or_uncovered_extent'
    for side in ['left','right']:
        for key in ['parapharyngeal_prestyloid_region','carotid_poststyloid_region_if_named','parotid_space','masticator_space','buccal_space','sublingual_space','submandibular_space','posterior_cervical_space','covered_retropharyngeal_region','covered_danger_space_region','prevertebral_region','paraspinal_region','visceral_and_anterior_cervical_regions_if_named']:add(key,space,[0,1,2,3,4],side)
        for key in ['parotid_superficial_deep_lobes_and_duct','submandibular_gland_deep_extension_and_duct','sublingual_gland_and_ducts','thyroid_lobe_and_encountered_parathyroid','mylohyoid_boundary_and_actual_defects','hyoglossus_genioglossus_and_tongue_components','digastric_stylohyoid_and_styloid_apparatus','masseter_temporalis_and_pterygoids','sternocleidomastoid_and_trapezius','sternohyoid_sternothyroid_omohyoid_and_thyrohyoid','longus_colli_longus_capitis_and_scalenes','paraspinal_muscle_and_encountered_spinal_interfaces','common_internal_external_carotid_courses_and_branches','internal_external_and_anterior_jugular_courses_and_tributaries','carotid_sheath_vagus_sympathetic_and_encountered_IX_XI_XII','encountered_facial_lingual_inferior_alveolar_or_other_neural_routes','covered_skull_base_foraminal_neural_and_vascular_interfaces','mandible_dental_and_temporomandibular_interfaces','covered_hyoid_laryngeal_pharyngeal_and_esophageal_interfaces','covered_thoracic_inlet_subclavian_and_brachial_plexus_interfaces']:add(key,tissue,[0,1,2,3,4],side)
        for key in ['actual_Ib_nodes','actual_II_nodes','actual_III_nodes','actual_IV_nodes','actual_V_nodes','actual_VI_nodes','covered_VII_or_other_map_dependent_nodes','covered_retropharyngeal_parotid_and_other_unassigned_nodes']:add(key,node,[0,3,4],side)
        for key in ['each_lesion_or_collection_component_and_interface','each_actual_gland_muscle_vessel_or_nerve_displacement','each_actual_skull_base_neural_or_visceral_spread_connection','each_actual_nodal_or_vascular_complication']:add(key,tissue,[0,1,2,3,4],side,True)
    for key in ['investing_fascia_and_superficial_boundary','buccopharyngeal_fascia','alar_or_intercarotid_fascia_if_named','prevertebral_fascia_and_actual_compartments','pretracheal_or_visceral_fascia_if_named','retropharyngeal_midline_and_lateral_connections','danger_space_and_obtained_mediastinal_connection','pharyngeal_mucosal_lymphoid_and_constrictor_components','laryngeal_mucosal_cartilage_and_paraglottic_interfaces','tracheal_wall_lumen_and_source_air_interface','esophageal_wall_lumen_and_surrounding_planes','thyroid_isthmus_and_encountered_midline_variants','hyoid_and_midline_floor_of_mouth_boundaries','skin_subcutaneous_fat_and_platysma','obtained_vertebral_disc_spinal_canal_and_epidural_interfaces','actual_midline_Ia_and_other_named_nodes','each_actual_crossing_or_unassigned_lesion_extent']:
        add(key,space if 'space' in key or 'fascia' in key else tissue,[0,1,2,3,4])
    item={'investigation_id':INV,'module_id':ref['investigation']['module_id'],'title':'Every acquired supra infrahyoid compartment content boundary and connection','scope_status':'expanded_draft_requires_independent_neck_space_anatomical_review','modality_scope':['MRI'],'sources':[{'title':s['title'],'url':s['url'],'reviewed_at':'2026-10-07','review_status':'source_reporting_or_anatomical_context_reviewed_no_graphics_reused'} for s in guide['sources']],'source_contract_sha256':digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']}),'reporting_checklist':guide['checklist'],'reporting_template_sections':guide['template_sections'],'structures':structures,
        'expansion_rules':['Every actual space/content/interface, site, variant, lesion/repair and connection requires independent instantiation; listed groups are a known floor.','Fascial terminology and retropharyngeal/danger/prevertebral boundaries require the actual named convention and source; a potential space is not a directly visible native wall.','MRI source roles remain separate from CT bone/calcium, vascular flow, clinical airway/swallowing function, microscopy and specimen photography.'],
        'source_scope_issues':['Existing neck primitives and selected inherited figures do not establish all source fascia, glands, nerves/vessels, nodes or disease interfaces.','Fine optical source samples and label masks are not automatically registered current-patient MRI or independent anatomical approval.'],
        'functional_evidence_requirements':['Airway compromise, swallowing, vocal/motor/sensory function, vessel patency and thrombosis need actual corresponding acquisitions/clinical evidence, not static contact geometry.','Histology, microscopic invasion, organism, viability and drainability are supplied source/clinical domains, not fabricated 3D tissues.','Displacement patterns and MRI signal/diffusion/enhancement support localisation/differential; they do not establish a unique tumour or tissue identity.'], 'clinical_validation_status':'draft_requires_head_neck_radiologist_and_relevant_anatomical_review'}
    path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=INV]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');n=len(requirements_for(item));print(len(structures),'groups;',n,'parts;',n*3,'representation obligations')
if __name__=='__main__':build()
