#!/usr/bin/env python3
"""Enumerate pulmonary and extrapulmonary thoracic anatomy, without turning microbiology into geometry."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_thoracic_tb_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.tuberculosis';MODES=['Radiography','CT','MRI','Ultrasound']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',pathology=False):
        structures.append({'id':'thoracic_tb.'+key,'name':name,'tissue_class':'thoracic_tissue_lesion_or_connection','required_parts':[{'id':'thoracic_tb.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':MODES,'condition':'Instantiate every actual covered side/lobe/segment, variant, lesion, nodal group and connection with its actually acquired modality/phase/sequence and resolution. Projection overlap or unresolved microscopic boundaries remain missing; a permitted modality does not automatically resolve every required part. Standard labels are a known floor, not a fixed case count.','requirement_basis':'effective_pulmonary_and_extrapulmonary_thoracic_TB_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':'pathology_example' if pathology else 'anatomical_reference'}})
    region='full_actual_covered_region each_consolidation_nodule_cavity_or_other_component source_airway_vessel_pleural_or_septal_relation actual_distribution_and_supported_extent source_modality_resolution_and_sampling_limit each_resolved_vs_overlapped_or_microscopic_boundary comparison_if_actually_obtained uncovered_or_unassessed_extent'
    segments={'right':['upper_apical','upper_posterior','upper_anterior','middle_lateral','middle_medial','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal'],'left':['upper_apical','upper_posterior','upper_anterior','lingular_superior','lingular_inferior','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal']}
    for side,lobes in [('right',['upper','middle','lower']),('left',['upper_with_lingula','lower'])]:
        for lobe in lobes:add(side+'_'+lobe+'_territory',side.capitalize()+' '+lobe.replace('_',' ')+' lobe/territory',region,[0,1,3,4],side)
        for seg in segments[side]:add(side+'_'+seg+'_region',side.capitalize()+' actual '+seg.replace('_',' ')+' segmental region',region+' combined_or_accessory_assignment_if_present',[0,1,3,4],side)
        add(side+'_additional_region',side.capitalize()+' every additional/variant/unassigned region',region+' each_actual_region_not_standard_labels',[0,1,3,4],side)
        for key,name in [('consolidation','each consolidation or ground-glass region'),('cavity','each cavity/abscess or cyst-like mimic'),('nodules','every nodular/miliary/tree-in-bud region'),('fungal_component','each suspected intracavitary component or fungal-ball mimic'),('fibrocalcific','each scar/calcium/volume-loss region')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_named_site_and_full_obtained_extent every_source_resolved_margin_wall_or_component adjacent_airway_vessel_septal_and_pleural_interfaces source_content_enhancement_or_signal_if_acquired local_axis_measurement_and_calibration_if_available matching_source_chronology_if_obtained mimics_and_unresolved_microscopic_or_uncovered_extent',[0,1,3,4],side,True)
        for key,name in [('central_airway','every relevant main/lobar bronchial route'),('distal_airway','every relevant source-resolved distal bronchial/bronchiolar route'),('pulmonary_arterial','each relevant pulmonary arterial branch'),('systemic_collateral','every relevant bronchial/nonbronchial systemic route'),('venous','every covered relevant venous return')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_origin_and_full_obtained_course every_covered_branch_or_variant source_lumen_wall_or_projection_limit lesion_cavity_node_or_fistula_interface actual_endpoint_or_connection_if_resolved source_phase_sequence_and_evaluability uncovered_or_unresolved_extent',[0,1,2,3],side)
        for key,name in [('hilar_nodes','hilar/peribronchial nodal regions'),('axillary_nodes','axillary nodal regions'),('covered_cervical_nodes','covered supraclavicular/lower-cervical nodal regions')]:add(side+'_'+key,side.capitalize()+' every actual '+name,'each_actual_named_nodal_site full_source_boundary_and_obtained_extent source_size_calibration_and_internal_components attenuation_signal_enhancement_or_calcium_if_acquired adjacent_airway_vessel_soft_tissue_or_fistulous_relation actual_comparison_and_sampling_limits microscopic_or_uncovered_extent',[2,3,4],side)
        for key,name in [('pleura','pleural layers/compartments/recesses'),('fluid','each pleural fluid/loculation region'),('pleural_air','each pleural air or hydropneumothorax region'),('empyema_extension','every empyema/necessitans extension'),('fistula','every actual bronchopleural/other thoracic fistulous connection')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_covered_compartment_and_every_component source_resolved_boundary_wall_and_content airway_lung_chest_wall_or_diaphragmatic_relation full_obtained_course_extent_and_endpoints_if_present every_communication_or_unresolved_connection source_modality_phase_and_evaluability uncovered_extent_and_mimics',[0,2,3,4],side,key!='pleura')
        add(side+'_breast_chestwall',side.capitalize()+' covered breast/chest-wall/soft-tissue region','actual_named_site_and_covered_compartments every_source_mass_fluid_or_fistulous_component parenchymal_skin_fascial_and_adjacent_rib_interfaces_if_resolved full_obtained_extent_and_connections modality_specific_acquired_source_or_unavailable_mammogram actual_comparison_and_unresolved_extent',[2,3,4],side)
    for key,name in [('trachea_carina','Covered tracheal/carinal region'),('pericardium','Covered pericardium and compartments'),('myocardium_chambers','Each covered myocardial/chamber interface'),('mediastinal_soft_tissue','Every relevant covered mediastinal soft-tissue region'),('oesophagus','Covered oesophageal route/interfaces'),('sternum_clavicles','Covered sternum/clavicle and joint regions'),('thoracic_spine','Every relevant covered thoracic vertebral/disc/paraspinal region'),('diaphragm_upper_abdomen','Covered diaphragm/upper-abdominal tissue and nodal interfaces')]:add(key,name,'actual_named_site_and_full_obtained_extent every_source_resolved_tissue_boundary_or_component adjacent_lung_airway_vessel_node_or_fistula_relation actual_mass_fluid_calcification_destruction_or_mimic_if_present source_phase_sequence_resolution_and_quality modality_specific_unresolved_or_uncovered_extent actual_comparison_and_supported_uncertainty',[0,2,3,4])
    for region in ['upper_paratracheal','lower_paratracheal','subcarinal','prevascular','retrotracheal','aortopulmonary','para_aortic','para_oesophageal','pulmonary_ligament','additional_or_unassigned']:
        add('mediastinal_nodes_'+region,'Every actual '+region.replace('_',' ')+' nodal group','each_actual_group_side_and_covered_node source_boundary_internal_content_and_obtained_extent source_size_method_and_calibration_if_available adjacent_airway_vessel_pleural_or_oesophageal_relation calcium_or_enhancement_signal_if_acquired necrotic_appearing_vs_unresolved_microscopic_component actual_source_comparison_and_uncertainty',[2,3,4])
    for side in ['left','right']:
        add(side+'_relevant_ribs_bones',side.capitalize()+' every actually implicated rib/bone/joint interface','actual_source_number_or_variant_and_covered_course cortical_medullary_joint_and_soft_tissue_boundary_if_resolved every_lesion_destructive_fluid_or_sequestral_component adjacent_pleural_chest_wall_or_paraspinal_relation each_actual_additional_covered_bone_not_generic_parent source_modality_resolution_and_uncovered_extent',[3,4],side)
    for key,name in [('vascular_cavity_connection','Every suspected aneurysm/bleeding-related vascular-cavity interface'),('residual_post_treatment','Every actual residual/post-treatment lesion or repair interface')]:add(key,name,'each_actual_named_site_and_full_obtained_extent vessel_airway_cavity_or_other_tissue_boundary each_actual_component_connection_and_endpoint source_phase_and_available_comparison quality_and_unresolved_or_uncovered_extent clinical_or_functional_evidence_is_separate',[0,1,3,4],pathology=True)
    return {'investigation_id':IDENT,'module_id':ref['investigation']['module_id'],'title':'Pulmonary and extrapulmonary thoracic TB imaging','scope_status':'expanded_draft_requires_independent_thoracic_infection_anatomical_review','modality_scope':MODES,'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-07','review_status':'primary_morphology_scope_or_diagnostic_domain_reference_reviewed'} for t,u in zip(['RA TB morphology/mimics','2024thoracic multiorgan source review','2025WHO diagnostic domains; no reused graphics'],URLS)],'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':structures,'expansion_rules':['Every actual acquired region/lesion/nodal chain/connection and variant must be independently instantiated; named parent structures are not complete native geometry.','Use only genuinely resolving acquired sources; CXR cannot borrow CT/MRI/US microscopic or wall/route information.','Separate courtesy-source holds and unavailable native series/models remain unresolved; licensing/source labels cannot approve anatomy.'],'source_scope_issues':['Radiographic/CT patterns do not alone distinguish new infection/reactivation, establish viability/infectivity/resistance or unique organism.','Normal imaging and scar/calcium do not establish absence of latent or coexisting active disease.','Cavity/fungal-ball/aneurysmal/fistulous/nodal/pericardial or chest-wall appearance needs actual source extent, clinical context and mimics.','Mammography/US/MRI/angiographic or other sources remain separate modalities; teaching cases/timelines cannot be merged.','Courtesy figures8/14/15, full native tissue/branch/lesion models and independent clinical/source anatomical validation remain outstanding.'],'functional_evidence_requirements':['Actual laboratory/specimen/molecular/culture/susceptibility sources with dates are diagnostic evidence requirements, not structures to invent in3D.','Pressure/constriction/tamponade/flow or clinical severity requires corresponding measured/clinical evidence; static morphology alone cannot supply it.','Interval response/activity requires matched actual acquisition/coverage and clinical/laboratory chronology, not a teaching-case image sequence.'],'clinical_validation_status':'draft_requires_thoracic_radiologist_and_relevant_infection_clinical_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=IDENT]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n');n=len(requirements_for(item));print(len(item['structures']),'groups;',n,'leaves;',n*3,'representation obligations')
