#!/usr/bin/env python3
"""Enumerate actual cystic-lung lesions, regional tissue interfaces and diagnostic source limits."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_cystic_lung_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.hrct-cystic-lung'
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'cystic_lung.'+key,'name':name,'tissue_class':'cystic_lung_tissue_interface_or_source_control','required_parts':[{'id':'cystic_lung.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],'laterality':side,'modality_scope':['CT'],'condition':'Instantiate every actual covered side/lobe/segment, variant, cyst-like lesion, associated component and tissue interface with actual source plane/reconstruction and evaluability. Standard labels are a known floor, not a fixed actual variant or complete patient count. Microscopic, unacquired or unresolved anatomy remains missing. Clinical/genetic/tissue sources are separate from CT.','requirement_basis':'effective_cystic_lung_CT_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    regional='actual_covered_extent_and_boundaries each_cyst_or_mimic_site source_airway_vessel_pleural_or_septal_interfaces regional_cyst_number_or_justified_burden source_opacity_nodule_fibrosis_or_other_component each_resolved_or_unresolved_boundary actual_reconstruction_phase_window_and_evaluability uncovered_or_unassessed_extent'
    segs={'right':['upper_apical','upper_posterior','upper_anterior','middle_lateral','middle_medial','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal'],'left':['upper_apical','upper_posterior','upper_anterior','lingular_superior','lingular_inferior','lower_superior','lower_medial_basal','lower_anterior_basal','lower_lateral_basal','lower_posterior_basal']}
    for side,lobes in [('right',['upper','middle','lower']),('left',['upper_with_lingula','lower'])]:
        for lobe in lobes:add(side+'_'+lobe+'_lobe',side.capitalize()+' '+lobe.replace('_',' ')+' lobe/territory',regional,[0,1,2,3],side)
        for segment in segs[side]:add(side+'_'+segment+'_region',side.capitalize()+' actual '+segment.replace('_',' ')+' segmental region',regional+' actual_combined_accessory_or_variant_assignment',[0,1,2,3],side)
        add(side+'_additional_region',side.capitalize()+' every actual combined/accessory/unassigned regional variant',regional+' each_additional_source_defined_region_not_standard_label',[0,1,2,3],side)
        for key,name in [('pleura_recesses','pleura and costophrenic/other recesses'),('fissures','actual major_minor_accessory_fissures'),('peribronchovascular','peribronchovascular compartment'),('subpleural','subpleural peripheral compartment'),('paramediastinal','paramediastinal compartment')]:add(side+'_'+key,side.capitalize()+' '+name.replace('_',' '),'full_actual_covered_boundary each_cyst_lesion_or_mimic_relation local_wall_airway_vessel_or_septal_interface source_extent_distribution_and_quality each_actual_opacity_or_solid_component comparison_and_unresolved_or_uncovered_extent',[0,1,2,3,4],side)
        for key,name in [('cyst','each true-or-suspected cyst'),('cavity','each cavity'),('bulla_emphysema','each bulla/emphysematous region'),('pneumatocele','each possible pneumatocele'),('bronchiectasis','each source bronchiectatic airway'),('honeycomb','each honeycomb region'),('cystic_mass','each cyst-associated mass or solid component')]:add(side+'_'+key,side.capitalize()+' '+name,'each_actual_site_and_obtained_extent outer_wall_airspace_or_tissue_boundary_if_resolved variable_wall_thickness_regularity_and_source_limits internal_content_septa_or_mural_component each_airway_vessel_and_adjacent_parenchymal_relation local_axis_measurement_window_and_calibration actual_same_site_comparison_and_chronology mimics_and_unresolved_microscopic_components',[0,1,2,3],side,purpose='pathology_example')
        for key,name in [('nodule','every solid/cavitating or intracystic nodule'),('ground_glass','every ground_glass region'),('septa_reticulation','every septal_reticular region'),('fibrosis','every fibrotic_or_distorted region')]:add(side+'_'+key,side.capitalize()+' '+name.replace('_',' '),'each_actual_site_and_extent lesion_vs_intervening_parenchymal_boundary cyst_wall_airway_vessel_or_pleural_relation actual_distribution_and_source_sampling source_measurement_or_comparison_if_available technical_limits_and_differential unresolved_or_uncovered_components',[0,1,2,3],side,purpose='pathology_example')
        for key,name in [('pneumothorax','actual pneumothorax'),('pleural_fluid','each pleural fluid or other lesion')]:add(side+'_'+key,side.capitalize()+' '+name,'source_pleural_compartment_and_obtained_extent adjacent_cyst_lung_and_chest_wall_relationship source_resolution_and_quality clinical_effect_or_fluid_characterisation_if_supplied chronology_and_actual_prior_source uncertainty_and_uncovered_extent',[0,4],side,purpose='pathology_example')
        for key,name in [('airway','every actually covered relevant airway branch'),('artery','every source-resolved relevant pulmonary/systemic arterial branch'),('vein','every source-resolved relevant venous connection')]:add(side+'_'+key,side.capitalize()+' '+name,'actual_origin_and_obtained_course every_relevant_branch_or_connection source_lumen_wall_or_partial_volume_limit cyst_or_mimic_interface_and_continuity actual_distal_endpoint_if_covered contrast_phase_or_noncontrast_evaluability unavailable_or_unresolved_extent',[0,1,2,3,4],side)
    for key,name,parts,steps in [('nodes','Every covered mediastinal/hilar lymph-node or mass region','each_actual_site_and_source_boundary local_size_method_and_calibration cyst_lung_airway_and_vessel_relation source_density_or_component_if_resolved comparison_and_coverage_limits',[2,4]),('renal','Every covered relevant renal/adrenal/upper-abdominal lesion','each_actual_organ_and_covered_extent lesion_or_mass_interfaces_if_present actual_acquired_phase_and_calibration source_only_morphology_and_uncertainty renal_or_genetic_diagnosis_not_from_uncovered_source',[4]),('acquisition','Actual CT acquisition and measurement sources','source_identity_date_and_clinical_question complete_obtained_coverage_and_sampling reconstruction_window_phase_and_motion local_measurement_axis_edge_convention_calibration actual_inspiration_expiration_contrast_if_obtained uncertainty_and_unperformed_tests',[0,1,2,3,4]),('comparison','Every actual comparison lesion/site','source_identity_date_and_prior_coverage actual_corresponding_site_and_component registration_or_plane_sampling_difference supported_interval_change_and_uncertainty changes_not_inferred_from_unmatched_teaching_cases',[0,1,2,3,4]),('clinical_context','Actual systemic/history/diagnostic sources','source_identity_date_and_available_scope smoking_autoimmune_infection_or_hereditary_history actual_genetic_microbiology_or_histological_evidence clinical_function_or_systemic_findings_if_supplied current_patient_not_teaching_case_source unavailable_or_uncertain_confirmation',[4]),('distribution_burden','Complete obtained regional distribution/burden source','actual_coverage_of_each_side_lobe_and_variant number_or_explicitly_qualified_burden_estimate apical_basal_axial_and_pleural_relationship every_relevant_cyst_or_associated_component age_count_heuristic_not_unique_or_exclusion_diagnosis source_quality_and_unassessed_regions',[0,1,2,3,4])]:add(key,name,parts,steps)
    return {'investigation_id':IDENT,'module_id':'rad.4.hrct','title':'HRCT cystic lung disease','scope_status':'expanded_draft_requires_independent_thoracic_cystic_lung_review','modality_scope':['CT'],'sources':[{'title':t,'url':u,'reviewed_at':'2026-10-06','review_status':s} for t,u,s in zip(['RA cystic lung differential','2026 original cystic CT pictorial review'],URLS,['effective_full_heading_and_mimic_systemic_and_solitary_lesion_scope_reviewed','original_XML_and_all11_CT_figures_reviewed'])],'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':structures,'expansion_rules':['Instantiate all actual cyst-like lesions and regional interfaces; standard side/segment labels are not complete native geometry or lesion counts.','Source thin-wall/count/age and pattern rules do not independently establish benignity, genotype, histology or a unique diagnosis.','Uncovered/unresolved microscopic walls, native branch or distribution anatomy require further source evidence; a whole lung parent model supplies none.'],'source_scope_issues':['RA four-and-forty rule is explicitly contextual; screening suspicion/recurrent pneumothorax cannot be excluded by small counts.','Thin-wall morphology, central dots, cysts-with-ground-glass/nodules and costophrenic patterns overlap across diagnoses. Negative PET or wall thinning alone does not establish benignity.','2026 source FDS/AMP terminology is retained with actual source history; teaching cases do not set current patient genotype/histology.','Original figure1 caption E3D vs actual axial image; figures2/4 omit actualI; figure5 printedH/I/K skipsG/J. Mismatches are explicit, not repaired.','Microscopic lining, functional disease severity, source genetic/tissue confirmation and raw complete disease-specific 3D model coverage remain unresolved.'],'functional_evidence_requirements':['Air trapping, perfusion/dynamic function and clinically meaningful severity require actual acquired or supplied sources.','Full burden and interval change require stated source coverage, plane/calibration, matched-site comparison and uncertainty.'],'clinical_validation_status':'draft_requires_thoracic_radiologist_and_relevant_clinical_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';d=json.loads(path.read_text());d['investigations']=[i for i in d['investigations'] if i['investigation_id']!=IDENT]+[item];d['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in d['investigations']];path.write_text(json.dumps(d,indent=2)+'\n');n=len(requirements_for(item));print(len(item['structures']),'groups;',n,'leaves;',n*3,'representation obligations')
