#!/usr/bin/env python3
"""Expand actual covered nongated-CT compartments, variants, disease and evidence controls."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.check_radiology_fidelity import digest
from tools.check_msk_fidelity import requirements_for
from tools.anatomy_sources.update_chest_cardiovascular_reporting import URLS
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.ct-cardiovascular-pearls'
SEGMENTS=['basal_anterior','basal_anteroseptal','basal_inferoseptal','basal_inferior','basal_inferolateral','basal_anterolateral','mid_anterior','mid_anteroseptal','mid_inferoseptal','mid_inferior','mid_inferolateral','mid_anterolateral','apical_anterior','apical_septal','apical_inferior','apical_lateral','apical_cap']
def build():
    ref=detail(Curriculum(),resolve(IDENT))['radiology_reference'];g=ref['reporting'];structures=[]
    def add(key,name,parts,steps,side='not_applicable',purpose='anatomical_reference'):
        structures.append({'id':'chest_cv.'+key,'name':name,'tissue_class':'covered_chest_cardiovascular_structure_or_source_control','required_parts':[{'id':'chest_cv.'+key+'.'+p,'name':p.replace('_',' ').capitalize()} for p in parts.split()],
          'laterality':side,'modality_scope':['CT'],'condition':'Instantiate every actual covered structure, branch, chamber region, lesion, variant and repair with source CT/phase/gating/coverage, laterality, calibration and uncertainty. Labels are a known floor, not source-resolved geometry. Routine nongated CT does not supply all thin layers, coronary/valve or functional/haemodynamic data; unassessed structures remain explicit rather than inferred from a normal companion.',
          'requirement_basis':'effective_chest_CT_cardiovascular_reporting_scope','report_refs':[{'checklist_index':i,**g['checklist'][i]} for i in steps],'walkthrough_step_indices':steps,'source_urls':URLS,'requires_site_instantiation':True,'context_requirements':{'purpose':purpose}})
    chamber='source_covered_wall_and_pool_boundaries full_resolved_extent source_phase_defined_size_or_shape each_inflow_outflow_or_valve_interface endocardial_epicardial_or_trabecular_border_if_resolved actual_septal_or_appendage_relation each_defect_mass_or_other_component mixing_motion_or_other_source_mimic actual_function_source_if_obtained unassessed_or_unresolved_extent'
    for key,name,side in [('RA','Right atrium','right'),('RV','Right ventricle','right'),('LA','Left atrium','left'),('LV','Left ventricle','left'),('RAA','Right atrial appendage','right'),('LAA','Left atrial appendage','left')]:add(key,name,chamber,[0,1],side)
    for key,name in [('interatrial_septum','Interatrial septum'),('interventricular_septum','Interventricular septum'),('AV_septal_interface','AV septal/chamber junctions'),('LVOT','Actual LV outflow/aortomitral interface'),('RVOT','Actual RV outflow'),('atrial_membrane','Each actual cor-triatriatum membrane/band')]:add(key,name,'actual_origin_attachment_and_boundary complete_source_resolved_extent each_chamber_valve_or_vessel_interface actual_defect_or_fenestration_if_resolved contrast_phase_or_mixing_relation source_visualisation_vs_inference actual_motion_or_shunt_data_if_obtained uncertain_or_uncovered_extent',[0,1,2])
    for n,region in enumerate(SEGMENTS,1):add('LV_region_'+str(n),'Covered LV '+region.replace('_',' '),'source_region_assignment_if_model_applied actual_covered_endocardial_border compact_or_midwall_region_if_resolved epicardial_border_and_fat_interface source_phase_defined_thickness_or_thinning each_fat_calcium_or_attenuation_region actual_aneurysm_or_other_shape_component trabecular_or_papillary_relation temporal_perfusion_or_viability_source_if_obtained unassigned_or_unresolved_extent',[0,1],'left')
    for key,name in [('RV_inflow_wall','RV inflow wall'),('RV_free_wall','RV body/free wall'),('RV_outflow_wall','RV outflow wall'),('RV_septal_interfaces','RV septal/insertion interfaces')]:add(key,name,'complete_covered_region each_source_resolved_wall_interface actual_thickness_and_phase_if_measured trabecular_papillary_or_other_border actual_fat_calcium_or_attenuation_region source_motion_and_partial_volume effects_source_if_obtained unassessed_or_unresolved_extent',[0,1],'right')
    for side in ['right','left']:add(side+'_papillary_chordal',side.capitalize()+' source-resolved papillary/chordal apparatus','each_actual_group origin_body_tip_if_resolved each_resolved_chordal_course leaflet_and_wall_interface actual_tissue_or_calcification_region source_phase_or_motion_limit unsupported_thin_parts_unassessed',[0,1,2],side)
    for valve in ['aortic','mitral','tricuspid','pulmonary']:add(valve+'_valve',valve.capitalize()+' native/prosthetic valve apparatus','actual_leaflet_disc_or_repair_if_resolved annulus_and_root_or_chamber_plane subvalvar_and_supravalvar_interface each_calcium_or_other_component actual_vegetation_mass_or_mimic if_measured_dimension_and_source actual_motion_or_flow_source_if_obtained unresolved_or_uncovered_thin_apparatus',[0,2])
    vessel='actual_origin_or_proximal_interface full_covered_course each_actual_branch_or_junction source_resolved_lumen_and_wall named_axis_edge_phase_and_diameter_if_measured each_variant_or_lesion_component actual_endpoint_or_drainage adjacent_cardiac_airway_or_other_relation source_opacification_motion_or_other_limit directly_seen_vs_inferred_or_uncovered_extent'
    for key,name in [('aortic_root','Aortic root'),('ascending_aorta','Ascending aorta'),('arch','Actual aortic arch'),('isthmus','Aortic isthmus/diverticular region'),('descending_aorta','Covered descending aorta')]:add(key,name,vessel,[2,3])
    for sinus in ['right_coronary','left_coronary','noncoronary']:add(sinus+'_sinus',sinus.replace('_',' ').capitalize()+' aortic sinus','actual_source_resolved_sinus_boundary valve_leaflet_annular_and_wall_interfaces actual_coronary_ostium_or_absent_ostium_role source_defined_root_axis_and_phase if_measured_local_dimensions_and_method each_actual_aneurysm_neck_wall_or_other_component adjacent_chamber_or_vessel_relation unresolved_or_uncovered_extent',[2,3])
    for side in ['right','left']:
        for key,name in [('brachiocephalic_artery','Brachiocephalic arterial channel if actually present'),('carotid','Covered common carotid origin'),('subclavian','Covered subclavian origin/course'),('vertebral','Covered relevant vertebral origin'),('bronchial_arteries','Each relevant covered bronchial artery'),('pulmonary_artery','Main pulmonary artery/covered lobar branches'),('caval_channel','Each actually present caval venous channel'),('brachiocephalic_vein','Brachiocephalic vein')]:add(side+'_'+key,side.capitalize()+' '+name,vessel,[3],side)
        for key,name in [('upper_pulmonary_vein','Upper pulmonary venous return'),('lower_pulmonary_vein','Lower pulmonary venous return'),('other_pulmonary_vein','Every actual common/accessory/dual pulmonary venous return')]:add(side+'_'+key,side.capitalize()+' '+name,vessel+' chamber_connection_and_variant each_actual_segmental_tributary_if_relevant',[0,3],side)
    for key,name in [('pulmonary_trunk','Pulmonary trunk'),('IVC','Covered IVC'),('hepatic_venous_junction','Covered hepatic-vein/caval connections'),('azygos','Covered azygos vein/continuation'),('hemiazygos','Covered hemiazygos/accessory channels'),('left_superior_intercostal_vein','Left superior intercostal vein/aortic nipple'),('levoatrial_cardinal_vein','Each actual levoatrial cardinal channel'),('coronary_sinus','Coronary sinus and covered cardiac venous return'),('scimitar_return','Actual scimitar/anomalous infracardiac return'),('ductus_ligament_region','Each actual patent ductal or inferred ligamentous component'),('systemic_lung_supply','Each actual systemic-lung/sequestration feeding channel'),('systemic_lung_drainage','Each actual sequestration/systemic-lung venous drainage')]:add(key,name,vessel,[0,3])
    for key,name in [('LM','Covered left main coronary'),('LAD','Covered anterior descending coronary'),('LCx','Covered circumflex coronary'),('RCA','Covered right coronary'),('coronary_branches','Every relevant covered additional coronary branch/graft'),('coronary_variant','Each actual coronary origin/course variant'),('coronary_fistula','Each actual coronary fistula/connection')]:add(key,name,vessel+' actual_ostium_course_and_adjacent_structure each_visual_calcium_region nongated_vs_diagnostic_coronary_source_limits',[2,3])
    for key,name in [('pericardium','Covered pericardial layers'),('pericardial_compartments','Each pericardial compartment/reflection/recess'),('epicardial_fat','Covered epicardial/pericardial fat'),('pericardial_cyst','Each actual pericardial cyst or other lesion')]:add(key,name,'complete_covered_source_extent each_resolved_layer_or_boundary each_fluid_fat_calcium_or_thickened_region source_resolved_lesion_and_all_components myocardial_vessel_or_other_interface source_phase_sampling_and_calibration actual_dynamic_or_clinical_effect_data_if_available unassessed_or_unresolved_extent',[4])
    disease='actual_site_and_every_component full_covered_extent source_resolved_lumen_wall_or_tissue_border layer_chamber_and_vessel_relations original_CT_phase_and_window_or_calibration morphology_mixing_motion_and_other_mimics actual_measurements_and_reference_if_supported clinical_priors_or_other_diagnostic_evidence_if_available missing_temporal_flow_or_tissue_sources unresolved_or_uncovered_extent'
    for key,name,steps in [('filling_defect','Each actual filling defect/thrombus differential',[0,1]),('mass','Each actual cardiac/pericardial mass',[0,1,2,4]),('vegetation','Each actual vegetation/valvar mass differential',[0,2]),('septal_shunt','Each actual septal/vascular shunt component',[0,3]),('myocardial_injury','Each actual suspected chronic/acute myocardial injury region',[1]),('myocardial_aneurysm','Each ventricular aneurysm/pseudoaneurysm/diverticulum component',[0,1]),('hypertrophy_dilation','Every actual chamber/wall phenotype',[0,1]),('calcification','Every actual myocardial/coronary/valve/annular/wall calcium region',[1,2,3,4]),('embolic_disease','Each actual source-supported pulmonary/vascular embolic component',[3]),('aortic_disease','Each actual source-supported aortic wall/lumen disease component',[3]),('venous_variants','Every actual caval/pulmonary/cardiac venous variant',[0,3]),('pericardial_disease','Every actual effusion/thickening/calcification/inflammatory/mass component',[4]),('other_disease','Every additional actual cardiovascular lesion or mimic',[0,1,2,3,4])]:add(key,name,disease+(' actual_outpouching_subtype_and_differential source_resolved_neck_or_communication native_myocardium_pericardial_or_other_boundary neighbouring_organ_or_surgical_relation actual_dynamic_contraction_source_if_obtained' if key=='myocardial_aneurysm' else ''),steps,purpose='pathology_example')
    add('repair_device','Every actual covered device/graft/repair','actual_source_resolved_device_or_conduit_identity complete_covered_route each_attachment_anastomosis_or_native_interface valve_chamber_and_vessel_relationship each_actual_complication_or_mimic source_artefact_and_unresolved_lumen actual_model_or_function_source_if_known unassessed_or_uncovered_extent',[0,1,2,3,4],purpose='pathology_example')
    for key,name,parts,steps in [('CAC_visual','Actual nongated visual CAC assessment','adequate_covered_coronary_source each_visible_coronary_calcium_region whole_patient_visual_burden_method none_mild_moderate_severe_or_unassessed technique_motion_and_coverage_limits distinction_from_stenosis_or_unvalidated_Agatston_score clinical_symptom_and_risk_context_if_provided',[2]),('valve_calcium','Actual valve/annular calcium assessment','leaflet_vs_root_wall_annular_or_coronary_location whole_source_visual_burden_method actual_other_valve_or_root_findings phase_sampling_and_motion_limits actual_echocardiographic_or_other_function_if_supplied unresolved_location_or_severity',[2,3]),('acquisition','Actual CT acquisition/source controls','patient_exam_modality_and_indication contrast_route_phase_or_unenhanced_source actual_ECG_gating_and_cardiac_phase_if_known spatial_sampling_reformats_and_original_calibration cardiac_respiratory_motion_and_metals complete_covered_and_uncovered_regions source_window_and_processing each_unavailable_extra_phase_or_sequence',[0,1,2,3,4]),('functional_evidence','Actual temporal/haemodynamic/clinical evidence','actual_obtained_motion_or_EF_source actual_flow_pressure_shunt_or_perfusion_source clinical_tamponade_constriction_or_valve_severity_evidence imaging_association_vs_aetiology_diagnosis clinical_lab_genetic_histological_or_other_confirmation_if_supplied unavailable_or_unperformed_tests',[0,1,2,3,4]),('comparison','Every actual serial/reference comparison','patient_and_examination_identity dates_and_interval matching_actual_region_phase_and_coverage comparable_axis_edge_and_measurement_conventions each_actual_changed_site_or_component clinical_and_intervention_context_if_available unavailable_priors_or_unresolved_change',[0,1,2,3,4])]:add(key,name,parts,steps)
    return {'investigation_id':IDENT,'module_id':'rad.5.cardiac-masses-devices','title':'Chest CT cardiovascular findings','scope_status':'expanded_draft_requires_independent_chest_cardiovascular_radiology_review','modality_scope':['CT'],'sources':[{'title':title,'url':url,'reviewed_at':'2026-10-06','review_status':status} for title,url,status in zip(['RA cardiovascular pearls','RA chest cardiovascular pearls','Significant incidental cardiac CT pictorial review','Nongated calcification consensus'],URLS,['effective_full_heading_and_relevant_source_scope_reviewed','effective_shared_topic_scope_reviewed','original_XML_relevant_nongated_wall_defect_and_structural_passages_reviewed','original_XML_visual_calcium_and_modality_limits_reviewed'])],
      'source_contract_sha256':digest({k:ref.get(k) for k in ('reporting','report_templates','walkthrough','reading')}),'reporting_checklist':g['checklist'],'reporting_template_sections':g['template_sections'],'structures':structures,'expansion_rules':['Every actual covered branch/variant, region/layer and lesion component needs independently reviewed CT/site/state-specific image, schematic and model evidence. Named labels are not native boundaries or full tissue coverage.','Parent heart/normal tree or a different examination/modality cannot supply actual septal, coronary, valvar, venous or pericardial disease geometry.','Unassessed/unresolved anatomy and missing temporal/calibrated data remain explicit and are not normal or zero requirements.'],
      'source_scope_issues':['Routine nongated phase/motion can overestimate wall thickness; no fixed thickness/diameter/ratio is adopted as universal clinical severity or functional diagnosis.','Visual patient-based coronary calcium burden is not coronary stenosis/CAD-RADS or automatically calibrated Agatston data. Distinguish valve/root/wall/annular calcium sites and unavailable functional severity.','Single-phase filling defects/mixing, contrast reflux, chamber size and pericardial fluid/thickening do not independently prove thrombus, pressure, EF, shunt, tamponade or constrictive physiology.','Actual pulmonary venous count/drainage, systemic venous and coronary/arch/ductal/systemic-lung connections must be traced; standard anatomy is not all variants.','Original PMC6365314/PMC7774698 grants are CC BY4, but selected figure-specific rights/pixels, native structures and full current independent clinical review remain separate pending work.'],
      'functional_evidence_requirements':['Temporal function, flow/pressure, perfusion and clinical effects require actual corresponding sources, not routine CT stills or a generic model.','Record original method/calibration, contrast/gating/motion, coverage and uncertainty for actual morphology/measurements.','Further clinical assessment is contextual, not an automatic procedure/risk or pathology diagnosis from a picture.'],
      'clinical_validation_status':'draft_requires_cardiothoracic_radiologist_and_cardiovascular_clinical_team_review'}
if __name__=='__main__':
    item=build();path=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(path.read_text());data['investigations']=[i for i in data['investigations'] if i['investigation_id']!=IDENT]+[item];data['scope']['catalog_investigation_ids']=[i['investigation_id'] for i in data['investigations']];path.write_text(json.dumps(data,indent=2)+'\n');print(len(item['structures']),'groups;',len(requirements_for(item)),'leaves;',len(requirements_for(item))*3,'representation obligations')
