#!/usr/bin/env python3
"""Reconcile the actual MRI reporting scope and assessment prompts with primary consensus."""
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
INV='ra.mri-endometriosis';PREFIX='open-endometriosis-esur-2025-'
URL='https://link.springer.com/article/10.1007/s00330-025-11611-3'
CHECKS=[
 ('Adnexa','Assess each ovary and tube separately: lesion number, location, source signal, residual parenchyma, adhesional position, tubal content and any suspected solid tissue. Record unresolved characterization.'),
 ('Anterior central compartment','Localize bladder findings to anterior/posterior dome or base/trigone; inspect the vesicouterine relationship and each proximal round ligament. Record actual wall/lumen interfaces and ureteric-orifice proximity when evaluable.'),
 ('Medial central compartment','Assess torus, each proximal uterosacral ligament, pouch of Douglas, posterior vaginal wall/fornix, rectovaginal space and external myometrial infiltration. Separate site, extent, adhesions and uncertainty.'),
 ('Posterior central compartment and bowel','Map every observed rectal/rectosigmoid lesion and each covered segment. Record source-supported mural depth, longitudinal extent, inferior margin relative to the anal verge and luminal effect; do not infer transmural invasion from tethering.'),
 ('Lateral compartments, ureters and nerves','Assess each distal round ligament, mediolateral/posterolateral parametrium, ureter and actual covered neural relationship. Trace obstruction toward the kidneys when acquired; preserve unassessed course or uncertain intrinsic/extrinsic involvement.'),
 ('Uterus and superficial disease','Assess uterus, junctional zone/myometrium and associated adenomyosis separately from external infiltration. Describe any source-observed peritoneal foci and adhesions; negative MRI does not exclude superficial endometriosis.'),
 ('Extra-pelvic sites and examination limits','Review actual covered abdominal-wall/scar, umbilical, inguinal, sigmoid, ileocaecal/appendiceal and diaphragmatic sites. Record unacquired extent, unresolved lesions and implications for complete mapping.')]
SECTIONS=[
 ('ADNEXA','Right/left ovary and tube evaluability: [ ]. Each lesion identity/site, dimensions, multiplicity and source signal: [ ]. Position/adhesional relationships: [ ]. Residual ovarian parenchyma: [ ]. Tubal calibre/content/wall: [ ]. Suspected solid tissue and actual characterization sequences: [ ]. Uncertainty: [ ].'),
 ('ANTERIOR CENTRAL COMPARTMENT','Bladder anterior dome / posterior dome-vesicouterine level / base-trigone: [ ]. Lesion site/laterality and anteroposterior extent: [ ]. Wall/lumen interface evaluability: [ ]. Ureteric-orifice distance, if evaluable: [ ]. Vesicouterine involvement: [ ]. Right/left proximal round ligament and source-supported measurements: [ ].'),
 ('MEDIAL CENTRAL COMPARTMENT','Torus and right/left proximal uterosacral site, source planes and findings: [ ]. Pouch of Douglas and adhesional relationships: [ ]. Posterior vaginal wall/fornix lesion extent: [ ]. Rectovaginal space and peritoneal-reflection relationship: [ ]. External myometrial infiltration location/extent: [ ]. Unresolved boundaries: [ ].'),
 ('POSTERIOR CENTRAL COMPARTMENT AND BOWEL','Each lesion and involved rectal/rectosigmoid segment: [ ]. Number, longitudinal length, wall thickness and inferior-margin distance to the anal verge: [ ]. Source-supported depth, luminal effect and adjacent interfaces: [ ]. Measurement planes/method and uncertainty: [ ].'),
 ('LATERAL COMPARTMENTS, URETERS AND NERVES','Right/left distal round ligament and inguinal course: [ ]. Mediolateral/posterolateral parametrium and mesorectal/pelvic-wall relationship: [ ]. Each ureter site, proximal extent and obstruction/renal coverage: [ ]. Source-resolved intrinsic/extrinsic distinction: [ ]. Actual covered obturator/lumbosacral-root/plexus/sciatic relationship: [ ]. Unassessed structures or extent: [ ].'),
 ('UTERUS AND SUPERFICIAL DISEASE','Uterine orientation, cavity, junctional zone and myometrial evaluability: [ ]. Associated internal adenomyosis description/source measurements: [ ]. Covered ovarian-fossa, mesosalpinx, pouch-of-Douglas and parietal-peritoneal observations: [ ]. Adhesions, confidence and limitations: [ ].'),
 ('EXTRA-PELVIC SITES AND LIMITATIONS','Covered abdominal wall/scars and layer interfaces, umbilicus, inguinal sites, sigmoid, ileocaecal junction/appendix and diaphragm: [ ]. Each observed lesion location/extent and adjacent relationships: [ ]. Unacquired/unassessed regions: [ ]. Unresolved mapping or characterization: [ ].')]
IMAGES=[['fig1'],['fig3','table2-a','table2-b'],['fig4','table2-c','table2-d','table2-e'],['fig5','table2-f'],['table2-g','table2-h','table2-i','table2-j','table2-k'],['fig1','table2-d'],['fig6','table2-l']]
LOOKS=[
 'Inspect both ovaries and tubes in the actual T1, fat-separated T1 and T2 source. If solid tissue is suspected, document available characterization and missing contrast/diffusion evidence; a clot or shading sign alone is not definitive exclusion of another lesion.',
 'Trace actual bladder surfaces, vesicouterine interface and bilateral proximal round ligaments in acquired multiplanar images. Locate and measure a finding only where boundaries and scale are evaluable; published source cases are separate examples.',
 'Inspect both uterosacrals in multiple actual planes, torus, peritoneal reflection, posterior vagina and retrouterine relationships. A one-plane focus or thickness alone may remain uncertain. Do not borrow a depicted source-case lesion into the current examination.',
 'Trace the covered rectum and rectosigmoid, retaining each observed lesion and source-resolved mural interface. Document actual distance/length measurement methods; a mushroom-cap appearance or contact is not calibrated histological depth.',
 'Inspect bilateral lateral compartments, distal round ligaments, parametrial tissue, actual ureteric course and acquired kidney views. Assess each covered neural relationship using the actual source; a conceptual line is not a segmented nerve or demonstrated functional impairment.',
 'Review the actual uterine cavity, junctional zone and myometrium for associated adenomyosis. Inspect covered peritoneal surfaces on appropriate sequences. Explicitly retain limited sensitivity for superficial disease.',
 'Review every actually covered extra-pelvic site and surgical scar; preserve unacquired diaphragm, bowel, wall or inguinal extent. Conclude with source-supported findings, uncertain mapping and the classification/version only if actually assessed.']
def save(path,value):path.write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n')
def integrate():
 out=ROOT/'docs/endometriosis-source-review';out.mkdir(exist_ok=True)
 p=ROOT/'data/radiology/investigation-source-images.json';pool=json.loads(p.read_text());held=out/'held-legacy-and-native-candidates.json'
 if not held.exists():save(held,{'legacy_remote_images':pool.get(INV,[]),'legacy_reason':'No independently established commercial redistribution grant for these remote source thumbnails. Local licensed originals replace this investigation use only.','native_model_candidates':[{'source':'CVH5 original pelvic U3D','existing_review':'docs/cvh5-independent-decoder-review/README.md','hold':'Whole original geometry decoder remains independently unverified; source names, candidate arrays and scene agreement do not clear it.'},{'source':'West Bohemia female pelvic templates','existing_review':'docs/west-bohemia-pelvic-source-review/README.md','hold':'Original template arrays are independently preserved, but clinical anatomical accuracy, original acquisition, units, axes and fine layer boundaries remain unverified. No clinical runtime/model coverage is granted.'}],'native_model_published':False})
 pool.pop(INV,None);save(p,pool)
 p=ROOT/'data/radiology/investigation-overrides-non-msk.json';overrides=json.loads(p.read_text());guide=overrides[INV]['reporting']
 guide.update(reviewed_at='2026-10-10',protocol=['Record actual symptoms, prior surgery, comparison, preparation and examination coverage/quality. Review acquired multiplanar high-resolution T2, T1 with appropriate fat separation, and kidney views when supplied; explicitly record missing regions or sequences.','Describe lesion characterization from sequences actually obtained. When an adnexal solid component is suspected, document available diffusion/contrast evidence and unresolved characterization; do not claim enhancement or exclusion from an unperformed sequence.'],checklist=[{'label':a,'detail':b} for a,b in CHECKS],template_sections=[{'heading':a,'body':b} for a,b in SECTIONS],measurements=[{'name':'Lesion and organ extent','method':'Measure each identified lesion in recorded evaluable source planes with actual scale: include site-specific dimensions, adnexal maximum diameter, bladder anteroposterior extent, posterior vaginal extent and affected bowel length/wall thickness.','pitfall':'Source drawings and published display pixels are not independently calibrated measurements of the current patient.'},{'name':'Surgical interface distances','method':'When evaluable in the actual examination, document inferior bowel-lesion margin to the anal verge and bladder-lesion proximity to each identified ureteric orifice, with source plane/method and uncertainty.','pitfall':'Tethering, contact, mucosal oedema or a diagram does not establish transmural invasion or supply an unobserved interface.'}],classification=None,criteria_table=None,pitfalls=['A negative or limited MRI does not exclude superficial peritoneal endometriosis.','Separate each actual lesion, side and compartment; preserved publication cases and conceptual drawings are not registered current-patient evidence.','Avoid diagnosis or extent inferred from a single uncertain plane, thickness alone, missing sequences or unassessed regions.'],impression_prompts=['Summarize the observed disease distribution, each relevant compartment/site and source-supported extent.','State important ureteric/bowel/neural relationships, unresolved characterization and examination limitations.','Record an adopted classification/version and source-supported derivation only when actually assessed; no automatic score is supplied.'],escalation=['Communicate source-supported significant ureteric obstruction or another urgent identified complication through the appropriate clinical pathway.'],sources=[{'title':'ESUR consensus MRI for endometriosis — protocol, lexicon and compartment analysis (2025)','url':URL},{'title':'Radiology Assistant — Endometriosis MRI detection','url':'https://radiologyassistant.nl/abdomen/unsorted/endometriosis-mri-detection'}])
 save(p,overrides)
 p=ROOT/'data/radiology/reporting-steps/abdomen.json';d=json.loads(p.read_text());entry=d['investigations'][INV];old=entry['steps'];new=[]
 for i,((label,detail),(heading,body),images,look) in enumerate(zip(CHECKS,SECTIONS,IMAGES,LOOKS)):
  step=copy.deepcopy(old[min(i,len(old)-1)]);step.update(label=label,detail=detail,sections=[heading],normal={heading:'Source adequacy and actual covered extent: [__]. Observed findings at each relevant site/side/interface: [__]. Recorded measurements and method where evaluable: [__]. Unassessed or unresolved structures, characterization and boundaries: [__].'},findings=['Source-supported finding at [site and side]: [__]. Actual extent, measurement method and uncertainty: [__].'],images=[PREFIX+k for k in images],measurements=['Lesion and organ extent','Surgical interface distances'] if i in [0,1,2,3,4] else [],parts=[],look=look,tip='Published figures and conceptual anatomy are source references, not observations of the current examination. Record what was actually evaluated and preserve uncertainty.')
  step['landmark']=['ovaries','bladder','cervix','rectum','uterus','uterus','uterus'][i];new.append(step)
 entry.update(start={'images':[PREFIX+'fig2',PREFIX+'fig1'],'module_illustrations':False},steps=new,preset_mode='assessment-prompts',walkthrough_reviewed_at='2026-10-10',model={'family':'female','reporting_aim':'The procedural pelvic diagram is conceptual orientation only. It is not complete source-derived ovarian, tubal, parametrial, ureteric, neural or fine uterine/bowel-wall anatomy and does not represent individual endometriosis or its surgical boundaries. Published cases and held native model candidates are independent of the current patient.'})
 save(p,d)
 print('Seven complete assessment-prompt steps bound to licensed source artwork; no unobserved normal findings.')
if __name__=='__main__':integrate()
