#!/usr/bin/env python3
"""Preserve implanted support/ECMO source projections with device-era and operational limits."""
import argparse,hashlib,json,urllib.request,xml.etree.ElementTree as E
from pathlib import Path
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/implanted-support-published-source-review';PREFIX='open-implanted-support-pmc6837777-fig';IDENT='ra.cardiovascular-devices'
META_SHA='15a56073b0074f84a70e47e573bbaa57b12806bbc95b295176f5e21958a453b8'
FDA='https://www.fda.gov/medical-devices/cardiovascular-devices/medtronic-heartware-ventricular-assist-device-hvad-system'
TITLES={1:'IABP source marker projection',2:'Jugular dual-lumen VV ECMO',3:'Separate VV ECMO cannula projections',4:'Paediatric carotid/femoral VA ECMO',5:'Paediatric Berlin Heart LV support',6:'Neonatal biventricular Berlin Heart support',7:'HeartMate II source angle/pocket annotations',8:'Source HeartMate II follow-up migration',9:'Historical HeartWare support system',10:'HeartMate III projected components',11:'Source decommissioned HeartWare system'}
SPECIFIC={1:'The original source calls for 2-cm advancement from a carinal projection. This is a historical case statement, not a current repositioning instruction or universally calibrated upper/lower balloon assessment.',2:'The source describes an Avalon jugular dual-lumen VV configuration traversing SVC/RA/IVC. The projection does not independently resolve all drainage/return sideholes, return-jet alignment or recirculation.',3:'The source describes VV cannula projections in SVC/RA. Actual drainage versus return assignment, full circuit and functional adequacy need records and appropriate imaging.',4:'Source describes paediatric VA ECMO with right carotid arterial and right femoral venous access. It is a specific source case, not an adult access template or a recommendation to place those cannulae.',5:'Source chest/abdominal a/b views describe paediatric LV inflow and aortic outflow. Separate native interfaces, complete cannula/driveline/pump geometry and performance are unverified.',6:'Source neonatal biventricular support describes LV-to-aorta and RA-to-PA components. They are distinct circuits and source anatomy; a generic adult heart cannot substitute for this case.',7:'The original 72-degree inflow angle and 11-cm pocket annotation are source HMII case measurements, not independently calibrated here or universal acceptable values for other systems.',8:'Source reports the same HMII case after one year with 2-cm cranial migration. Exact dates, projection/registration and independently calibrated interval change are not supplied.',9:'Historical HeartWare case. FDA records state HVAD sale/distribution stopped on June 3, 2021. This figure supports recognition of existing implants, not new implantation or an assertion of current common use; current advisories/serial-number conditions need actual device-team review.',10:'Source frontal/lateral HMIII projections preserve the annotated outflow/pump appearance. Full radiolucent graft, inlet/tissue interface, current model/version and performance are not independently established.',11:'Source calls this HeartWare system decommissioned and the driveline intentionally severed. This intended state must not automatically be called accidental fracture/failure or ongoing support. HVAD is a historical existing-implant example; actual decommissioning record and current patient/device status remain unverified.'}
COMMON=' Complete original publisher JPEG, views and annotations are preserved byte-identically. Full original acquisition, physical calibration, same-examination/cross-figure registration, full native/device geometry and independent clinical approval are unavailable. Static projections do not independently measure flow, pump/circuit function or current system/MRI suitability.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    root.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);mp=root/'PMC6837777.1.json'
    if not mp.exists():mp.write_bytes(urllib.request.urlopen('https://pmc-oa-opendata.s3.amazonaws.com/PMC6837777.1/PMC6837777.1.json',timeout=45).read())
    if sha(mp.read_bytes())!=META_SHA:raise ValueError('Reviewed metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/')
    if m['is_retracted'] is not False:raise ValueError('Source retraction differs')
    xml=download_verified(http(m['xml_url']),root/'PMC6837777.1.xml');x=E.fromstring(xml);perm=x.find('.//article-meta/permissions');licence,url=exact_license(perm)
    if licence!='CC BY 4.0':raise ValueError('Original grant differs')
    authors=[' '.join([e.findtext('given-names',''),e.findtext('surname','')]) for e in x.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];sources=[];rows=[];entries=[]
    for n,title in TITLES.items():
        f=x.find('.//fig[@id="F'+str(n).zfill(4)+'"]');caption=' '.join(f.find('caption').itertext())
        if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['courtesy','reproduced','reprinted','adapted']):raise ValueError('Separate figure credit requires review')
        fn=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+fn+'?' in u));raw=download_verified(u,root/fn)
        with Image.open(root/fn) as im:
            im.load();s={'figure_number':n,'source_caption':caption,'source_media_url':u,'sha256':sha(raw),'width':im.width,'height':im.height,'pixel_mode':im.mode,'decoded_pixel_sha256':sha(im.tobytes()),'publisher_md5_verified':True,'source_pixels_changed':False}
        sources.append(s);local=f'web/reference-media/radiology-open/implanted-support-pmc6837777-fig{n}.jpg';(ROOT/local).write_bytes(raw);panels=list('ab') if n in [5,9,10,11] else ['whole'];state=f'implanted_support_source_pmc6837777_fig{n}';limits=SPECIFIC[n]+COMMON
        context={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'not_reported'},'extent':'local','depicted_state':state,'selected_panels':panels,'panel_types':dict.fromkeys(panels,'Radiography'),'panel_states':dict.fromkeys(panels,state),'source_historical_hvad':n in [9,11],'source_intentionally_decommissioned':n==11,'source_reported_same_case_as_figure':7 if n==8 else None,'full_acquired_series_included':False,'independent_calibrated_measurements_verified':False,'same_series_registration_verified':False,'cross_figure_patient_identity_verified':False,'full_device_native_geometry_verified':False,'current_system_function_or_mri_conditions_verified':False,'measured_circuit_flow_or_recirculation_verified':False}
        credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Complete original publisher JPEG preserved byte-identically. Historical model/case statements are not current device instructions. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data. No endorsement implied.'
        row={'id':PREFIX+str(n),'kind':'clinical-image','modality':'Radiography','figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':s['sha256'],'width':s['width'],'height':s['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC6837777/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC6837777/#F'+str(n).zfill(4),'asset_source_url':u,'clinical_panels':panels,'source_context':context,'image_state':state,'caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':licence,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original CC BY 4.0 XML/credits and complete JPEG pixels reviewed; historical/functional scope remains explicit and anatomically unapproved.'};rows.append(row);entries.append((row,local,s))
    proof={'pmcid':'PMC6837777','doi':m['doi'],'title':m['title'],'metadata_sha256':META_SHA,'xml_sha256':sha(xml),'original_license':licence,'original_license_url':url,'permissions_xml':E.tostring(perm,encoding='unicode'),'authors':authors,'figures':sources,'historical_regulatory_context':{'url':FDA,'reviewed_at':'2026-10-06','scope':'FDA HVAD sale/distribution stop on June 3, 2021; existing-implant recognition only, not full advisory/IFU review. No FDA/manufacturer images reused.'},'clinical_approval':False,'model_promoted':False}
    path=OUT/'original-source-review.json';path.write_text(json.dumps(proof,indent=2)+'\n');proof_sha=sha(path.read_bytes());assets=[]
    for row,local,s in entries:
        assets.append({'id':row['id'],'kind':'clinical_image','name':TITLES[row['figure_number']],'local_path':local,'sha256':row['sha256'],'modality':'Radiography','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':licence,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(path.relative_to(ROOT)),'evidence_sha256':proof_sha,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':s['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Local projections do not independently verify complete circuit/device/tissue geometry, function or current suitability.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'reviewed_at':'2026-10-06','evidence_path':'docs/implanted-support-published-source-review.md'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data[IDENT] if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start)
    for i,ns in {0:list(range(2,12)),1:[2,3,4,5,6,7,9,10,11],2:[1,2,3,4,5,6,7,9,10],3:[8,11],4:[7,8,9,11]}.items():node['steps'][i]['images']=list(dict.fromkeys(node['steps'][i].get('images',[])+[PREFIX+str(n) for n in ns]))
    extra=' Identify actual ECMO drainage and return routes and documented circuit type; cannula projection alone does not establish VV/VA configuration, return-jet alignment or recirculation.'
    if extra not in node['steps'][1]['tip']:node['steps'][1]['tip']+=extra
    extra=' Distinguish documented decommissioning/intentional driveline division from unplanned discontinuity. Historical HVAD recognition is not current new-implant suitability; full device-team/advisory review is separate.'
    if extra not in node['steps'][4]['tip']:node['steps'][4]['tip']+=extra
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'figure_number':r['figure_number'],'local_path':local,'sha256':r['sha256']} for r,local,s in entries],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Eleven original LVAD/ECMO projections preserved with historical, intended-state and functional limits.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
