#!/usr/bin/env python3
"""Preserve original nongated CT calcium examples with actual pixel letters and no function/score invention."""
import argparse,hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/chest-calcification-published-source-review';IDENT='ra.ct-cardiovascular-pearls';PREFIX='open-chest-calcium-pmc7774698-fig';PIN='26f799850dbc1374fef154f6c4eb79b49fd4350cb5f12a914e28d02b32bda020'
CONFIG={3:('Coronary visual calcium examples','abcdefgh','Original a-d are unenhanced and e-h contrast-enhanced examples from different patients. Printed none/mild/moderate/severe columns are source examples of visual burden, not independently calculated Agatston data, stenosis grades or exclusion of coronary disease from a single panel.'),4:('Aortic valve calcium/site examples','abcdefghijkl','Original a-d are unenhanced, e-l contrast enhanced, with i-l reformats. Original sites/grades illustrate leaflet/root/annular differentiation. Source visual labels do not independently establish measured valve obstruction, functional severity or a validated calcium score.'),5:('Mitral leaflet versus annular calcium','ab','Original a is contrast enhanced with source mitral-leaflet dysfunction/LA enlargement/effusion context; b is unenhanced annular calcium described without clinical sequelae. Keep the different sources/phases distinct; symptoms and valve physiology are source statements, not independently derived from these two images.'),6:('Mitral calcium visual examples','abcdefgh','Original a-d are unenhanced, e-h contrast-enhanced source severity examples from different patients. No independent valve function, acquired whole-calcium burden, serial comparison or actual calibrated scoring is supplied by these grids.'),7:('Pulmonary/papillary/myocardial/pericardial calcium','abcdef','Source a is pulmonary-arterial calcium, b papillary, c/f myocardial and d/e pericardial. Renal-failure/infarct or constriction/benign source labels are not independent aetiology, pressure or physiological confirmation. Preserve the site differences; pericardial calcium alone does not diagnose constriction.')}
COMMON=' Complete original publisher JPEG/annotations unchanged. Caption letters are uppercase, actual image letters lowercase; no labels redrawn. Full raw CT series/calibration, independent cross-panel patient/phase registration, all thin tissue/vessel/valve boundaries and clinical validation are unavailable. Still grids do not supply actual 3D geometry or measured function.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    OUT.mkdir(parents=True,exist_ok=True);archive=OUT/'packaged-source-images.json';removed=json.loads(archive.read_text())['replaced_unverified_investigation_images'] if archive.exists() else detail(Curriculum(),resolve(IDENT))['radiology_reference']['key_images'];mp=root/'PMC7774698.1.json'
    if sha(mp.read_bytes())!=PIN:raise ValueError('Reviewed original metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/');xml=download_verified(http(m['xml_url']),root/'PMC7774698.1.xml');tree=E.fromstring(xml);perm=tree.find('.//article-meta/permissions');lic,url=exact_license(perm)
    if lic!='CC BY 4.0' or m['is_retracted'] is not False:raise ValueError('Original grant/retraction differs')
    authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];rows=[];entries=[];figs=[]
    for number,(title,letters,special) in CONFIG.items():
        fig=tree.find('.//fig[@id="F'+str(number)+'"]');caption=' '.join(fig.find('caption').itertext())
        if fig.find('attrib') is not None or fig.find('permissions') is not None or any(w in caption.lower() for w in ['reproduced','reprinted','courtesy','adapted','modified from']):raise ValueError('Separate figure credit requires review')
        filename=fig.find('graphic').get('{http://www.w3.org/1999/xlink}href');asset_url=http(next(u for u in m['media_urls'] if '/'+filename+'?' in u));raw=download_verified(asset_url,root/filename)
        with Image.open(root/filename) as im:im.load();proof={'figure_number':number,'source_caption':caption,'source_media_url':asset_url,'sha256':sha(raw),'decoded_pixel_sha256':sha(im.tobytes()),'width':im.width,'height':im.height,'pixel_mode':im.mode,'publisher_md5_verified':True,'source_pixels_changed':False,'complete_in_pixel_material_inspected':True}
        figs.append(proof);local='web/reference-media/radiology-open/chest-calcium-pmc7774698-fig'+str(number)+'.jpg';(ROOT/local).write_bytes(raw);phases=({l:'unenhanced' if l in 'abcd' else 'enhanced_phase_not_named' for l in letters} if number in [3,4,6] else {'a':'enhanced_phase_not_named','b':'unenhanced'} if number==5 else dict.fromkeys(letters,'not_explicitly_named'));limits=special+COMMON
        context={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'not_reported'},'extent':'local','depicted_state':'source_visual_calcium_and_site_examples','selected_panels':list(letters),'panel_types':dict.fromkeys(letters,'CT'),'panel_states':dict.fromkeys(letters,'source_visual_calcium_example'),'panel_contrast_phase':phases,'caption_uppercase_to_actual_lowercase_map':{l.upper():l for l in letters},'source_visual_grades_are_independently_derived':False,'full_native_CT_series_or_voxel_calibration_verified':False,'same_patient_or_phase_registration_verified':False,'clinical_aetiology_or_function_independently_verified':False,'complete_coronary_valve_or_pericardial_geometry_verified':False,'projection_or_still_is_actual_3D_geometry':False}
        attribution=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Complete original publisher JPEG/labels preserved byte-identically. Source visual grades and clinical labels do not constitute independent clinical approval. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data.'
        row={'id':PREFIX+str(number),'kind':'clinical-image','modality':'CT','figure_number':number,'src':'/app/'+local.removeprefix('web/'),'sha256':proof['sha256'],'width':proof['width'],'height':proof['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC7774698/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC7774698/#F'+str(number),'asset_source_url':asset_url,'clinical_panels':list(letters),'source_context':context,'image_state':'source_visual_calcium_and_site_examples','caption':'Original Figure '+str(number)+': '+title+'. '+limits,'alt':'Original Figure '+str(number)+': '+title+'. '+limits,'source_caption_full':caption,'limits':limits,'structures_visible':['Source-local '+title.lower()],'license':lic,'license_url':url,'attribution':attribution,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original grant, selected captions/credits and complete in-pixel material reviewed.'};rows.append(row);entries.append((row,local,proof))
    review={'pmcid':'PMC7774698','doi':m['doi'],'title':m['title'],'authors':authors,'metadata_sha256':PIN,'xml_sha256':sha(xml),'permissions_xml':E.tostring(perm,encoding='unicode'),'original_license':lic,'original_license_url':url,'figures':figs,'not_selected_figures':[{'figure_number':n,'reason':'Management/recommendation flowchart, not anatomical tissue/source geometry.'} for n in [1,2]],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(review,indent=2)+'\n');proof_hash=sha(proof_path.read_bytes());assets=[]
    for row,local,p in entries:assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':'CT','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':lic,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':proof_hash,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':p['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Source CT still grids do not establish complete native tissue/branch geometry, raw calibration or independent clinical function/grade.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'evidence_path':'docs/chest-calcification-published-source-review.md','reviewed_at':'2026-10-06'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data[IDENT]['key_images']=[];path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/investigation-source-images.json';raw=path.read_text()
    if '"'+IDENT+'"' in raw:
        start=raw.index('[',raw.index('"'+IDENT+'"'));old,end=json.JSONDecoder().raw_decode(raw,start);raw=raw[:start]+'[]'+raw[end:];path.write_text(raw)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));entry,end=json.JSONDecoder().raw_decode(raw,start);entry['start']={'images':[PREFIX+'3',PREFIX+'4'],'module_illustrations':False};removed_ids={r['id'] for r in removed}
    for i,numbers in {0:[5,7],1:[7],2:[3,4,5,6],3:[4,7],4:[7]}.items():entry['steps'][i]['images']=list(dict.fromkeys([id for id in entry['steps'][i].get('images',[]) if id not in removed_ids]+[PREFIX+str(n) for n in numbers]))
    path.write_text(raw[:start]+json.dumps(entry,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);archive.write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,p in entries],'replaced_unverified_investigation_images':removed,'module_lesson_or_other_investigation_media_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Five original CT calcium/location grids retained; actual lowercase labels and source phase limits explicit.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
