#!/usr/bin/env python3
"""Preserve original fixed-lung publication anatomy without mixing specimen photos, setup or diagnostic CT."""
import argparse,hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/hipct-lung-publication-source-review';IDENT='ra.hrct-lung';PREFIX='open-hipct-lung-pmc9163096-fig';PIN='5e8fab242cd4dfaab24eef9363277a304e8b97703f1dec067b09d97d5d161faf'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(source):
    OUT.mkdir(parents=True,exist_ok=True);mp=source/'PMC9163096.1.json'
    if sha(mp.read_bytes())!=PIN:raise ValueError('Reviewed original article metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/');xml=download_verified(http(m['xml_url']),source/'PMC9163096.1.xml');tree=E.fromstring(xml);perm=tree.find('.//article-meta/permissions');lic,url=exact_license(perm)
    if lic!='CC BY 4.0' or m['is_retracted'] is not False:raise ValueError('Original source grant/retraction differs')
    authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];entries=[];figures=[]
    for n in [1,3]:
        f=tree.find('.//fig[@id="Fig'+str(n)+'"]');caption=' '.join(f.find('caption').itertext())
        if f.find('attrib') is not None or f.find('permissions') is not None or any(v in caption.lower() for v in ['reproduced','reprinted','courtesy','adapted','modified from']):raise ValueError('Unreviewed figure credit')
        filename=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+filename+'?' in u));raw=download_verified(u,source/filename)
        with Image.open(source/filename) as image:
            image.load();p={'figure_number':n,'source_caption':caption,'source_media_url':u,'source_file_sha256':sha(raw),'decoded_pixel_sha256':sha(image.tobytes()),'width':image.width,'height':image.height,'pixel_mode':image.mode,'publisher_md5_verified':True,'complete_original_pixels_inspected':True,'source_pixels_changed':False}
        figures.append(p);local=f'web/reference-media/radiology-open/hipct-lung-pmc9163096-fig{n}.jpg';(ROOT/local).write_bytes(raw)
        title='Fixed left lung, preparation and source organ rendering' if n==1 else 'Source multiscale lobular/septal/vascular and nodule anatomy'
        limits=('Original a/b are anatomical specimen photographs of an excised fixed lung and its mounting jar; c is an instrument-setup schematic; d is a flat source CT volume rendering at25.08µm pitch. Selected CT panel d is distinct from a/b/c. Numeric organ labels identify left upper/lower lobes, fissure and main bronchus in this source, not full microscopic tissue geometry.' if n==1 else 'Original a-d show source sampling-volume locations; e contains flat rendered VOI4b/VOI5 views; f shows the source partially calcified spiculated nodule across25.08µm,6.5µmVOI5 and2.5µmVOI2b data, with septa and perilobular vessels. Figure-f nodule regions are not the acquired VOI03/03b review blocks; no same-local-tissue correspondence is claimed. Source vessel labels do not separately identify every artery, vein or lymphatic, and no nodule histological/benignity diagnosis is inferred.')
        limits+=' Source donor is a94-year-old woman; fixed post-mortem, formalin/70%ethanol prepared tissue is not healthy in-vivo clinical HRCT. Phase-contrast scalar values are not HU. Full anatomical labelling, effective resolution, acquired published planes/native TIFF identity and independent source-registration/clinical validation remain unverified. Flat renderings are not supplied interactive3D meshes.'
        panels=['d'] if n==1 else list('abcdef');types={'a':'Anatomical specimen photograph','b':'Anatomical specimen photograph','c':'Schematic','d':'CT'} if n==1 else dict.fromkeys(panels,'CT');context={'setting':'cadaveric','laterality':'left','population':{'life_stage':'adult'},'extent':'local','depicted_state':'fixed_left_lung_source_anatomy','selected_panels':panels,'panel_types':types,'panel_states':dict.fromkeys(panels,'fixed_left_lung_source_anatomy'),'source_donor':{'identifier':'LADAF-2020-27','age_years':94,'sex':'female'},'acquisition_subtype':'ex_vivo_hierarchical_X_ray_phase_contrast_tomography','source_preparation':'formalin fixation and70percent ethanol scanning','healthy_in_vivo_reference':False,'clinical_HU_calibration_verified':False,'complete_native_tissue_or_structure_geometry_verified':False,'flat_volume_rendering_is_interactive_3D_model':False,'microscopic_or_nodule_diagnosis_independently_verified':False}
        if n==3:context['source_nodule_panel_VOIs']=['6.5um_VOI5','2.5um_VOI2b'];context['source_nodule_is_acquired_VOI03_or_VOI03b_block']=False
        credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY4.0. Complete original publisher JPEG preserved; article figure grant distinct from raw data grant. NLM/PMC dataset snapshot may not reflect latest NLM data.'
        row={'id':PREFIX+str(n),'kind':'clinical-image','modality':'CT','figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':p['source_file_sha256'],'width':p['width'],'height':p['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC9163096/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC9163096/#Fig'+str(n),'asset_source_url':u,'clinical_panels':panels,'source_context':context,'image_state':'fixed_left_lung_source_anatomy','caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local left lung lobes/fissure/main bronchus' if n==1 else 'Source-labelled secondary lobular septa/perilobular vessels and apical nodule'],'license':lic,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-07','rights_review':'Whole original image/caption and explicit original article figure grant inspected; separate raw dataset licence not substituted.'}
        if n==1:row.update(contains_schematic_panels=True,source_schematic_panels=['c'],schematic_structures_visible=['Synchrotron imaging setup; not tissue anatomy'],ancillary_panels=[{'kind':'Anatomical specimen photograph','panels':['a','b'],'structures_visible':['Source excised fixed left lung and preparation context'],'limits':'Specimen photographs, not in-vivo CT, separately classified from rendered panel d.'}])
        entries.append((row,local,p))
    proof={'pmcid':'PMC9163096','doi':m['doi'],'title':m['title'],'authors':authors,'original_license':lic,'original_license_url':url,'original_permissions_xml':E.tostring(perm,encoding='unicode'),'metadata_sha256':PIN,'xml_sha256':sha(xml),'figures':figures,'excluded_figure2':'Acquisition/reconstruction pipeline diagram, not additional anatomical tissue evidence.','original_raw_dataset_rights_independently_approved_by_this_figure_review':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(proof,indent=2)+'\n');evidence=[]
    for row,local,p in entries:evidence.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':'CT','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':lic,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':sha(proof_path.read_bytes()),'attribution':row['attribution'],'reviewed_at':'2026-10-07'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':p['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Prepared ex-vivo source anatomy and flat renderings do not establish full native structures, current clinical patient morphology or histological nodule diagnosis.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'evidence_path':'docs/hipct-lung-publication-source-review.md','reviewed_at':'2026-10-07'}})
    path=ROOT/'data/radiology/radiology-open-images.json';d=json.loads(path.read_text());d[IDENT]=[r for r in d.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+[r for r,_,_ in entries];path.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',evidence,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start)
    for i,numbers in {0:[3],1:[1,3],2:[3],3:[3]}.items():node['steps'][i]['images']=list(dict.fromkeys(node['steps'][i].get('images',[])+[PREFIX+str(n) for n in numbers]))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,_ in entries],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False,'module_lesson_or_other_investigation_media_changed':False},indent=2)+'\n');print('Two complete original fixed-lung figures retained; specimen/setup/CT roles separate and local blocks not borrowed.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
