#!/usr/bin/env python3
"""Preserve original CE/QISS MRA cases with distinct CT/DSA panels and source-data limits."""
import argparse,hashlib,json,sys,urllib.request,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/peripheral-mra-published-source-review';IDENT='ra.mra-peripheral-vessels';PREFIX='open-peripheral-mra-'
PINS={'PMC5072342':'1cd42c5838d3afef0d92debdadd13914f485f03f6a3be2a15fda5aa785f29b68','PMC3946661':'804e28c24704fd12fcf6587c199c25eaca18139b8368179e38bc2ca6953055ae'}
CONFIG={('PMC5072342',1):('CTA/QISS local calf comparison','b','The authors rate both CTA a and QISS MRA b excellent for local popliteal/tibial/peroneal depiction. A study quality score is not independent complete vessel/lesion review or a clinical fidelity guarantee.'),('PMC5072342',2):('Popliteal occlusion and collateral comparison','b','Original a is CTA, b QISS MRA and c catheter DSA. Source describes right femoral/popliteal lesions, calcification-limited CTA calf assessment and greater DSA collateral depiction. These are method-specific views; the DSA panel is not MRI, and MRI does not independently quantify calcium or clinical perfusion.'),('PMC5072342',3):('Femoral lesion and stenosis comparison','b','Original a is CTA, b QISS MRA and c catheter DSA. Source describes right femoral occlusion and lower-leg stenoses with CTA MIP calcification overlap. The caption does not separately name every femoral branch, distal endpoint or lesion for each displayed side; no complete tree or exact severity is inferred.'),('PMC3946661',2):('CE/HR-QISS post-PTA source case',['left','right'],'Original unlettered left is CE-MRA and right HR-QISS in a source 68-year-old male after right superficial-femoral PTA. Source reports femoral/tibial disease, distal-aortic motion limitation on QISS and less venous overlay. Published greater-than-50-percent labels and treatment context are source statements, not independently calibrated severity, outcome or current device/protocol clearance.'),('PMC3946661',3):('CE/HR-QISS collateral reconstitution source case',['left','right'],'Original unlettered left is CE-MRA and right HR-QISS in a source 72-year-old male. Source describes right SFA occlusion/reconstitution via profunda collaterals and bilateral fibular/tibial and left SFA findings. The images do not independently establish flow direction, full collateral courses, pedal-arch completion, wound perfusion or limb viability.')}
COMMON=' Complete original publisher JPEG and annotations preserved without cropping, enhancement or relabelling. MIP/angiographic projections are not actual 3D models. Full raw source series, original voxel/measurement calibration, independent examination/phase/patient registration, full distal vessel/wall/lesion extent and clinical validation are unavailable.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    from primer.curriculum import Curriculum
    from primer.radiology_catalog import detail,resolve
    root.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);archive_path=OUT/'packaged-source-images.json'
    removed=json.loads(archive_path.read_text())['replaced_unverified_investigation_images'] if archive_path.exists() else detail(Curriculum(),resolve(IDENT))['radiology_reference']['key_images']
    rows=[];entries=[];sources=[]
    for ident,numbers in [('PMC5072342',[1,2,3]),('PMC3946661',[2,3])]:
        mp=root/f'{ident}.1.json'
        if not mp.exists():mp.write_bytes(urllib.request.urlopen(f'https://pmc-oa-opendata.s3.amazonaws.com/{ident}.1/{ident}.1.json',timeout=45).read())
        if sha(mp.read_bytes())!=PINS[ident]:raise ValueError('Reviewed source metadata changed')
        metadata=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/')
        if metadata['pmcid']!=ident or metadata['is_retracted'] is not False:raise ValueError('Original source identity/retraction differs')
        xml=download_verified(http(metadata['xml_url']),root/f'{ident}.1.xml');tree=E.fromstring(xml);permissions=tree.find('.//article-meta/permissions');licence,license_url=exact_license(permissions)
        if licence!='CC BY 4.0' or tree.findtext('.//article-id[@pub-id-type="doi"]')!=metadata['doi']:raise ValueError('Original article grant/DOI differs')
        authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];source={'pmcid':ident,'title':metadata['title'],'doi':metadata['doi'],'metadata_sha256':PINS[ident],'xml_sha256':sha(xml),'permissions_xml':E.tostring(permissions,encoding='unicode'),'original_license':licence,'original_license_url':license_url,'authors':authors,'figures':[]};sources.append(source)
        if ident=='PMC3946661':source['held_upstream_credit_figures']=[{'figure_number':1,'original_caption':' '.join(tree.find('.//fig[@id="pone-0091078-g001"]/caption').itertext()),'reused':False,'reason':'Pulse diagram is modified from separately cited Edelman work; no upstream derivative rights verified.'}]
        for number in numbers:
            fid='Fig'+str(number) if ident=='PMC5072342' else 'pone-0091078-g'+str(number).zfill(3);figure=tree.find('.//fig[@id="'+fid+'"]');caption=' '.join(figure.find('caption').itertext())
            if figure.find('attrib') is not None or figure.find('permissions') is not None or any(word in caption.lower() for word in ['courtesy','reproduced','reprinted','adapted','modified from','modified after']):raise ValueError('Separate source credit requires review')
            filename=figure.find('graphic').get('{http://www.w3.org/1999/xlink}href');url=http(next(u for u in metadata['media_urls'] if '/'+filename+'?' in u));raw=download_verified(url,root/filename)
            with Image.open(root/filename) as im:
                im.load();pixels={'figure_number':number,'source_caption':caption,'source_media_url':url,'sha256':sha(raw),'decoded_pixel_sha256':sha(im.tobytes()),'pixel_mode':im.mode,'width':im.width,'height':im.height,'publisher_md5_verified':True,'source_pixels_changed':False,'complete_original_pixels_and_in_pixel_credits_inspected':True}
            source['figures'].append(pixels);title,selection,special=CONFIG[(ident,number)];selection=list(selection) if isinstance(selection,str) else selection;types={'a':'CT','b':'MRI',**({'c':'Radiography'} if number>1 else {})} if ident=='PMC5072342' else {'left':'MRI','right':'MRI'};sequence_types={'b':'noncontrast_QISS'} if ident=='PMC5072342' else {'left':'contrast_enhanced_MRA','right':'noncontrast_HR_QISS'};state='peripheral_arterial_disease_source_case' if not (ident=='PMC5072342' and number==1) else 'source_image_quality_comparison';limits=special+COMMON;identifier=PREFIX+ident.lower()+'-fig'+str(number);local='web/reference-media/radiology-open/peripheral-mra-'+ident.lower()+'-fig'+str(number)+'.jpg';target=ROOT/local;target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(raw)
            context={'setting':'in_vivo','laterality':'bilateral','population':{'life_stage':'adult' if ident=='PMC3946661' else 'not_reported'},'extent':'local','depicted_state':state,'selected_panels':selection,'panel_types':types,'panel_states':dict.fromkeys(types,state),'source_MRI_sequence_types':sequence_types,'source_layout_scheme':'original_letters' if ident=='PMC5072342' else 'unlettered_left_right','source_projection_subtypes':{'c':'catheter_digital_subtraction_angiography'} if ident=='PMC5072342' and number>1 else {},'full_native_volume_and_temporal_series_included':False,'independent_calibrated_lumen_or_lesion_measurements_verified':False,'complete_patient_tree_wall_and_pedal_extent_verified':False,'cross_panel_patient_series_or_phase_registration_verified':False,'cross_figure_patient_identity_verified':False,'flow_direction_pressure_perfusion_or_viability_verified':False,'projection_is_actual_3D_geometry':False,'source_diagnosis_treatment_or_outcome_independently_verified':False}
            credit=', '.join(authors)+'. '+metadata['title']+'. DOI '+metadata['doi']+'. CC BY 4.0. Original complete publisher JPEG/annotations retained byte-identically. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data. No clinical/anatomical endorsement or protocol/device clearance implied.'
            row={'id':identifier,'kind':'clinical-image','modality':'MRI','figure_number':number,'src':'/app/'+local.removeprefix('web/'),'sha256':pixels['sha256'],'width':pixels['width'],'height':pixels['height'],'source_url':f'https://pmc.ncbi.nlm.nih.gov/articles/{ident}/','figure_url':f'https://pmc.ncbi.nlm.nih.gov/articles/{ident}/#'+fid,'asset_source_url':url,'clinical_panels':selection,'source_context':context,'image_state':state,'caption':f'Original Figure {number}: {title}. '+limits,'alt':f'Original Figure {number}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local arterial paths and annotations in '+title.lower()],'license':licence,'license_url':license_url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original article grant, selected figure credits and whole original image pixels inspected; no separate in-pixel credits detected.'}
            if ident=='PMC5072342':row['ancillary_panels']=[{'kind':kind,'panels':[panel],'structures_visible':['Source comparator arterial projection and annotations'],'limits':'Original comparison context; not MRI acquisition, registered whole-vessel anatomy or independent clinical measurement.'} for panel,kind in types.items() if panel not in selection]
            rows.append(row);entries.append((row,local,pixels))
    proof={'sources':sources,'source_pixels_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(proof,indent=2)+'\n');proof_sha=sha(proof_path.read_bytes());assets=[]
    for row,local,pixels in entries:
        assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':'MRI','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':'CC BY 4.0','url':row['license_url'],'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':proof_sha,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':pixels['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Published MRA projections are partial source cases, not native complete trees, calibrated lesions, flow/perfusion or clinical validation.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'reviewed_at':'2026-10-06','evidence_path':'docs/peripheral-mra-published-source-review.md'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());data[IDENT]['key_images']=[];path.write_text(json.dumps(data,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);q=lambda n:PREFIX+'pmc5072342-fig'+str(n);p=lambda n:PREFIX+'pmc3946661-fig'+str(n);node['start']={'images':[p(2),q(1)],'module_illustrations':False};removed_ids={r['id'] for r in removed}
    for i,ids in {0:[p(2),p(3),q(2)],1:[p(2),p(3),q(2),q(3)],2:[q(2),q(3)],3:[q(1),q(2),p(3)],4:[q(1),q(2),p(2),p(3)]}.items():node['steps'][i]['images']=list(dict.fromkeys([identifier for identifier in node['steps'][i].get('images',[]) if identifier not in removed_ids]+ids))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);archive_path.write_text(json.dumps({'figures':[{'id':row['id'],'local_path':local,'sha256':row['sha256']} for row,local,pixels in entries],'replaced_unverified_investigation_images':removed,'module_lesson_images_or_other_investigations_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Five original MRA source figures preserved; CT/DSA roles separate, modified pulse diagram held, investigation remote gallery replaced.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
