#!/usr/bin/env python3
"""Preserve complete esophageal source masters and actual modality/case boundaries."""
import hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from primer.curriculum import Curriculum
from primer import radiology_catalog as catalog
from tools.check_radiology_fidelity import digest
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];SOURCE=Path('/Users/peter/Documents/ChatGPT/Primer/.research/esophagus-clinical-source-review');INV='ra.esophagus';PREFIX='open-esophagus-pmc5438315-fig';URL='https://pmc.ncbi.nlm.nih.gov/articles/PMC5438315/'
# Actual original publication panels. Full-page diagrams are not histological acquisitions.
ROLES={2:('Schematic',[],['full'],[]),3:('CT',['a','b'],[],[]),4:('Radiography',['full'],[],[]),5:('Radiography',['full'],[],[]),6:('CT',['a'],[],[('Radiography',['b'])]),7:('CT',['full'],[],[]),8:('Radiography',['full'],[],[]),9:('CT',['full'],[],[]),10:('CT',['full'],[],[]),11:('CT',['full'],[],[]),12:('Radiography',['a','b'],[],[]),13:('Radiography',['a','b'],[],[]),14:('CT',['b'],[],[('Radiography',['a'])]),15:('CT',['a','b'],[],[]),16:('CT',['c'],[],[('Radiography',['a','b'])]),17:('CT',['full'],[],[]),18:('CT',['full'],[],[]),19:('CT',['full'],[],[]),20:('CT',['a','b'],[],[])}
STEPS={2:[],3:[0],4:[0,2],5:[0,2],6:[0,2],7:[1],8:[1,2],9:[1],10:[1,3],11:[1,4],12:[0,2],13:[0,2],14:[0,2],15:[4],16:[4],17:[4],18:[4],19:[4],20:[4]}
EXTRA={3:'Source explicitly identifies both CT windows as the same patient; window/series identity is not validated registration or aspiration mechanism.',4:'Source bird-beak appearance is a morphology example, not independent motility subtype/manometry or exclusion of pseudoachalasia.',6:'Panel a is a source carrot CT example; panel b is a different patient with endoscopically confirmed hot-dog impaction. Do not merge identities or transfer tissue confirmation.',8:'Source leiomyoma label and smooth filling defect do not independently establish current histology.',9:'The source patient was found to have hemangioma despite a phlebolith appearance commonly seen in varices. This is not a unique current-patient classifier.',10:'Source maximum-intensity projection is processed CT, not a native3D mesh, complete vessel/wall map or calibrated portal pressure.',11:'The source blue outline is a publication annotation, not a supplied segmentation mask or independent tissue-boundary approval.',14:'Source fluoroscopy and IV/oral-contrast CT views are separately identified; calibrated temporal registration is unavailable.',15:'Source explicitly identifies pre/postcontrast views of the same patient; acquisition interval is unsupplied. Source extravasation and subsequent hematemesis do not supply new bleeding-rate or management measurements.',16:'Chest radiograph, esophagram and oral-contrast CT are distinct source modalities/projections; no native registration or exact source clock is supplied.',17:'Confirmed fistula is source clinical context; this selected CT does not supply independent complete tract/pathology/current-patient confirmation.',18:'Source atrioesophageal fistula example; no current invasive procedure or unique treatment recommendation is inferred.',19:'Source prolonged-intubation context is distinct from a new patient mechanism or complete fistulous tract map.',20:'Source contrast extravasation/clotted-blood context is not new calibrated bleeding rate, pressure, histology or an independent current treatment decision.'}
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package():
    proof_path=ROOT/'docs/esophagus-published-source-review/original-source-review.json';proof=json.loads(proof_path.read_text());tree=E.fromstring((SOURCE/'PMC5438315.1.xml').read_bytes());authors=[' '.join(filter(None,[n.findtext('given-names'),n.findtext('surname')])) for n in tree.findall('.//article-meta/contrib-group/contrib/name')]
    if proof['original_article_grant']!='CC BY 4.0' or len(proof['figures'])!=19:raise ValueError('Reviewed source grant/figure set differs')
    archive=proof_path.parent/'replaced-investigation-images.json'
    if not archive.exists():archive.write_text(json.dumps({'replaced_investigation_images':catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference']['key_images'],'reason':'Remote placeholder imagery does not provide locally byte-bound original source anatomy or clinical coverage.'},indent=2)+'\n')
    old={r['id'] for r in json.loads(archive.read_text())['replaced_investigation_images']};rows=[];assets=[]
    for figure in proof['figures']:
        n=figure['figure_number'];ident=PREFIX+str(n);mode,clinical,schematic,ancillary=ROLES[n];master=SOURCE/'PMC5438315/original-PDF-masters'/figure['source_master_filename'];raw=master.read_bytes()
        if sha(raw)!=figure['source_master_sha256']:raise ValueError('Original master changed')
        with Image.open(master) as image:
            image.load()
            if sha(image.tobytes())!=figure['decoded_pixel_sha256'] or image.size!=(figure['width'],figure['height']):raise ValueError('Original decoded samples differ')
        types={p:mode for p in clinical+schematic}
        for kind,panels in ancillary:types.update({p:kind for p in panels})
        context={'setting':'illustration' if n==2 else 'in_vivo','laterality':'not_applicable','population':{'life_stage':'unknown','age_not_supplied':True,'sex_not_supplied':True},'extent':'local','depicted_state':'source_wall_layer_illustration' if n==2 else 'source_esophageal_disease_example','selected_panels':clinical+schematic,'panel_types':types,'panel_states':{p:'source_wall_layer_illustration' if n==2 else 'source_esophageal_disease_example' for p in types},'source_different_figures_assumed_same_patient':False,'source_native_registration_verified':False,'source_static_views_supply_timed_transit_or_pressure':False,'source_labels_are_current_patient_histology_or_cause':False,'source_full_microanatomical_coverage_approved':False}
        if n in [3,15]:context['source_explicit_same_patient_panels']=clinical;context['source_case_groups']={'source_explicit_single_patient':clinical}
        elif n==6:context['source_case_groups']={'source_carrot_patient':['a'],'different_source_hotdog_patient':['b']};context['source_panels_are_different_patients']=True
        else:context['source_case_groups']={f'source_panel_{p}_identity_not_independently_verified':[p] for p in types}
        local=f'web/reference-media/radiology-open/esophagus-pmc5438315-fig{n}.png';(ROOT/local).write_bytes(raw)
        attribution=', '.join(authors)+'. Imaging of the oesophagus: beyond cancer. DOI '+proof['doi']+'. Figure '+str(n)+'. CC BY4.0. Original full PDF decoded samples and ICC preserved without enhancement, cropping, resizing or relabelling. No endorsement implied.'
        limit=('Conceptual anatomy/wall-layer drawing only; no acquired histology, whole native3D geometry, every microscopic layer or functional evidence. ' if n==2 else 'Selected published source views; age, sex, acquisition timing and full original native volume/cine are not supplied. Every fine wall/nerve/vessel/gland/lesion interface, calibrated transit/pressure or matched patient3D remains unapproved. ')+EXTRA.get(n,'Source morphology or author diagnosis remains source context, not a unique current patient diagnosis or exclusion rule.')
        row={'id':ident,'kind':'schematic' if n==2 else 'clinical-image','modality':mode,'figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':sha(raw),'width':figure['width'],'height':figure['height'],'source_url':URL,'figure_url':URL+'#Fig'+str(n),'asset_source_url':'https://pmc-oa-opendata.s3.amazonaws.com/PMC5438315.1/PMC5438315.1.pdf','clinical_panels':clinical,'schematic_panels':schematic,'source_context':context,'image_state':context['depicted_state'],'caption':('Source Figure2: conceptual esophageal course and wall layers.' if n==2 else 'Source Figure'+str(n)+': '+figure['source_caption_full'].split('.')[0]+'.'),'alt':'Complete original esophageal source Figure'+str(n)+'.','limits':limit,'source_caption_full':figure['source_caption_full'],'structures_visible':['Conceptual cervical/thoracic/abdominal course and drawn wall layers'] if n==2 else ['Source-local esophageal disease and adjacent interfaces; full native boundaries unapproved'],'license':'CC BY 4.0','license_url':proof['license_url'],'attribution':attribution,'rights_reviewed_on':'2026-10-08','rights_review':'Original article CC BY4 grant and no figure-specific exception in original XML; exact numbered source/PDF layout and pixel master reviewed.'}
        if ancillary:row['ancillary_panels']=[{'kind':kind,'panels':panels,'structures_visible':['Separately identified source esophagram/chest-projection context'],'limits':'Separate source modality and projection; no borrowed contrast state, native registration, unprovided source identity or new physiological measurement.'} for kind,panels in ancillary]
        catalog._validate_source_panel_roles(row);rows.append(row)
        assets.append({'id':ident,'kind':'schematic' if n==2 else 'clinical_image','name':'Original esophageal source Figure'+str(n),'local_path':local,'sha256':sha(raw),'modality':mode,'investigation_ids':[INV],'structure_ids':[],'requirement_coverage':{},'source_context':context,'source':{'url':URL,'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':'CC BY 4.0','url':proof['license_url'],'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':sha(proof_path.read_bytes()),'attribution':attribution,'reviewed_at':'2026-10-08'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':figure['decoded_pixel_sha256'],'source_PDF_object':figure['source_PDF_object'],'source_PDF_page':figure['source_PDF_page'],'source_ICC_sha256':figure['source_ICC_sha256'],'highest_resolution_acquired_master_verified':True},'anatomical_review':{'status':'pending','reason':'Complete published figures do not establish every native reported tissue/interface, current diagnosis or physiological measurement.'}})
    p=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(p.read_text());data[INV]=[r for r in data.get(INV,[]) if not r['id'].startswith(PREFIX)]+rows;p.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    p=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(p.read_text());data[INV]['key_images']=[];p.write_text(json.dumps(data,indent=2)+'\n')
    p=ROOT/'data/radiology/investigation-source-images.json';text=p.read_text()
    if '"'+INV+'"' in text:
        start=text.index('[',text.index('"'+INV+'"'));_,end=json.JSONDecoder().raw_decode(text,start);p.write_text(text[:start]+'[]'+text[end:])
    p=ROOT/'data/radiology/reporting-steps/chest.json';text=p.read_text();start=text.index('{',text.index('"'+INV+'"'));node,end=json.JSONDecoder().raw_decode(text,start);node.setdefault('start',{}).update(images=[],module_illustrations=False)
    for s in node['steps']:s['images']=[i for i in s.get('images',[]) if i not in old and not i.startswith(PREFIX)]
    for n,indices in STEPS.items():
        for index in indices:node['steps'][index]['images'].append(PREFIX+str(n))
    p.write_text(text[:start]+json.dumps(node,indent=2).replace('\n','\n    ')+text[end:])
    for value in vars(catalog).values():
        if callable(getattr(value,'cache_clear',None)):value.cache_clear()
    ref=catalog.detail(Curriculum(),catalog.resolve(INV))['radiology_reference'];p=ROOT/'data/radiology/non-msk-structure-requirements.json';data=json.loads(p.read_text());next(r for r in data['investigations'] if r['investigation_id']==INV)['source_contract_sha256']=digest({k:ref.get(k) for k in ['reporting','report_templates','walkthrough','reading']});p.write_text(json.dumps(data,indent=2)+'\n');print('18 clinical masters and one wall-layer schematic integrated; anatomy/functional coverage not granted')
if __name__=='__main__':package()
