#!/usr/bin/env python3
"""Preserve original CMR methods/cases and distinguish source plots from raw quantitative studies."""
import argparse,hashlib,json,urllib.request,xml.etree.ElementTree as E
from pathlib import Path
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/cmr-published-source-review';IDENT='ra.mri-cardiomyopathy';PREFIX='open-cmr-source-'
PINS={'PMC7066763':'70c8d1443ce7438dd8e4bbce05276776568821c832b306f8ef42e7774b206080','PMC11084160':'b017f68d1e04f1e1fa6ef4e7b2b5163a16c8dc963fe3b39953b21a41331c0a89'}
SCMR={1:('LV contour and papillary conventions','abcd'),2:('RV contour and plane conventions','abcd'),3:('Perfusion defect/artefact and ROI examples','abc'),4:('Source magnitude-LGE nulling comparison','left right'),6:('Source STIR oedema example','whole'),7:('Source T2-star image/fit comparison','AC'),8:('Source phase-contrast image/curve example','top'),9:('Source repaired aorta/branch MRA','abc')}
CASES={1:('Source hypertrophic phenotype','abcdefgh'),2:('Source amyloid phenotype','abcdefghi'),3:('Source genetically reported Fabry case','abcdefghijkl'),4:('Source biventricular arrhythmogenic phenotype','abcdefghi'),5:('Source thalassaemia/iron assessment','abcdeghi')}
BASE=' Complete original publisher JPEG, contours/labels/colour scales/graphs are unchanged. Full native cine, raw quantitative source images, independent physical/ROI calibration, clinical/pathology or genetic correspondence and source registration are unavailable. No EF, flow, map/ECV value, histology or patient-specific 3D geometry is independently derived from this picture.'
SPECIAL_S={1:'Source a/b includes papillary muscles in the LV blood pool; c/d excludes them. These are source conventions illustrated with ED/ES grids, not all acquired cine phases or independently validated volume/EF/mass data.',2:'Source a/b are transaxial RV contour grids, c/d short-axis grids with LV context. Source slices/ED/ES examples do not independently supply complete actual temporal coverage, basal-valve correction or measured biventricular function.',3:'Source a is labelled a perfusion defect, b a dark-band artefact and c contours/ROI. Appearance/time/width explanations are source context; these stills are not a dynamic perfusion study or measured myocardial blood flow.',4:'Original unlettered left/right magnitude-LGE pictures illustrate a source inversion-time change. This is not a universal TI, PSIR rule or independently registered/calibrated scar extent. The original instruction remains source evidence, not an automatic acquisition recommendation.',6:'Source STIR image includes myocardial/reference contours and is labelled acute myocarditis. Full coverage, signal-ratio calibration and independent diagnostic criteria are unavailable.',7:'Actual pixel letters are uppercase A-E. A/C are TE-labelled MRI grids; B/D/E are original tables/decay graphs, not acquired anatomy. Printed fit values/truncation and normal labels are source examples, not independently recomputed T2-star or universal diagnostic thresholds.',8:'Original unlettered top magnitude/phase grid and bottom flow curves remain whole. Phase columns are representative/grouped, not the full native 20-phase acquisition. Printed Qp/Qs 2 and indexed flow values are source annotations, not independent measurements or full shunt validation.',9:'Source MRA a/b/c depicts repaired ascending aorta and persistent dissection/branch findings. These local images are ancillary case context; full vessel wall/lumen, perfusion or operative correspondence are independently unverified.'}
SPECIAL_C={1:'Source a contains two SSFP subviews; b is T2-weighted, c/d T1 maps, e ECV picture and f-h LGE. A source HCM diagnosis is not independently validated from stills; full regional wall/stalk/temporal or quantitative data are unavailable.',2:'Source SSFP a-c, T1 maps d/e, ECV f and LGE g-i illustrate a source amyloid phenotype. Printed 17-mm thickness, map colours and claimed diagnostic pattern are not independent calibration, histology or amyloid subtype confirmation.',3:'Source says genetic diagnosis was obtained; the genetic record is not supplied/independently verified. SSFP a-c, T2 d, T1 e/f, T2 g, ECV h and LGE i-l remain original static examples, not a raw calibrated map/cine study.',4:'Source SSFP a/b, possible fat c, maps/ECV d-f and LGE g-i show the authors\' biventricular arrhythmogenic interpretation. Fat/bulging or pattern alone is not independently confirmed multi-criterion diagnosis, motion or genetics.',5:'Source SSFP a-c, T2-star image/map d/e, plotted decay f and native T1 g-i are retained. The caption combines hepatic iron concentration in mg/g with T2-star wording without a liver image; that dimensional/context ambiguity is not silently converted into a relaxation-time measurement. Source cardiac/liver iron/T1 statements and thresholds require actual raw acquisition/reference/clinical evidence.'}
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    root.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);rows=[];entries=[];proofs=[]
    for ident,config in [('PMC7066763',SCMR),('PMC11084160',CASES)]:
        mp=root/f'{ident}.1.json'
        if not mp.exists():mp.write_bytes(urllib.request.urlopen(f'https://pmc-oa-opendata.s3.amazonaws.com/{ident}.1/{ident}.1.json',timeout=45).read())
        if sha(mp.read_bytes())!=PINS[ident]:raise ValueError('Reviewed metadata differs')
        m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/')
        if m['is_retracted'] is not False:raise ValueError('Source retraction differs')
        xml=download_verified(http(m['xml_url']),root/f'{ident}.1.xml');x=E.fromstring(xml);perm=x.find('.//article-meta/permissions');licence,url=exact_license(perm)
        if licence!='CC BY 4.0':raise ValueError('Original grant differs')
        authors=[' '.join([e.findtext('given-names',''),e.findtext('surname','')]) for e in x.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];p={'pmcid':ident,'doi':m['doi'],'title':m['title'],'metadata_sha256':PINS[ident],'xml_sha256':sha(xml),'original_license':licence,'original_license_url':url,'permissions_xml':E.tostring(perm,encoding='unicode'),'authors':authors,'figures':[]}
        if ident=='PMC7066763':p['upstream_credit_figures_held']=[{'figure_number':n,'source_caption':' '.join(x.find('.//fig[@id="Fig'+str(n)+'"]/caption').itertext()),'reused':False,'reason':'Modified/adapted from separately cited upstream work; original commercial derivative rights not verified here.'} for n in [5,10]]
        proofs.append(p)
        for n,(title,selection) in config.items():
            fid='Fig'+str(n) if ident=='PMC7066763' else 'jcm-13-02621-f'+str(n).zfill(3);f=x.find('.//fig[@id="'+fid+'"]');caption=' '.join(f.find('caption').itertext())
            if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['courtesy','reproduced','reprinted','adapted','modified from']):raise ValueError('Separate credit requires review')
            fn=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+fn+'?' in u));raw=download_verified(u,root/fn)
            with Image.open(root/fn) as im:
                im.load();s={'figure_number':n,'source_caption':caption,'source_media_url':u,'sha256':sha(raw),'width':im.width,'height':im.height,'pixel_mode':im.mode,'decoded_pixel_sha256':sha(im.tobytes()),'publisher_md5_verified':True,'source_pixels_changed':False}
            p['figures'].append(s);id=PREFIX+ident.lower()+'-fig'+str(n);local='web/reference-media/radiology-open/'+id.removeprefix('open-')+'.jpg';(ROOT/local).write_bytes(raw)
            selected=selection.split() if ' ' in selection else ['whole'] if selection=='whole' else ['top'] if selection=='top' else list(selection)
            plots=list('BDE') if ident=='PMC7066763' and n==7 else ['bottom'] if ident=='PMC7066763' and n==8 else ['f'] if ident=='PMC11084160' and n==5 else []
            letters=list('ABCDE') if ident=='PMC7066763' and n==7 else ['top','bottom'] if ident=='PMC7066763' and n==8 else selected+plots;types={k:('Plot' if k in plots else 'MRI') for k in letters};state=f'cmr_source_{ident.lower()}_fig{n}';limits=(SPECIAL_S if ident=='PMC7066763' else SPECIAL_C)[n]+BASE
            context={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'not_reported'},'extent':'local','depicted_state':state,'selected_panels':selected,'panel_types':types,'panel_states':dict.fromkeys(letters,state),'source_graphical_panels':plots,'source_native_temporal_or_quantitative_data_included':False,'full_original_acquisition_verified':False,'independent_calibrated_function_or_mapping_verified':False,'source_case_diagnosis_independently_verified':False,'patient_phase_or_series_registration_verified':False,'full_myocardial_layer_geometry_verified':False,'source_layout_schemes':'unlettered_left_right' if ident=='PMC7066763' and n==4 else 'unlettered_top_bottom' if ident=='PMC7066763' and n==8 else 'original_pixel_labels','source_caption_metric_context_ambiguity':ident=='PMC11084160' and n==5}
            credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Complete original publisher JPEG/annotations preserved byte-identically. Printed source measurements/diagnoses are not independent clinical approval. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data. No endorsement implied.'
            row={'id':id,'kind':'clinical-image','modality':'MRI','figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':s['sha256'],'width':s['width'],'height':s['height'],'source_url':f'https://pmc.ncbi.nlm.nih.gov/articles/{ident}/','figure_url':f'https://pmc.ncbi.nlm.nih.gov/articles/{ident}/#'+fid,'asset_source_url':u,'clinical_panels':selected,'source_context':context,'image_state':state,'caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':licence,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original grant/figure credits and complete image pixels reviewed; adapted source exceptions held and raw-data/function limits explicit.'}
            if plots:row.update(contains_schematic_panels=True,schematic_structures_visible=['Original source signal/flow plots, not anatomical geometry'])
            rows.append(row);entries.append((row,local,s))
    proof={'sources':proofs,'source_pixels_changed':False,'clinical_approval':False,'model_promoted':False};path=OUT/'original-source-review.json';path.write_text(json.dumps(proof,indent=2)+'\n');proof_sha=sha(path.read_bytes());assets=[]
    for row,local,s in entries:
        assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':'MRI','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':'CC BY 4.0','url':row['license_url'],'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(path.relative_to(ROOT)),'evidence_sha256':proof_sha,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':s['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Source still grids, maps and graphs are not complete native temporal/quantitative geometry or independent clinical validation.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'reviewed_at':'2026-10-06','evidence_path':'docs/cmr-published-source-review.md'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);sc=lambda n:PREFIX+'pmc7066763-fig'+str(n);ca=lambda n:PREFIX+'pmc11084160-fig'+str(n);node['start']={'images':[sc(1),sc(4)],'module_illustrations':False}
    for i,ids in {0:[sc(1),sc(2),sc(8)],1:[sc(1),sc(2),*[ca(n) for n in range(1,6)]],2:[sc(6),sc(7),*[ca(n) for n in range(1,6)]],3:[sc(4),*[ca(n) for n in range(1,5)]],4:[sc(8),sc(9),ca(2)]}.items():node['steps'][i]['images']=list(dict.fromkeys(node['steps'][i].get('images',[])+ids))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,s in entries],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Thirteen complete CMR source figures preserved; adapted credits held and quantitative/motion limits explicit.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
