#!/usr/bin/env python3
"""Preserve source QISS variants/perforators with original annotations and separate patients."""
import argparse,hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/peripheral-perforator-published-source-review';IDENT='ra.mra-peripheral-vessels';PREFIX='open-peripheral-perforator-pmc9964888-fig';PIN='012506f33ec80c95e112f85df999a4216749eca7bc22a67a6a3b1d00ede20147'
CONFIG={1:('Source venous/metal/stair-step/slab artefacts','abcd','Source a shows venous overlap, b metal-associated signal loss, c stair-step and d slab-intensity variation. The caption explicitly says motion artefact is not displayed because it needs serial transverse slices. Signal loss is not automatically occlusion or safe device-lumen assessment.'),2:('Source lower-leg vessel quality examples','abcd','The caption calls this a schematic illustration of scores, but actual pixels are four axial MR examples with original circles. Research visibility grades are not anatomical diagrams, measured lumen walls or independent clinical fidelity thresholds.'),3:('Source branching/hypoplastic tibial variants','abc','Source a shows posterior tibial first with fibular/anterior tibial common trunk, labelled Kim type I-C; b right and c bilateral hypoplastic posterior tibial arteries. FA in this source means fibular artery, not femoral artery. Source foot supply/dominance is not independently measured pressure, flow direction or viability.'),4:('Source fibular perforator examples','ab','Source a is axial and b sagittal/perforator projection; the caption says these belong to two different patients. Do not join them into one complete vessel or registered 3D route.'),6:('Source posterior tibial occlusion/reconstitution','whole','Original bracket marks source left posterior tibial occlusion and arrow a stair-step artefact. Source interprets distal refill from fibular artery and cautions against harvesting it in that case. This remains authors’ surgical-context interpretation, not independent measured flow, a universal rule or procedure recommendation.'),8:('Source perforator/septal/cutaneous relationships','abcd','Source a/b shows a 62-year-old male and c/d a 49-year-old male. Red lines mark source perforator courses; yellow b marks posterolateral intermuscular septum. These local axial views/annotations are not complete septal, cutaneous or perforator volume and are not registered across patients.')}
COMMON=' Complete original publisher JPEG/labels are unchanged. Full native source series/temporal coverage, independent calibration/registration, all tissue/vessel boundaries, true acquired 3D geometry and independent clinical review are unavailable.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    OUT.mkdir(parents=True,exist_ok=True);mp=root/'PMC9964888.1.json'
    if sha(mp.read_bytes())!=PIN:raise ValueError('Reviewed source metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/');xml=download_verified(http(m['xml_url']),root/'PMC9964888.1.xml');tree=E.fromstring(xml);permissions=tree.find('.//article-meta/permissions');lic,url=exact_license(permissions)
    if lic!='CC BY 4.0' or m['is_retracted'] is not False or tree.findtext('.//article-id[@pub-id-type="doi"]')!=m['doi']:raise ValueError('Original identity/grant differs')
    authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];rows=[];sources=[];records=[]
    for number,(title,selection,special) in CONFIG.items():
        fid='jcm-12-01634-f'+str(number).zfill(3);fig=tree.find('.//fig[@id="'+fid+'"]');caption=' '.join(fig.find('caption').itertext())
        if fig.find('attrib') is not None or fig.find('permissions') is not None or any(w in caption.lower() for w in ['reproduced','courtesy','reprinted','modified from','adapted from']):raise ValueError('Separate figure rights require review')
        filename=fig.find('graphic').get('{http://www.w3.org/1999/xlink}href');source_url=http(next(u for u in m['media_urls'] if '/'+filename+'?' in u));raw=download_verified(source_url,root/filename)
        with Image.open(root/filename) as im:im.load();proof={'figure_number':number,'source_caption':caption,'sha256':sha(raw),'decoded_pixel_sha256':sha(im.tobytes()),'width':im.width,'height':im.height,'pixel_mode':im.mode,'source_media_url':source_url,'publisher_md5_verified':True,'source_pixels_changed':False,'whole_in_pixel_material_inspected':True}
        sources.append(proof);local='web/reference-media/radiology-open/peripheral-perforator-pmc9964888-fig'+str(number)+'.jpg';(ROOT/local).write_bytes(raw);panels=list(selection) if selection!='whole' else ['whole'];state='source_anatomical_variant_or_quality_example' if number!=6 else 'source_occlusion_reconstitution_example';limits=special+COMMON
        patients=({'a':'source_case_A','b':'source_case_B'} if number==4 else {'a':'source_age62_case','b':'source_age62_case','c':'source_age49_case','d':'source_age49_case'} if number==8 else dict.fromkeys(panels,'not_independently_identified'))
        context={'setting':'in_vivo','laterality':'left' if number==6 else 'bilateral' if number==3 else 'not_reported','population':{'life_stage':'adult' if number==8 else 'not_reported'},'extent':'local','depicted_state':state,'selected_panels':panels,'panel_types':dict.fromkeys(panels,'MRI'),'panel_states':dict.fromkeys(panels,state),'source_panel_patient_groups':patients,'source_modality':'QISS_MRA_source_examples','source_FA_abbreviation':'fibular_artery','source_caption_calls_schematic_but_pixels_are_MRI_quality_examples':number==2,'full_native_volume_or_series_included':False,'independent_calibrated_measurements_verified':False,'same_examination_or_cross_patient_registration_verified':False,'complete_vessel_wall_perforator_or_tissue_geometry_verified':False,'flow_perfusion_dominance_or_viability_verified':False,'operative_suitability_independently_verified':False,'projection_or_annotation_is_actual_3D_geometry':False}
        attribution=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Original complete publisher JPEG retained byte-identically. Source research scores and operative statements are not independent clinical approval. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data.'
        row={'id':PREFIX+str(number),'kind':'clinical-image','modality':'MRI','figure_number':number,'src':'/app/'+local.removeprefix('web/'),'sha256':proof['sha256'],'width':proof['width'],'height':proof['height'],'clinical_panels':panels,'source_context':context,'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC9964888/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC9964888/#'+fid,'asset_source_url':source_url,'image_state':state,'caption':'Original Figure '+str(number)+': '+title+'. '+limits,'alt':'Original Figure '+str(number)+': '+title+'. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'source_background':'white','license':lic,'license_url':url,'attribution':attribution,'rights_reviewed_on':'2026-10-06','rights_review':'Original grant, selected captions/credits and full in-pixel material inspected; no separate restrictive credits found.'};rows.append(row);records.append((row,local,proof))
    review={'pmcid':'PMC9964888','doi':m['doi'],'title':m['title'],'authors':authors,'metadata_sha256':PIN,'xml_sha256':sha(xml),'permissions_xml':E.tostring(permissions,encoding='unicode'),'original_license':lic,'original_license_url':url,'figures':sources,'not_selected_figures':[{'figure_number':5,'reason':'Population/location boxplot, not acquired anatomical geometry.'},{'figure_number':7,'reason':'Operative skin marking and source safety distances are not native MRI anatomy or universal clearance.'}],'noncommercial_pedal_source_not_reused':{'pmcid':'PMC10713136','metadata_sha256':'ab42d4b56ec7ed488852ad427db609e0fb5c7dc95bdf9d29213fc6d5a4e9ceb8','original_license':'CC BY-NC 4.0','reused':False},'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(review,indent=2)+'\n');proof_hash=sha(proof_path.read_bytes());assets=[]
    for row,local,p in records:assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':'MRI','investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':lic,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':proof_hash,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':p['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Source research MRI stills/annotations do not supply native complete branch/tissue geometry, quantified physiology or clinical validation.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'evidence_path':'docs/peripheral-perforator-published-source-review.md','reviewed_at':'2026-10-06'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));entry,end=json.JSONDecoder().raw_decode(raw,start)
    for i,numbers in {1:[3,6],2:[6],3:[3,4,6,8],4:[1,2,4,8]}.items():entry['steps'][i]['images']=list(dict.fromkeys(entry['steps'][i].get('images',[])+[PREFIX+str(n) for n in numbers]))
    path.write_text(raw[:start]+json.dumps(entry,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,p in records],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Six original MRI variant/perforator/artefact figures retained; noncommercial pedal source excluded.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
