#!/usr/bin/env python3
"""Copy exact original and lossless browser movie, preserving presentation chronology."""
import argparse,hashlib,json,sys
from pathlib import Path
from fractions import Fraction
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from primer.source_motion import validate_motion_references
ROOT=Path(__file__).resolve().parents[2];PROOF=ROOT/'docs/swallowing-dynamic-source-review';ID='swallowing-pmc9188511-mri-montage';INV='ra.swallowing'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(source):
    p=PROOF/'original-movie-review.json';review=json.loads(p.read_text());raw=(source/review['source']['file']).read_bytes();browser=(source/'browser-lossless.webm').read_bytes()
    if sha(raw)!=review['source']['sha256'] or review['source']['license']!='CC BY 4.0':raise ValueError('Original movie/rights changed')
    original=[l.split(',')[-1].strip() for l in (source/'original-RGB-frame-sha256.txt').read_text().splitlines() if not l.startswith('#')]
    decoded=[l.split(',')[-1].strip() for l in (source/'browser-RGB-frame-sha256.txt').read_text().splitlines() if not l.startswith('#')]
    if original!=decoded or len(original)!=64 or original!=[r['decoded_RGB_sha256'] for r in review['frames']]:raise ValueError('Original decoded RGB frames differ')
    probe=json.loads((source/'browser-probe.json').read_text());frames=[r for r in probe['frames'] if r['media_type']=='video'];source_times=[float(Fraction(r['presentation_timestamp_fraction_seconds'])) for r in review['frames']];transport_times=[float(r['best_effort_timestamp_time']) for r in frames];error=max(abs(a-b) for a,b in zip(source_times,transport_times))
    if len(frames)!=64 or error>0.001:raise ValueError('Transport chronology changed')
    out=ROOT/'web/reference-media/radiology-motion';out.mkdir(exist_ok=True);original_name=ID+'-original.mp4';browser_name=ID+'-lossless.webm';(out/original_name).write_bytes(raw);(out/browser_name).write_bytes(browser)
    transport={'original_movie_review_sha256':sha(p.read_bytes()),'original_movie_sha256':sha(raw),'browser_movie_sha256':sha(browser),'decoded_RGB_frame_sha256':decoded,'all_64_decoded_RGB_frames_unchanged':True,'source_pts_seconds':source_times,'transport_pts_seconds':transport_times,'maximum_transport_timestamp_rounding_seconds':error,'frames_added_removed_resized_cropped_or_enhanced':False,'clinical_or_anatomical_approval':False};tp=PROOF/'browser-transport-review.json';tp.write_text(json.dumps(transport,indent=2)+'\n')
    attribution=', '.join(review['source']['authors'])+'. Dynamic MRI of swallowing. DOI '+review['doi']+'. Original Supplementary ESM2, CC BY4.0. Browser adaptation: lossless VP9 transport, all64 decoded RGB frames unchanged; container timestamp rounding below1ms. Original MPEG4 movie retained.'
    caption='Published MRI teaching montage from a healthy-volunteer source cohort. Individual subject identity, age and sex are not supplied. Seven sagittal-style panels in source reading order; this is a separate research case, not this examination’s VFSS.'
    limits='Stored MRI grid2×2×6mm and seven slices. Sliding-window combination and temporal regularisation mean the published≈12fps reconstruction is not independent12fps sampling. Display movie frames are not raw MRI intensities/affines or validated 3D tissue labels. No source phase classification, aspiration exclusion, pressure, unique mechanism, current-patient registration or clinical/anatomical coverage is approved. Source supplement says Figure6 while the article links Figure4; discrepancy retained.'
    row={'id':ID,'title':'Dynamic MRI research reference · separate source','modality':'MRI','src':'/app/reference-media/radiology-motion/'+browser_name,'sha256':sha(browser),'original_src':'/app/reference-media/radiology-motion/'+original_name,'original_sha256':sha(raw),'width':1233,'height':1084,'frames':64,'source_pts_seconds':source_times,'transport_pts_seconds':transport_times,'max_transport_timestamp_error_seconds':0.001,'decoded_RGB_frames_unchanged':True,'source_url':review['source']['article_URL'],'license_url':review['source']['license_URL'],'caption':caption,'limits':limits,'attribution':attribution,'reference_only':True,'clinical_approval':False,'anatomical_approval':False,'structure_ids':[],'requirement_coverage':{},'motion_context':{'source_pmcid':'PMC9188511','current_patient_registered':False,'modality_is_primary_VFSS':False,'independent_12_fps_sampling_verified':False,'native_3D_tissue_geometry_verified':False,'individual_patient_age_or_sex_verified':False},'source_proof_path':str(p.relative_to(ROOT)),'transport_proof_path':str(tp.relative_to(ROOT))}
    path=ROOT/'data/radiology/source-motion-references.json';data=json.loads(path.read_text()) if path.exists() else {};data[INV]=[r for r in data.get(INV,[]) if r['id']!=ID]+[row];validate_motion_references(data,{INV},ROOT/'web');path.write_text(json.dumps(data,indent=2)+'\n')
    ledger_path=ROOT/'data/radiology/radiology-asset-evidence.json';ledger=json.loads(ledger_path.read_text());assets=[]
    for tag,name,payload,evidence in [('original',original_name,raw,p),('transport',browser_name,browser,tp)]:
        assets.append({'id':ID+'-'+tag,'kind':'source_motion_reference','reference_only':True,'name':'Published source MRI movie · '+tag,'local_path':'web/reference-media/radiology-motion/'+name,'sha256':sha(payload),'investigation_ids':[INV],'structure_ids':[],'requirement_coverage':{},'source':{'url':row['source_url'],'license':{'name':'CC BY 4.0','url':row['license_url'],'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(p.relative_to(ROOT)),'evidence_sha256':sha(p.read_bytes()),'attribution':attribution,'reviewed_at':'2026-10-08'}},'anatomical_review':{'status':'pending','reason':'MRI montage and temporal reconstruction do not establish every fine structure or clinically validated event.'}})
    ledger['reference_rights_assets']=[r for r in ledger.get('reference_rights_assets',[]) if not r['id'].startswith(ID+'-')]+assets;ledger_path.write_text(json.dumps(ledger,indent=2)+'\n');print('Original and lossless source movie registered; all64 decoded frames retained, no clinical coverage')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
