#!/usr/bin/env python3
"""Preserve original cardiac mimic/thrombus images without inventing modality, motion or geometry."""
import argparse,hashlib,json,urllib.request,xml.etree.ElementTree as E
from pathlib import Path
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/cardiac-mimic-published-source-review';IDENT='ra.cardiac-masses';PREFIX='open-cardiac-mimic-pmc10818366-fig'
META_SHA='b9f09b029eedc17fa0e30599b7c6846193c1fe1c3cba272490d28806de72e904'
CONFIG={1:('Coumadin ridge','Ultrasound','whole',{}),2:('Prominent crista terminalis','MRI','ab',{}),3:('Prominent Eustachian remnant','Ultrasound','whole',{}),4:('RV muscular ridge and source MR map','MRI','abc',{}),5:('Lipomatous interatrial septum','CT','whole',{}),6:('Lipomatous septum with source FDG uptake','CT','ab',{'PET-CT':['d']}),7:('Source appendage thrombus','CT','b',{'Ultrasound':['a']}),8:('Source infarct-related LV thrombus','MRI','whole',{}),9:('Source mitral vegetation','CT','cd',{'Ultrasound':['a']}),10:('Source prosthetic aortic vegetation','Ultrasound','whole',{}),11:('Source catheter-associated endocarditis','CT','b',{'Ultrasound':['a']}),12:('Mitral annular calcification','CT','a',{}),13:('Pericardial cyst','MRI','ab',{}),14:('Partially thrombosed coronary aneurysm','CT','ab',{})}
SPECIFIC={1:'Source TEE still shows a Coumadin/atrial ridge. A local plane does not prove its complete relation to the appendage/pulmonary vein or motion; source-like tissue is not independent exclusion of a superimposed lesion.',2:'Source a is a cine-labelled MRI still and b T1-weighted. Actual temporal series and complete ridge extent/attachments are unavailable.',3:'Source TEE still depicts an Eustachian remnant. Complete IVC/atrial attachment, variant anatomy and mobility are not independently resolved.',4:'Source MRI a/b/c are cine-labelled still, LGE and T2-map picture. The original colour scale is preserved but raw mapping acquisitions, sequence calibration, quantitative ROI and temporal motion are not supplied.',5:'Source CT depicts lipomatous septal thickening. Complete fossa/atrial contour, clinical effect and independent tissue/diagnostic validation remain unverified.',6:'Source a/b are CT, c flat CT VR and d PET/CT fusion. Uptake in source-described lipomatous tissue is not automatic malignancy. No SUV calibration or actual 3D geometry is derived from the picture.',7:'Source a is TEE and b CT, both retained. Source calls the finding appendage thrombus; actual phase/timing, complete lesion/attachment geometry, clinical confirmation and independent registration are unavailable.',8:'Source LGE MRI still describes LV thrombus related to infarction. Full lesion extent, source temporal function, inversion/timing calibration and independent diagnostic confirmation are unavailable.',9:'Source a is 2D TEE, b a rendered 3D TEE picture and c/d CT. The complete rendered echo panel is preserved but is not acquired native geometry or a temporal study. Clinical/microbiological diagnosis and full thin-valve/vegetation interfaces are not independently proven.',10:'Source TEE still describes prosthetic aortic endocarditic vegetation. This picture does not independently establish all prosthetic/leaflet interfaces, infection criteria or physiology.',11:'Source a is TEE and b CT of catheter-associated endocarditis. Complete catheter/lesion attachment, clinical/microbiological confirmation and same-examination correspondence remain unverified.',12:'Source a is precontrast CT; b is called a cine sequence without an explicit modality in the caption. Panel b is retained with unresolved modality and is not selected as confirmed MRI or temporal evidence. Annular/caseous tissue or functional diagnosis cannot be inferred from one plane.',13:'Source MRI a/b are T2 STIR and LGE views of a pericardial cyst. Full wall/communication and all contrast/temporal details are unavailable; imaging pattern is not universal histology.',14:'Source a/b are CT planes; c/d flat CT volume renderings. Complete coronary wall/lumen/thrombus, fistula or functional consequences are not established; no native mesh is inferred from VR.'}
COMMON=' Complete original publisher JPEG/labels are unchanged. Full original acquisitions, independent voxel/measurement calibration, phase/registration/cross-figure patient correspondence and complete anatomical/clinical review remain unavailable. Static source patterns do not independently establish histology, dynamic function or complete 3D anatomy.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    root.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);mp=root/'PMC10818366.1.json'
    if not mp.exists():mp.write_bytes(urllib.request.urlopen('https://pmc-oa-opendata.s3.amazonaws.com/PMC10818366.1/PMC10818366.1.json',timeout=45).read())
    if sha(mp.read_bytes())!=META_SHA:raise ValueError('Reviewed source metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/')
    if m['is_retracted'] is not False:raise ValueError('Source retraction differs')
    xml=download_verified(http(m['xml_url']),root/'PMC10818366.1.xml');x=E.fromstring(xml);perm=x.find('.//article-meta/permissions');licence,url=exact_license(perm)
    if licence!='CC BY 4.0':raise ValueError('Original grant differs')
    authors=[' '.join([e.findtext('given-names',''),e.findtext('surname','')]) for e in x.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];sources=[];entries=[];rows=[]
    for n,(title,modality,clinical,anc) in CONFIG.items():
        f=x.find('.//fig[@id="medicina-60-00070-f'+str(n).zfill(3)+'"]');caption=' '.join(f.find('caption').itertext())
        if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['courtesy','reproduced','reprinted','adapted']):raise ValueError('Separate figure credit requires review')
        fn=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+fn+'?' in u));raw=download_verified(u,root/fn)
        with Image.open(root/fn) as im:
            im.load();s={'figure_number':n,'source_caption':caption,'source_media_url':u,'sha256':sha(raw),'width':im.width,'height':im.height,'pixel_mode':im.mode,'decoded_pixel_sha256':sha(im.tobytes()),'publisher_md5_verified':True,'source_pixels_changed':False}
        sources.append(s);local=f'web/reference-media/radiology-open/cardiac-mimic-pmc10818366-fig{n}.jpg';(ROOT/local).write_bytes(raw);selected=['whole'] if clinical=='whole' else list(clinical);letters=['whole'] if n in [1,3,5,8,10] else list('abcd') if n in [6,9,14] else list('abc') if n==4 else list('ab');types=dict.fromkeys(letters,modality)
        for kind,panels in anc.items():
            for p in panels:types[p]=kind
        if n==9:types['b']='Ultrasound'
        if n==12:types['b']='Not specified'
        state=f'cardiac_mimic_source_pmc10818366_fig{n}';limits=SPECIFIC[n]+COMMON
        context={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'not_reported'},'extent':'local','depicted_state':state,'selected_panels':selected,'panel_types':types,'panel_states':dict.fromkeys(letters,state),'source_ct_volume_rendering_panels':['c'] if n==6 else list('cd') if n==14 else [],'source_3d_echo_rendering_panels':['b'] if n==9 else [],'unresolved_modality_panels':['b'] if n==12 else [],'source_cine_labelled_static_panels':['a'] if n in [2,4] else ['b'] if n==12 else [],'full_acquired_series_included':False,'native_temporal_motion_acquired':False,'independent_quantitative_map_or_suv_verified':False,'same_series_registration_verified':False,'cross_figure_patient_identity_verified':False,'full_lesion_attachment_geometry_verified':False,'independent_clinical_or_histological_diagnosis_verified':False,'flat_renderings_are_actual_3d_geometry':False}
        ancillary=[{'kind':kind,'panels':panels,'structures_visible':['Source-described '+title.lower()],'limits':'Separate source modality panels are not the primary acquired anatomy or a complete temporal/quantitative study.'} for kind,panels in anc.items()]
        credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Complete original publisher JPEG preserved byte-identically; source diagnostic captions are not independent approval. NLM/PMC Article Dataset snapshot; may not reflect latest NLM data. No endorsement implied.'
        row={'id':PREFIX+str(n),'kind':'clinical-image','modality':modality,'figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':s['sha256'],'width':s['width'],'height':s['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC10818366/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC10818366/#medicina-60-00070-f'+str(n).zfill(3),'asset_source_url':u,'clinical_panels':selected,'ancillary_panels':ancillary,'source_context':context,'image_state':state,'caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':licence,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original XML/credits and complete JPEG pixels inspected; static, mixed and unresolved roles explicit; clinical review pending.'};rows.append(row);entries.append((row,local,s))
    proof={'pmcid':'PMC10818366','doi':m['doi'],'title':m['title'],'metadata_sha256':META_SHA,'xml_sha256':sha(xml),'original_license':licence,'original_license_url':url,'permissions_xml':E.tostring(perm,encoding='unicode'),'authors':authors,'figures':sources,'source_main_figure_count':len(x.findall('.//fig')),'unresolved_modality_figures':[12],'clinical_approval':False,'model_promoted':False,'source_pixels_changed':False,'noncommercial_other_article_images_not_reused':'PMC9558634'}
    path=OUT/'original-source-review.json';path.write_text(json.dumps(proof,indent=2)+'\n');proof_sha=sha(path.read_bytes());assets=[]
    for row,local,s in entries:
        assets.append({'id':row['id'],'kind':'clinical_image','name':CONFIG[row['figure_number']][0],'local_path':local,'sha256':row['sha256'],'modality':row['modality'],'investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':licence,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(path.relative_to(ROOT)),'evidence_sha256':proof_sha,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':s['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Local still/projection/rendered panels do not independently establish complete attachment/lesion anatomy, motion, quantitative maps or diagnosis.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'reviewed_at':'2026-10-06','evidence_path':'docs/cardiac-mimic-published-source-review.md'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['start']={'images':[PREFIX+'2',PREFIX+'7'],'module_illustrations':False}
    for i,ns in {0:list(range(1,15)),1:[2,4,7,8,9,13,14],2:[4,5,6,8,12,13,14],3:[2,4,6,8,13],4:[9,10,11,14]}.items():node['steps'][i]['images']=list(dict.fromkeys(node['steps'][i].get('images',[])+[PREFIX+str(n) for n in ns]))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'figure_number':r['figure_number'],'local_path':local,'sha256':r['sha256']} for r,local,s in entries],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False,'remaining_source_figures_not_packaged':list(range(15,39))},indent=2)+'\n');print('Fourteen original mimic/thrombus/related figures preserved; remaining source neoplasm figures still outstanding.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
