#!/usr/bin/env python3
"""Preserve source CXR cases with CT comparator roles, normal-looking view limits and unresolved cases held."""
import argparse,hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/chest-radiograph-published-source-review';IDENT='ra.chest-radiography';PREFIX='open-cxr-original-'
PINS={'PMC5621990':'782186b9ccfb3bd4a1a2f1e85044329a741188b85249b192dca80d42edaa92ab','PMC12679500':'77a431926d1fe5039528795bb879ef5a47c7e3da0665dcc211c672abcc884bd0'}
XR='Radiography'
CONFIG={
 'PMC5621990':{
 1:('Retrosternal clear space and source oedema examples',{'a':XR,'b':XR},'Source a has a normal retrosternal clear space, not independent whole-patient normality. Source b has reticular opacity and effusions with source oedema context; appearance alone is not a measured pressure or unique aetiology.'),
 2:('Retrosternal mass and right-heart source comparisons',{'a':XR,'b':'CT','c':XR,'d':'CT'},'a/b and c/d are two different source cases: mediastinal mass versus source right-ventricular/pulmonary-artery enlargement. Keep comparator modalities and patients distinct. No pressure, EF, shunt or histology is independently derived.'),
 3:('Source chronic hypersensitivity case and CT comparison',{'a':XR,'b':'CT'},'Source53-year-old woman with chronic HP. a lateral radiograph and b sagittal CT are source correspondences, not independently registered full series or confirmation of exposure causality.'),
 4:('Source fibrosis hidden by projected structures',{'a':'CT','b':XR,'c':'CT'},'Source68-year-old man with IPF. Radiograph b shows retrosternal reticulation while CTa/c shows source basilar disease. Apparent absence at an overlapping radiographic site is not exclusion or a complete burden measurement.'),
 5:('Separate source fine-line and reticular examples',{'a':XR,'b':XR},'Source a is63-year-old asymptomatic man with normal-labelled radiograph; b is a different67-year-old man with unclassified pulmonary fibrosis. These are separate people, not a disease-progression pair.'),
 6:('Abnormal lateral and source-normal frontal view',{'a':'CT','b':XR,'c':XR},'Source67-year-old man with CT fibrosis a; b lateral shows anterior changes while c frontal is source-labelled normal. Normal-looking c does not mean a normal patient or exclude disease visible on other sources.'),
 7:('Source IPF across lateral and CT views',{'a':XR,'b':'CT','c':'CT'},'Source84-year-old woman with IPF. Lateral a has retrosternal opacity without depicting the full basilar CTb/c pattern. Whole native disease extent, raw calibration and independent histological classification are unavailable.'),
 8:('Source lymphangitic case and CT comparison',{'a':XR,'b':'CT'},'Source62-year-old woman with metastatic adenocarcinoma/lymphangitic context. Lateral a and CTb retain original source septal appearances; no independent malignancy/pathology confirmation or complete nodal/whole-lung extent is inferred.'),
 9:('Normal-labelled frontal view with abnormal lateral/CT',{'a':XR,'b':XR,'c':'CT','d':'CT'},'Source55-year-old male smoker. a frontal is source-normal, b lateral abnormal, CTc/d shows emphysema and source-suspected DIP ground glass. Original caption c axial/d sagittal conflicts with actual c sagittal/d axial pixels; preserve the mismatch. No whole normality, definite histology or new phase/calibration is inferred.')},
 'PMC12679500':{
 14:('Source enteric-tube projected position examples',{'A':XR,'B':XR},'OriginalA is an upper-abdominal/lower-thoracic field and B a chest/upper-abdominal field. Source-labelled gastric tip projections do not independently establish complete intraluminal3D course, absence of wall complications, calibration or same-patient registration.'),
 15:('Source right-airway enteric-tube malposition',{'A':XR},'Actual single panelA label is retained even though caption has no letter breakdown. Source-labelled right bronchial malposition is a projected source example; complete entry-to-tip route, exact branch/site, consequences and treatment are not independently confirmed.')}}
COMMON=' Whole original publisher JPEG/labels preserved. Raw native series, exact AP/PA/position and scanner calibration are not verified unless explicitly stated by the source. Selected stills do not prove complete tissue/wall/branch anatomy or an interactive3D model; independent clinical review remains pending.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    OUT.mkdir(parents=True,exist_ok=True);archive=OUT/'packaged-source-images.json';removed=json.loads(archive.read_text())['replaced_investigation_images'] if archive.exists() else detail(Curriculum(),resolve(IDENT))['radiology_reference']['key_images'];rows=[];entries=[];sources=[]
    for pmc,config in CONFIG.items():
        mp=root/(pmc+'.1.json')
        if sha(mp.read_bytes())!=PINS[pmc]:raise ValueError('Reviewed original metadata differs')
        m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/');xml=download_verified(http(m['xml_url']),root/(pmc+'.1.xml'));tree=E.fromstring(xml);perm=tree.find('.//article-meta/permissions');lic,url=exact_license(perm)
        if lic!='CC BY 4.0' or m['is_retracted'] is not False:raise ValueError('Original source grant/retraction differs')
        authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];source={'pmcid':pmc,'title':m['title'],'doi':m['doi'],'authors':authors,'metadata_sha256':PINS[pmc],'xml_sha256':sha(xml),'permissions_XML':E.tostring(perm,encoding='unicode'),'license':lic,'license_url':url,'figures':[]};sources.append(source)
        if pmc=='PMC12679500':source['held_figures']=[{'number':1,'reason':'In pixels original arrow points near proximal neck entry, not the claimed distal-tip marker. Correct-source tip assertion not independently established.','reused':False},{'number':16,'reason':'Original noncontrastCT label is uncertain against apparent vascular opacification; no native phase/whole-route/perforation confirmation.','reused':False}]
        for n,(title,types,limit) in config.items():
            fid=('FIG' if pmc=='PMC12679500' else 'Fig')+str(n);f=tree.find('.//fig[@id="'+fid+'"]');caption=' '.join(f.find('caption').itertext())
            if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['reproduced','reprinted','courtesy','adapted','modified from']):raise ValueError('Unreviewed separate figure credit')
            name=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+name+'?' in u));raw=download_verified(u,root/name)
            with Image.open(root/name) as im:im.load();pixels={'figure_number':n,'source_caption':caption,'source_media_url':u,'sha256':sha(raw),'decoded_pixel_sha256':sha(im.tobytes()),'width':im.width,'height':im.height,'pixel_mode':im.mode,'publisher_MD5_verified':True,'complete_in_pixel_material_inspected':True,'source_pixels_changed':False}
            source['figures'].append(pixels);local=f'web/reference-media/radiology-open/cxr-original-{pmc.lower()}-fig{n}.jpg';(ROOT/local).write_bytes(raw);selected=[p for p,t in types.items() if t==XR];state='source_chest_projection_case_examples';c={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'adult' if pmc=='PMC5621990' and n in [3,4,5,6,7,8,9] else 'not_reported'},'extent':'local','depicted_state':state,'selected_panels':selected,'panel_types':types,'panel_states':dict.fromkeys(selected,state),'raw_series_or_calibration_verified':False,'full_native_anatomy_or_3D_route_verified':False,'source_disease_or_normality_independently_confirmed':False,'independent_comparator_registration_verified':False}
            if pmc=='PMC5621990':
                if n in [1,5]:c['source_normal_label_does_not_apply_to_pathology_comparator']=True;c['panel_states']['a']='normal_anatomical_reference'
                if n==2:c['source_case_groups']={'mediastinal_mass':list('ab'),'right_heart_PA_enlargement':list('cd')}
                if n in [6,9]:c['source_normal_frontal_does_not_exclude_other_view_or_CT_disease']=True;c['panel_states']['c' if n==6 else 'a']='normal_appearing_projection'
                if n==9:c['actual_CT_planes_vs_caption_mismatch']={'c':'actual_sagittal_caption_axial','d':'actual_axial_caption_sagittal'}
            if pmc=='PMC12679500':c['source_panel_scope']='projected_device_examples_only';c['same_patient_or_native_route_verified']=False
            limits=limit+COMMON;credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY4.0. Complete original publisher JPEG preserved; source findings do not constitute independent clinical approval. NLM/PMC dataset snapshot may not reflect latest NLM data.'
            row={'id':PREFIX+pmc.lower()+'-fig'+str(n),'kind':'clinical-image','modality':XR,'figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':pixels['sha256'],'width':pixels['width'],'height':pixels['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/'+pmc+'/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/'+pmc+'/#'+fid,'asset_source_url':u,'clinical_panels':selected,'source_context':c,'image_state':state,'caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':lic,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-07','rights_review':'Original figure grant/caption/complete pixels inspected; no separate figure credit. Modalities/case labels/mismatches retained.'}
            if any(t=='CT' for t in types.values()):row['ancillary_panels']=[{'kind':'CT','panels':[p for p,t in types.items() if t=='CT'],'structures_visible':['Source case cross-sectional comparator anatomy'],'limits':'CT is a separate acquisition and not a radiographic field, full registered native series or independently confirmed pathology.'}]
            rows.append(row);entries.append((row,local,pixels))
    proof={'sources':sources,'source_pixels_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(proof,indent=2)+'\n');assets=[]
    for row,local,p in entries:assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':XR,'investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':'CC BY 4.0','url':row['license_url'],'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':sha(proof_path.read_bytes()),'attribution':row['attribution'],'reviewed_at':'2026-10-07'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':p['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Selected projections/CT comparators do not establish full native anatomy, clinical causes, calibration or3D device routes.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'evidence_path':'docs/chest-radiograph-published-source-review.md','reviewed_at':'2026-10-07'}})
    path=ROOT/'data/radiology/radiology-open-images.json';d=json.loads(path.read_text());d[IDENT]=[r for r in d.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(path.read_text());d[IDENT]['key_images']=[];path.write_text(json.dumps(d,indent=2)+'\n')
    path=ROOT/'data/radiology/investigation-source-images.json';raw=path.read_text()
    if '"'+IDENT+'"' in raw:
        start=raw.index('[',raw.index('"'+IDENT+'"'));old,end=json.JSONDecoder().raw_decode(raw,start);path.write_text(raw[:start]+'[]'+raw[end:])
    r=lambda n:PREFIX+'pmc5621990-fig'+str(n);t=lambda n:PREFIX+'pmc12679500-fig'+str(n);path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node.setdefault('start',{})['images']=[r(1),r(6)];node['start']['module_illustrations']=False;removed_ids={i['id'] for i in removed}
    for i,ids in {0:[r(1),r(6)],1:[r(1),r(2)],2:[r(3),r(4),r(5),r(6),r(7),r(8),r(9)],3:[r(1)],4:[t(14),t(15)]}.items():node['steps'][i]['images']=list(dict.fromkeys([id for id in node['steps'][i].get('images',[]) if id not in removed_ids]+ids))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);archive.write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,p in entries],'replaced_investigation_images':removed,'module_lesson_or_other_investigation_media_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Eleven original source figures retained; CT comparisons and normal-view caveats explicit; unresolved device cases held.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
