#!/usr/bin/env python3
"""Preserve original thoracic TB source cases with real modalities, population and chronology; no lab inference."""
import argparse,hashlib,json,sys,xml.etree.ElementTree as E
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from PIL import Image
from primer.curriculum import Curriculum
from primer.radiology_catalog import detail,resolve
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/thoracic-tb-published-source-review';IDENT='ra.tuberculosis';PREFIX='open-thoracic-tb-pmc11449295-fig';PIN='df05d12221e19cf551d1af3ce1b3ba51e7fe4e7ab57861142465e6ca35997966'
R='Radiography';C='CT';U='Ultrasound';M='MRI'
CONFIG={
 1:(R,{'A':R,'B':M},'Child pulmonary/paraspinal source comparison','Source3-year-old girl; B contrast-enhanced T1MRI is distinct from frontal radiographA. Spine destruction/abscess and pulmonary source labels do not independently establish culture, genotype or full native spinal/airway anatomy.'),
 2:(R,{'A':R,'B':R,'C':R,'D':C},'Source cavity, scar and fungal-ball sequence','Source88-year-old man: A initial, B2years later, C5years later; D CT fungal-ball appearance. These stated intervals are retained without independent registration, exact per-frame age or lab confirmation. Scar does not itself establish noninfectivity.'),
 3:(C,{'A':R,'B':C,'C':C},'Source nodular and tree-in-bud comparisons','Source61-year-old woman. RadiographA and CTB/C are distinct acquired source views, not interchangeable resolution or independently registered whole-series burden.'),
 4:(C,{'A':C,'B':C},'Source tree-in-bud, cavity and traction airways','Source30-year-old man. Original CT pattern/annotations retained; tree-in-bud/cavitation is not unique for TB, timing, viability or resistance.'),
 5:(C,{'A':R,'B':C,'C':C},'Source fibrocalcific and nodal comparison','Source84-year-old man. Source Ranke-complex/scar/calcium labels do not independently prove past/cleared infection, noninfectivity or absence of coexisting active disease.'),
 6:(C,{'A':R,'B':C},'Source miliary pattern across radiography and CT','Source67-year-old woman. Tiny nodules have a differential; selected views do not measure full burden or prove organism or microscopic dissemination.'),
 7:(C,{'A':C,'B':C,'C':C},'Source cavity and fungal-ball phase examples','Source69-year-old man. A lung window, B unenhanced, C enhanced source images preserve phase roles. No new calibrated enhancement measurement, microbial confirmation or tumour exclusion is independently inferred.'),
 9:(C,dict(zip('ABCDEFG',[R,R,R,C,C,C,C])),'Source miliary/effusion and regional nodal sequence','Source24-year-old man: radiographB7days after A, Cafter drainage; CTDinitial and E/F5days later, Gabdominal contrast-enhanced source. Preserve differing timelines/coverage; observed response and fluid are not independently proven organism, treatment success or full disease extent.'),
 10:(U,{'A':U,'B':U,'C':U},'Pleural ultrasound in three source patients','A85-year-old woman, B59-year-old man, C60-year-old man. Three different patients, not progression. Fluid/septa/pleural thickening and needle annotations do not independently establish fluid chemistry, TB culture or complete native pleural geometry.'),
 11:(C,{'A':R,'B':C,'C':C,'D':C},'Source pericardial and pleural comparison','Source81-year-old man. Enlarged radiographic silhouette and CTfluid/thickening preserve source findings; neither pressure, tamponade, organism nor full functional effect is measured from these stills.'),
 12:(C,{'A':C,'B':C},'Source empyema/fistula and chest-wall extension','Source47-year-old woman. A lung window/Bsoft-tissue window CT source suspected tract/extent retained. No independent whole native fistulous tract, clinical diagnosis or lab proof is supplied.'),
 13:(C,{'A':C,'B':C,'C':C,'D':C},'Source pericardial versus coronary calcium','Source79-year-old man. A/Bunenhanced,C/Denhanced at source corresponding levels. Pericardial calcium/source atrial size suggests morphology, not confirmed constrictive physiology, pressure or unique TB cause.'),
 16:(U,{'A':R,'B':U,'C':R},'Source axillary node US and mammographic comparison','Source56-year-old woman: A/CrightMLOmammograms, BcolourDopplerUS; C1year after source therapy. Source aspiration/AFB result is text, not independently imaged microbiology, genotype or resistance. Mammography is not chest radiography and comparison is not a quantified treatment response.')}
COMMON=' Complete original publisher JPEG/annotations preserved. Source TB labels and ages describe these cases, not the current reader patient or independent clinical confirmation. Full native series, measurement/calibration, all microscopic/tissue/branch boundaries, complete3D models and anatomical validation remain unavailable.'
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(source_root):
    OUT.mkdir(parents=True,exist_ok=True);archive=OUT/'packaged-source-images.json';removed=json.loads(archive.read_text())['replaced_investigation_images'] if archive.exists() else detail(Curriculum(),resolve(IDENT))['radiology_reference']['key_images'];mp=source_root/'PMC11449295.1.json'
    if sha(mp.read_bytes())!=PIN:raise ValueError('Original reviewed metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/');xml=download_verified(http(m['xml_url']),source_root/'PMC11449295.1.xml');tree=E.fromstring(xml);perm=tree.find('.//article-meta/permissions');lic,url=exact_license(perm)
    if lic!='CC BY 4.0' or m['is_retracted'] is not False:raise ValueError('Original grant/retraction differs')
    authors=[' '.join([n.findtext('given-names',''),n.findtext('surname','')]) for n in tree.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];rows=[];entries=[];figures=[]
    for n,(primary,types,title,special) in CONFIG.items():
        f=tree.find('.//fig[@id="tzae031-F'+str(n)+'"]');caption=' '.join(f.find('caption').itertext())
        if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['courtesy','reproduced','reprinted','adapted','modified from']):raise ValueError('Separate figure credit requires review')
        name=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+name+'?' in u));raw=download_verified(u,source_root/name)
        with Image.open(source_root/name) as im:im.load();p={'figure_number':n,'source_caption':caption,'source_media_url':u,'sha256':sha(raw),'decoded_pixel_sha256':sha(im.tobytes()),'width':im.width,'height':im.height,'pixel_mode':im.mode,'publisher_MD5_verified':True,'complete_original_pixels_inspected':True,'source_pixels_changed':False}
        figures.append(p);local=f'web/reference-media/radiology-open/thoracic-tb-pmc11449295-fig{n}.jpg';(ROOT/local).write_bytes(raw);selected=[k for k,v in types.items() if v==primary];state='source_thoracic_TB_case_examples'.lower();c={'setting':'in_vivo','laterality':'not_reported','population':{'life_stage':'immature' if n==1 else 'adult'},'extent':'local','depicted_state':state,'selected_panels':selected,'panel_types':types,'panel_states':dict.fromkeys(selected,state),'source_labels_are_independent_lab_confirmation':False,'genotype_viability_infectivity_or_resistance_verified':False,'full_native_anatomical_or_3D_extent_verified':False,'independent_comparison_registration_or_calibration_verified':False}
        if n==2:c['source_time_groups']={'initial':['A'],'two_year_follow_up':['B'],'five_year_follow_up':['C'],'CT_source':['D']}
        if n==7:c['source_CT_phase_roles']={'A':'lung_window','B':'unenhanced','C':'enhanced'}
        if n==9:c['source_time_groups']={'initial_CXR':['A'],'seven_day_CXR':['B'],'after_drainage_CXR':['C'],'initial_CT':['D'],'five_day_CT':['E','F'],'abdominal_CT':['G']}
        if n==10:c['source_patient_groups']=[{'panels':['A'],'age_years':85,'sex':'female'},{'panels':['B'],'age_years':59,'sex':'male'},{'panels':['C'],'age_years':60,'sex':'male'}]
        if n==13:c['source_CT_phase_roles']={'A':'unenhanced','B':'unenhanced','C':'enhanced','D':'enhanced'}
        if n==16:c['projection_subtype']={'A':'right_MLO_mammography','C':'right_MLO_mammography'};c['source_time_groups']={'initial_mammogram':['A'],'US_source':['B'],'one_year_follow_up_mammogram':['C']};c['source_biopsy_AFB_result_is_image_derived']=False
        limits=special+COMMON;credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY4.0. Complete original publisher JPEG preserved; source labels do not grant clinical approval. NLM/PMC dataset snapshot may not reflect latest NLM data.'
        row={'id':PREFIX+str(n),'kind':'clinical-image','modality':primary,'figure_number':n,'src':'/app/'+local.removeprefix('web/'),'sha256':p['sha256'],'width':p['width'],'height':p['height'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC11449295/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC11449295/#tzae031-F'+str(n),'asset_source_url':u,'clinical_panels':selected,'source_context':c,'image_state':state,'caption':f'Original Figure {n}: {title}. '+limits,'alt':f'Original Figure {n}: {title}. '+limits,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':lic,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-07','rights_review':'Original article grant, selected whole captions/pixels reviewed; separate courtesy figures held.'}
        other=set(types.values())-{primary}
        if other:row['ancillary_panels']=[{'kind':kind,'panels':[k for k,v in types.items() if v==kind],'structures_visible':['Source separately acquired comparator anatomy'],'limits':'Actual different modality/source; not primary acquisition, matched whole native series or independent diagnostic proof.'} for kind in sorted(other)]
        rows.append(row);entries.append((row,local,p))
    held=[{'figure_number':n,'source_caption':' '.join(tree.find('.//fig[@id="tzae031-F'+str(n)+'"]/caption').itertext()),'reason':'Separate courtesy credit requires scope/permission review; not reused.','runtime_promoted':False} for n in [8,14,15]];proof={'pmcid':m['pmcid'],'doi':m['doi'],'title':m['title'],'authors':authors,'metadata_sha256':PIN,'xml_sha256':sha(xml),'permissions_xml':E.tostring(perm,encoding='unicode'),'original_license':lic,'original_license_url':url,'figures':figures,'held_figures':held,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False};proof_path=OUT/'original-source-review.json';proof_path.write_text(json.dumps(proof,indent=2)+'\n');assets=[]
    for row,local,p in entries:assets.append({'id':row['id'],'kind':'clinical_image','name':row['caption'].split('. ')[0],'local_path':local,'sha256':row['sha256'],'modality':row['modality'],'investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':lic,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(proof_path.relative_to(ROOT)),'evidence_sha256':sha(proof_path.read_bytes()),'attribution':row['attribution'],'reviewed_at':'2026-10-07'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':p['decoded_pixel_sha256'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Source stills/comparators do not establish full native tissue, all lesions/branches, lab proof or clinical approval.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'evidence_path':'docs/thoracic-tb-published-source-review.md','reviewed_at':'2026-10-07'}})
    path=ROOT/'data/radiology/radiology-open-images.json';d=json.loads(path.read_text());d[IDENT]=[r for r in d.get(IDENT,[]) if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(path.read_text());d[IDENT]['key_images']=[];path.write_text(json.dumps(d,indent=2)+'\n')
    path=ROOT/'data/radiology/investigation-source-images.json';raw=path.read_text()
    if '"'+IDENT+'"' in raw:
        start=raw.index('[',raw.index('"'+IDENT+'"'));old,end=json.JSONDecoder().raw_decode(raw,start);path.write_text(raw[:start]+'[]'+raw[end:])
    path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node.setdefault('start',{}).update(images=[PREFIX+'3',PREFIX+'4'],module_illustrations=False);removed_ids={r['id'] for r in removed}
    for i,numbers in {0:[1,2,3,4,6,7],1:[3,4,6,9],2:[5,9,16],3:[9,10,11,12,13],4:[2,5,7,9,13,16]}.items():node['steps'][i]['images']=list(dict.fromkeys([id for id in node['steps'][i].get('images',[]) if id not in removed_ids]+[PREFIX+str(n) for n in numbers]))
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);archive.write_text(json.dumps({'figures':[{'id':r['id'],'local_path':local,'sha256':r['sha256']} for r,local,p in entries],'replaced_investigation_images':removed,'module_lesson_or_other_investigation_media_changed':False,'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Thirteen original thoracic TB figures preserved with actual modality/population/phase/time groups; courtesy figures held.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
