#!/usr/bin/env python3
"""Preserve original support-device CT/radiographs/schematics and disclose creator processing/conflicts."""
import argparse,hashlib,json,urllib.request,xml.etree.ElementTree as E
from pathlib import Path
from PIL import Image
from tools.anatomy_sources.acquire_adrenal_published_figures import download_verified
from tools.anatomy_sources.acquire_pancreatitis_vascular_figures import exact_license
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'docs/cardiac-support-published-source-review';IDENT='ra.cardiovascular-devices';PREFIX='open-cardiac-support-pmc10350447-fig'
META_SHA='4280adb2c61750553f42fd835f60ec74d73b7d285a69efe8b2b2c6211812a5d5'
VENDOR='https://www.livanova.com/cannulae/en-us/specialty-cannulae'
CONFIG={1:('Support-route schematics','Schematic','','abc'),2:('IABP markers and length mismatch','CT','cd','ab'),3:('Low IABP and visceral complications','CT','bc','a'),4:('Axillary IABP before/after malposition','Radiography','ab',''),5:('Transaxillary left Impella source position','CT','b','a'),6:('High Impella and ECMO contrast distribution','CT','b','a'),7:('Impella and papillary apparatus entanglement','CT','b','a'),8:('Source-described aortic dissection with Impella','CT','whole',''),9:('Low Impella and ventricular/pericardial complication','CT','b','a'),10:('Source Impella RP projection','Radiography','whole',''),11:('Source custom right-sided Impella 5.5 configuration','Radiography','whole',''),12:('Protek Duo and thoracic complication example','CT','b','a')}
CLAHE={4:list('ab'),6:['a'],7:['a'],10:['whole'],12:['a']}
LIMITS={1:'All a/b/c panels are conceptual route drawings, not acquired imaging or actual device CAD. Original illustrator signatures/UR Medicine credit marks remain visible; source acknowledgements name Nazdezhda D. Kiriyak and Jane Lichorowic, Medical Illustrators, URMC.',
 2:'Source a/b are chest/abdomen radiographs, c/d CT. The source describes lower-marker/length mismatch despite an apparently acceptable upper projection. The 5-cm CT distance and vertebral levels are source case context, not independently calibrated or universal acceptable targets.',
 3:'Source a radiograph and b/c CT describe low balloon position, visceral ostial obstruction and caecal complication. Full branch perfusion and the causal clinical diagnosis are source-reported, not independently quantified from stills.',
 4:'Source a/b are before/after attempted advancement with different malpositions. Both radiographs were CLAHE processed by the creators. Dates, registration, original unprocessed images and complete arterial route are unavailable.',
 5:'Source a radiograph and b CT show a left-sided configuration. The original 3.5-cm recommendation is Impella CP context; it is not a universal depth for other models. Independent source calibration/current IFU conformity are unverified.',
 6:'Source a is creator-CLAHE radiography, b CT. The source attributes unusual aortic/LV opacification to concurrent VA ECMO. Single-phase distribution does not independently measure flow or prove the full patient/device configuration.',
 7:'Source a is creator-CLAHE radiography, b CT. Local papillary entanglement is source-described and may not be visible on projection; no complete papillary/chordal geometry or pump function is independently established.',
 8:'Complete source noncontrast CT panel describes displaced intimal calcification compatible with dissection. Full flap/lumen geometry, extent and haemodynamics are not supplied.',
 9:'Source a radiograph and b CT describe low placement, wall perforation and haemopericardium. Static density/effusion does not independently establish tamponade or complete wall/device trajectory.',
 10:'Complete creator-CLAHE radiograph shows source Impella RP with source-described IVC inlet/PA outflow. This is a local case/configuration, not proof of every port, complete current system or functional performance.',
 11:'The source describes a custom right-sided placement of an LV Impella 5.5 through a PA graft. This is a reported nonstandard surgical configuration, not a routine approved right-support indication or implantation instruction; procedural/current manufacturer evidence is not supplied.',
 12:'Source a is creator-CLAHE radiography and b CT. The caption says an outlet should be in the RV, conflicting with the article table/body and current manufacturer RA drainage/MPA return description. Original wording is preserved in source evidence; do not adopt that RV-outlet sentence as a normal target. Model/version/actual port assignment and clinical cause of effusion/haemothorax require separate evidence.'}
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package(root):
    root.mkdir(parents=True,exist_ok=True);OUT.mkdir(parents=True,exist_ok=True);mp=root/'PMC10350447.1.json'
    if not mp.exists():mp.write_bytes(urllib.request.urlopen('https://pmc-oa-opendata.s3.amazonaws.com/PMC10350447.1/PMC10350447.1.json',timeout=45).read())
    if sha(mp.read_bytes())!=META_SHA:raise ValueError('Reviewed metadata differs')
    m=json.loads(mp.read_text());http=lambda u:u.replace('s3://pmc-oa-opendata/','https://pmc-oa-opendata.s3.amazonaws.com/')
    if m['is_retracted'] is not False:raise ValueError('Source retraction changed')
    xml=download_verified(http(m['xml_url']),root/'PMC10350447.1.xml');x=E.fromstring(xml);perm=x.find('.//article-meta/permissions');licence,url=exact_license(perm)
    if licence!='CC BY 4.0':raise ValueError('Original grant differs')
    authors=[' '.join([e.findtext('given-names',''),e.findtext('surname','')]) for e in x.findall('.//article-meta/contrib-group/contrib[@contrib-type="author"]/name')];ack=' '.join(x.find('.//ack').itertext());sources=[];rows=[];entries=[]
    for n,(title,modality,clinical,other) in CONFIG.items():
        f=x.find('.//fig[@id="Fig'+str(n)+'"]');caption=' '.join(f.find('caption').itertext())
        if f.find('attrib') is not None or f.find('permissions') is not None or any(w in caption.lower() for w in ['courtesy','reproduced','reprinted','adapted']):raise ValueError('Separate credit requires review')
        fn=f.find('graphic').get('{http://www.w3.org/1999/xlink}href');u=http(next(u for u in m['media_urls'] if '/'+fn+'?' in u));raw=download_verified(u,root/fn)
        with Image.open(root/fn) as im:
            im.load();s={'figure_number':n,'source_caption':caption,'source_media_url':u,'publisher_md5_verified':True,'sha256':sha(raw),'width':im.width,'height':im.height,'pixel_mode':im.mode,'decoded_pixel_sha256':sha(im.tobytes()),'source_pixels_changed':False,'source_creator_CLAHE_panels':CLAHE.get(n,[])}
        sources.append(s);local=f'web/reference-media/radiology-open/cardiac-support-pmc10350447-fig{n}.jpg';(ROOT/local).write_bytes(raw);selected=['whole'] if clinical=='whole' else list(clinical);ancillary=[]
        if modality=='CT' and other:ancillary=[{'kind':'Radiography','panels':list(other),'structures_visible':['Source-described support device projection'],'limits':'Radiographs are separate projected views, not acquired CT anatomy; original creator processing is disclosed where present.'}]
        letters=list('abc') if n in [1,3] else list('abcd') if n==2 else ['whole'] if n in [8,10,11] else list('ab');types={p:('Schematic' if n==1 else 'Radiography' if p in other or modality=='Radiography' else 'CT') for p in letters};state=f'cardiac_support_source_pmc10350447_fig{n}'
        limits=LIMITS[n]+' Complete original publisher JPEG/labels are preserved without new processing. Original voxel/projection calibration, raw unprocessed acquisition, independent phase/registration/cross-figure patient identity and complete device/tissue geometry remain unavailable. No measured flow, function, current device suitability or procedure recommendation is inferred.'
        context={'setting':'conceptual' if n==1 else 'in_vivo','laterality':'not_reported','population':{'life_stage':'not_reported'},'extent':'local','depicted_state':state,'selected_panels':selected,'panel_types':types,'panel_states':dict.fromkeys(letters,state),'source_creator_CLAHE_panels':CLAHE.get(n,[]),'new_image_processing_applied':False,
            'full_acquired_series_included':False,'independent_calibrated_measurements_verified':False,'same_series_registration_verified':False,'cross_figure_patient_identity_verified':False,'raw_unprocessed_acquisition_included':False,'complete_device_tissue_geometry_verified':False,'current_model_ifu_conformity_verified':False,'quantitative_flow_or_function_verified':False}
        credit=', '.join(authors)+'. '+m['title']+'. DOI '+m['doi']+'. CC BY 4.0. Original complete publisher JPEG preserved byte-identically, including creator CLAHE where declared. '+('Source acknowledgements: '+ack+' Original illustrator signatures/UR Medicine credits retained. ' if n==1 else '')+'NLM/PMC Article Dataset snapshot; may not reflect latest NLM data. No endorsement implied.'
        shown=f'Original Figure {n}: {title}. '+limits;row={'id':PREFIX+str(n),'kind':'schematic' if n==1 else 'clinical-image','modality':modality,'figure_number':n,'src':'/app/'+local.removeprefix('web/'),'width':s['width'],'height':s['height'],'sha256':s['sha256'],'source_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC10350447/','figure_url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC10350447/#Fig'+str(n),'asset_source_url':u,'clinical_panels':selected,'ancillary_panels':ancillary,'source_context':context,'image_state':state,'caption':shown,'alt':shown,'limits':limits,'source_caption_full':caption,'structures_visible':['Source-local '+title.lower()],'license':licence,'license_url':url,'attribution':credit,'source_background':'white','rights_reviewed_on':'2026-10-06','rights_review':'Original CC BY 4.0 XML/credits and all complete JPEG pixels reviewed; creator processing/source conflicts explicit, clinical review pending.'}
        rows.append(row);entries.append((row,local,s))
    proof={'pmcid':'PMC10350447','doi':m['doi'],'title':m['title'],'metadata_sha256':META_SHA,'xml_sha256':sha(xml),'original_license':licence,'original_license_url':url,'permissions_xml':E.tostring(perm,encoding='unicode'),'authors':authors,'acknowledgements':ack,'figures':sources,
        'manufacturer_context':{'url':VENDOR,'reviewed_at':'2026-10-06','review_scope':'Current product description of proximal RA drainage and distal MPA return only; not complete IFU/current-model audit. No manufacturer images reused.'},'caption_component_conflict_figures':[12],'nonstandard_source_configuration_figures':[11],'clinical_approval':False,'model_promoted':False}
    path=OUT/'original-source-review.json';path.write_text(json.dumps(proof,indent=2)+'\n');proof_sha=sha(path.read_bytes());assets=[]
    for row,local,s in entries:
        assets.append({'id':row['id'],'kind':'schematic' if row['figure_number']==1 else 'clinical_image','name':CONFIG[row['figure_number']][0],'local_path':local,'sha256':row['sha256'],'modality':row['modality'],'investigation_ids':[IDENT],'structure_ids':[],'requirement_coverage':{},'source_context':row['source_context'],'source':{'url':row['source_url'],'figure_url':row['figure_url'],'asset_url':row['asset_source_url'],'license':{'name':licence,'url':url,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str(path.relative_to(ROOT)),'evidence_sha256':proof_sha,'attribution':row['attribution'],'reviewed_at':'2026-10-06'}},'pixel_provenance':{'source_pixels_changed':False,'decoded_pixel_sha256':s['decoded_pixel_sha256'],'source_creator_CLAHE_panels':s['source_creator_CLAHE_panels'],'highest_resolution_acquired_master_verified':False},'anatomical_review':{'status':'pending','reason':'Local source pictures/conceptual drawings do not verify every device port/interface, full geometry or function.'},'visual_review':{'status':'source_checked','sha256':row['sha256'],'reviewed_at':'2026-10-06','evidence_path':'docs/cardiac-support-published-source-review.md'}})
    path=ROOT/'data/radiology/radiology-open-images.json';data=json.loads(path.read_text());data[IDENT]=[r for r in data[IDENT] if not r['id'].startswith(PREFIX)]+rows;path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n');append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',assets,prefix=PREFIX)
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['start']['images']=list(dict.fromkeys(node['start']['images']+[PREFIX+'1']))
    for i,ns in {0:[1,5,10,11,12],1:[2,4,5,10,11,12],2:[2,4,5,6,7,9,10,11,12],3:[3,4,6,7,8,9,12]}.items():node['steps'][i]['images']=list(dict.fromkeys(node['steps'][i]['images']+[PREFIX+str(n) for n in ns]))
    extra=' For a dual-lumen RA-PA system, distinguish drainage and return lumens/ports using the actual model/source. ProtekDuo manufacturer describes proximal RA drainage and distal main-PA return; the source Figure 12 RV-outlet wording is not adopted as a normal target.'
    if extra not in node['steps'][2]['tip']:node['steps'][2]['tip']+=extra
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:]);(OUT/'packaged-source-images.json').write_text(json.dumps({'figures':[{'figure_number':r['figure_number'],'local_path':local,'sha256':r['sha256']} for r,local,s in entries],'clinical_approval':False,'model_promoted':False,'structure_coverage_granted':False},indent=2)+'\n');print('Twelve support source figures preserved with creator-processing, modality, model and caption-conflict limits.')
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);package(p.parse_args().source_root)
