#!/usr/bin/env python3
"""Retain the complete source expert tumour geometry and paired processed MRI."""
import gzip,hashlib,json,struct,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT))
import numpy as np
from tools.anatomy_sources.package_laryngeal_phonation_reference import canonical_gzip
from tools.anatomy_sources.package_aortic_rupture_figures import append_evidence
ATLAS='ispy1-expert1002';FAMILY='breast-tumour-source';PROOF=ROOT/'docs/breast-native-MRI-source-review/ISPY1_1002-expert';OUT=ROOT/'web/anatomy'/ATLAS
SOURCE='https://www.cancerimagingarchive.net/analysis-result/ispy1-tumor-seg-radiomics/';GRANT='https://creativecommons.org/licenses/by/3.0/'
ATTRIBUTION='Chitalia et al. Expert tumor annotations and radiomic features for ISPY1/ACRIN6657. TCIA DOI10.7937/TCIA.XC7A-QT20. CC BY3.0. Original data: Newitt,Hylton and I-SPY1/ACRIN6657 Trial Team,DOI10.7937/K9/TCIA.2016.HDHPGJLK. Adaptation: source0.5 label interface,float32 transport and illustrative display normals; no endorsement.'
NOTES=[
 'One expert source case ISPY1_1002. Source age/sex and visit-specific tissue results are not supplied in this package. This is an original processed source tumour annotation,not normal breast anatomy or the current patient.',
 'Producer expert manual structural tumour mask includes enhancing and non-enhancing primary lesion regions. All5,144 triangles and both original components (5,100 and44 triangles) remain. Computed and functional tumour masks are different source products and are not substituted.',
 'Original source MRI is bias-corrected,resampled to1mm isotropic and z-scored across the three timepoints. This is a processed source grid,not independently verified1mm native acquisition resolution. The expert mask and all three processed MRI volumes have identical source qform grids. Original bias-corrected0.78125×0.78125×2mm images and functional mask remain separately preserved in review.',
 'No new source voxel resampling,source affine replacement,fitting,smoothing,capping,component deletion or decimation. Colours and normals are illustrative,not photographic tumour tissue. Source coordinate cameras use the encoded source RAS basis; original patient/raw DICOM registration remains unverified.',
 'Whole breast skin,duct/gland/lobular/fascial,neural/vascular/lymphatic,nodal,chest-wall,additional lesion and device anatomy remain unresolved. A source expert primary-tumour annotation does not establish every reported structure,whole disease extent,current histology,stage,response or physiology.',
 'Three source phase indices follow the producer pre/early/late dataset convention; no independently verified injection clock,calibrated enhancement kinetics or tissue diagnosis is supplied. There is no registration with published ultrasound cases or the separately held ISPY1_1001 threshold mask.',
 'Source publisher MD5 manifest and local SHA256 identities are verified. Expert review belongs to the source annotation; independent whole reporting/anatomical approval remains pending. '+ATTRIBUTION]
def sha(raw):return hashlib.sha256(raw).hexdigest()
def package():
    proof=json.loads((PROOF/'original-source-review.json').read_text());row=next(r for r in proof['source_surfaces'] if r['producer_role']=='expert structural tumour');visual=json.loads((PROOF/'visual-review.json').read_text())
    if not proof['expert_manual_mask_exactly_matches_all_three_processed_1mm_MRI_grids'] or not visual['expert_manual_two_components_and_all_5144_triangles_retained']:raise ValueError('Expert source correspondence/review changed')
    position=gzip.decompress((PROOF/'masks_stv_manual-positions.f64.gz').read_bytes());face=gzip.decompress((PROOF/'masks_stv_manual-triangles.u32.gz').read_bytes())
    if sha(position)!=row['positions_sha256'] or sha(face)!=row['triangles_sha256']:raise ValueError('Original source geometry changed')
    v=np.frombuffer(position,'<f8').reshape(-1,3);f=np.frombuffer(face,'<u4').reshape(-1,3);stored=v.astype('<f4');error=float(np.abs(stored.astype(float)-v).max());assert error<=4e-5
    normal=np.zeros_like(v);tri=v[f];cross=np.cross(tri[:,1]-tri[:,0],tri[:,2]-tri[:,0])
    for i in range(3):np.add.at(normal,f[:,i],cross)
    length=np.linalg.norm(normal,axis=1);normal[length>0]/=length[length>0,None]
    decoded=struct.pack('<4sII',b'BP3D',len(v),f.size)+stored.tobytes()+normal.astype('<f4').tobytes()+face;encoded=canonical_gzip(decoded);OUT.mkdir(parents=True,exist_ok=True);ident=ATLAS+'-expert-structural-tumour';file=OUT/(ident+'.bin.gz');file.write_bytes(encoded);assert gzip.decompress(file.read_bytes())[12+len(v)*24:]==face
    part={'id':ident,'name':'expert structural tumour · both source components','file':'/app/anatomy/'+ATLAS+'/'+file.name,'sha256':sha(encoded),'decoded_sha256':sha(decoded),'vertices':len(v),'triangles':len(f),'bounds':[stored.min(0).tolist(),stored.max(0).tolist()],'source_positions_sha256':sha(position),'source_triangles_sha256':sha(face),'source_components':2,'source_component_triangle_counts':[5100,44],'source_boundary_edges':0,'color':'#ce9c73','layer':'expert_source','regions':[FAMILY],'clinical_fidelity':'unverified'}
    low=stored.min(0);high=stored.max(0);manifest={'dataset':'ISPY1_1002 expert structural tumour · processed source reference','source_url':SOURCE,'license':'CC BY3.0','license_url':GRANT,'coordinate_system':{'basis':'RAS','units':'source-declared millimetres','unit_meters':.001,'display_basis':'native-ras-to-x-left-y-superior-z-anterior','registration':'Original source qform; matching processed source grids only,raw patient registration unverified'},'parts':{ident:part},'regions':{FAMILY:{'title':'Expert primary tumour source · partial breast anatomy','side':'source case ISPY1_1002','parts':[{'id':ident,'layer':'expert_source'}],'layers':[['expert_source','Original expert mask interface']],'source_coordinate_cameras':True,'source_up_range':[float(low[2]-1),float(high[2]+1)],'focus_bounds':[low.tolist(),high.tolist()],'uncropped_label':'Complete original expert mask · both components retained'}},'viewer_notes':NOTES,'total_triangles':5144,'complete_breast_geometry_verified':False,'clinical_approval':False,'anatomical_approval':False,'status':'Partial source reference; full anatomical validation pending','runtime_promoted':True}
    (OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');(OUT/'ATTRIBUTION.md').write_text('# Source expert tumour reference\n\n'+'\n\n'.join(NOTES)+'\n')
    p=ROOT/'data/radiology/source-anatomy-references.json';refs=json.loads(p.read_text());entry={'id':ATLAS+'-expert-manual','label':'Expert primary tumour and matching processed MRI · partial','atlas':ATLAS,'family':FAMILY,'manifest_url':'/app/anatomy/'+ATLAS+'/manifest.json','manifest_sha256':sha((OUT/'manifest.json').read_bytes()),'initial_layer':'expert_source','initial_cropped':False,'population_note':' '.join(NOTES)}
    for inv in ['ra.mri-breast','ra.breast-cancer-staging']:refs[inv]=[r for r in refs.get(inv,[]) if r['atlas']!=ATLAS]+[entry.copy()]
    p.write_text(json.dumps(refs,indent=2,ensure_ascii=False)+'\n')
    rights={'name':'CC BY3.0','url':GRANT,'commercial_use':True,'redistribution':True,'review_status':'verified','evidence_path':str((PROOF/'original-acquisition.json').relative_to(ROOT)),'evidence_sha256':sha((PROOF/'original-acquisition.json').read_bytes()),'attribution':ATTRIBUTION,'reviewed_at':'2026-10-08'};append_evidence(ROOT/'data/radiology/radiology-asset-evidence.json',[{'id':ident,'kind':'model','name':part['name'],'local_path':str(file.relative_to(ROOT)),'sha256':sha(encoded),'investigation_ids':['ra.mri-breast','ra.breast-cancer-staging'],'structure_ids':[],'requirement_coverage':{},'source':{'url':SOURCE,'license':rights},'anatomical_review':{'status':'pending','reason':'One expert processed primary-tumour label does not independently supply every reported breast structure or current patient diagnosis.'}}],prefix=ATLAS+'-')
    (PROOF/'reader-transport-review.json').write_text(json.dumps({'manifest_sha256':entry['manifest_sha256'],'mesh_sha256':sha(encoded),'decoded_sha256':sha(decoded),'all_original_faces_retained':True,'source_triangles':5144,'source_components':2,'source_component_triangles':[5100,44],'maximum_float32_position_error_source_units':error,'source_coordinates_fitted_or_geometry_repaired':False,'clinical_approval':False},indent=2)+'\n');print('Complete expert source mask packaged:5144 triangles,two unchanged components')
if __name__=='__main__':package()
