#!/usr/bin/env python3
"""Reconcile prostate teaching with primary reporting guidance; no anatomical approval."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2];NODE='rad.5.prostate-mri'
MRI_GUIDANCE='https://edge.sitecorecloud.io/americancoldf5f-acrorgf92a-productioncb02-3650/media/ACR/Files/RADS/PI-RADS/PIRADS-2019.pdf'
EAU='https://uroweb.org/guidelines/prostatecancer/chapter/diagnostic-evaluation'

def reconcile(node):
    node['goal']='Assess prostate MRI by the applicable PI-RADS v2.1 sequence and zonal rules, distinguish mimics, and report imaging extent separately from histology and management.'
    ref=node['reference'];approach=ref['approach']
    approach[0]['detail']='Identify peripheral, transition and central zones and anterior fibromuscular stroma, with actual side and base/midgland/apex. Their patient-specific extent may differ from an idealized sector diagram.'
    approach[3]['detail']='Measure suspicious lesions on ADC in the PZ and T2W in the TZ; use the best-depicting sequence if those are compromised, and record the plane/series. The 1.5 cm criterion applies within the specified suspicious sequence-score definitions; size alone does not assign category 5.'
    approach[4]['detail']='Describe actual glandular-surface contact, direct extraprostatic extension, neurovascular, seminal-vesicle, sphincter and adjacent-organ findings with confidence. Apply the specified invasive-behaviour sequence-score criterion when established; uncertain contact is not definite invasion.'
    approach[5]['detail']='Use the PI-RADS v2.1 41-region map: 38 prostate regions, two seminal-vesicle regions and one external urethral-sphincter region. Include every involved sector of a reported lesion. This idealized localization map is not a patient segmentation or a complete anatomical model.'
    ref['pitfalls']=[
        'Using the wrong zone or dominant sequence; score the actual adequate T2W and DWI/ADC observations before applying the published combination rules.',
        'Using DCE curve typing or enhancement alone to assign histology. Positive focal DCE has a specific PZ DWI3 upgrade role, and clinical/pathological correlation remains separate.',
        'Assigning category5 from size alone, or from unresolved contact/contour change. The required suspicious sequence morphology or specified definite invasive behaviour must be established.',
        'Treating a dark T1 patch in haemorrhage, low T2 seminal-vesicle signal, or one ADC value as a definitive diagnosis or exclusion of cancer.',
        'Conflating an outer fibromuscular glandular boundary with the TZ/PZ pseudocapsule; neither is a complete true histological capsule.',
        'Treating an MRI extension description as DRE-based clinical stage, pathological stage or a automatic treatment choice. State the evidence and applicable staging framework.',
        'Treating PSA density or PI-RADS suspicion as a universal biopsy trigger. Current guidance integrates MRI quality, clinical risk, prior sampling, patient circumstances and preferences.'
    ]
    ref['template']=ref['template'].replace('Extraprostatic extension: [absent / present - describe].','MRI extraprostatic extension: [not assessed / no convincing evidence / suspected / definite - describe evidence and confidence].').replace('Seminal vesicle invasion: [absent / present].','MRI seminal-vesicle findings: [source observations and confidence]; unresolved extent [ ].').replace('[Plain-language statement of what this means for biopsy.]','[Imaging suspicion and separate individualized clinical/biopsy discussion; current guideline context.]')
    ref['template']=ref['template'].replace('Multiparametric prostate MRI: T2W, DWI (high b-value ≥1400) with ADC, DCE.','Actual examination and comparison: [ ]. T2W planes/quality: [ ]. DWI acquired/calculated b-values and quality: [ ]. ADC source/calibration: [ ]. DCE acquisition/contrast/timing or not obtained: [ ]. Coverage and limitations: [ ].').replace('DCE [positive/negative]','DCE [positive/negative/not acquired/not evaluable]')
    q=node['quiz']
    q[1]['answer']='PI-RADS 4; management still requires clinical risk assessment'
    q[1]['choices'][2]=q[1]['answer']
    q[1]['explain']='In this supplied adequate examination, PZ DWI3 with corresponding early focal DCE is PI-RADS4. DCE is positive or negative for this combination rule; washout-curve typing is not required, and DCE does not upgrade the category to5. The category expresses imaging suspicion, not proven cancer or an automatic biopsy instruction. PI-RADS itself separates management from scoring. Current clinical guidance combines MRI with PSA density, prior sampling, family history, other risk factors, examination quality and patient circumstances. State the imaging assessment and the separate clinical discussion.'
    q[3]['prompt']=q[3]['prompt'].replace('What does the T1-dark area most likely represent?','How should the T1-dark area be interpreted with the other sequences?')
    q[3]['answer']='A suspicious tumour pattern: the haemorrhage exclusion sign'
    q[3]['choices'][2]=q[3]['answer']
    q[3]['explain']='A T1-dark focus within T1-bright post-biopsy haemorrhage, with concordant suspicious T2 and diffusion findings, is a haemorrhage-exclusion pattern that raises concern for tumour. It is not histological confirmation, and T1W is not a map proving where cancer is absent. Blood age, heterogeneous bleeding, susceptibility and other mimics remain relevant; the citrate mechanism is a proposed explanation, not a measured fact in this case. Review every sequence, timing and limitation, correlate supplied tissue evidence, and distinguish imaging suspicion from diagnosis. For staging, post-biopsy changes may reduce accuracy and timing should follow the actual clinical question and source quality.'
    q[5]['explain']='Under the explicitly supplied two-point mono-exponential model, ADC=ln(800/400)/(1000-100)=7.70×10^-4 mm²/s, or0.77×10^-3 mm²/s. The calculation assumes the stated b-values, same source region and comparable calibrated acquisitions. ADC depends on b-values, vendor and processing, and benign and malignant tissues overlap. A value within or outside a proposed threshold range does not independently establish or exclude cancer. Interpret qualitative morphology/diffusion and the complete clinical context. These hypothetical calibrated inputs must not be borrowed by an uncalibrated source ADC display.'
    q[6]['answer']='First, stronger diffusion weighting commonly lowers SNR and can require longer echo time or more acquisition effort; the practical result depends on the scanner and protocol. A calculated high-b image is a producer-derived image, not a separately acquired measurement. Second, diffusion kurtosis can make high-b signal depart from a mono-exponential fit, changing the ADC estimate. PI-RADS v2.1 requires a high-b image set of at least1400 s/mm², acquired or calculated, and recommends a maximum b-value no greater than1000 s/mm² for ADC calculation. Record actual acquisition/derivation, quality, source ROI and calibration.'
    q[6]['explain']='PI-RADS v2.1 accepts acquired or calculated high-b images, with at least1400 s/mm² for that image set. It recommends no more than1000 s/mm² in the ADC calculation to limit diffusion-kurtosis effects on the mono-exponential model. Stronger gradients and higher diffusion weighting impose signal/echo-time and scan-effort tradeoffs, but image quality depends on the actual system. A synthesized image is not automatically cleaner, a measured high-b acquisition or interchangeable calibrated data. Keep its derivation and the ADC fit separate.'
    q[8]['answer']='There is no convincing MRI evidence of seminal-vesicle invasion in the supplied views, but imaging does not establish pathological non-involvement. Bilateral symmetric low T2W signal without restricted diffusion or abnormal enhancement may reflect age-related atrophy or amyloid deposition; amyloid is a possible explanation, not confirmed histology. Review the source extent and quality, the base/vesicle angle and each ejaculatory-duct/vesicle interface, including any contiguous tumour. Concerning findings include actual diffusion/enhancement abnormality, disrupted interfaces and source continuity with a base lesion. An apical focus or symmetry alone does not exclude occult or multifocal disease.'
    q[8]['explain']='Low T2W seminal-vesicle signal is nonspecific. Symmetric age-related changes can mimic invasion, while diffusion/enhancement abnormalities and the actual base/duct/tumour relationships add evidence. Preserve uncovered or uncertain tissue rather than requiring a fixed count of signs, inferring amyloid from MRI or claiming pathological clearance. Separate source MRI observations, confidence and any supplied tissue findings.'
    device_context=' The coil’s current manufacturer instructions explicitly permit an approved liquid fill.'
    q[9]['prompt']=q[9]['prompt'].split(device_context)[0]+device_context
    q[9]['answer']='Use an approved liquid fill under the coil’s current instructions'
    q[9]['choices'][1]=q[9]['answer']
    q[9]['explain']='In the specified device, air near the posterior gland creates susceptibility differences that can distort echo-planar DWI. A manufacturer-approved liquid fill and correct positioning can reduce that cause; the prompt explicitly supplies permission for that method. The PI-RADS technical guidance discusses liquid perfluorocarbon or barium suspension as examples, not a universal prescription for every coil. Use the actual device instructions, MR safety and local protocol. Do not infer that a coil is always required or always improves the examination; reassess the obtained sequence quality.'
    q[11]['explain']='The ellipsoid volume is4.8×3.6×4.2×0.52=37.7mL; PSA density is8.4/37.7=0.22ng/mL/mL. Record each dimension, native plane, volume method and PSA date; segmentation and ellipsoid estimates can differ. PSA density contributes to risk assessment, and it is not a PI-RADS scoring input or a universal biopsy threshold. Current EAU guidance combines MRI category/quality and PSA density with clinical risk and the patient context. A single0.15 threshold must not automatically determine biopsy or reassure against cancer.'
    q[12]['prompt']='Order these anatomical extent descriptions from organ-confined to progressively more extensive involvement. This asks about TNM anatomical definitions, not automatic DRE-based clinical stage, pathological stage or treatment.'
    q[12]['explain']='In the anatomical TNM definitions, organ-confined disease corresponds to T2, extraprostatic extension to T3a, seminal-vesicle invasion to T3b and specified adjacent-structure invasion such as rectal wall to T4. The requested ordering remains organ-confined, EPE, SVI, rectal-wall invasion. Report MRI sites, source evidence and confidence separately: EAU risk-group clinical T staging is based on DRE, while pathological stage needs tissue assessment. MRI extent does not automatically set those stages, prove negative interfaces or choose nerve-sparing surgery, radiotherapy or systemic therapy.'
    q[13]['answer']='Measure the longest dimension on ADC for a PZ lesion and T2W for a TZ lesion. If that sequence is compromised, use the best-depicting sequence and document it. The axial measurement is the minimum convention; report the largest dimension and plane if larger on sagittal/coronal images. Describe the three category3–5 lesions individually; up to four principal suspicious lesions are ordinarily mapped, but this is not an absolute cap and additional findings can be appropriate. Category2/benign landmarks can be reported when useful. The index lesion has the highest category, here5; ties are resolved by EPE, then by size when no tied lesion shows EPE. Include all involved sectors and source series/images.'
    q[13]['explain']='Use ADC for PZ and T2W for TZ measurement, with a documented fallback when those are compromised. Record the longest relevant dimension and its plane/series. Four principal suspicious lesions is a reporting convention, not a rule forbidding more; include additional findings when clinically useful. The index is chosen by highest category, then EPE for ties, then largest size if EPE is absent. These are localization conventions and do not independently dictate treatment or prove complete tumour extent.'
    q[14]['answer']='The described non-focal linear or wedge-shaped PZ morphology and mild non-focal diffusion findings support T2W2 and DWI2, giving PI-RADS2 in the supplied adequate examination. Inflammation, fibrosis or atrophy are plausible imaging explanations; prostatitis is not confirmed by appearance alone. Describe the actual pattern, comparison and limitations. This category does not prove absence of clinically significant cancer or automatically cancel biopsy when clinical suspicion remains high.'
    q[14]['explain']='PZ assessment is driven by the actual diffusion findings and their morphology. Linear/wedge-shaped or diffuse change with mild non-focal diffusion abnormality can reflect benign inflammatory/fibrotic change; it differs from a suspicious focal marked abnormality. Do not upgrade solely because PSA rises, but do not let a low imaging category replace individualized clinical risk assessment or tissue evidence. Preserve source quality and unresolved discordance.'
    for media in node.get('lesson_media',[]):
        if media.get('renderer')=='radiology-anatomy':media['instructions']='Schematic orientation only. The gland/zone shapes do not verify native tissue boundaries, the41-region map, ducts, nerves, vessels, seminal vesicles or sphincter. Open the reporting reference for separately scoped original MRI and source gland/ROI models.'
    return node

def build():
    p=ROOT/'data/curriculum/11-radiology.json';text=p.read_text();token='"id": "'+NODE+'"';at=text.index(token);start=text.rfind('{',0,at);node,end=json.JSONDecoder().raw_decode(text,start);before=json.dumps(node,sort_keys=True)
    node=reconcile(node);p.write_text(text[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+text[end:])
    p=ROOT/'data/radiology/reporting-models.json';d=json.loads(p.read_text());d[NODE]['reporting_aim']='Partial schematic orientation only; native zonal, ductal, neurovascular, seminal-vesicle and sphincter boundaries remain unverified. Original MRI/gland/ROI references in the reporting desk are separate source cases with explicit limits.';d[NODE]['instructions']='Drag to rotate the schematic and inspect orientation concepts. '+d[NODE]['reporting_aim'];p.write_text(json.dumps(d,indent=2,ensure_ascii=False)+'\n')
    print('Reconciled prostate reference and15 quiz items; source anatomy/clinical approvals unchanged')

if __name__=='__main__':build()
