#!/usr/bin/env python3
"""Read checksum-bound original binary PLY geometry and source NRRD declarations; do not repair meshes."""
import argparse,hashlib,json,re,zipfile
from pathlib import Path
import numpy as np

def sha(raw):return hashlib.sha256(raw).hexdigest()
def ply(raw):
    marker=b'end_header\n';end=raw.index(marker)+len(marker);header=raw[:end].decode('ascii');lines=header.splitlines()
    if 'format binary_little_endian 1.0' not in lines:raise ValueError('Original binary-little-endian PLY required')
    n=int(next(l.split()[-1] for l in lines if l.startswith('element vertex ')));k=int(next(l.split()[-1] for l in lines if l.startswith('element face ')))
    properties=[l for l in lines if l.startswith('property ')]
    if properties!=['property float x','property float y','property float z','property list uchar int vertex_indices']:raise ValueError('Unexpected original source properties')
    if len(raw)!=end+n*12+k*13:raise ValueError('Original binary mesh length differs')
    vertices=np.frombuffer(raw,'<f4',n*3,end).reshape(-1,3)
    packed=np.frombuffer(raw,dtype=np.dtype([('count','u1'),('indices','<i4',(3,))]),count=k,offset=end+n*12)
    if not np.isfinite(vertices).all() or not (packed['count']==3).all():raise ValueError('Invalid original mesh samples')
    faces=packed['indices']
    if faces.min()<0 or faces.max()>=n:raise ValueError('Original mesh index outside vertex array')
    # Chunked source area checks keep the seven-million-triangle bone mesh intact.
    zero=0
    for start in range(0,k,100000):
        triangles=vertices[faces[start:start+100000]].astype(float);zero+=int((np.linalg.norm(np.cross(triangles[:,1]-triangles[:,0],triangles[:,2]-triangles[:,0]),axis=1)==0).sum())
    return vertices,faces,{'original_header':header,'vertices':n,'triangles':k,'source_float32_position_sha256':sha(vertices.tobytes()),
        'source_int32_face_sha256':sha(faces.astype('<i4').tobytes()),'source_bounds':[vertices.min(0).tolist(),vertices.max(0).tolist()],
        'zero_area_triangles':zero,'source_comment_coordinate_declaration':[l for l in lines if 'SPACE=' in l],
        'source_generator_repair_or_hole_filling_comments':[l for l in lines if 'repair=' in l or 'hole_filling=' in l or 'min_comp_' in l],
        'new_smoothing_repair_decimation_or_component_deletion':False}

def header(stream):
    raw=b''
    while b'\n\n' not in raw:
        line=stream.readline(8192)
        if not line or len(raw)>100000:raise ValueError('Original NRRD header missing/too large')
        raw+=line
    text=raw.split(b'\n\n')[0].decode();fields={}
    for line in text.splitlines():
        if line.startswith('#') or ':' not in line:continue
        key,value=line.split(':=',1) if ':=' in line else line.split(':',1);fields[key]=value.strip()
    return text,fields

def review(root,output):
    acquisition=json.loads((output/'ZETA-original-acquisition.json').read_text());records={r['member']:r for r in acquisition['members']}
    if not acquisition['archive']['publisher_MD5_verified'] or not acquisition['all_original_members_CRC_and_SHA_checked']:raise ValueError('Complete original acquisition required')
    archive_digest=hashlib.sha256()
    with (root/'ZETA.zip').open('rb') as stream:
        for block in iter(lambda:stream.read(4*1024*1024),b''):archive_digest.update(block)
    if archive_digest.hexdigest()!=acquisition['archive']['sha256']:raise ValueError('Complete acquired archive changed')
    meshes=[];volumes=[];selected=root/'ZETA-selected';selected.mkdir(exist_ok=True)
    with zipfile.ZipFile(root/'ZETA.zip') as z:
        for info in z.infolist():
            name=info.filename
            if name.endswith('.ply'):
                raw=z.read(info);record=records[name]
                if sha(raw)!=record['sha256']:raise ValueError('Original acquired mesh member changed')
                path=selected/Path(name).name;path.write_bytes(raw);v,f,p=ply(raw);meshes.append({'member':name,'original_member_sha256':record['sha256'],'ZIP_CRC_reverified':True,**p})
            elif name.endswith('.nrrd'):
                with z.open(info) as stream:text,fields=header(stream)
                segments=[{'field':k,'value':v} for k,v in fields.items() if k.endswith('_Name') or k.endswith('_Layer') or k.endswith('_LabelValue') or k.endswith('_ColorAutoGenerated')]
                volumes.append({'member':name,'original_member_sha256':records[name]['sha256'],'original_header':text,'source_fields':fields,'source_segment_names_layers_values_and_auto_colours':segments,'full_scalar_payload_readback_independently_verified':False})
    proof={'case':'ZETA','original_acquisition_proof_sha256':sha((output/'ZETA-original-acquisition.json').read_bytes()),'meshes':meshes,'volumes':volumes,
        'all_original_PLY_triangles':sum(m['triangles'] for m in meshes),'new_source_geometry_or_colour_changes_applied':False,
        'source_PLYs_contain_photographic_RGB_attributes':False,'NRRD_frame_and_source_mesh_identity_registration_independently_approved':False,
        'clinical_approval':False,'runtime_promoted':False,'structure_coverage_granted':False}
    (output/'ZETA-original-geometry-header-review.json').write_text(json.dumps(proof,indent=2)+'\n');print([(Path(m['member']).name,m['vertices'],m['triangles'],m['zero_area_triangles']) for m in meshes]);print('Original triangles',proof['all_original_PLY_triangles'])
if __name__=='__main__':
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--source-root',type=Path,required=True);p.add_argument('--output',type=Path,required=True);a=p.parse_args();review(a.source_root,a.output)
