#!/usr/bin/env python3
"""Separate actual thoracic TB imaging from microbiology, resistance, activity and unassessed normality."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.tuberculosis'
URLS=['https://radiologyassistant.nl/chest/tb/tuberculosis','https://pmc.ncbi.nlm.nih.gov/articles/PMC11449295/','https://www.who.int/publications/i/item/9789240107984']
def update():
    details=['Record every actual consolidation/nodule/cavity or other parenchymal component, source site/extent and quality, with a supported differential.','Describe actually resolved airway-centred, random/miliary or other distribution and acquired regional extent; do not infer unique organism or microscopic spread from morphology.','Describe every covered nodal site and source-resolved size/internal/adjacent interface; distinguish projection overlap or unresolved tissue from verified nodes.','Inspect actual pleural, airway and relevant thoracic complications with source modality/phase and full obtained connections; clinical effect/organism remains separate.','Record actual sequelae and matching-source change; separate apparent chronic morphology from supplied clinical/microbiological confirmation, activity, infectivity and resistance.']
    looks=['Review actual radiographic/CT or other acquired sources with appropriate projection/reconstruction/windows and coverage. Trace each visible lesion, wall/content, associated airway/vessel/pleural relation and mimics. A teaching-case diagnosis does not describe the current patient.','Assess every covered side/lobe/region and source-resolved bronchiolar/lobular relationships. Tree-in-bud and random nodules have multiple causes; small lesions may be unresolved on radiography and better depicted on actual CT.','Inspect actual hilar/mediastinal/axillary or other covered nodal groups, attenuation/signal/enhancement/calcium or necrotic-appearing components if supported by acquired sources, airway/vessel displacement and uncovered extent.','Trace effusions, pleural thickening, empyema/air/fluid or fistulous/chest-wall components, airway narrowing/bronchiectatic change and relevant pericardial/vascular/bone interfaces. Contrast, MRI, US/Doppler and other phases are separate sources only if acquired.','Compare actual dates, matched sites, source projection/coverage/phase and treatment/clinical context. Record fibrosis/calcium/volume loss or new change; actual laboratory/specimen, molecular/culture/susceptibility and clinical source results require their own identities/dates.']
    tips=['Cavitation, consolidation, nodules or an apparent fungal-ball component are not unique TB or independently proven microbiology. Missing or limited views cannot be negative disease evidence.','Imaging distribution alone does not distinguish new infection from reactivation, establish bacillary viability/infectivity, or prove drug resistance. Actual immune/clinical context must be supplied, not inferred.','Necrotic-appearing/enlarged/calcified nodes have a differential. Imaging alone does not supply tissue histology, acid-fast results, genotype or resistance status.','Imaging fluid is not proven TB/chyle or a physiological severity measurement. Possible haemoptysis-related vascular lesions or other urgent complications require actual acquired evidence and clinical assessment.','Scarring or calcification does not alone exclude coexisting active disease or establish noninfectivity. Normal imaging does not exclude latent infection or unavailable microscopic disease. State uncertainty and missing confirmation; do not infer successful treatment from unmatched stills.']
    bodies=['Actual source modality/projection/phase and region [ ]; each consolidation/nodule/cavity/collection or other component [ ]; wall/content/adjacent interfaces and obtained extent [ ]; calibrated measurement method/window/axis if available [ ]; differential and quality/unresolved extent [ ].','Each covered side/lobe/actual region and supported distribution [ ]; airway-centred/tree-in-bud, random/miliary or other pattern [ ]; actual source resolution and mimics [ ]; unassessed regional/microscopic extent [ ]; supplied clinical/immune context without inferred timing or organism [ ].','Each covered nodal site [ ]; source-resolved boundary/size/attenuation/signal/enhancement/calcium and adjacent airway/vessel relation [ ]; actual acquisition/comparison [ ]; necrotic-appearing differential and missing tissue/laboratory confirmation [ ]; uncovered groups [ ].','Actual pleural fluid/air/thickening/empyema and source extent [ ]; airway course/narrowing or bronchiectatic component [ ]; each source-supported fistula/chest-wall/pericardial/vascular/bone relation [ ]; modality/phase and confidence [ ]; clinical effect and urgent source findings if supplied [ ]; unresolved extent [ ].','Actual prior sources/dates/methods and matching site change [ ]; source fibrosis/calcium/volume loss or other sequelae [ ]; supplied clinical/specimen/laboratory/molecular/culture/susceptibility results with dates [ ]; activity/infectivity/resistance confirmation or uncertainty [ ]; treatment chronology and unavailable/unassessed evidence [ ].']
    guide={'reviewed_at':'2026-10-07','protocol':['Record actually acquired views/modalities, contrast/sequence/phase, coverage, quality and available comparison. Do not substitute CT/MRI/US tissue information when the source is only a radiograph.','Describe observed thoracic morphology and its differential. Infection/disease/resistance are distinct diagnostic domains; supplied clinical and laboratory sources cannot be invented from images.'],'checklist':[{'label':l,'detail':d} for l,d in zip(['Parenchyma','Spread pattern','Nodes','Pleura and airways','Sequelae and comparison'],details)],'measurements':[{'name':'Cavity or collection','method':'Record actual site, source modality/projection, local axes/edge convention/window and calibration for representative dimensions; describe full obtained extent and uncertainty.','pitfall':'One source still does not supply whole3D extent or unique TB diagnosis; measurements depend on actual source technique.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['State actual source-supported morphology, regional extent and examination limits with a differential.','Separate imaging suspicion from supplied microbiological/clinical diagnosis, activity, infectivity and resistance status; name missing evidence.','Describe supported interval change/sequelae and urgent complications without asserting an absent history or successful treatment from unassessed sources.'],'escalation':['Communicate source-suspected thoracic infection or urgent haemoptysis/airway/pleural/pericardial/vascular complications according to local clinical/infection-control pathways; imaging alone does not determine infectivity or management.'],'template_sections':[{'heading':h,'body':b} for h,b in zip(['PARENCHYMA','SPREAD PATTERN','NODES','PLEURA AND AIRWAYS','SEQUELAE AND COMPARISON'],bodies)],'sources':[{'title':t,'url':u} for t,u in zip(['RA thoracic TB morphology and mimics','2024pulmonary/extrapulmonary thoracic imaging review','2025WHOdiagnosis domains; reference only, no reused graphics'],URLS)]}
    p=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(p.read_text());d.setdefault(IDENT,{})['reporting']=guide;p.write_text(json.dumps(d,indent=2)+'\n')
    p=ROOT/'data/radiology/reporting-steps/chest.json';raw=p.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['model']={'family':'thorax','reporting_aim':'Partial thoracic orientation only. This companion does not supply actual patient TB lesions/cavities, full native nodal/pleural/airway/vascular/chest-wall interfaces, microscopic disease, genotype, viability, infectivity or resistance. Report actual acquired sources; unresolved anatomy and diagnostic confirmation remain unassessed.'}
    for i,s in enumerate(node['steps']):s['normal']={};s['detail']=details[i];s['look']=looks[i];s['tip']=tips[i]
    p.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:])
if __name__=='__main__':update()
