#!/usr/bin/env python3
"""Require acquired HRCT anatomy and clinical sources; avoid unperformed expiration and normal/progression presets."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.hrct-lung'
URLS=['https://radiologyassistant.nl/chest/hrct/basic-interpretation','https://radiologyassistant.nl/chest/hrct/common-diseases','https://radiologyassistant.nl/chest/hrct/fibrosis-of-the-lung-on-hrct-imaging','https://pmc.ncbi.nlm.nih.gov/articles/PMC11914337/','https://pmc.ncbi.nlm.nih.gov/articles/PMC9851481/','https://publications.ersnet.org/content/erj/66/6/2500158']
def update():
    details=['Describe every actual dominant and associated ground-glass, consolidative, nodular, reticular/cystic or other pattern with source-defined site, extent, tissue interfaces and quality.','Record all covered side/lobe/segment and secondary-lobule/axial/pleural relationships with actual regional distribution and variant/coverage limits.','Describe each source fibrosis, distortion, traction airway, honeycomb and volume-loss component; separate the CT pattern from aetiological/multidisciplinary diagnosis.','Trace actual airway and regional mosaic changes; describe expiratory/prone findings only from those acquired phases with technique and source uncertainty.','Compare actual matching source sites and methods; report complications and supplied clinical/physiological context without inferring progression, pressure or function from a still.']
    looks=['Inspect thin source sections and multiple windows/reformats. Distinguish reticular septa from non-fibrotic thickening, ground glass from vessel-obscuring consolidation, cyst/mimic and every solid or airspace component. Dependent density and incomplete inspiration can simulate disease.','Trace every covered lobe/actual segment and variant, central/peripheral/subpleural/peribronchovascular/perilobular compartments, fissures, pleural recesses and source-resolved secondary lobules. Identify centrilobular, perilymphatic or random nodular patterns without borrowing invisible microscopic anatomy.','Assess actual irregular inter/intralobular septa, distortion, displacement, traction bronchi/bronchioles and honeycomb versus mimics. Review all spatial gradients and alternative/mixed features before naming UIP/probable UIP/indeterminate/alternative under a stated reference; valid unclassifiable morphology remains explicit.','Trace luminal/wall changes and airway-artery relationships across actual planes. Mosaic attenuation may be airway, vascular or infiltrative; a three-density appearance on inspiration does not supply an expiratory study. Compare inspiration/expiration/prone only when actually acquired.','Record prior date/coverage/phase/reconstruction and comparable sites, symptoms and PFT dates/values if supplied. Review acute opacity, pleural/mediastinal air or fluid, nodes, masses and covered vascular/systemic clues with alternative causes.']
    tips=['Ground glass alone is not fibrosis, unique inflammation, infection or a specific histology. Motion, under-inspiration, window/reconstruction and partial volume may alter apparent pattern and thin tissue borders.','A representative still cannot establish whole-lung disease absence, burden or a microscopic lobular map. State mixed patterns, each actual region and unassessed coverage.','A CT UIP pattern does not equal idiopathic pulmonary fibrosis; secondary causes and multidisciplinary confidence matter. Honeycombing can overlap other fibrotic diseases; CT appearance is not the histological definition.','Do not assert no air trapping on an unperformed expiration or resolution on an unperformed prone scan. Air trapping/mosaicism alone does not uniquely diagnose HP; bronchiolocentric features can have other causes.','CT progression alone does not establish PPF. The named2022 definition uses at least two of symptoms/radiology/physiology within one year, no alternative explanation, in fibrotic ILD other than IPF. Preserve actual dates and sources; new acute opacity is not unique for exacerbation.']
    bodies=['Each actual dominant/secondary pattern and location [ ]; full obtained extent and source-resolved borders [ ]; nodules, septa, cystic/airspace/solid components [ ]; acquisition/window/motion/inspiration limits [ ]; differential and unassessed extent [ ].','Covered side/lobe/actual segment/variant [ ]; basal/apical and axial/peripheral gradient [ ]; subpleural, peribronchovascular, perilobular, fissural/recess and source lobular relationships [ ]; nodular distribution model if justified [ ]; quality/burden estimate and coverage limits [ ].','Actual reticulation, architectural distortion/displacement, volume loss, traction bronchiectasis/bronchiolectasis and honeycomb or mimic [ ]; each site/extent/source uncertainty [ ]; CT pattern and named reference/date if supported [ ]; primary/secondary or unclassifiable differential and supplied multidisciplinary source/confidence [ ].','Actual airway lumen/wall/branch and artery/cyst relationship [ ]; mosaic/three-density distribution and differential [ ]; actually acquired inspiration/expiration/prone phase and source findings [ ]; unavailable phases, perfusion or dynamic/function evidence [ ]; regional quality limits [ ].','Prior matching source dates/sites/coverage and technique [ ]; actual radiological change and uncertainty [ ]; symptoms and physiological source/date/values if supplied [ ]; named progression definition/window/exclusion context if applied [ ]; actual pleural/mediastinal air/fluid, nodes/mass/vascular/covered systemic findings [ ]; acute alternatives and communication [ ].']
    guide={'reviewed_at':'2026-10-06','protocol':['Record actual volumetric/thin-section HRCT coverage, reconstruction, inspiratory adequacy and artefacts. Expiration, prone, contrast and serial studies are separate acquired sources only when performed.','Use source-resolved lobular/tissue and airway interfaces; named CT patterns differ from clinical, pathological, genetic and physiological conclusions. Do not substitute the orientation model for actual native disease anatomy.'],'checklist':[{'label':l,'detail':d} for l,d in zip(['Dominant pattern','Distribution','Fibrosis','Airways and air trapping','Comparison and context'],details)],'measurements':[{'name':'Extent and progression','method':'Record source method, actual covered regions, visual/quantitative basis, phase/calibration and uncertainty for any burden estimate; compare justified matching methods/sites.','pitfall':'Selected stills or a parent lung model do not supply full volumetric burden or calibrated serial change.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['State source-supported dominant/mixed morphology, distribution, fibrotic features and coverage/quality limits.','Name a supported CT pattern with its reference/date and confidence; separate idiopathic/secondary or unclassifiable multidisciplinary diagnosis and missing sources.','Describe actual interval change and complications; apply named progression criteria only with the required dated radiological/clinical/physiological evidence.'],'escalation':['Communicate actual acute respiratory/pleural/mediastinal complications through local clinical pathways; CT pattern alone does not establish physiological instability or treatment choice.'],'template_sections':[{'heading':h,'body':b} for h,b in zip(['DOMINANT PATTERN','DISTRIBUTION','FIBROSIS','AIRWAYS AND AIR TRAPPING','COMPARISON AND CONTEXT'],bodies)],'sources':[{'title':t,'url':u} for t,u in zip(['RA basic HRCT morphology','RA common differential','RA fibrosis pattern approach','ESR/ESTI practice recommendations','Named2022 IPF/PPF definitions','2025ERS/ATS multidisciplinary pattern terminology'],URLS)]}
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(path.read_text());d.setdefault(IDENT,{})['reporting']=guide;path.write_text(json.dumps(d,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['model']={'family':'thorax','reporting_aim':'Partial thoracic orientation only. This companion does not supply source patient fibrosis, microscopic lobules/septa, full native airway/vessel/lymphatic walls, honeycomb/lesion geometry, regional disease burden or acquired respiratory/physiological change. Report actual source images; missing anatomy remains unassessed.'}
    for i,step in enumerate(node['steps']):step['normal']={};step['detail']=details[i];step['look']=looks[i];step['tip']=tips[i]
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:])
if __name__=='__main__':update()
