#!/usr/bin/env python3
"""Require actually observed cystic lung anatomy, source comparison and contextual diagnosis."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.hrct-cystic-lung'
URLS=['https://radiologyassistant.nl/chest/cystic-lung-disease/analysis-of-cystic-lung-disease-1-1-1','https://pmc.ncbi.nlm.nih.gov/articles/PMC13200743/']
def update():
    details=['Trace each actual cyst or cyst-like lesion through obtained source planes; describe wall, contents, shape, septa, mural components and airway/vessel continuity with source uncertainty.','Record actual count/extent and regional distribution across every covered lobe, axial compartment, pleural recess and fissural/mediastinal interface; identify coverage limits.','Describe each solid/cavitating nodule, mural or intracystic component and its relationship to cysts, airways and vessels; assess actual prior change.','Describe intervening parenchyma, ground glass, septa, reticulation, fibrosis, honeycombing, emphysema and airway change with source phase and differential.','Review pleura, pneumothorax/fluid, covered nodes and systemic findings; separate observed CT from supplied history, genetics, microbiology or tissue evidence.']
    looks=['Use original thin sections and matching reformats, multiple windows, stated reconstruction/calibration and local axes. Distinguish cysts from cavities, bullae/emphysema, pneumatoceles, honeycombing and cystic bronchiectasis; do not infer epithelial lining or microscopic wall layers from CT.','Inspect each actual covered side/lobe/region and variant: apical/basal, central/peripheral, peribronchovascular, subpleural/paramediastinal and interlobar relationships. Representative pictures cannot establish full cyst count or exclusion of disease elsewhere.','Record wall nodularity/irregular thickening, intracystic material, traversing vessels and adjacent nodules/masses. Trace airway continuity and assess prior source images at matched sites without assuming registration.','Assess every covered regional airway/interstitial/vascular interface. Expiratory air trapping, perfusion and dynamic behaviour require those actually acquired sources; inspiratory CT alone does not provide them.','Assess actual pleura/recesses, mediastinal/hilar nodes and covered upper abdominal organs. Renal, cutaneous, genetic, infection and smoking/autoimmune context must come from supplied current source/history, not the teaching-case diagnosis.']
    tips=['Wall thickness or apparent absence alone is not a diagnostic cutoff; partial volume, reconstruction and orientation affect thin walls. Thick/irregular components and a cyst-like cavity require a stated differential.','The source four-cysts/age-forty rule is a contextual heuristic, not a diagnosis or exclusion rule, particularly with recurrent pneumothorax or suspected hereditary disease. Costophrenic distribution supports a differential, not a unique diagnosis.','New/growing mural solid tissue or changing cyst-associated nodules warrant appropriate clinical evaluation. Wall thinning or low/negative PET uptake alone does not establish benignity; no PET finding is borrowed when PET was not obtained.','LAM/BHD-FDS/PLCH/LIP/AMP-DIP patterns overlap with infection, neoplasia, deposition and other causes. Record morphology and uncertainty; source terminology does not prove histology, genotype or functional severity.','No pneumothorax, chylous fluid, renal tumour, systemic disease or hereditary finding may be asserted from unassessed anatomy. CT fluid is not proven chyle; urgency depends on actual findings and clinical context.']
    sections=[{'heading':h,'body':b} for h,b in zip(['CYST MORPHOLOGY','DISTRIBUTION','ASSOCIATED NODULES','BACKGROUND LUNG','EXTRAPULMONARY CONTEXT'],['Actual lesion/site and cyst versus mimic [ ]; wall/shape/content/septa/mural or traversing-vessel interface [ ]; full source-resolved extent [ ]; representative size/axis/window/calibration and uncertainty [ ]; microscopic/unresolved components [ ].','Actual count or justified extent estimate [ ]; every covered side/lobe/region and zonal/axial pattern [ ]; costophrenic, subpleural, mediastinal and fissural relation [ ]; variant/coverage/unevaluable extent [ ]; prior source comparison [ ].','Each source solid/cavitating, mural/intracystic or adjacent nodule/mass [ ]; actual cyst/airway/vessel relation [ ]; local site, extent, size/method and change [ ]; comparison/registration/source limits [ ]; concerning or indeterminate component [ ].','Each covered regional ground glass, septal/reticular/fibrotic/emphysematous or airway finding [ ]; intervening tissue versus lesion [ ]; actual acquired inspiration/expiration/contrast source [ ]; differential and technical limits [ ].','Actual pleural pneumothorax/fluid or other complication [ ]; covered nodal/vascular/upper-abdominal finding [ ]; supplied smoking, autoimmune/infectious, genetic/tissue or other history/source/date [ ]; unavailable/uncovered systemic or functional evidence [ ]; prior change and communication [ ].'])]
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(path.read_text());d.setdefault(IDENT,{})['reporting']={'reviewed_at':'2026-10-06','protocol':['Record actual thin-section CT acquisition, coverage, source voxel/reconstruction/window, inspiratory level, motion and available comparison. Expiration/contrast or other tests are separate only if performed.','Trace source cyst-like lesions and all covered regional interfaces. Teaching diagnoses, typical distributions and representative stills are not the current patient observations or complete native anatomy.'],'checklist':[{'label':l,'detail':v} for l,v in zip(['Cyst morphology','Distribution','Associated nodules','Background lung','Extrapulmonary context'],details)],'measurements':[{'name':'Representative cysts','method':'Measure selected source-resolved lesions in stated orthogonal/local planes, wall/airspace edge convention, reconstruction/window and actual calibration; describe justified range, burden estimate and uncertainty.','pitfall':'One lesion or still does not establish whole-lung burden, microscopic wall structure or calibrated serial change.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['Describe actual cyst/mimic morphology, distribution, associated solid/parenchymal findings and full obtained extent with technical confidence.','Give a supported differential and the clinical/genetic/tissue sources or missing evidence; do not convert an age/count heuristic or teaching pattern into a confirmed diagnosis.','State concerning interval change or complication and appropriate source/context-dependent clinical assessment.'],'escalation':['Communicate an observed pneumothorax or other clinically urgent complication through local pathways; source pattern alone does not establish physiological instability.'],'template_sections':sections,'sources':[{'title':t,'url':u} for t,u in zip(['Radiology Assistant cystic lung approach','2026 original cystic lung CT pictorial review'],URLS)]};path.write_text(json.dumps(d,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start)
    node['model']={'family':'thorax','reporting_aim':'Partial thoracic orientation only. This companion does not supply individual patient cysts, microscopic walls, complete airway/vessel interfaces, lobar/segmental disease distribution, mural nodules, genotype, histology or dynamic function. Report actual acquired sources; missing anatomy remains unassessed.'}
    for i,step in enumerate(node['steps']):step['normal']={};step['detail']=details[i];step['look']=looks[i];step['tip']=tips[i]
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:])
if __name__=='__main__':update()
