#!/usr/bin/env python3
"""Require actual nongated CT anatomy/source evidence without normal function or stenosis inference."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.ct-cardiovascular-pearls'
URLS=['https://radiologyassistant.nl/cardiovascular/pearls/cardiovascular-pearls-on-chest-ct','https://radiologyassistant.nl/chest/pearls/cardiovascular-pearls-on-chest-ct-2','https://pmc.ncbi.nlm.nih.gov/articles/PMC6365314/','https://pmc.ncbi.nlm.nih.gov/articles/PMC7774698/']
def update():
    details=['Review all covered chamber/appendage boundaries, septa and structural connections with actual phase/coverage limits; separate filling defect from mixing or unresolved lumen.','Describe each source-resolved myocardial site, wall, thickness/morphology, fat, calcium or attenuation difference with its acquisition/phase and differential.','Assess actual coronary course/calcification and each source-resolved valve/annulus within technique limits; distinguish calcium location/burden from diagnostic stenosis or valve function.','Trace every covered aortic/pulmonary/venous channel, branch origin, course and endpoint, including actual variants and directly seen versus inferred connections.','Review all covered pericardial compartments/recesses and adjacent fat, fluid, thickening, calcium, cysts or masses with full source extent and uncertainty.']
    looks=['Trace venae cavae, RA/RV, pulmonary arteries, every covered pulmonary venous return, LA/LAA, LV and aortic outflow. Inspect septa, appendages, membrane/connection variants and source-resolved mass/defect interfaces.','Inspect all actually covered LV/RV/septal regions and endocardial/epicardial interfaces on appropriate windows and source reformats. Relate abnormalities to a stated region model if used; do not assign unassessed regions or estimate temporal function from stills.','Inspect coronary origins/courses and cumulative visible calcium; separate aortic valve leaflets from aortic wall/root, mitral annulus and coronary calcium. Review covered native/prosthetic valves and any visible coronary aneurysm, fistula or anomalous course with source limits.','Measure at named levels perpendicular to actual vessel axes with source calibration and stated edge convention. Trace systemic/pulmonary veins and covered arch/coronary/bronchial or systemic-lung branches and their actual drainage/attachments.','Assess covered pericardium around the heart, reflections/recesses and epicardial fat in original source planes. Record cyst/mass margins, adjacent interfaces and any source evidence for clinical effects.']
    tips=['Go-with-the-flow is an anatomical search mnemonic, not a measurement of flow, shunt direction or haemodynamics. Early contrast mixing can mimic LAA or chamber thrombus; report actual evidence and uncertainty rather than diagnose from one filling defect.','Unknown cardiac phase and oblique nongated planes can overestimate wall thickness. Fat, calcium or focal low attenuation support contextual differentials, not automatic infarct timing, viability, scar volume or cardiomyopathy aetiology.','For adequately covered nongated CT, a whole-patient visual CAC burden may be none/mild/moderate/severe with method/limits. That is not CAD-RADS stenosis grading or an uncalibrated Agatston score. Valve calcium alone does not independently establish haemodynamic valve severity.','No universal vessel size or artery-to-aorta ratio proves pulmonary hypertension, shunt flow or acute/chronic disease. Trace actual number, origin and venous drainage; left SVC drainage and pulmonary vein number are not universal normal configurations.','Fluid, thickening or calcification does not independently establish tamponade, constrictive physiology, infection or histology. Static images and generic geometry do not supply physiological measurements.']
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';data=json.loads(path.read_text());entry=data['investigations'][IDENT]
    for i,s in enumerate(entry['steps']):s.update(normal={},detail=details[i],look=looks[i],tip=tips[i])
    entry['steps'][1]['findings'][0]='Source-resolved myocardial fat/calcium in the [actual region]; associated thinning or other morphology [ ]; clinical/prior comparison and differential [ ].'
    entry['steps'][2]['findings'][0]='Whole-patient visual coronary calcium burden [none / mild / moderate / severe / unassessed], with actual coronary distribution and technique limits [ ].'
    entry['steps'][3]['findings'][1]='Main pulmonary artery [ ] mm at [source-defined axis/level]; comparison artery/reference and method [ ]; associated morphology [ ]; haemodynamic confirmation [available / unavailable].'
    entry['model']={'family':'heart','reporting_aim':'Partial cardiac orientation only. This companion does not supply the patient-specific chamber/appendage walls, coronary tree, all venous/arch variants, valve apparatus, myocardial lesions, pericardial compartments, repair anatomy or measured flow/function. Report from the actual CT source and retain nongated/phase/coverage limitations.'};path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());guide={'reviewed_at':'2026-10-06','protocol':['State actual CT indication, obtained coverage, contrast route/phase or unenhanced acquisition, ECG gating if any, reconstructed planes/resolution, source calibration, respiratory/cardiac motion and prior surgery/device context.','Review every covered cardiac/great-vessel compartment on original source and appropriate reformats/windows. Routine chest CT does not automatically supply diagnostic coronary, valve, temporal function, perfusion or tissue-characterisation data; unassessed/unresolved structures remain explicit.'],
      'checklist':[{'label':label,'detail':detail} for label,detail in zip(['Chambers','Myocardium','Coronaries And Valves','Great Vessels','Pericardium'],details)],'measurements':[{'name':'Visible vessel diameter','method':'Measure each actual source-resolved vessel perpendicular to its local axis at a named level, with stated edge convention, units, phase and calibration; retain non-diagnostic boundaries.','pitfall':'Motion, obliquity and nongated/contrast-phase limits affect root/vascular measurements; diameter does not independently measure pressure or shunt/function.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['Describe actual source-supported cardiovascular findings by site/extent and appropriate differential.','Separate anatomical/attenuation findings from functional, haemodynamic or diagnostic conclusions requiring further source evidence.','State contrast/gating/motion/coverage limits and comparison; contextual clinical assessment is not an automatic investigation or procedure mandate.'],
      'escalation':['Promptly communicate source-suspected acute cardiovascular abnormalities such as acute aortic pathology, embolic disease or rupture/haemorrhage with actual technique and uncertainty; management depends on the clinical team.'],
      'template_sections':[{'heading':'CHAMBERS','body':'Actual covered RA/RV/LA/LV and appendage boundaries [ ]; size/shape and source method/phase [ ]; septal or membrane/connection variant [ ]; filling defect/mass/mixing source and differential [ ]; unassessed regions and unavailable flow/function [ ].'},{'heading':'MYOCARDIUM','body':'Each actual covered chamber/region/layer interface [ ]; source-resolved thickness/morphology with phase/axis [ ]; fat/calcium/attenuation findings and extent [ ]; focal thinning, aneurysm/pseudoaneurysm/diverticulum or other component with actual neck/boundary [ ]; prior/clinical context and differential [ ]; unavailable temporal/perfusion/viability/tissue data [ ].'},{'heading':'CORONARIES AND VALVES','body':'Covered coronary origins/courses and actual anomaly/aneurysm/fistula if resolved [ ]; whole-patient visual CAC burden/method/limits [ ]; named distribution [ ]; no unsupported coronary stenosis/Agatston classification [ ]; aortic leaflet/root/wall versus mitral annular and other calcification sites [ ]; each covered valve/prosthesis morphology and source limits [ ]; valve functional data if separately obtained [ ].'},{'heading':'GREAT VESSELS','body':'Each covered aortic segment/branch, pulmonary artery and systemic/pulmonary venous channel [ ]; actual origin/course/drainage/attachment and variant [ ]; directly seen versus inferred or unassessed extent [ ]; local axis/edge-defined measurements and source phase [ ]; actual thromboembolic/wall/repair findings and confidence [ ]; unavailable pressure/shunt/perfusion evidence [ ].'},{'heading':'PERICARDIUM','body':'Covered layers/compartments/recesses and adjacent epicardial fat [ ]; actual fluid/thickening/calcium distribution and source-resolved boundaries [ ]; cyst/mass or other component and interfaces [ ]; prior/source comparison and differential [ ]; clinical/functional confirmation of tamponade/constriction or other effect if available [ ]; unresolved or uncovered extent [ ].'}],
      'sources':[{'title':title,'url':u} for title,u in zip(['RA cardiovascular pearls','RA chest cardiovascular pearls','Incidental cardiac disease CT pictorial review','BSCI/BSCCT/BSTI nongated calcification consensus'],URLS)]};data.setdefault(IDENT,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
if __name__=='__main__':update()
