#!/usr/bin/env python3
"""Require actual MRI/CT sinonasal tissue and bone sources; no patency, dehiscence or benignity invention."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.mri-sinuses'
URLS=['https://radiologyassistant.nl/head-neck/paranasal-sinuses/mri-examination','https://pmc.ncbi.nlm.nih.gov/articles/PMC11392720/','https://pmc.ncbi.nlm.nih.gov/articles/PMC11676659/']
def update():
    details=['Describe each actually covered sinus/compartment and source lesion/secretions/mucosa with extent, modality and uncertainty.','Trace source-resolved drainage/nasal routes, obstruction and variants without assuming visible aeration proves functional patency.','Assess actual operative landmarks/variants with appropriate acquired thin-bone source; do not infer absent dehiscence from unassessed or unresolved MRI.','Describe each source tissue/bone component and acquired signal/enhancement/diffusion/CT bone response with technique and differential.','Trace every source-supported extrasinus interface/route and uncertainty, separating visible morphology from histological/perineural/microbial confirmation.']
    looks=['Review every covered side/sinus, including actual frontal/maxillary/sphenoid/ethmoid subdivisions and variants. Trace full source lesion/secretions/mucosal boundaries on obtained sequences/windows; record unilateral/bilateral pattern and unassessed extent.','Inspect actual ostia/recesses/infundibular/nasal/choanal routes, turbinates/septum and relevant variants with the acquired source resolution. Contact/opacification is not a complete 3D tract or measured flow; unacquired CT/endoscopic information remains unavailable.','Use actually obtained thin-section bone imaging for relevant skull-base/lateral-lamella/foveal, lamina-papyracea and optic/carotid-canal relationships. Record measured source planes/calibration, asymmetry and uncertainty rather than forcing a normal or operative-risk category.','Distinguish source signal from true aeration, proteinaceous material, blood/fungal or solid components using actual pre/postcontrast T1/T2/other sequences, CT windows and DWI/ADC if obtained. Separate remodelling/sclerosis/calcification/dehiscence/destruction and marrow replacement.','Inspect covered orbital walls/compartments/apex, pterygopalatine/infratemporal/masticator routes, foramina/cranial nerves, skull-base marrow, cavernous sinus, dura/brain and adjacent soft tissues. Report every actual source extent/connection and unavailable contrast/diffusion or thin-bone information.']
    tips=['A low-signal MRI sinus is not automatically aerated; protein-rich/fungal/blood material may simulate air. Hyperdensity or high T2 signal alone does not establish benignity, organism or absence of tumour.','MRI anatomy/visible lumen does not alone prove complete drainage patency; low resolution or overlap must remain explicit. Use each actual source and variant, not an inherited generic sinus outline.','MRI soft-tissue detail cannot substitute for unacquired/unresolved thin-bone integrity. Partial volume can mimic defects; a missing wall on one image is not confirmed dehiscence or a normal operative variant.','Enhancement/diffusion/CT morphology can overlap across inflammation, secretions and neoplasia. DWI needs actual ADC/source technique; no unique histology, restricted diffusion or quantitative values are borrowed from unperformed sequences.','No extrasinus extension is asserted absent from unassessed anatomy. Perineural, orbital/cavernous or intracranial findings require appropriate source extent and clinical correlation; urgency or diagnosis is not inferred solely from the teaching-case label.']
    bodies=['Each actual covered side/sinus/compartment/variant [ ]; lesion versus secretions/mucosa and full obtained extent [ ]; sequence/window/contrast/calibration and quality [ ]; unilateral/bilateral distribution [ ]; unresolved or uncovered extent and differential [ ].','Actual source-visible ostia/recesses/drainage/nasal/choanal routes [ ]; each obstruction/contact/variant and surrounding interfaces [ ]; source resolution and uncertainty [ ]; unassessed thin-bone or endoscopic/functional information [ ].','Actual acquired operative-anatomy source/planes/resolution [ ]; skull-base/foveal/lateral-lamella and orbital wall relationships [ ]; optic/carotid and relevant canal/nerve variant [ ]; source-supported defect/asymmetry/measurement or uncertainty [ ]; unassessed integrity/risk components [ ].','Each actual solid/fluid/secretions/mucosal and bone/marrow component [ ]; source pre/postcontrast T1/T2/CT and DWI/ADC if acquired [ ]; calibrated extent/axis/method [ ]; remodelling/sclerosis/calcium/destruction or mimic [ ]; histological/microbial differential and missing sequences [ ].','Every source-supported orbital/apical, skull-base/foraminal/nerve, fossa/adjacent soft-tissue, cavernous/dural/intracranial route and obtained extent [ ]; margins/encasement/continuity or uncertainty [ ]; actual acquired source support and coverage limits [ ]; clinical/tissue/microbiological confirmation if supplied [ ]; unassessed interfaces [ ].']
    guide={'reviewed_at':'2026-10-07','protocol':['Record actual MRI sequences/contrast/DWI/ADC, coverage/resolution and available comparison. CT or other bone/drainage/clinical sources are separate and only used when actually acquired or supplied.','Review all covered sinus/drainage/tissue/operative and extrasinus interfaces; a parent sinus model or teaching diagnosis does not supply native patient walls, patency, histology, organism or extent.'],'checklist':[{'label':l,'detail':d} for l,d in zip(['Disease distribution','Surgical anatomy','Bone response','Tissue character','Spread'],[details[0],details[2],details[3],details[3],details[4]])],'measurements':[{'name':'Focal lesion extent','method':'Measure each relevant source-resolved tissue/component on actual orthogonal/local axes, sequence/window/contrast and source calibration, describing obtained extent and uncertainty.','pitfall':'Protein-rich or low-signal material does not uniquely establish tumour/air; selected stills do not supply full3D extent.'},{'name':'Surgical defect/variant','method':'State actual acquired bone source/resolution, named location, orthogonal planes, edge convention/calibration and uncertainty for a supported defect or variant.','pitfall':'Unacquired or unresolved thin-bone information cannot become a negative dehiscence statement or normal operative-risk class.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['Describe actual source-supported sinus/drainage/tissue/bone morphology and full obtained extent with modality/resolution limits.','Give a supported differential and any supplied tissue/clinical/organism confirmation; signal, hyperdensity, enhancement or diffusion alone does not uniquely diagnose or prove benignity.','Report relevant operative/extrasinus source findings and uncertainty, with unassessed anatomy and appropriate clinical/source-dependent urgency.'],'escalation':['Communicate suspected orbital/apical, intracranial, cavernous/vascular or acute invasive complications according to local clinical pathways; actual source/clinical context and confirmation govern management.'],'template_sections':[{'heading':h,'body':b} for h,b in zip(['SINUS DISTRIBUTION','DRAINAGE AND NASAL CAVITY','OPERATIVE ANATOMY','FOCAL TISSUE AND BONE','EXTRASINUS EXTENSION'],bodies)],'sources':[{'title':t,'url':u} for t,u in zip(['RA complementary sinonasal CT/MRI','2024sinonasal lesion review','2024nasal mass case series'],URLS)]}
    p=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(p.read_text());d.setdefault(IDENT,{})['reporting']=guide;p.write_text(json.dumps(d,indent=2)+'\n')
    p=ROOT/'data/radiology/reporting-steps/head-neck.json';raw=p.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['model']={'family':'sinuses','reporting_aim':'Partial sinonasal orientation only. This companion does not supply native patient drainage routes/functional patency, all thin bone/optic/carotid/nerve interfaces, source lesions, perineural or intracranial extent, histology or organism. Actual acquired MRI/CT/clinical sources and unassessed anatomy remain explicit.'}
    for i,s in enumerate(node['steps']):s['normal']={};s['detail']=details[i];s['look']=looks[i];s['tip']=tips[i]
    p.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:])
if __name__=='__main__':update()
