#!/usr/bin/env python3
"""Keep CT morphology distinct from confirmed PH and avoid central-clot and negative-quality presets."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.pulmonary-hypertension'
URLS=['https://radiologyassistant.nl/cardiovascular/thoracic-aorta-1/acute-aortic-syndrome-1','https://academic.oup.com/eurheartj/article/43/38/3618/6673929','https://pmc.ncbi.nlm.nih.gov/articles/PMC11657945/','https://pmc.ncbi.nlm.nih.gov/articles/PMC10971453/']
def update():
    details=['Record actual arterial opacification, motion/mixing and most distal reliably evaluable level for each side/territory; unassessed segments cannot be negative.','Describe every source-supported filling defect by named vessel/side, proximal/distal extent, occlusive component and confidence, including acute-on-chronic or mimic uncertainty.','Describe webs/bands, eccentric material, narrowing/pouch/recanalisation and collaterals with actual source morphology; chronic thromboembolic disease is distinct from confirmed haemodynamic PH.','Record actual phase/method-defined RV/LV and PA/aortic measurements, septal and source-reflux morphology; separate CT clues from obtained cardiac/haemodynamic results.','Review all covered parenchymal/pleural, small-airway/interstitial, left-heart/valve and congenital/venous connections relevant to the supplied question; keep alternative causes and unavailable perfusion/clinical evidence explicit.']
    looks=['Original thin arterial source images with orthogonal confirmation by territory; note bolus phase, transient mixing, cardiac/respiratory/metal artefact and partial volume. Do not extrapolate contrast quality from the main PA to distal branches.','Trace actual pulmonary trunk/bifurcation, right/left main, each covered lobar/segmental/subsegmental branch and variants. A defect can be central or eccentric; correlate margins, vessel calibre and source quality across planes.','Inspect actual vessel wall/lumen interfaces, webs/slits/bands, ring/length stenoses, pouch/tapered terminations, calcification, recanalisation and bronchial/nonbronchial systemic collateral routes. Retain mixed acute/chronic patterns and alternative intravascular causes.','Use declared axial/four-chamber or other source methods at stated planes; record phase/edge/calibration and prior comparison. Review RV/RA/LV/septum, valves/outflow, PA branches, coronary/root relations and caval/hepatic contrast reflux with injection context.','Assess every covered lobe/region, pleura, airways/interstitium and actual pulmonary venous/left-heart or shunt anatomy. Mosaic attenuation has vascular, airway and infiltrative differentials; expiration, iodine/perfusion maps, V/Q, MRI/echo and haemodynamic results are distinct sources only if actually obtained.']
    tips=['Absent contrast or severe motion is a technical limitation, not proof of occlusion or a negative embolic examination. Record affected segments and unresolved defect/mixing boundaries.','Acute emboli may be eccentric as well as central. No location/angle alone dates a clot or excludes acute-on-chronic disease; distinguish source filling defects from motion, mixing, partial-volume or other mimics.','CTEPD may occur without PH; CT chronic morphology alone does not establish CTEPH or operability. A limited or negative CTPA does not alone exclude distal chronic disease; clinical/perfusion assessment is separate.','CT dimensions, RV/LV, septal shape and reflux suggest morphology, not measured pressure or EF. In the named 2022 ESC/ERS definition PH requires resting mPAP >20 mmHg by haemodynamic source; precapillary pattern also requires PAWP ≤15 mmHg and PVR >2 WU. No such values are inferred from CT.','Emphysema/fibrosis, mosaic attenuation, septal thickening or a filling mass are differential clues, not automatic WHO-group, PVOD, sarcoma, infarct or viability diagnoses. Trace actual connections and retain clinical/tissue/functional uncertainty; no treatment choice is made from the companion model.']
    path=ROOT/'data/radiology/reporting-steps/cardiovascular.json';data=json.loads(path.read_text());entry=data['investigations'][IDENT]
    for i,s in enumerate(entry['steps']):s.update(normal={},detail=details[i],look=looks[i],tip=tips[i])
    entry['steps'][4]['findings']=['Source-observed peripheral wedge-shaped opacity in [actual region]; imaging/clinical differential and comparison [ ].','Mosaic attenuation in [regions], with source vascular calibre/airway/interstitial observations [ ]; unavailable expiration/perfusion evidence [ ].','Emphysema/fibrosis/left-heart or other associated morphology [ ]; supplied clinical/haemodynamic classification [available / unavailable].']
    entry['model']={'family':'thorax','reporting_aim':'Partial thoracic orientation only. This companion does not supply patient-specific distal pulmonary arteries/veins, all branch variants, emboli/webs/stenoses, bronchial collaterals, complete right-heart wall/valves, microvascular disease or measured perfusion/pressure/function. Report actual acquired sources; missing or unresolved anatomy remains unassessed.'};path.write_text(json.dumps(data,indent=2,ensure_ascii=False)+'\n')
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';data=json.loads(path.read_text());guide={'reviewed_at':'2026-10-06','protocol':['State actual clinical question, contrast/CTPA or other acquired CT method, coverage, bolus timing, motion/metal/partial-volume limits and prior treatment/context. Assess every actually covered territory separately.','Separate source CT morphology from dynamic perfusion, V/Q, echo/MRI, catheter pressures/resistance and clinical/tissue diagnosis; identify the source, date, definition and uncertainty of any supplied measurements.'],
      'checklist':[{'label':label,'detail':detail} for label,detail in zip(['Adequacy','Thrombus','Chronicity','Right heart','Consequences'],details)],'measurements':[{'name':'RV/LV ratio','method':'Record source RV and LV diameters with named matching method/planes, cardiac phase if known, units/calibration and ratio uncertainty; compare actual prior method/coverage.','pitfall':'Morphological ratio is not independently measured pressure, EF or unique acute strain/aetiology.'},{'name':'Main pulmonary artery','method':'Measure source-resolved PA perpendicular to its local axis at a named level and source phase; use a stated ascending-aortic/reference measurement method and edge convention if ratio is reported.','pitfall':'PA diameter/ratio alone does not diagnose haemodynamic PH or establish a clinical group; motion and contrast/coverage limits remain.'}],
      'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['State actual source-supported defects by side, named vessel and full obtained extent with per-territory technical confidence.','Separate acute, chronic, mixed and uncertain morphology from haemodynamic PH, functional severity and clinical/operability conclusions.','Describe associated cardiac, pulmonary venous, lung/pleural and shunt findings with actual source/clinical correlation and unperformed tests.'],
      'escalation':['Communicate source-suspected acute PE or significant associated cardiac findings and limitations according to local urgency pathways; clinical severity and management depend on supplied clinical/haemodynamic assessment.'],
      'template_sections':[{'heading':'ARTERIAL QUALITY','body':'Actual CT/contrast phase and source calibration/coverage [ ]; side/territory opacification and motion/mixing/metal/partial-volume limits [ ]; most distal actually evaluable branch per territory [ ]; unevaluable or unassessed segments [ ]; effect on defect assessment [ ].'},{'heading':'EMBOLI','body':'Source-supported defect [absent in evaluable territory / present / indeterminate]; each named side/vessel and proximal/distal extent [ ]; occlusive component/margins [ ]; central/eccentric or other morphology [ ]; actual acute/chronic/mixed differential and confidence [ ]; mimics/unresolved or uncovered extent [ ].'},{'heading':'CHRONIC FEATURES','body':'Actual webs/bands/slits, wall-adherent material/calcium, stenosis/length, pouch/tapered occlusion, recanalisation or vessel remodelling [ ]; each branch and collateral origin/course/reconstitution [ ]; prior/source comparison [ ]; acute-on-chronic or other intravascular differential [ ]; CTEPD versus supplied haemodynamic PH evidence [ ]; technique limits [ ].'},{'heading':'RIGHT HEART AND PULMONARY ARTERY','body':'RV/LV source diameters, named planes/method/phase/calibration and ratio with limits [ ]; RV/RA wall/shape, septum and source caval/hepatic reflux with injection context [ ]; PA/aortic diameter site/axes/edge convention [ ]; separate actual echo/MRI/RHC source/date/values/units and definition if provided [ ]; unavailable pressure/resistance/function and comparison [ ].'},{'heading':'LUNGS AND ASSOCIATED CAUSES','body':'Each covered lobe/region: opacity/infarct differential, mosaic attenuation with vascular/airway/interstitial findings, septa, pleura and nodes [ ]; actual left-heart/valve, pulmonary venous and congenital/shunt connections [ ]; source iodine/expiration/perfusion/VQ or other acquisitions if obtained [ ]; PVOD/sarcoma/other cause differential with clinical/tissue evidence or uncertainty [ ]; unassessed extent/tests and prior change [ ].'}],
      'sources':[{'title':t,'url':u} for t,u in zip(['RA PH/thromboembolic imaging','2022 ESC/ERS PH definitions','CTEPD imaging review (source text only; restricted figures)','Updated clinical/haemodynamic definitions review'],URLS)]};data.setdefault(IDENT,{})['reporting']=guide;path.write_text(json.dumps(data,indent=2)+'\n')
if __name__=='__main__':update()
