#!/usr/bin/env python3
"""Require actual chest radiograph projection, interfaces and comparison; no normal/exposure/device invention."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];IDENT='ra.chest-radiography'
URLS=['https://radiologyassistant.nl/chest/chest-x-ray/basic-interpretation','https://radiologyassistant.nl/chest/chest-x-ray/heart-failure','https://radiologyassistant.nl/chest/chest-x-ray/lung-disease','https://pmc.ncbi.nlm.nih.gov/articles/PMC12127945/']
def update():
    details=['Record actual source projection, position, acquisition/coverage and quality; distinguish technical limitations and artefacts from disease.','Inspect every covered airway, hilar, mediastinal and cardiac silhouette/interface with source projection limits; do not infer resolved chamber/wall anatomy or physiology from overlap.','Describe each actual pulmonary opacity/lucency, vascular or volume-change pattern and covered regional extent; assess hidden and overlapping areas with appropriate uncertainty.','Assess each actually visible pleural/diaphragmatic/recess interface and complication, with projection/position-dependent visibility and source limits.','Trace each actually present device and inspect all covered osseous/soft-tissue/upper-abdominal review regions; record full obtained route/tip/landmark relation and unresolved extent.']
    looks=['Confirm actual AP/PA/lateral or other view and erect/supine/decubitus position from source data; assess rotation, inspiration, penetration, motion, clipping, artefacts and source scaling. No view is assumed present.','Inspect trachea/carinal/main bronchial region, both hila, cardiac borders, aortic/pulmonary/caval contours, mediastinal lines/recesses and retrosternal/retrocardiac regions. Silhouette loss is a projected interface clue; correlate views only if acquired.','Inspect apices, perihilar/retrocardiac and subdiaphragmatic lung, every covered zone and any supported lobar/localisation signs. Describe each consolidation/interstitial/nodular/mass/lucent or volume-loss component and actual air bronchogram/fissural/hilar displacement without assuming one cause.','Assess both apices, lateral/posterior costophrenic regions if obtained, fissural/subpulmonic compartments, pleural lines and diaphragmatic contours. Supine air/fluid distribution differs from erect views. Distinguish skinfolds, bullae and other mimics with source confidence.','Trace each airway/enteric/vascular/drain/device route, tip and visible ports against actual landmarks; note device type, acquisition time and any position-dependent uncertainty. Review each covered rib/clavicle/scapula/vertebral/sternal region, joints, chest-wall/breast/neck soft tissue and visible upper abdomen.']
    tips=['Technical correction, crop or annotation removal can change source presentation; preserve original source and disclose processing. An unavailable or limited view is not an adequately assessed negative study.','CTR interpretation requires the actual method and projection; AP/supine magnification or poor inspiration must not be treated as standard PA size. Silhouette enlargement does not measure pressure, EF, shunt or establish a unique cause.','Consolidation, oedema, infection, haemorrhage, collapse and malignancy can overlap. Air bronchograms or projected volume-loss signs support a differential, not unique pathology or microscopic confirmation.','An inconspicuous pneumothorax/effusion on a limited/supine film is not exclusion. Do not derive an exact fluid volume, tension physiology or fluid chemistry from one projection. Free gas/urgent findings require actual source and clinical assessment.','No device or complication is asserted absent until actual covered sources are assessed. Projected tip distances require named landmarks, phase/position and calibration; lumen/wall/3D course and dynamic function may remain unresolved.']
    sections=[{'heading':h,'body':b} for h,b in zip(['PROJECTION AND QUALITY','AIRWAYS AND CARDIOMEDIASTINUM','LUNGS','PLEURA AND DIAPHRAGM','DEVICES AND BONES'],['Actual acquired views/projection/position/date [ ]; coverage, rotation, inspiration, exposure/penetration/motion and artefacts [ ]; source scaling/processing [ ]; effect on assessment and unavailable views [ ].','Actual airway/carinal/hilar/mediastinal/cardiac contour and silhouette findings [ ]; named interface and obtained-view support [ ]; size method/projection/calibration and uncertainty [ ]; unresolved tissue or missing physiological/clinical confirmation [ ].','Each actual covered region and opacity/lucency/nodule/mass/interstitial or vascular pattern [ ]; air bronchogram, volume/displacement and supported localisation [ ]; hidden apical/perihilar/retrocardiac/subdiaphragmatic regions [ ]; differential, comparison and technical limits [ ].','Each visible pleural/recess/fissural/diaphragmatic interface [ ]; source air/fluid/thickening or other component and projected extent [ ]; actual position/view and confidence [ ]; mimics, subdiaphragmatic gas and source/clinical urgency [ ]; unassessed extent [ ].','Each actually present device/type/route/tip/port and named landmarks [ ]; source date/view/position and calibrated distance if justified [ ]; possible complication and uncertainty [ ]; each covered bone/joint/soft-tissue/upper-abdominal finding [ ]; incomplete route or covered-region limits [ ].'])]
    guide={'reviewed_at':'2026-10-07','protocol':['Confirm actually acquired views and source position, coverage, acquisition time and processing. Compare prior views with their own geometry/quality; missing lateral or other projections remain unavailable.','Review every covered central/peripheral/hidden interface systematically. Radiography is projection imaging: source silhouettes do not establish all native tissue boundaries, complete3D anatomy or clinical physiology.'],'checklist':[{'label':l,'detail':d} for l,d in zip(['Quality','Airways and mediastinum','Lungs','Pleura','Devices and review areas'],details)],'measurements':[{'name':'Cardiothoracic ratio','method':'Record actual cardiac/thoracic diameter method, acquired projection, position, inspiration and source calibration/uncertainty. Interpret only within a stated appropriate protocol.','pitfall':'AP/supine magnification and low inspiration do not supply a comparable standard PA ratio or measured cardiac function.'},{'name':'Device tip distance','method':'Use actual tip/port and named source landmark on a stated view/position with real calibration; record respiratory/temporal and overlap uncertainty.','pitfall':'A projected distance or single view does not prove full3D intraluminal course, intended device function or unchanged position.'}],'classification':None,'criteria_table':None,'pitfalls':tips,'impression_prompts':['Describe actually supported source findings, regional extent, projection quality and unassessed interfaces.','State a supported differential and comparison limitations; separate morphology from clinical/physiological confirmation.','Report actual device/complication findings and appropriate source/context-dependent urgency.'],'escalation':['Communicate suspected urgent pneumothorax, free gas, device complication or acute cardiopulmonary findings through local clinical pathways; tension/instability depends on actual source and clinical assessment.'],'template_sections':sections,'sources':[{'title':t,'url':u} for t,u in zip(['RA systematic chest anatomy','RA projection-dependent heart failure signs','RA pulmonary patterns/localisation','Original radiograph quality-control study; text/processing limits only'],URLS)]}
    path=ROOT/'data/radiology/investigation-overrides-non-msk.json';d=json.loads(path.read_text());d.setdefault(IDENT,{})['reporting']=guide;path.write_text(json.dumps(d,indent=2)+'\n')
    path=ROOT/'data/radiology/reporting-steps/chest.json';raw=path.read_text();start=raw.index('{',raw.index('"'+IDENT+'"'));node,end=json.JSONDecoder().raw_decode(raw,start);node['model']={'family':'thorax','reporting_aim':'Partial thoracic orientation only. This companion does not supply actual patient projection geometry, all native hilar/mediastinal/pleural interfaces, every rib/joint/soft tissue, disease/device3D routes or cardiac/respiratory function. Report actual acquired sources; unresolved or uncovered anatomy remains unassessed.'}
    for i,s in enumerate(node['steps']):s['normal']={};s['detail']=details[i];s['look']=looks[i];s['tip']=tips[i]
    path.write_text(raw[:start]+json.dumps(node,indent=2,ensure_ascii=False).replace('\n','\n    ')+raw[end:])
if __name__=='__main__':update()
