"""Build original, topic-specific reporting worksheets (no source article copying).

The compact specifications below are authored content. Radiology Assistant's
separate catalog supplies linked foundation readings, not report wording.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# id suffix: clinical fields ; key-image purposes ; interpretive pitfall
SPECS = {
'contrast': ('Agent, concentration, dose, route and injection rate|Renal function and acute kidney injury|Previous contrast reaction: agent, symptoms and severity|Pregnancy, relevant medication and alternative imaging|Extravasation or reaction: observations, treatment and outcome', 'Injection and timing record|Diagnostic phase adequacy|Complication if present', 'Record the actual agent and reaction phenotype; an allergy label alone is insufficient for planning a future examination.'),
'radiation-safety': ('Clinical justification and alternatives|Patient size, pregnancy enquiry where applicable|Scan range, phases and acquisition settings|CTDIvol, DLP or modality-specific dose metrics|Optimisation and explanation of any repeat acquisition', 'Scan coverage|Dose report|Example of diagnostic image quality', 'Scanner dose indices describe the examination; they are not a direct measurement of an individual patient’s organ dose.'),
'ct-image': ('Acquisition, reconstruction thickness and interval|Soft tissue, lung and bone windows|Attenuation measurement: HU, ROI and phase|Multiplanar localisation|Artefact and its effect on interpretation', 'Matched soft-tissue window|Matched lung or bone window|Orthogonal reformatted image', 'Compare like phases and avoid partial-volume ROIs; a single postcontrast attenuation is not a measurement of enhancement.'),
'mri-sequences': ('Sequence identity: T1, T2, fluid-sensitive, DWI and ADC|Fat suppression and chemical shift|Diffusion: b values and matched ADC|Precontrast and postcontrast comparison|Motion, susceptibility and subtraction artefact', 'Matched T1 and T2|DWI with corresponding ADC|Precontrast and postcontrast subtraction', 'High diffusion-weighted signal needs an ADC comparison; T2 shine-through must not be called restricted diffusion.'),
'modalities': ('Clinical question and urgency|Modality and coverage selected|Contrast or tracer requirement|Contraindications and patient preparation|Expected strengths, limitations and alternative examination', 'Anatomic overview|Question-specific acquisition|Limitation or blind spot', 'The best modality is the one that can answer the specific clinical question with an acceptable acquisition in this patient.'),
'ultrasound-physics': ('Transducer frequency, depth and focus|Gain, dynamic range and harmonic settings|Compression and patient positioning|Doppler: angle, scale, wall filter and spectral sample|Artefact: shadow, enhancement, aliasing or reverberation', 'Grayscale target and landmarks|Colour Doppler with settings|Spectral trace with angle correction', 'Absence of colour signal at insensitive settings is not proof of absent flow.'),
'biopsy-safety': ('Target and diagnostic question|Consent, anticoagulation, coagulation and antibiotic plan|Route, intervening structures and guidance modality|Needle or catheter, passes and specimen handling|Immediate complications and postprocedure plan', 'Target and planned safe route|Needle tip within target|Postprocedure complication check', 'Confirm that the route avoids vulnerable structures and that tissue is sent in the correct medium for the requested analyses.'),
'oncology-response': ('Cancer type, therapy and baseline date|Target lesions: organ, series/image and diameter|Sum of diameters at baseline, nadir and current study|Non-target disease and new lesions|Response criteria, version and overall category', 'Matched target at baseline|Matched target at nadir|Current target or new lesion', 'A response category depends on the named criteria and reference timepoint; describe unequivocal progression separately from uncertain new findings.'),
'structured-reporting': ('Clinical question and comparison|Technique and diagnostic limitations|Required organ or segment observations|Measurements, classification and evidence|Concise impression and communication', 'Overview with orientation|Decisive finding and measurement|Image supporting the impression', 'Unfilled brackets are prompts, not negative findings. Delete irrelevant sections and reconcile the impression with the observations.'),
'ir-basics': ('Indication, consent and preprocedure assessment|Vascular or percutaneous access and guidance|Diagnostic angiographic or drainage findings|Devices, embolic material and technical endpoint|Complications, haemostasis, drains and follow-up', 'Access and anatomy|Target before treatment|Final angiogram or catheter position', 'A technical endpoint does not by itself establish clinical success; state how and when the clinical response will be assessed.'),
'airways': ('Trachea and central bronchi|Bronchiectasis: distribution, calibre and wall thickening|Small-airway nodules and tree-in-bud pattern|Mosaic attenuation and expiratory air trapping|Mucus plugging, collapse and complications', 'Central airway multiplanar view|Representative abnormal bronchus|Matched inspiratory and expiratory levels', 'Separate air trapping from other causes of mosaic attenuation using expiratory imaging and the vascular pattern.'),
'hrct': ('Inspiratory, expiratory and prone acquisitions|Dominant pattern: reticulation, ground glass, nodules or cysts|Axial and craniocaudal distribution|Traction bronchiectasis and honeycombing|Ancillary findings and fibrosis pattern category', 'Representative upper-lung level|Basal and subpleural pattern|Prone or expiratory discriminator', 'Describe the pattern and confidence before naming a disease; dependent density and emphysema can imitate interstitial abnormalities.'),
'mediastinum': ('Compartment and relation to adjacent structures|Size, attenuation or signal and enhancement|Fat, fluid, calcification and solid components|Nodal stations and short-axis measurements|Compression, invasion and associated thoracic findings', 'Compartment on axial image|Coronal extent|Nodes or threatened adjacent structure', 'Use an explicit nodal map; a mediastinal station number is not interchangeable with a descriptive anatomic label.'),
'pleura': ('Laterality and extent of effusion or pneumothorax|Pleural thickness, nodularity and enhancement|Loculation, gas and drain position|Adjacent lung expansion and parenchymal disease|Chest wall, diaphragm and mediastinal involvement', 'Overall pleural distribution|Pleural abnormality or loculation|Drain position or associated lung finding', 'Imaging may suggest pleural infection or malignancy but does not replace appropriate fluid or tissue sampling.'),
'chest-infection': ('Distribution and dominant parenchymal pattern|Cavitation, tree-in-bud and bronchial changes|Pleural collections and lymph nodes|Complications and interval change|Clinical and microbiological correlation', 'Representative airspace opacity|Cavity or small-airway pattern|Complication or interval comparison', 'A CT pattern alone does not identify the organism. CO-RADS is a historical COVID suspicion scheme, not microbiological confirmation.'),
'pe-pulm-htn': ('Pulmonary arterial opacification and motion|Embolus: vessel, side and most proximal level|Acute or chronic morphological features|RV/LV relationship and other right-heart findings|Infarction, pleura and alternative explanation', 'Most proximal embolus|RV and LV comparison|Chronic web, perfusion pattern or infarct', 'Report technical limits and right-heart findings; imaging severity alone does not determine haemodynamic instability.'),
'lung-cancer': ('Primary lesion: lobe, size and solid component|Local invasion, separate nodules and atelectasis|Nodes: stations and short axis|Pleural, adrenal, hepatic, bone and other spread|Imaging TNM with named edition and uncertain components', 'Primary tumour measurement|Most consequential nodal station|Suspected local invasion or distant disease', 'State the staging edition used; imaging suspicion of nodal disease is not histological proof.'),
'chest-xray': ('Projection, rotation, inspiration and exposure|Airways and cardiomediastinal contours|Lungs: focal or diffuse opacity and volume loss|Pleura: effusion or pneumothorax|Bones, soft tissues, tubes and lines', 'Whole chest projection|Focused finding|Prior comparison or device tip', 'Account for projection and inspiratory volume before interpreting cardiac size or basal density.'),
'pulmonary-nodule': ('Risk context, age and applicable pathway|Nodule: lobe, type and mean diameter or volume|Solid component of a subsolid nodule|Morphology, calcification and perifissural features|Growth, comparison interval and follow-up eligibility', 'Thin-section nodule with measurement|Orthogonal view or solid component|Matched prior examination', 'Do not apply an incidental-nodule table to screening, known cancer or immunosuppression without checking its exclusions.'),
'aorta': ('Technique: unenhanced, angiographic and relevant delayed phase|Dissection flap, intramural haematoma or penetrating ulcer|Proximal/distal extent and branch-vessel involvement|Orthogonal aortic measurements|Rupture, pericardial blood and organ malperfusion', 'Proximal extent|Branch involvement or true/false lumens|Rupture or malperfusion feature', 'Identify ascending-aortic involvement and threatened branches explicitly; record urgent communication rather than relying on report delivery.'),
'cardiac-mri': ('Acquisition and limitations|LV and RV indexed volumes, ejection fractions and mass|Regional wall motion|Oedema, mapping values and local reference ranges|Late enhancement: location, transmurality and distribution', 'Cine end diastole and end systole|Mapping or oedema sequence|Late enhancement in matching planes', 'Interpret mapping against the local scanner/sequence reference range; an enhancement pattern supports but does not independently prove an aetiology.'),
'cardiac-masses-devices': ('Mass or device location and dimensions|Attachment, mobility and relation to valves|Signal, attenuation, perfusion and enhancement|Obstruction, embolic sequelae and pericardium|Device continuity, lead tip and complications', 'Mass attachment or device course|Contrast behaviour|Functional effect or complication', 'Distinguish normal structures and thrombus from a mass before inferring tumour histology.'),
'congenital-ct': ('Situs and systemic/pulmonary venous connections|Atrioventricular and ventriculoarterial connections|Septal defects and chamber relationships|Great arteries, arch and pulmonary arteries|Coronary origins, shunts and postoperative anatomy', 'Segmental anatomy overview|Venous and arterial connections|Coronary or postoperative detail', 'Use sequential segmental description; apparent left/right position alone cannot identify a morphological chamber.'),
'coronary-ct': ('Coronary quality and dominance|Origins and course|Segment-level stenosis and plaque|Plaque burden and modifiers|CAD-RADS 2.0 impression', 'Coronary origins|Curved MPR of stenosis|Plaque and extracardiac finding', 'Use the expanded CCTA template for complete CAD-RADS reporting.'),
'peripheral-vascular': ('Territory, technique and timing|Inflow, lesion location, length and severity|Occlusion, reconstitution and collateral pathways|Runoff and distal target vessels|Aneurysm, wall disease and nonvascular findings', 'Inflow overview|Worst lesion in orthogonal plane|Distal runoff or collateral pathway', 'State the reference method for a stenosis measurement; criteria differ by vascular bed and imaging modality.'),
'tavi-ct': ('Annulus: systolic phase, area, perimeter and diameters|Valve morphology and calcification distribution|Coronary heights and sinus dimensions|Sinotubular junction and ascending aorta|Iliofemoral access: minimum lumen, calcification and tortuosity', 'Double-oblique annular plane|Coronary height measurement|Narrowest access segment', 'Measure luminal calibre on a plane orthogonal to the vessel; device selection belongs to the multidisciplinary planning process.'),
'stroke': ('Last-known-well context and acquisition times|Haemorrhage and established ischaemic change|Vessel occlusion: side and segment|Collateral status and cervical vessels|Perfusion maps, mismatch and technical limitations', 'Noncontrast brain finding|Occlusion on CTA|Perfusion/ collateral finding if acquired', 'Describe actual imaging findings and timing; automated perfusion maps need quality review and clinical correlation.'),
'brain-tumour': ('Intra- or extra-axial location and size|T1/T2/FLAIR, diffusion and susceptibility|Enhancement, perfusion and spectroscopy if obtained|Oedema, mass effect, ventricular obstruction|Multiplicity, dissemination and prior treatment', 'Lesion in orthogonal planes|Enhancement and diffusion|Mass effect or dissemination', 'Report the compartment and imaging differential; imaging alone cannot establish the molecular tumour classification.'),
'brain-anatomy': ('Side, lobe and cortical/deep grey localisation|White matter tract and commissural relationship|Arterial territory and borderzone pattern|Brainstem/cerebellar compartment|Relevant ventricular, cisternal and venous anatomy', 'Axial localisation|Coronal anatomic relationship|Vascular territory overview', 'Anatomic variants and overlapping vascular territories limit assignment from location alone.'),
'cns-infection': ('Meningeal, ependymal or parenchymal distribution|Diffusion restriction and ADC|Ring, nodular or leptomeningeal enhancement|Haemorrhage, oedema and mass effect|Sinus/ear source, vascular complications and hydrocephalus', 'Enhancement distribution|DWI with ADC|Source or intracranial complication', 'Restricted diffusion supports some infections but is not organism-specific; urgently describe obstructive hydrocephalus or herniation.'),
'venous-csf': ('Venous opacification and filling defects|Sinus/cortical vein location and extent|Venous infarction or haemorrhage|Brain sag, dural enhancement and subdural collections|Spinal leak localisation if studied', 'Venographic abnormality|Parenchymal consequence|CSF-related sign or leak level', 'Normal venous variants and flow gaps can mimic thrombosis; combine source images with the appropriate venographic sequence.'),
'dementia': ('Protocol and motion limits|Global and regional atrophy pattern|Medial temporal and other named visual ratings|White matter burden and strategic infarcts|Microbleeds, superficial siderosis and alternative structural causes', 'Coronal medial temporal level|Regional cortical atrophy|FLAIR and susceptibility findings', 'Use age-aware interpretation and named rating scales; MRI supports the clinical assessment rather than determining dementia subtype alone.'),
'epilepsy-mri': ('Dedicated protocol and motion|Hippocampal volume, architecture and signal|Cortical thickness and grey-white junction|Focal lesion, malformation or acquired injury|Concordance with clinical/EEG localisation', 'Coronal hippocampal plane|High-resolution cortical abnormality|Matched FLAIR/T2 finding', 'A normal structural MRI does not exclude epilepsy; record whether an epilepsy-specific acquisition was adequate.'),
'head-trauma': ('Scan technique and time from injury|Extra-axial blood and contusions|Skull/base fracture and extracranial soft tissues|Mass effect, cisterns and midline shift|Interval change and vascular injury concern', 'Haemorrhage overview|Bone-window fracture|Cisterns and mass effect', 'Document urgent communication for critical findings and distinguish imaging observations from clinical CT selection rules.'),
'intracranial-haemorrhage': ('Compartment, site, extent and dimensions|Intraventricular or subarachnoid extension|Oedema, hydrocephalus and shift|CTA/MRA: aneurysm or vascular malformation if acquired|Interval change and suspected underlying lesion', 'Haemorrhage distribution|Ventricular/cisternal effect|Underlying vascular abnormality', 'Different haemorrhage compartments imply different causes; describe the distribution before assigning an aetiology.'),
'ms-white-matter': ('Lesion number and periventricular, juxtacortical, infratentorial or cord location|Lesion morphology and orientation|New or enlarging T2 lesions against dated comparison|Enhancing lesions and sequence timing|Mimics, vascular burden and atypical features', 'Representative distribution|New lesion matched to prior|Enhancing or spinal lesion', 'Apply the explicitly named diagnostic criteria in clinical context; nonspecific white-matter foci are not equivalent to multiple sclerosis.'),
'spine-imaging': ('Vertebral numbering and alignment|Fracture morphology and ligament complex|Level-specific discs, canal and foramina|Cord, conus and cauda equina|Marrow, epidural collection and paraspinal tissues', 'Sagittal overview|Axial worst level|Cord/ligament or epidural abnormality', 'State numbering assumptions and report the structure actually compressed, including side and level.'),
'neck-nodes': ('Primary disease context|Side and cervical nodal level|Short axis, shape, necrosis and enhancement|Extranodal extension features|Vascular encasement and additional nodal stations', 'Level-defining landmarks|Most suspicious node|Suspected extranodal extension', 'Size is one feature; morphology and drainage territory can matter even when a node is small.'),
'deep-neck-spaces': ('Epicentre and involved supra/infrahyoid spaces|Fluid, fat, solid tissue and enhancement|Airway narrowing and displacement|Vascular involvement and thrombosis|Skull-base, mediastinal and perineural extension', 'Space of origin|Airway and vascular relationship|Inferior or skull-base extension', 'Displacement of normal fat planes helps localise a lesion; a collection and inflamed solid tissue may require different next steps.'),
'orbit': ('Globe, lens and optic nerve|Intraconal/extraconal compartment and extraocular muscles|Bone, foreign body and traumatic changes|Enhancement, diffusion and inflammatory spread|Orbital apex, cavernous sinus and intracranial extension', 'Lesion compartment|Coronal muscle/optic nerve view|Orbital apex or fracture', 'Check for a potentially metallic intraorbital foreign body before selecting MRI in the appropriate trauma context.'),
'sinuses': ('Sinuses involved and drainage pathway|Secretions, mucosal disease and enhancement|Bone remodelling, erosion or dehiscence|Orbit, skull base and intracranial spread|Surgical variants and prior intervention', 'Ostiomeatal complex|Bone boundary or variant|Extrasinus extension', 'Describe aggressive extrasinus findings separately from routine mucosal thickening.'),
'temporal-bone': ('External auditory canal and tympanic membrane|Middle ear, ossicles and mastoid|Otic capsule, facial nerve canal and tegmen|Inner ear and internal auditory canal|DWI/enhancement if MRI performed', 'Ossicles and epitympanum|Otic capsule and facial canal|Diffusion lesion or tegmen defect', 'Small anatomy requires appropriate thin sections; postoperative change can alter both the expected landmarks and the differential.'),
'thyroid-tirads': ('Thyroid size and background parenchyma|Each nodule: location and three dimensions|Composition, echogenicity, shape, margins and echogenic foci|ACR TI-RADS points and category per nodule|Cervical nodes and applicable size-based recommendation', 'Nodule transverse measurements|Longitudinal nodule view|Suspicious feature or lymph node', 'A category and a management recommendation are separate outputs; the latter also depends on nodule size and clinical context.'),
'pancreas-acute': ('Timing from symptom onset and technique|Pancreatic enlargement and enhancement|Necrosis: site and extent|Collections: location, content, wall and timing|Vascular, ductal and other complications', 'Pancreatic enhancement|Collection wall and solid debris|Vascular or ductal complication', 'Collection terminology depends on content and time; gas raises concern for infection but needs clinical correlation.'),
'appendicitis': ('Appendix visibility, location and diameter|Wall, enhancement and compressibility|Appendicolith and periappendiceal inflammation|Perforation, collection and obstruction|Alternative cause and examination limits', 'Appendix longitudinal view|Transverse measurement|Complication or alternative diagnosis', 'A nonvisualised appendix is not automatically a normal appendix; state secondary signs and examination limitations.'),
'biliary': ('Gallbladder distension, wall and contents|Intra/extrahepatic duct calibre and level of obstruction|Stone, stricture or mass|Pericholecystic inflammation and complications|Liver, pancreas and postoperative anatomy', 'Gallbladder wall and contents|Duct calibre and obstruction|Causative lesion or complication', 'Gallbladder wall thickening has non-biliary causes; interpret it with distension, local inflammation and the clinical context.'),
'bowel-ischaemia': ('Mesenteric arterial and venous patency|Affected bowel distribution and enhancement|Wall thickness, dilation and pneumatosis|Mesenteric oedema, ascites and portal venous gas|Perforation and other organ hypoperfusion', 'Arterial or venous cause|Bowel enhancement comparison|Complication or affected territory', 'An unenhanced examination cannot reliably assess mural enhancement; communicate suspected threatened bowel urgently.'),
'bowel-obstruction': ('Bowel segment, calibre and obstruction grade|Transition point and suspected cause|Closed-loop configuration and mesenteric twist|Mural enhancement and mesenteric vessels|Free fluid, pneumatosis and perforation', 'Transition point|Second transition or closed loop|Enhancement/vascular complication', 'Identify both transition points when a closed loop is suspected and assess ischaemic complications explicitly.'),
'abdominal-trauma': ('Acquisition phases and limitations|Organ injuries with location and dimensions|Active bleeding, pseudoaneurysm and vascular injury|Bowel, mesentery, urinary tract and diaphragm|Haemoperitoneum and associated fractures', 'Most consequential organ injury|Arterial bleeding focus|Delayed phase or associated injury', 'Name the grading system/version and describe active vascular findings independently of the grade.'),
'ibd': ('Bowel preparation, distension and motion|Involved segments, length and mural thickness|Oedema, enhancement, ulcers and diffusion|Stricture length and prestenotic dilation|Fistula, abscess, mesentery and extraintestinal findings', 'Most active bowel segment|Stricture and proximal dilation|Penetrating complication', 'Imaging features of inflammation and fibrosis overlap; avoid claiming an exact tissue fraction from routine images.'),
'pancreas-tumour': ('Mass/cyst site, dimensions and enhancement|Main duct and common bile duct|Arterial and venous contact: vessel, angle, length and narrowing|Nodes, liver, peritoneum and other spread|Cyst morphology, mural nodule and duct communication', 'Primary lesion and ducts|Vessel contact on orthogonal planes|Metastasis or cyst mural nodule', 'Separate a cystic-lesion characterisation from a pancreatic-cancer staging report; vascular contact must be described vessel by vessel.'),
'peritoneum': ('Peritoneal and mesenteric distribution|Nodules, plaques, omental change and ascites|Bowel serosa, mesenteric root and organ surfaces|Abdominal wall defect, sac and contents|Obstruction, strangulation or other complications', 'Distribution overview|Mesenteric root or critical implant|Hernia neck and contents', 'State the sites that affect surgical access or resectability; a global label of carcinomatosis loses important anatomy.'),
'rectal-mr': ('Primary site, height and relation to sphincters/peritoneal reflection|Tumour length, T2 morphology and diffusion|Extramural depth, mesorectal fascia and EMVI|Mesorectal and extramesorectal nodes|Treatment response or fistula tract anatomy as applicable', 'Tumour perpendicular T2 plane|Closest fascia or sphincter relationship|DWI, node or fistula extension', 'Baseline staging, restaging and fistula mapping are distinct tasks; explicitly select the relevant pathway and comparison.'),
'acute-abdomen': ('Clinical localisation, urgency and protocol|Bowel, appendix and mesentery|Hepatobiliary, pancreas, spleen and urinary tract|Vessels, peritoneal gas/fluid and pelvic organs|Primary diagnosis, complication and alternatives', 'Likely cause|Complication or vascular status|Alternative or relevant negative region', 'Match the acquisition to the clinical question and state when the chosen technique cannot exclude a critical alternative.'),
'liver': ('Background liver, risk population and protocol|Observation: segment, size and number|Unenhanced signal/attenuation and enhancement phases|Vascular/biliary involvement and extrahepatic disease|LI-RADS category only where applicable, with version', 'Arterial-phase lesion|Portal/delayed phase comparison|Diffusion, hepatobiliary or vascular detail', 'Do not assign LI-RADS outside its intended population or without the required diagnostic-quality acquisition.'),
'kidney': ('Lesion side, pole, size and location|Unenhanced density/signal and enhancement|Cyst wall, septa, calcification and nodules|Renal sinus, veins, collecting system and nodes|Bosniak 2019 category for appropriate cystic masses', 'Unenhanced and enhanced comparison|Enhancing septum or nodule|Renal vein or local extent', 'Enhancement is a change from baseline; a single contrast phase cannot always distinguish a solid mass from a dense cyst.'),
'scrotum': ('Side, symptoms and examination limitations|Testicular size, echotexture and lesion location|Bilateral colour/spectral perfusion comparison|Cord, epididymis, hydrocele and scrotal wall|Mass characteristics or urgent torsion concern', 'Bilateral grayscale comparison|Matched Doppler perfusion|Spermatic cord or focal lesion', 'Preserved intratesticular flow does not by itself exclude partial or intermittent torsion.'),
'adrenal': ('Side, dimensions and homogeneity|Unenhanced attenuation and ROI|Enhancement phases and washout if valid|Chemical-shift signal if MRI acquired|Prior growth, local invasion and oncological context', 'Unenhanced ROI|Matched delayed ROI or opposed-phase image|Prior comparison or local extension', 'Use adrenal characterisation criteria only with the appropriate protocol; endocrine assessment is a separate clinical question.'),
'bladder-virads': ('Distension, protocol and previous resection/treatment|Tumour number, site and dimensions|T2 appearance of muscularis propria|Diffusion and early enhancement relationship to muscle|Perivesical, adjacent-organ and nodal findings', 'T2 tumour-muscle interface|Matched DWI and ADC|Early enhancement interface', 'Treatment and poor bladder distension can impair VI-RADS assessment; state the limiting factor and avoid false precision.'),
'ovarian-orads': ('Menopausal status, symptoms and modality|Side, origin and dimensions|Locules, solid tissue, papillary projections and flow|MRI signal, diffusion and enhancement if obtained|Ascites, peritoneal disease and named O-RADS system/version', 'Lesion overview and dimensions|Solid/papillary component|Doppler or enhancement discriminator', 'Ultrasound and MRI O-RADS are different systems; identify which was used and whether the examination is complete.'),
'prostate-mri': ('Clinical PSA and gland volume|Technical quality|Lesion sector, dimensions and dominant sequence|PI-RADS v2.1 and local extension|Nodes and bones', 'T2 localisation|DWI and ADC|DCE or capsule relationship', 'Use the expanded prostate MRI template for lesion-by-lesion scoring and image correlation.'),
'uterine-mr': ('Clinical pathway: cervical/endometrial cancer, endometriosis or anomaly|Uterus, cavity, junctional zone and cervix|Tumour depth and cervical/parametrial extension|Deep endometriosis compartments or uterine morphology|Nodes, adnexa, urinary tract and other extension', 'Sagittal uterine overview|Plane perpendicular to primary lesion|Critical compartment or adjacent organ', 'Tailor the staging fields to the primary organ and named classification; a combined pelvic survey is not a substitute for those measurements.'),
'breast-calcifications': ('Side, site and comparison|Morphology and distribution|Extent and associated mass/distortion|Magnification or tomosynthesis findings|Assessment category, correlation and recommended action', 'Magnified calcifications|Orthogonal localisation|Prior comparison or associated distortion', 'Morphology and distribution both matter; distinguish the assessment from a recommendation that accounts for the full clinical context.'),
'breast-mri': ('Indication, cycle/treatment context and protocol|Background enhancement and fibroglandular tissue|Mass/non-mass enhancement: site, size and descriptors|Diffusion, enhancement kinetics and extent|Nodes, chest wall and modality-specific assessment', 'Precontrast and subtraction finding|Extent in orthogonal plane|Node or chest-wall relationship', 'An enhancing focus is not automatically malignant; correlate morphology, kinetics, other modalities and the clinical question.'),
'breast': ('Examination type, views and comparison|Breast composition|Mass, asymmetry, distortion and calcifications|Side, quadrant/depth, size and associated features|BI-RADS assessment with edition and concordant recommendation', 'Finding on both projections|Spot/magnified or tomosynthesis image|Matched prior study', 'A new asymmetry and stable overlapping tissue may need different workups; ensure that findings and final assessment agree.'),
'ankle-foot': ('Side, mechanism and projections|Fracture site, morphology and displacement|Mortise, syndesmosis and alignment|Posterior malleolus, medial structures and associated injury|Soft tissues, osteochondral injury or tendon findings', 'Mortise alignment|Fracture in orthogonal plane|Posterior fragment or syndesmosis', 'Evaluate the whole injury pattern; a single fibular fracture description can miss an unstable ankle injury.'),
'marrow-muscle': ('Clinical pathway: infection, stress, muscle or marrow disease|Signal abnormality: site, length and compartment|Fracture line, cortical disruption or muscle/tendon tear|Ulcer, sinus tract, collection and enhancement|Joint, neurovascular and adjacent tissue involvement', 'T1 marrow or muscle anatomy|Fluid-sensitive abnormality|Fracture line, sinus tract or collection', 'Oedema is a response pattern, not a specific diagnosis; use the anatomic route and clinical context to narrow its cause.'),
'bone-tumours': ('Age, symptoms and lesion location|Margins, transition zone and matrix|Cortex, periosteum and fracture|Soft-tissue component and local extent|Multiplicity, comparison and imaging differential', 'Whole lesion radiograph|Matrix and transition zone|MRI extent or soft tissue component', 'Describe aggressiveness and the differential without prescribing an unplanned biopsy route that could compromise definitive surgery.'),
'fracture-description': ('Bone, side and segment|Fracture orientation and comminution|Displacement, angulation, shortening and rotation|Joint extension, congruity and alignment|Associated fractures and soft-tissue findings', 'Orthogonal fracture views|Articular extension|Associated injury', 'Specify the reference fragment and direction when describing displacement; ambiguous geometry misleads treatment planning.'),
'hip': ('Clinical pathway and acquisition|Head-neck morphology and acetabular coverage|Labrum, cartilage and subchondral bone|Tendons, bursae and surrounding muscles|Arthroplasty position, lucency, fracture or collection', 'Coronal hip overview|Head-neck or acetabular measurement|Implant interface or labral abnormality', 'Morphological features associated with impingement need symptom correlation; they do not establish the clinical syndrome alone.'),
'knee': ('Menisci: tear site, morphology, root and displaced fragment|Cruciate and collateral ligaments|Cartilage: compartment, depth and extent|Bone contusion, fracture and alignment|Extensor mechanism, effusion, cysts and loose bodies', 'Meniscal tear in two planes|Ligament injury|Cartilage/osteochondral lesion', 'A meniscal signal abnormality requires attention to surface extension, morphology and postoperative context.'),
'msk-mri': ('Indication, side and anatomic coverage|Bone marrow and cortex|Joint cartilage, fluid and synovium|Tendons, ligaments and muscles|Neurovascular structures and mass/collection', 'Anatomic overview|Abnormality on orthogonal planes|Associated instability or complication', 'Specify structure, location and functional consequence rather than reporting a list of nonspecific signal abnormalities.'),
'shoulder': ('Rotator cuff tendon involvement, tear dimensions and retraction|Muscle atrophy and fatty change|Long head of biceps and pulley|Labrum, capsule and instability-related bone injury|Cartilage, AC joint and bursae', 'Cuff tear and retraction|Muscle bulk/fatty change|Labral or instability injury', 'Report both tendon failure and muscle condition; a tear measurement alone is insufficient for operative planning.'),
'arthritis': ('Joints involved and symmetry|Joint-space loss and distribution|Erosions, osteophytes and new bone|Mineralisation and soft-tissue calcification|Alignment, ankylosis and progression', 'Distribution across affected joints|Representative erosion/new bone|Alignment or interval change', 'The distribution across joints can be more discriminating than a single erosion.'),
'wrist-hand': ('Bone alignment and carpal arcs|Fracture site and displacement|Scapholunate/lunotriquetral relationships|TFCC, cartilage and ligaments if MRI obtained|Tendons, nerve and soft tissues', 'PA carpal alignment|True lateral alignment|Fracture or ligament abnormality', 'Projection can distort apparent carpal alignment; confirm positioning before assigning instability.'),
'paeds-hip-elbow': ('Age, side and indication|Hip coverage, alpha angle and dynamic stability if ultrasound|Ossification centres and expected development|Elbow alignment lines and fat pads|Fracture, displacement and growth-plate involvement', 'Hip standard coronal plane|Elbow true lateral|Alignment line or displaced ossification centre', 'Normal developmental anatomy changes with age; compare the finding with age-appropriate landmarks.'),
'paediatric': ('Age/size and clinical question|Modality and dose optimisation|Sedation, contrast and preparation if used|Developmental anatomy and primary findings|Limitations, alternatives and communication', 'Age-appropriate overview|Question-specific finding|Complication or developmental comparison', 'Adult reference values and protocols should not be transferred automatically to children.'),
'child-abuse': ('Clinical history supplied, examination date and protocol|Skeletal survey completeness and image quality|Each injury: side, bone, site and morphology|Intracranial, spinal and visceral findings if imaged|Prior examinations and multidisciplinary communication', 'Overview of affected bone|Focused injury in two projections|Associated injury with correct annotation', 'Describe findings objectively and document communication; imaging alone cannot establish the precise time, intent or perpetrator of an injury.'),
'paeds-masses-neuro': ('Age and clinical pathway|Mass organ of origin, size and composition|Vascular relationship, nodes and spread|Neonatal ventricles, germinal matrix and parenchyma if ultrasound|Associated malformations and follow-up comparison', 'Organ of origin or standard cranial plane|Vascular relationship or haemorrhage|Extension or ventricular measurement', 'Do not use an adult organ-mass differential without considering the child’s age and the lesion’s true organ of origin.'),
'paeds-chest': ('Gestational/postnatal age and respiratory support|Projection and inflation|Parenchymal pattern and distribution|Cardiomediastinal anatomy and pleura|Lines/tubes and complications', 'Whole neonatal or paediatric chest|Line/tube tip|Focal complication', 'Use the age, support settings and timing of treatment to interpret a neonatal lung pattern.'),
'paeds-abdomen': ('Age and symptom pattern|Bowel gas, calibre and distribution|Intussusception, rotation or obstructing lesion as relevant|Pneumatosis, portal venous gas and free air/fluid|Solid organs, urinary tract and complication', 'Bowel pattern overview|Targeted diagnostic sign|Perfusion or complication', 'A normal radiograph cannot exclude all urgent abdominal disease; state when targeted ultrasound or another examination is required.'),
'nuclear-general': ('Indication and study type|Radiopharmaceutical, activity, route and timing|Acquisition and technical quality|Distribution, quantitative measures and focal abnormalities|SPECT/CT correlation and study-specific interpretation', 'Whole-body or organ distribution|Focused planar views|Tomographic/anatomic correlation', 'Tracer uptake reflects its biological pathway; it is not automatically specific for one diagnosis.'),
'pet-ct': ('Indication, tumour type and treatment timing|Tracer, activity, uptake time and glucose|PET and CT acquisition quality|Disease sites, size and uptake measurements|Response criteria if applicable and incidental findings', 'Distribution overview|Index lesion with fused CT|New lesion or treatment-response comparison', 'Inflammation and treatment effects can be FDG-avid; standardise comparisons and identify limitations of the CT component.'),
'theranostics': ('Target and radiopharmaceutical|Indication, prior therapy and uptake time|Lesion distribution and target expression|Discordant lesions and anatomic correlation|Physiological uptake, pitfalls and relevant organ findings', 'Target-expression overview|Representative avid lesion|Discordant or potentially misleading uptake', 'Target expression on one scan is not the sole criterion for treatment eligibility; integrate the disease and treatment-specific pathway.'),
'esophagus-swallowing': ('Indication and examination type|Swallow phases, bolus consistency and position|Aspiration/penetration and clearance|Level, length and morphology of narrowing|Motility, mucosa, leak and extrinsic compression', 'Pharyngeal swallow phase|Stricture or mucosal abnormality|Leak, aspiration or dynamic sequence reference', 'Differentiate structural imaging from a functional swallowing assessment; record the bolus and timing of an aspiration event.'),
'anal-cancer': ('Tumour site, dimensions and craniocaudal extent|Anal canal, sphincters and intersphincteric plane|Adjacent organ involvement|Mesorectal, pelvic and inguinal nodes|Imaging stage with edition and limitations', 'Primary tumour in orthogonal planes|Sphincter/organ relationship|Suspicious regional node', 'Anal and rectal cancer use different staging rules and nodal maps; confirm the primary site before assigning a category.'),
'gi-tumours-foreign-bodies': ('Indication and enteric distension|Lesion or object: site, size and composition|Bowel wall, enhancement and luminal effect|Mesentery, vessels, nodes and spread|Perforation, abscess or obstruction', 'Lesion or object localisation|Bowel wall/mesentery relationship|Complication or disease extension', 'A sharp foreign body may perforate without extensive free gas; local inflammatory change and exact localisation matter.'),
'pelvic-floor': ('Patient position, contrast and dynamic phases|Anatomic landmarks and reference lines|Anterior, middle and posterior compartment descent|Rectocele, intussusception and evacuation|Rest versus strain/evacuation measurements', 'Rest landmarks|Maximal strain|Evacuation and retained contrast', 'Record technique and effort; inadequate evacuation or strain can underestimate the abnormality.'),
'breast-implants-male': ('Clinical pathway, laterality and comparison|Implant type, location and contour if present|Shell integrity and intra/extracapsular material|Peri-implant fluid, capsule or mass|Male breast pattern, focal lesion and nodes', 'Implant contour or male breast overview|Shell/gel-specific abnormality|Peri-implant collection, mass or node', 'Implant integrity assessment and cancer assessment answer different questions; a peri-implant mass or late fluid collection needs an appropriate dedicated workup.'),
'tinnitus': ('Pulsatile or non-pulsatile, side and auditory findings|Temporal bone, middle ear and skull base|Arterial course, calibre and vascular lesions|Venous sinuses, jugular bulb and diverticulum|Internal auditory canals and cerebellopontine angles', 'Temporal bone vascular relationship|Arterial/venous abnormality|Internal auditory canal or skull-base lesion', 'Choose imaging according to the tinnitus phenotype; a vascular contact or variant may be incidental.'),
'trigeminal': ('Side and clinical pain/neuropathy pattern|Brainstem nuclei and cisternal nerve|Vessel-nerve relationship and root morphology|Meckel cave, cavernous sinus and skull-base foramina|Enhancement, mass, demyelination and perineural spread', 'High-resolution cisternal nerve|Vessel contact with nerve morphology|Meckel cave or foraminal abnormality', 'Simple neurovascular contact is common; report nerve displacement or atrophy and consider nonvascular causes.'),
'sella': ('Indication and endocrine/visual context|Gland and lesion dimensions|T1/T2, enhancement and dynamic imaging if obtained|Stalk, optic chiasm and cavernous sinuses|Suprasellar extension, haemorrhage and sphenoid anatomy', 'Coronal sellar plane|Sagittal gland/stalk view|Chiasm, cavernous sinus or haemorrhage', 'Describe anatomic involvement and urgent compression separately from presumed hormonal function, which imaging does not determine.'),
'elbow-mri': ('Tendon origins and distal biceps/triceps|Medial and lateral ligament complexes|Cartilage and osteochondral surfaces|Bone marrow, fracture and alignment|Ulnar/radial/median nerves and joint bodies', 'Tendon or ligament injury|Osteochondral surface|Nerve course or displaced body', 'Name the injured component and its extent; signal changes without discontinuity may not represent a full-thickness tear.'),
'neonatal-spine': ('Age, skin marker and acoustic window|Vertebral numbering and conus level|Filum thickness/appearance and cord motion|Dorsal tract, mass and posterior elements|Associated dysraphism and examination limits', 'Longitudinal conus and numbered levels|Transverse cord and filum|Skin tract or associated abnormality', 'Document how levels were counted; poor windows or uncertain numbering limit confidence and may require MRI correlation.'),
'gi-ultrasound': ('Fasting/preparation and transducer|Segment identification and compressibility|Wall thickness, layers and vascularity|Peristalsis, contents and surrounding mesentery|Graded compression limits and extraintestinal findings', 'Longitudinal bowel layers|Transverse wall measurement|Doppler or dynamic compression', 'Wall thickness depends on distension and technique; record the conditions of the measurement.'),
'craniosynostosis': ('Age, head-shape concern and modality|Sutures: patent, narrowed or fused|Skull-shape pattern and cranial-base anatomy|Orbits, ventricles and intracranial findings if evaluable|Multisuture involvement and associated anomalies', 'Suture overview|Specific fused/patent suture|Skull-base or orbital relationship', 'A head-shape abnormality does not alone establish suture fusion; choose an age-appropriate examination and minimise radiation.'),
}

WORKSHEETS = {'contrast', 'radiation-safety', 'ct-image', 'mri-sequences', 'modalities', 'ultrasound-physics', 'structured-reporting', 'brain-anatomy', 'paediatric'}


def build():
    nodes = [node for node in json.loads((ROOT / 'data/curriculum/11-radiology.json').read_text())['nodes']
             if node['id'].startswith('rad.')]
    additional = ROOT / 'data/radiology/additional-modules.json'
    if additional.exists():
        known = {n['id'] for n in nodes}
        nodes += [n for n in json.loads(additional.read_text())
                  if n['id'].startswith('rad.') and n['id'] not in known]
    guides = {}
    for node in nodes:
        key = node['id'].split('.', 2)[2]
        fields, images, note = SPECS[key]
        fields, images = fields.split('|'), images.split('|')
        worksheet = key in WORKSHEETS
        template_title = node['title'] + (' — review worksheet' if worksheet else ' — structured report')
        sections = [
            {'heading': 'INDICATION', 'body': 'Clinical question: [ ].\nRelevant history, prior treatment and urgency: [ ].'},
            {'heading': 'COMPARISON', 'body': '[None available / date and examination]. Relevant interval change: [ ].'},
            {'heading': 'TECHNIQUE AND QUALITY', 'body': 'Modality, protocol, coverage and contrast: [ ].\nQuality: [diagnostic / limited / non-diagnostic].\nLimitation and effect on the clinical question: [ ].'},
            {'heading': 'KEY IMAGES', 'body': '\n'.join(f'[IMG {i}: {label}; series __ image __]' for i, label in enumerate(images, 1))},
        ]
        sections += [{'heading': field.upper(), 'body': '[Observations / measurements with units / not assessed and reason].'} for field in fields]
        sections += [
            {'heading': 'IMPRESSION', 'body': '1. Answer to the clinical question: [ ].\n2. Principal finding, location and extent: [ ].\n3. Relevant classification and version, if applicable: [ ].\n4. Complication, alternative diagnosis or unresolved limitation: [ ].'},
            {'heading': 'RECOMMENDATION AND COMMUNICATION', 'body': 'Further evaluation if indicated, with reason and timeframe: [ ].\nCritical finding communicated to [ ] at [ ]; method [ ].\n[Delete if not applicable].'},
        ]
        points = []
        for media in node.get('lesson_media', []):
            for item in media.get('long_description', {}).get('items', []):
                if item.get('detail'):
                    points.append(item['detail'])
        guides[node['id']] = {
            'overview': node['goal'] + ' Use the linked foundation readings for the illustrated teaching cases, then apply the reporting checklist to a supervised case.',
            'learning_points': list(dict.fromkeys(points + ['Review ' + field[0].lower() + field[1:] + '.' for field in fields] + [note])),
            'report_templates': [{'id': key + '-report', 'title': template_title,
                'description': 'Original educational ' + ('review worksheet' if worksheet else 'report scaffold') + '. Complete the relevant observations; remove unused prompts before use.',
                'sections': sections, 'notes': [note], 'sources': []}],
            'key_images': [{'id': key + '-image-' + str(i), 'label': 'IMG ' + str(i) + ': ' + label,
                'description': 'Placeholder for ' + label[0].lower() + label[1:] + '. Record the series/image reference and annotate the feature being demonstrated.'} for i, label in enumerate(images, 1)],
        }
    destination = ROOT / 'data/radiology/module-guides.json'
    destination.write_text(json.dumps(guides, ensure_ascii=False, indent=2) + '\n')
    print(f'Wrote {len(guides)} module guides to {destination}')


if __name__ == '__main__':
    build()
